- History.md
- README.md
- ext/puma_http11/mini_ssl.c
- lib/puma/dsl.rb
- lib/puma/minissl.rb
- lib/puma/minissl/context_builder.rb
- test/test_binder.rb
- test/test_config.rb
Add ability to set OpenSSL verification flags (https://www.openssl.org/docs/manmaster/man3/X509_VERIFY_PARAM_set_hostflags.html#VERIFICATION-FLAGS).
We had a need to set `X509_V_FLAG_PARTIAL_CHAIN` flag. Most major TLS libraries behaves like this by default but not OpenSSL (https://github.com/openssl/openssl/issues/7871). Adding ability to set any verification flag allows us to set `X509_V_FLAG_PARTIAL_CHAIN` flag. I think it may be useful for others too.
I implemented this for MRI only as I don't know how to do this for JRuby (and if this is even required?).
> [SSL] Add ability to set verification flags

- History.md
This PR sorted the release version order.
It seems descending order is good for this file.
> Sort the release version order in descending order of release date

- README.md
While reading the configuration file finding notes in the README, I was suddenly confused, and found the wording unclear.
This PR adds more words.
Implementation:
https://github.com/puma/puma/blob/d2f9d6de7b1b8e6bbdb9d5c29cc738cc4b52fb6c/lib/puma/control_cli.rb#L122
> README: Clarify config file fallbacks [ci skip]

- docs/plugins.md
This PR adds a note to the Puma docs that heroku plugin is no longer a current need.
I didn't change more of the text, since the example plugin "heroku" was good at not being a built-in plugin, so the examples were better off keeping it, until a new non-built-in plugin has been added.
> [doc] plugins: Add note about Heroku plugin sunset [ci skip]

- History.md
- lib/puma/const.rb
- test/test_response_header.rb
This PR fixes some false positive matches that was introduced in https://github.com/puma/puma/pull/2439
> Make illegal header matching more stringent

- docs/compile_options.md
Ensure that the full cflags option is quoted when
using bundle install
Without this, compilation would fail with this error:
Installing puma 5.1.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /usr/local/bundle/gems/puma-5.1.1/ext/puma_http11
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20201214-9-1yhulk9.rb extconf.rb --with-cflags\=-D
PUMA_QUERY_STRING_MAX_LENGTH\=64000
checking for BIO_read() in -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
> [ci skip] Improve quoting of bundle cflags

- README.md
- docs/kubernetes.md
Adds documentation for running in Kubernetes, including the rolling deploy/graceful shutdown interaction and its workaround mentioned in #2343. Closes #2343 @nateberkopec
> [ci skip] K8s docs

- History.md
- lib/puma/runner.rb
- test/config/prune_bundler_print_nio_defined.rb
- test/test_integration_cluster.rb
There's a bug related to https://github.com/puma/puma/issues/2018. Essentially, if the `nio4r` gem is ever loaded into the puma master process, it makes it impossible to do things like upgrade `nio4r` during a phased restart and also makes it impossible to remove the gems from disk without breaking phased restarts. Those problems were addressed mostly by my own https://github.com/puma/puma/pull/2427. 
In PR #2427, I was pretty sure I made it so that if you're running a puma cluster with `--prune-bundler`, the puma master process would never load `nio4r`. It turns out that actually, if you enable the status server, the puma master process ends up loading `nio4r` -- the status server is launched in a _thread_ in the master process. Since the status server just uses its own instance of …
> Remove nio from status server

- History.md
- lib/puma/null_io.rb
- test/test_null_io.rb
Makes Puma::NullIO more similar to [StringIO].
[StringIO]: https://docs.ruby-lang.org/en/2.5.0/StringIO.html#method-i-string
> Add #string method to Puma::NullIO

- History.md
- lib/puma/dsl.rb
- test/test_rack_handler.rb
Fixes the issue with running puma handler with `Host: '::1'`, right now we have a backtrace, since `[::1]` should be used as a hostname in URIs.
```
$ bundle exec rails s -u puma -b '::1'
=> Booting Puma
=> Rails 6.0.3.4 application starting in development
=> Run `rails server --help` for more startup options
* Puma version: 5.1.1 (ruby 2.7.2-p137) ("At Your Service")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 9014
Exiting
Traceback (most recent call last):
…
10: from /home/ojab/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:327:in `start'
9: from /home/ojab/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.1.1/lib/rack/handler/puma.rb:71:in `run'
8: from …
```
> Build proper url instead of interpolating in `Puma::DSL#port`

- lib/puma/dsl.rb
default max threads is changed in MRI since https://github.com/puma/puma/commit/05936689c832e33a915a052b10a20b5bbd173e1a
- ~~[ ] I have added appropriate tests if this PR fixes a bug or adds a feature.~~
- ~~[ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.~~
- ~~[ ] I have updated the documentation accordingly.~~
> [changelog skip][ci skip] Fixes threads comment in dsl.rb

- History.md
- lib/puma/configuration.rb
- lib/puma/dsl.rb
- lib/puma/reactor.rb
- lib/puma/server.rb
- test/config/with_symbol_convert.rb
- test/test_config.rb
- test/test_puma_server.rb
nio4r will soon have experimental support for io_uring via libev. The brave might want to try it out :) regardless of that, allowing users to explicitly set the IO selector backend seems like a good idea to me.
> Allow specifying the desired IO selector backend for nio4r

- History.md
- lib/puma/server.rb
`Server#read_body` seems to have been left behind as part of a refactoring done in 6777c771d829a31634b968c74a829cc53b80a144, where the contents of this method were copied into the newly-created `Client` class but never removed from `Server`, even though it's no longer called anywhere. This PR removes the unused method.
> Remove Server#read_body

- History.md
- lib/puma/launcher.rb
When a server is stopped, the last line of the log is `Goodbye!`.  Currently, this line is output before the listeners are closed.  Note that this is not output when a server is halted.
While working with updated tests, and checking for closed listeners, I noticed this.
Hence, change `Goodbye!` to appear after the listeners are closed.  Whether `Goodbye!` should be output when a server is halted, not sure...
> Change 'Goodbye!' message to be output after listeners are closed

- History.md
- ext/puma_http11/extconf.rb
- ext/puma_http11/mini_ssl.c
- lib/puma/minissl.rb
While working on an update to the test suite, client connections were slow with ssl tests.  
Currently, a new context is created for each accepted client connection.  A context also reads two files for the cert and key.
Refactored to use one context created in MiniSSL::Server.new.
Code is included in a `misc` folder that reports on the times needed to open the socket and write a simple request.  It logs the time of each client's GET request, each having about a 100k body, then sorts the times, and outputs percentile times.  See the socket_times.md in the misc folder for info.
Times for this PR (see 'test ssl connection times` step):
https://github.com/MSP-Greg/puma/actions/runs/453868127
Times for current master:
https://github.com/MSP-Greg/puma/actions/runs/453894649
The CI for the PR …
> Fix SSL Context - minissl.c, minissl.rb, extconf.rb

- lib/puma/dsl.rb
Related to https://github.com/puma/puma/issues/2393, #2143
> Document workers and threads environment variables [changelog skip]

- docs/rails_dev_mode.md
Hello, it's my first time here! 👋  
Closes https://github.com/puma/puma/issues/2352 
The documentation is a new file `docs/rails_dev_mode.md` as suggested and pretty much a paraphrase/copy pasta of @earksiinni's analysis and observation.
> [ci skip] Add documentation on interlock issue in Rails development mode

- lib/puma.rb
- lib/puma/detect.rb
`puma.rb` loads `puma/puma_http11`, which contains the compiled c code for ssl.  Move ssl detection from `puma/detect.rb` to `puma.rb`
Fix `Puma::IS_WINDOWS` and `Puma.windows?` to work with JRuby.
No breaking API changes.
JFYI, quick benchmark of predicate methods (`Puma.ssl?`) vs constants (`Puma::HAS_SSL`), showed constants were about twice as fast.  But, both are 'fast enough'.  Haven't looked thru the code to change...
> Move ssl detection to puma.rb [changelog skip]

- History.md
- lib/puma/minissl.rb
MiniSSL::Socket#write performs some string 'dice & chop', and was using both byte and character methods.  Convert all to byte methods.
Closes https://github.com/puma/puma/issues/2542
Note that this is only noticeable when the response headers/body are such that x.length != x.bytesize
I will write a test for it, but did the checking locally with a 600kB body.  Was using `curl` and `git diff`, need to find a more Ruby based solution...
> Bug Fix - MiniSSL::Socket#write - use data.byteslice(wrote..-1)

- History.md
- lib/rack/handler/puma.rb
Hello! 
I found an issue where I had to require `'rack'` or more specifically, `'rack/common_logger'` when verbose is set to true, `:Verbose => true`. 
Take this example: 
```ruby
require 'rack/handler/puma'
app = -> environment {[200, {}, []]}
Rack::Handler::Puma.run(app, :Verbose => true)
```
This is the exception: 
```
Traceback (most recent call last):
10: from /usr/bin/irb:23:in `<main>'
9: from /usr/bin/irb:23:in `load'
8: from /Library/Ruby/Gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
7: from (irb):3
6: from /Users/mapleong/.gem/ruby/2.6.0/gems/puma-5.2.0/lib/rack/handler/puma.rb:63:in `run'
5: from /Users/mapleong/.gem/ruby/2.6.0/gems/puma-5.2.0/lib/rack/handler/puma.rb:32:in `config'
4: from /Users/mapleong/.gem/ruby/2.6.0/gems/puma-5.2.0/lib/rack/handler/puma.rb:32: …
```
> Explicitly require rack/common_logger if :Verbose is true

- History.md
- lib/puma/client.rb
- test/test_puma_server.rb
Rack expects CGI keys as strings (see [lint.rb](https://github.com/rack/rack/blob/a05f8d56f9ac4da14dddb8f312a3b43644f73397/lib/rack/lint.rb#L305)). 
- Existing tests updated.
- One error and some rubocop offenses, but they are there also for the base repository.
> Set @env[CONTENT_LENGTH] value as string.

- .github/workflows/mri.yml
- .github/workflows/non_mri.yml
Recent examples (these were all yellow but I cancelled them)
- https://github.com/puma/puma/runs/1826040463?check_suite_focus=true
- https://github.com/puma/puma/runs/1825682787?check_suite_focus=true
- https://github.com/puma/puma/runs/1825683423?check_suite_focus=true
- https://github.com/puma/puma/runs/1825636952?check_suite_focus=true
- https://github.com/puma/puma/runs/1825636286?check_suite_focus=true
GitHub Actions is out of capacity for macOS: https://github.com/actions/virtual-environments/issues/2486
Perhaps better to add macos-11.0 back when the above issue is resolved.
> Remove macOS 11 builds, try to stabilize CI [changelog skip]

- History.md
- lib/puma/request.rb
- lib/puma/server.rb
`Server##cork_socket` & `Server##uncork_socket` work on TCPSockets, but when using an ssl client, a MiniSSL::Socket is passed to them.
Use 'to_io', which is available with all 'socket objects' used in Puma.
I haven't worked with wireshark for a while, and that's probably the only way to see a difference?
> server.rb - properly cork & uncork ssl clients

- History.md
- lib/puma/null_io.rb
- test/test_events.rb
- test/test_null_io.rb
Add `#flush` and `#sync` methods to `Puma::NullIO`.
This fixes an issue if you're using `Events.null`, e.g.:
```ruby
i = Puma::Launcher.new(Puma::Configuration.new, {events: Puma::Events.null})
i.run
```
Without this patch, this would fail with:
```
NoMethodError: undefined method `sync' for #<Puma::NullIO:0x00007fb0cbb7cec8>
Did you mean?  sync=
from /Users/ob/workspace/ruby/puma/lib/puma/events.rb:67:in `log'
```
> Add `#flush` and `#sync` methods to `Puma::NullIO`

- History.md
- lib/puma/configuration.rb
- lib/puma/dsl.rb
- lib/puma/runner.rb
- test/rackup/write_to_stdout.ru
- test/test_integration_single.rb
Fixes #2545. In Puma 5.2, Puma stopped mutating the `sync` flag on the global `STDOUT` and `STDERR` objects. This can cause user application logs to be not flushed on every write if users were depending on this behavior. This PR restores `sync` behavior for those streams to the pre-5.2 behavior. We may re-introduce the change again in 6.0 with better documentation.
To verify this change, I used a Rack app that writes to stdout on every request
```ruby
#stdout_test.ru
app = lambda do |env|
$stdout.write "hello\n"
[200, {"Content-Type" => "text/plain"}, ["Hello World"]]
end
run app
```
Start puma, piping its stdout to something that's not a TTY:
```sh
bundle exec ruby -Ilib bin/puma stdout_test.ru | tee puma.out
```
Then, send a bunch of requests
```sh
seq 100 | xargs -n 1 -I{} curl …
```
> Restore sync=true on global stdout/stderr streams

- Gemfile
- test/helpers/integration.rb
- test/test_busy_worker.rb
- test/test_integration_single.rb
Fix CI
1. Add racc to Gemfile for JRuby RuboCop
2. test_busy_worker - skip teardown
3. test_integration_single - patch from PR 2560
> Fix CI [changelog skip]

- History.md
- lib/puma/binder.rb
Closes #2504
A test for this exists in the updated test framework.  Will open a PR for it after all the library file changes have been accepted.
> Don't close systemd activated socket on pumactl restart

- History.md
- lib/puma/cluster.rb
- lib/puma/configuration.rb
- lib/puma/dsl.rb
- test/test_config.rb
- test/test_integration_cluster.rb
Running Puma in cluster-mode is likely a misconfiguration in most
scenarios.
Cluster mode has some overhead of running an addtional 'control' process
in order to manage the cluster. If only running a single worker it is
likely not worth paying that overhead vs running in single mode with
additional threads instead.
There are some scenarios where running cluster mode with a single worker
may still be warranted and valid under certain deployment scenarios, see
the linked issue for details.
From experience at work, we were able to migrate our Rails applications
from single worker cluster to single-mode and saw a reduction of RAM
usage of around ~15%.
Closes #2534
> Print warning when running one-worker cluster

- History.md
- lib/puma/cluster.rb
- lib/puma/cluster/worker_handle.rb
- test/helpers/integration.rb
- test/test_integration_cluster.rb
- test/test_preserve_bundler_env.rb
- test/test_worker_gem_independence.rb
Fixes #2528 adding the reason for worker timeout and the startup time when worker boots
> Add debug to worker timeout and startup. Closes #2528

- lib/puma.rb
- test/helper.rb
- test/helpers/integration.rb
- test/test_binder.rb
- test/test_cli.rb
- test/test_config.rb
- test/test_http11.rb
- test/test_integration_cluster.rb
- test/test_integration_pumactl.rb
- test/test_integration_single.rb
- test/test_integration_systemd.rb
- test/test_launcher.rb
- test/test_preserve_bundler_env.rb
- test/test_pumactl.rb
- test/test_redirect_io.rb
- test/test_unix_socket.rb
- test/test_worker_gem_independence.rb
The TestSkips class was originally used for skipping tests based on OS and used `skip_on` & `skip_unless`.
1. Change `skip_on` to `skip_if`.
2. Add more options for things like `UNIXSocket`, `Kernel.fork`, ssl support, etc.
3. Update tests to use updated syntax.
This also makes skip messages more consistent, which is used by code that will be added to another PR that groups test skips so one doesn't have to wade thru a large list to see the failures & errors.
See:
https://github.com/MSP-Greg/puma/runs/2051481529?check_suite_focus=true#step:9:528
> Update helper.rb TestSkips, add HAS_UNIX_SOCKET to puma.rb [changelog skip]

- test/helper.rb
Many CI jobs have a large number of skips, and Minitest's verbose output lists skips, failures, & errors in the order they occurred.
This adds code to helper.rb to group the skips by their skip message, making it easier to see better information about the skips, and places the failure & error logging at the end of the summary output.
> Minitest - Add code to group & summarize test skips [changelog skip]

- lib/puma/server.rb
- lib/puma/thread_pool.rb
Two small things:
- https://github.com/puma/puma/pull/2079/files#r422738756 -> swap the order of calls so that the faster call (float comparison) runs first.
- https://github.com/puma/puma/pull/2079/files#r596114279 -> don't call `.to_f` on option that we already know is a float.
> Micro optimisations in `wait_for_less_busy_worker` feature

- README.md
The rubinius website doesn't seem to be related to Ruby anymore. Now it's simply says:
I guess that link used to be relevant, but it no longer is.
> Update link to rubinius

- docs/restart.md
See https://github.com/puma/puma/blob/v5.2.2/lib/puma/dsl.rb#L615-L623
The default changed in Puma 5 with #2143. Docs later updated in #2481.
> preload_app! is not always disabled by default [ci skip]

- lib/puma/request.rb
- test/test_puma_server.rb
Went through several versions, benched all of them, and this seemed the best compromise for small and large (100kb) chunked bodies, both ascii compatible and not.
Closes #2583
Also, Fix `TestPumaServer#test_custom_io_selector`. On fast systems, stopping the server happened fast enough so that `IOError: selector is closed` was raised.
> request.rb - fix chunked body assembly for ascii incompatible encodings

- lib/puma/server.rb
This fixes the issue for me when I run Puma in FreeBSD using Vagrant. Instructions for that over at https://github.com/dentarg/puma-vagrant/tree/0c858e572fff48b3148b3bec81518471393f94df#freebsd
Close https://github.com/puma/puma/issues/2556
This change is included in https://github.com/puma/puma/pull/2554, but that PR has a lot of other changes too, hopefully this will be easier to review, merge and release.
> Define `UNPACK_TCP_STATE_FROM_TCP_INFO` in the right place

- ext/puma_http11/http11_parser.h
Modify `puma_parser` struct to remove 8 bytes padding in 64-bit machine.
`benchmarks/wrk/hello.sh` shows performance improvement from 4631.424 to 4750.686 (5 times average).
I use Ruby 3.0.0 and WSL2 Ubuntu 20.04
> [changelog skip] Reduce puma_parser struct padding

- .github/workflows/mri.yml
- .github/workflows/non_mri.yml
GitHub Actions has skipping CI built in, but only checks the commit message. I removed too much in 26776c86.
> Be able to skip CI from pull request title [ci skip]

- lib/puma/server.rb
Similar code and naming is used `Server#cork_socket` & `Server#uncork_socket`...
> Server#closed_socket? - parameter may be a MiniSSL::Socket

- History.md
- lib/puma/cluster.rb
When you're trying to access a thread-local variable on Ruby < 2.7, and you call `thread_variable_get` on a `Process::Waiter` (a subclass of `Thread`), it will segfault. This adds a check for which Ruby version you're on to make it safe for Ruby 2.6.
Closes #2566.
> Handle segfault in Ruby 2.6.6 on thread-locals

- lib/puma/server.rb
- test/test_puma_server.rb
Fixes #2574 (a regression released in v5.0.3), with an added test to prevent future regressions.
#2575 extends this fix by adding a `between_bytes_timeout` configuration option that allows for different timeout values for the initial data received by the client, and subsequent chunks of data. This extra option may eventually be useful but this PR is intended to more narrowly fix the regression first.
> Fix timing out requests too early

- lib/puma/server.rb
- test/test_puma_server.rb
Handle error that `e.backtrace` is nil.
Current implementation assumes `e.backtrace` is an Array, and will raise `NoMethodError` to the top of thread-pool, this will output an empty response body.
Closes #2552
> Handle fatal error that has no backtrace

- lib/puma.rb
- lib/puma/binder.rb
- lib/puma/control_cli.rb
- test/test_pumactl.rb
- test/test_unix_socket.rb
Closes #2526
Tests for abstract UNIXSockets exist in the updated test framework. Will open a PR for it after all the library file changes have been accepted.  Tested both server & control binding...
> Add support for Linux's abstract sockets

- lib/puma/const.rb
- lib/puma/request.rb
- test/test_puma_server.rb
IPV6 Host was not properly parsed.
With the insanely detailed bug report his was fixed in no time:  👍
Closes #2584
> Improve parsing of HTTP_HOST header

- lib/puma/client.rb
In `tcp` mode when both `remote_addr_value` and `remote_addr_header` are not set, `client.peerip` method
calls `@io.peeraddr` in every request, I dont't think we need to reset `@peerip` to `nil` in such condition.
`@io.peeraddr` uses two syscalls `getpeername` and `recevfrom`, by caching the `@peerip` in `Client` instance, 
we can save two syscalls on every request in an established connection, except for the first request.
`hello.ru` performance improvement:
- master, 4107 RPS
- caching peerip, 5224 RPS
> Reset peerip only if remote_addr_header is set

- lib/puma/client.rb
Puma has a limit (`Puma::Const::MAX_BODY` - around 110 KiB) over which
it will write request bodies to disk for handing off to the
application. When it does this, the request body can be left on disk
if the Puma process receives SIGKILL. Consider an extremely minimal
`config.ru`:
run(proc { [204, {}, []] })
If we then:
1. Start `puma`, noting the process ID (to kill it later).
2. Start a slow file transfer, using `curl --limit-rate 100k` (for
example) and `-T $PATH_TO_LARGE_FILE`.
3. Watch `$TMPDIR/puma*`.
We will see Puma start to write this temporary file. If we then send
SIGKILL to Puma, the file won't be cleaned up. With this patch, it
will - at least on POSIX systems. On Windows it may still be available.
This is suggested in the Ruby Tempfile documentation, and even uses this …
> Immediately unlink temporary files

- docs/architecture.md
Just started reading the architecture docs, for me as a first time
reader it would be useful to have direct link to stated class in the
markdown.
This commit passes through `architecture.md` only, if this is something
that makes sense to you I can pass through all the `docs/`
> [changelog skip] Link to classes in the architecture docs.

- lib/puma/queue_close.rb
- lib/puma/server.rb
- test/test_puma_server.rb
This refactoring PR moves the `drain_on_shutdown` implementation out of `#graceful_shutdown` to reduce duplication with the main server accept loop, including a test covering the basic behavior of this option to prevent regressions.
There might be some slight change in timing around when exactly the `:state` event gets fired (before or after connections are all drained), but this doesn't seem important enough to worry about (there was zero test coverage around it).
- dad2708 refactors `TestPumaServer#server_run`, in order to allow arbitrary option arguments to be passed. This made writing the added test with a custom option a bit easier and more readable, and allowed me to clean up a bit of boilerplate in the rest of the test suite.
> Refactor drain on shutdown

- docs/deployment.md
- docs/plugins.md
- docs/systemd.md
Sanitizing docs on few places. Ain't much. But, it's honest work :).
> Few documentations fixes. [ci skip] [changelog skip]

- lib/puma/cluster.rb
- test/test_integration_systemd.rb
Fixes event firings needed for systemd integration.
Closes #2572.
Note that `@events.fire_on_stopped!` was not called when in cluster mode, this also fixes that.
These tests take some time, I tested locally with two restarts, it passed.
> systemd - fix event firing

- lib/puma/client.rb
- lib/puma/request.rb
- lib/puma/server.rb
As a followup to df72887170c7ef3614c941c9bdefb4a1f3546ebf, this PR is an attempt to refactor the 'keepalive-connection shedding' logic to improve its performance and reliability.
Summary of changes:
1. Instead of closing the socket by breaking out of the `Server#process_client` loop from the 'keepalive == true' branch, move the connection-shedding logic to modify the `res_info[:keep_alive]` variable in `Request#str_headers`. This writes the `Connection: close` header as part of the final response before closing the socket, allowing clients to reopen a new connection more gracefully (for example, preventing 'socket read' errors from being logged in `wrk`).
2. Instead of shedding the keepalive connection after a fixed number of consecutive inline requests, shed the connection whenever the …
> Improvements to keepalive-connection shedding

- lib/puma/binder.rb
- lib/puma/dsl.rb
- test/test_binder.rb
Closes https://github.com/puma/puma/issues/2623
As well as updating the docs to reflect that TCP_NODELAY is off by default, I've tweaked the code so that `low_latency=false` doesn't set TCP_NODELAY, which is consistent with how other options are parsed. Let me know if the tests are a bit overkill.
I'm not sure how best to test that the created socket has or lacks TCP_NODELAY in JRuby, since this version of JRuby has a very minimal Socket implementation (no constants, no bool method). For now I've skipped my new tests if we're running them in JRuby, but any guidance would be appreciated.
> Update docs for low_latency option and fix parsing issue

- lib/puma/cluster/worker.rb
Closes [2222](https://github.com/puma/puma/issues/2222). 
The current issue occurs if the server can't be started and raised exceptions before signal re-registration is done.I put the code to log the first line of back trace to gives consistent error log if there is some error in worker starts.
> Fix sigterm misbehavior

- lib/puma/configuration.rb
Closes https://github.com/puma/puma/issues/2626
In https://github.com/rack/rack/commit/b95cb72463bac5a087294c7ecf94674db7aa41fe#diff-79892c6315a7f9c02489803e95ce828a8a32759b9f8f196aa98e6826eb562e55R96, Rack removed the ability to pass options from the command line. It now  fails when you try to do that, and no longer exposes them from`Builder.load_file`. Puma shouldn't fail when this happens.
This commit falls back to an empty object when Rack does not pass options back from `Builder.load_file`.
> Gracefully handle Rack not accepting CLI options

- lib/puma/binder.rb
- lib/puma/dsl.rb
- lib/puma/request.rb
- test/test_puma_server.rb
> Add rack_url_scheme to Puma::DSL, allows setting of rack.url_scheme header

- ext/puma_http11/mini_ssl.c
When using client certificates, session id context needs to be set. OpenSSL documentation covers it like this:
> If the session id context is not set on an SSL/TLS server and client
certificates are used, stored sessions will not be reused but a fatal
error will be flagged and the handshake will fail. 
Details: https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_session_id_context.html
Ruby OpenSSL wrapper conforms to this by setting the session id context to a random sequence of bytes whenever a context is created:
http://github.com/ruby/openssl/blob/master/lib/openssl/ssl.rb#L493
I am open to suggestions about generating random bytes. I feel like there can be a better way than this.
> Set session id context while creating SSLContext

- lib/puma.rb
- lib/puma/app/status.rb
- lib/puma/json_serialization.rb
- test/test_json_serialization.rb
For the hooks defined in `Puma::DSL`, the previous naming had the unfortunate side-effect of causing `JSON` to resolve to `Puma::JSON` rather than, the likely more expected, `::JSON` module.
Closes #2639
> Rename the `Puma::JSON` module to `Puma::JSONSerialization`

- ext/puma_http11/extconf.rb
- ext/puma_http11/mini_ssl.c
PR #2633 throws deprecation warnings in Ruby 3.  Fix by using `Random.bytes` when available.
> minissl.c - Use Random.bytes if available

- ext/puma_http11/extconf.rb
Check for 'pkg_config' when compiling with OpenSSL support.
Closes #1412
> Use pkg_config for OpenSSL if available

- lib/puma/binder.rb
When systemd creates a UNIXSocket with a path that is contained in a symlinked directory, Ruby may read the path as the real path.
Closes #2638
> Binder#parse - allow for symlinked unix path, add create_activated_fds debug ENV

- lib/puma/thread_pool.rb
Fix deadlock issue in thread pool.
This deadlock can happen when a thread is being trimmed, if the main server thread has already accepted a new incoming request and is waiting for the thread pool to not be full.
I was unable to write a test for this (race conditions are hard to reproduce!), but I was able to confirm this is a regression introduced in 5.0 by #2220. Previously, Puma did call `not_full.signal` when a thread was being trimmed: https://github.com/puma/puma/blob/v4.3.8/lib/puma/thread_pool.rb#L109.
I'm happy to add a test if anyone has suggestions for how to write one :)
Fixes #2655.
> Fix deadlock issue in thread pool

- lib/puma/server.rb
- lib/puma/thread_pool.rb
- test/test_thread_pool.rb
Include the name of the server in thread pool threads.
This change makes it easier to distinguish between the threads created by the pools for the main server and the control server.
> Better names for thread pool threads

- CONTRIBUTING.md
Related to the comment at https://github.com/puma/puma/pull/2656#pullrequestreview-699284873
(We don't have the changelog check anymore.)
> CONTRIBUTING: update section about changelog [ci skip]

- docs/deployment.md
modify docs/deployment.md: `preload!` -> `preload_app!`
> `preload!` -> `preload_app!` in docs/deployment.md [ci skip]

- docs/deployment.md
I noticed in #2663 that we had some redundant restart documentation. I replaced it with a reference to the authoritative restart docs.
> Reference restart docs from deployment docs [ci skip]

- lib/puma/client.rb
- lib/puma/cluster.rb
- lib/puma/cluster/worker.rb
- lib/puma/minissl.rb
- lib/puma/request.rb
- lib/puma/server.rb
- test/helpers/integration.rb
Replace `IO.select` with `IO#wait_readable`/`IO#wait_writable` when checking a single IO.
This changed an intermittent macOS issue into something stable, which was an `Errno::EPIPE` error being raised when a client writes to a UNIXSocket, and the server is closing.  Fixed in test file.
> Replace IO.select with IO#wait_* when checking a single IO

- History.md
I'm pretty sure History.md is mostly automatically generated and then manually cleaned up, but I think https://github.com/puma/puma/pull/2656 probably should've made the cut.
> Add threadpool deadlock fix to history for 5.4.0 [ci skip]

- docs/systemd.md
This pull request fixes a link in the documentation.
In systemd.md, a link to GH issue is broken. 
https://github.com/puma/puma/blob/9e2f5d12b259ce0e7664ddcb8570425996e40bc9/docs/systemd.md
Because the link notation needs a URL reference bottom of the document, but it doesn't exist.
This PR adds the URL reference. The link will work.
https://github.com/pocke/puma/blob/f788c40b07b80cffb84d2e8e28cf3e8b04964ce8/docs/systemd.md
> [doc] Add missing link to GH issue in systemd.md [ci skip]

- .github/workflows/mri.yml
- .github/workflows/non_mri.yml
https://github.blog/changelog/2021-08-16-github-actions-macos-11-big-sur-is-generally-available-on-github-hosted-runners/
> Add macOS 11 Big Sur to CI

- Gemfile
Currently, the Puma Gemfile has rack restricted to `"~> 1.6"`.  The current Rails Gemfile.lock is using [`rack (2.2.3)`](https://github.com/rails/rails/blob/e9f38a164e36104cc495d5ac5859e57f6be75f36/Gemfile.lock#L354).
Maybe we should use `">= 1.6.13"`, as older Ruby version will still test with `1.6`...
> Gemfile - update Rack to >= 1.6.13

- README.md
- puma.gemspec
Puma uses threads, which execute in parallel. Threads which can't execute in parallel may be considered concurrent, but it's a degenerate form of parallelism i.e. multiple threads which are sharing a single processor would be considered to running concurrently. It would be good to see a consistent use of this terminology, although I suspect there will be people who have a different interpretation.
Parallelism should be used to describe simultaneous execution. Concurrency should be used to describe interleaved execution.
> Prefer to use "parallel" rather than "concurrent". [ci skip]

- lib/puma/launcher.rb
- test/bundle_app_config_test/.bundle/config
- test/bundle_app_config_test/Gemfile
- test/bundle_app_config_test/config.ru
- test/test_preserve_bundler_env.rb
Without this, if puma is launched with BUNDLE_APP_CONFIG set, that will
be lost inside of unbundled_env, which causes the worker processes to use a
potentially different bundler configuration.
Closes #2687
> Preserve BUNDLE_APP_CONFIG on worker fork

- README.md
- lib/puma/cli.rb
Personally, I think `puma -C "-"` is pretty opaque, but `puma --no-config` is a bit easier to understand at glance.
This is totally my opinion, but I feel like it's an improvement and doesn't risk changing the old behavior unintentionally.
I'm also not quite sure how to best test this, so if there are any suggestions I'm happy to jump on that!
> Add a semantic CLI option for no config file

- lib/puma/dsl.rb
- test/test_config.rb
fixes what seems to be a simple typo, now it behaves like expected
Do you think any test is needed for it?
> allow multiple after_worker_fork hooks

- lib/puma/client.rb
- lib/puma/const.rb
- lib/puma/dsl.rb
- lib/puma/server.rb
- test/test_puma_server.rb
This adds support for parsing the [PROXY Protocol](http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) (version 1 only). It's behind the `set_remote_address` feature when invoked like `set_remote_address proxy_protocol: :v1`. I put the `v1` in there in case some bold soul wants to add v2 support at some point.
This gracefully handles the case where the client doesn't send the PROXY protocol and falls back to normal logic.
Closes #2651
> add support for the PROXY protocol (v1 only)

- test/helper.rb
- test/test_puma_localhost_authority.rb
- test/test_puma_server_ssl.rb
1. Move SSLEventsHelper to test/helper.rb, fixes `warning: method redefined`
2. Collapse 'Debugging Info' in Actions log
3. Fix 'shadowed variable' warning
> Test Fixes

- lib/puma/minissl.rb
When the server wants to close a persistent SSL connection
because it was idle for `persistent_timeout`, the call stack is:
Reactor.wakeup!
Server#reactor_wakeup
Client#close
MiniSSL::Socket#close
The close method is called from within the reactor thread.
In this case, `should_drop_bytes?` is true, because `@engine.shutdown`
is false the first time it is called.
Then, `read_and_drop(1)` is called, which starts by selecting on the
socket. Now because this is a server-initiated close of an idle
connection, in almost all cases there will be nothing to select,
and hence the thread will just wait for 1 second.
Since this is called by the reactor, the reactor will halt for 1 second
and not be able to buffer any data during that time, which has huge
effects on overall worker throughput.
Now I'm …
> Fix performance of server-side SSL connection close.

- lib/puma/server.rb
- test/helpers/integration.rb
- test/rackup/close_listeners.ru
- test/test_integration_single.rb
> More elaborate exception handling.

- README.md
Also, the GitHub project description mentions "Concurrency" but I believe it's better to use "Parallelism" here for consistency.
> Fix missing `Concurrency` -> `Parallelism`.

- README.md
- lib/puma/configuration.rb
- lib/puma/control_cli.rb
- test/test_cli.rb
- test/test_config.rb
- test/test_pumactl.rb
Using APP_ENV to set the environment is supported by Sinatra and
Sidekiq, so it makes sense to support the same behavior in Puma.
Like Sidekiq, APP_ENV will take precedence over RACK_ENV and RAILS_ENV.
APP_ENV defers to any argument passed via the --environment flag.
> Add support for APP_ENV environment variable

- test/test_cli.rb
Some tests were removed in a6cdca8 because they weren't really testing any functionality. I'm attempting to add those tests back, but with some real functionality being tested.
> Reimplement delete environment tests

- README.md
Since localhost v1.1.9 (https://github.com/socketry/localhost/commit/a4fe7db33c4a2da966e2faf93d33c4e005e912f2) just `require "localhost"` works: https://github.com/puma/puma/pull/2610#issuecomment-923354385
Close https://github.com/puma/puma/issues/2706
> Improve localhost SSL integration docs [ci skip]

- lib/puma/cluster.rb
- lib/puma/cluster/worker.rb
- lib/puma/runner.rb
Looking through this file, I noticed some identical code that could be cleaned up.
This is only better subjectively, but I didn't see anything re: refactors in the contributing doc. If Puma tends to avoid style-oriented refactors like this one without a strong rationale, feel free to close this PR.
> Clean up some duplicated code

- lib/puma/client.rb
- lib/puma/cluster/worker.rb
- lib/puma/minissl.rb
- lib/puma/runner.rb
- lib/puma/server.rb
- lib/puma/util.rb
- test/test_busy_worker.rb
- test/test_out_of_band_server.rb
Move calls to Thread#purge_interrupt_queue to a module function. This
means if/when this pattern needs to change it can change in one place
instead of a dozen or more places.
> Extract calls to purge_interrupt_queue

- .github/workflows/non_mri.yml
It does not seem useful (redundant with running it on CRuby), makes builds slower, and also sometimes makes builds fail: https://github.com/puma/puma/runs/4047984193?check_suite_focus=true
> Do not run rubocop on non-CRuby

- lib/puma/detect.rb
- test/helpers/integration.rb
- test/test_integration_cluster.rb
- test/test_integration_single.rb
Attempt to fix several intermittent failures in CI.  Small changes to test files, with one addition (`Puma::IS_OSX`) to lib/ext files.
Continuation of PR #2738.
> Fix intermittent CI issues

- ext/puma_http11/mini_ssl.c
- lib/puma/binder.rb
- lib/puma/dsl.rb
- lib/puma/minissl.rb
- lib/puma/minissl/context_builder.rb
- test/test_binder.rb
- test/test_config.rb
- test/test_integration_ssl.rb
- test/test_minissl.rb
- test/test_puma_server_ssl.rb
We need a way to specify cert and key objects or PEM strings in Puma configuration without relying on file paths. The use-case is when deploying to cloud provider and fetching certificates from Secrets Manager on application boot-up to avoid persisting the certificates on disk for security reasons.
- This PR is more than 100 lines, but it all comes together to support this feature 
- Other than some randomly failing tests, there is a failing build for [ubuntu-20.04 truffleruby-head](https://github.com/puma/puma/runs/4002932158?check_suite_focus=true) on master.
PR with clean history for: https://github.com/puma/puma/pull/2719
> Support for cert_pem and key_pem with ssl_bind DSL

- ext/puma_http11/org/jruby/puma/MiniSSL.java
Was reviewing the JRuby native bits and noticed a few low hanging fruits around unnecessary byte[] copying.
The `String` instances retrieved from `read` / `extract` will now be ASCII-8BIT just like the C bits (w `rb_str_new`).
Also, the exception handling seems to be incomplete thus it would be better to allow to raise the original exception instead of dummy wrapping into a Java `RuntimeException`, and where wrapping is present let's have the original Java cause around.
> [jruby] a couple refactorings - avoid copy-ing bytes

- test/test_cli.rb
- test/test_thread_pool.rb
1. `test_thread_pool.rb` - newer RuboCop fixes - fix RuboCop issue (newer RuboCop)
2. `test_cli.rb` - fix (?) CI itermittent error. See https://github.com/puma/puma/runs/4073168355?check_suite_focus=true#step:9:602
```
TestCLI#test_control_clustered:
Errno::EAGAIN: Resource temporarily unavailable
/Users/runner/work/puma/puma/test/test_cli.rb:28:in `sysread'
/Users/runner/work/puma/puma/test/test_cli.rb:28:in `wait_booted'
```
> CI - itermittent fix and RuboCop

- lib/puma/request.rb
- lib/puma/server.rb
- test/test_puma_server.rb
- test/test_response_header.rb
Always send what the lowlevel_error handler returns to the client.
Refactors some code out of `Request#handle_request` to a new `Request#write_response` that can be used from `Server` to send the response from `lowlevel_error`
Closes #2341
> Always send lowlevel_error response to client

- test/helpers/integration.rb
- test/test_integration_cluster.rb
1. Currently, integration tests stop the CI if a response read timeout happens.  Catch the error and flunk the test.
2. There are two methods in `test_integration_cluster.rb` that are used when generating several requests.  One had a read timeout set to 20 seconds, the other (which has failed recently) had the timeout set to the default of 10.  Increase to 15.
These timeout errors seem to have recently increased, may be due to a change in Actions runners...
> [CI] Fix Timeout Errors when reading responses

- test/helpers/integration.rb
With recent CI, starting sub-processes may not happen as quickly as in the past.  This results in failures if objects are not yet initialized when used.
These changes fix the failure shown in https://github.com/puma/puma/runs/4093551821?check_suite_focus=true#step:9:570
```
test/helpers/integration.rb:118:in `wait_for_server_to_boot': undefined method `include?' for nil:NilClass (NoMethodError)
from test/helpers/integration.rb:284:in `block in hot_restart_does_not_drop_connections'
```
> [CI] integration.rb - allow for nil in wait_for_server_to_boot

- lib/puma/server.rb
Handle `@notify.close` in the same manner as `@check.close`
CI has very infrequent failures.  See https://github.com/puma/puma/runs/4085098935?check_suite_focus=true#step:9:385, which had the following error:
```
/Users/runner/work/puma/puma/lib/puma/server.rb:384:in `close': Bad file descriptor (Errno::EBADF)
from /Users/runner/work/puma/puma/lib/puma/server.rb:384:in `handle_servers'
from /Users/runner/work/puma/puma/lib/puma/server.rb:261:in `block in run'
```
> server.rb - rescue handling (`Errno::EBADF`) for `@notify.close`

- lib/puma/client.rb
Spotted happening in CI: https://github.com/puma/puma/runs/4095295281?check_suite_focus=true
2021-11-03 16:34:54 +0000 Exception handling servers: #<Errno::EBADF: Bad file descriptor>/Users/runner/work/puma/puma/lib/puma/client.rb:163:in `close': Bad file descriptor (Errno::EBADF)
TestRackServer#test_large_post_body =
from /Users/runner/work/puma/puma/lib/puma/client.rb:163:in `close'
Related to #2700? (that changed `rescue Object` to `IOError, Errno::EBADF` and re-raises these two)
See also #2312 that added `Errno::EBADF` (and #2745 that improves on that)
> Rescue `Errno::EBADF` in `Client#close`

- test/config/ssl_config.rb
Make `puma -C test/config/ssl_config.rb` works out-of-the-box. Looks
like tests haven't complained because `test_ssl_configuration_from_DSL`
doesn't actually start Puma.
> Use correct paths in test/config/ssl_config.rb

- ext/puma_http11/extconf.rb
Older Windows builds could compile with the wrong OpenSSL if more than one exists on the system.  This occurs with the Actions windows-2019 image.  Previous output from test log below:
```
Puma::MiniSSL                   OpenSSL
OPENSSL_LIBRARY_VERSION: OpenSSL 1.1.1  11 Sep 2018      OpenSSL 1.0.2j  26 Sep 2016
OPENSSL_VERSION: OpenSSL 1.1.1l  24 Aug 2021     OpenSSL 1.0.2j  26 Sep 2016
```
CI did pass with the incorrect OpenSSL version, but if the app loaded Ruby's OpenSSL, two different OpenSSL libraries would be loaded.  Also, the install wouldn't be portable.  Probably not a good thing...
> extconf.rb - fix openssl with old Windows builds

- test/test_puma_server_ssl.rb
In Ubuntu 22.04 (development release), we have got the following error:
```
1) Failure:
TestPumaServerSSLClient#test_verify_fail_if_client_unknown_ca [/tmp/autopkgtest.nnOHcD/build.YFu/src/test/test_puma_server_ssl.rb:306]:
Expected /self\ signed\ certificate\ in\ certificate\ chain/ to match # encoding: ASCII-8BIT
\#    valid: true
"OpenSSL certificate verification error: self-signed certificate in certificate chain - 19".
```
Changing the expected error message from "self signed certificate" to "self-signed certificate" fixes the test failure.
> Fix error message in test_verify_fail_if_client_unknown_ca

- docs/signals.md
SIGINFO (added in #1320) is missing from docs. Not sure if this should mention that SIGINFO  is not supported in Linux?
> Add SIGINFO to documentation [ci skip]

- test/helpers/integration.rb
- test/test_integration_cluster.rb
- test/test_preserve_bundler_env.rb
Integration tests have been causing CI failures.  Update code to (hopefully) eliminate most of the failures.
The main change is the addition of `#read_response` to `helpers/integration.rb`, which replaces the current `#read_body`.  This method was taken from the updated test framework I've been working on.  It's not a full-on replacement for net/http, but it processes the response to a much greater degree than the current code.
> [CI] Fix intermittent integration test failures/errors

- lib/puma/cluster.rb
- lib/puma/cluster/worker.rb
- lib/puma/configuration.rb
- lib/puma/const.rb
- lib/puma/dsl.rb
- test/helpers/integration.rb
- test/test_integration_cluster.rb
- test/test_launcher.rb
This PR adds support for changing the worker check interval. Previously, the interval was hardcoded to 5 seconds.
> Add worker_check_interval configuration option

- CONTRIBUTING.md
- test/helper.rb
Useful if you want quicker feedback when you know something fails
instantly, example:
rerun -x -c -- TEST_CASE_TIMEOUT=2 bundle e m test/test_integration_ssl.rb:126
> tests: add `TEST_CASE_TIMEOUT`

- lib/puma/cluster/worker.rb
- lib/puma/plugin.rb
- lib/puma/runner.rb
- lib/puma/server.rb
- lib/puma/thread_pool.rb
- test/test_integration_cluster.rb
- test/test_thread_pool.rb
Keep thread names under 15 characters.
Linux thread names are limited to 15 characters. Trying to set a longer name will just silently do nothing 😡 
This PR ensures that all threads created by Puma have names that are 15 characters or shorter. Who needs vowels anyway.
> Keep thread names under 15 characters

- lib/puma/server.rb
server.rv - refactors code involving `@options[:remote_address]`used to initialize Client objects.
Refactors often involve personal code preferences. I felt this was an improvement, but I don't feel strongly about it...
> server.rb - refactor code using @options[:remote_address]

- .github/workflows/mri.yml
- .github/workflows/non_mri.yml
Currently, GitHub Actions supports 20 concurrent Ubuntu/Widows jobs and 5 concurrent macOS jobs.  Below is the job count before and after this PR:
```
Ubuntu/Win  macOS   Total
Current CI  MRI         22        16      38
non-MRI      5         4       9
Total       27        20      47
PR CI       MRI         25        11      36
non-MRI      5         4       9
Total       30        15      45
```
Since there are currently 20 macos jobs, there are 4 sets that run.  Ubuntu/Widows only requires 2 sets (20 + 7).  This PR adjusts the number of macos jobs to 15, so three sets run.  Hence, speeding up CI.
Other changes:
1. Installed gems are cached by setup-ruby (thanks for @eregon's work)
2. A job is added with Ubuntu master using yjit
3. windows-2022 image is used
4. Windows master ucrt …
> Revise Actions workflows - fewer macos jobs, use Bundler cache, windows-2022, yjit job

- test/test_pumactl.rb
Here's a small hotfix to remove the pid-file in the end of the test.
> [CI] Remove the t3-pid file after tests

- .github/workflows/mri.yml
- Gemfile
- Rakefile
- lib/puma/thread_pool.rb
From https://github.com/puma/puma/pull/2779
>Most recent RubyGems versions go with Psych >= 4.0 that breaks the RuboCop rake task. We use an old RuboCop version to target Ruby 2.2. So, we cannot upgrade RuboCop to latest and we have to patch it to work with the newer Psych versions.
>
>We're also fixing some CI warnings for Ruby versions 2.3 - 2.5 for RubyGems versions having a bug that prevents `required_ruby_version` from working for Bundler.
>
>You can see the failing CI builds here: https://github.com/puma/puma/actions/runs/1619499856.
but instead of patching RuboCop we bump it to the last version that still supports Ruby 2.2.
Close https://github.com/puma/puma/pull/2779
> Bump RuboCop to work with newer Psych versions

- .github/workflows/mri.yml
https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/
> CI: Add Ruby 3.1

- lib/puma/cluster.rb
- lib/puma/configuration.rb
- lib/puma/dsl.rb
- test/test_integration_cluster.rb
This PR adds support for an alternate worker culling strategy: instead of culling the workers at the end of the internal worker list (which in all likelihood are the most recently started workers), setting the new `worker_culling_strategy` configuration option to `oldest` will cull the workers which were started the longest time ago.
This strategy makes it easier to implement a rolling restart of workers. This would be useful for us because our workers tend to leak memory over time. While of course the right thing to do would be write good code that does not leak memory :D in practice it's very hard and replacing workers every so often is a cheap and easy strategy.
> Alternate worker culling strategy

- lib/puma/cli.rb
- lib/puma/launcher.rb
- lib/puma/state_file.rb
- test/test_cli.rb
Update code and tests for StateFile:
1. remove yaml requirement for lib code
2. improve tests
3. deprecate lib constants only used for testing
> Remove yaml (psych) requirement in StateFile

- docs/architecture.md
- lib/puma/binder.rb
- lib/puma/dsl.rb
- test/test_binder.rb
- test/test_config.rb
- test/test_thread_pool.rb
We're adding option for setting the socket backlog value with the `ssl_bind` DSL, and updating the docs with a hint to the `net.core.somaxconn` sysctl value. What's interesting here is that on older Linux kernels it defaults to 128 ([reference](https://github.com/torvalds/linux/blob/ca2ef2d9f2aad7a28d346522bb4c473a0aa05249/Documentation/networking/ip-sysctl.rst#tcp-variables)), so the actual backlog value is capped to it.
> somaxconn - INTEGER
> Limit of socket listen() backlog, known in userspace as SOMAXCONN. Defaults to 4096. (Was 128 before linux-5.4) See also tcp_max_syn_backlog for additional tuning for TCP sockets.
Even with the default backlog value of 1024 (when kernel allows it), we are seeing some requests get dropped (504 errors with AWS ALB). That happens with a super fast …
> Allow backlog parameter to be set with ssl_bind DSL

- ext/puma_http11/mini_ssl.c
- test/test_puma_server_ssl.rb
Fixes `warning: undefining the allocator of T_DATA class Puma::MiniSSL::Engine` which is the result of a (good) change to Ruby master (v3.2.0).
Removes unused variable in test_puma_server_ssl.rb - Fix warning: assigned but unused variable
> Fix warning from Ruby master (will be 3.2.0)

- lib/puma/launcher.rb
Process.respond_to?(:fork) is already defined as Puma.forkable?, so let's use it.
> Cleanup: Replace Process.respond_to?(:fork) with Puma.forkable?

- lib/puma/cluster.rb
- test/test_integration_cluster.rb
PR #2773 introduced `worker_culling_strategy = :oldest` which was designed to improve memory efficiency by culling "leaky" older workers first.
In `:fork_worker` mode however, this option culls worker0 (which tends to be the oldest), which seems contrary to the intention of improving memory efficiency. This will spawn an entirely new worker0 process, and the other childs (n >= 1) will not have any CoW memory share with this process.
Instead, it's better to exclude worker0 from the culling in `:fork_worker` mode.
> In fork_worker mode, worker_culling_strategy "oldest" shouldn't cull worker 0

- .github/workflows/mri.yml
- test/test_integration_pumactl.rb
Currently CI is running on a 'special' branch of MSP-Greg/setup-ruby-pkgs.  It and ruby/setup-ruby have been updated to work with Ruby 3.1 and the new windows-2022 image.  Revert to the normal branches.
Fixes an intermittent error in `test/test_integration_pumactl.rb`
> [CI] Update actions, fix intermittent test error

- CONTRIBUTING.md
- tools/Dockerfile
Ruby 2.6 reaches EoL soon.
[ci skip]
> Use Ruby 3.1 in our Dockerfile

- lib/puma/binder.rb
- lib/puma/dsl.rb
- test/config/ssl_self_signed_config.rb
- test/test_config.rb
- test/test_integration_ssl.rb
> Support `localhost` integration in `ssl_bind`

- lib/puma/cli.rb
- test/test_cli.rb
This PR adds a `-s`, `--silent` option which deactivate Puma messages displayed on the prompt.
Without the option:
```sh
$ bundle exec bin/puma test/rackup/hello.ru
* Puma version: 5.5.2 (ruby 2.6.6-p146) ("Zawgyi")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 88245
* Listening on http://0.0.0.0:9292
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2022-01-18 16:38:07 +0100 ===
- Goodbye!
```
With the option:
```sh
$ bundle exec bin/puma --silent test/rackup/hello.ru
^C%
```
> Adds a --silent option to the CLI

- lib/puma/runner.rb
It's possible for the configured environment to be something other than `RACK_ENV`, e.g. `APP_ENV` or `RAILS_ENV`, but the runner will always log the value of `RACK_ENV`.
This changes the log output to show the configured environment value.
See https://github.com/puma/puma/blob/v5.5.2/lib/puma/configuration.rb#L203
> Log environment using option value

- ext/puma_http11/extconf.rb
- ext/puma_http11/mini_ssl.c
This makes a change for OpenSSL 3 which is recommended by OpenSSL, and also removes the deprecation warnings when compiled with OpenSSL 3.
I've only tested Puma with OpenSSL 3 on Windows, if anyone can test on other platforms, that would be appreciated.  Make sure to use a Ruby that is also compiled with OpenSSL 3.
> Updates for OpenSSL 3

- ext/puma_http11/mini_ssl.c
- ext/puma_http11/puma_http11.c
Fix compile warnings in `ext/puma_http11/mini_ssl.c` and `ext/puma_http11/puma_http11.c`.
Closes #2806
> Fix two 'old-style-definition' compile warning

- lib/puma/request.rb
- lib/puma/server.rb
- test/test_puma_server.rb
- test/test_response_header.rb
This reverts commit f8acac1f0702fea1a4f88d68a40bb2f53650b14c.
In response to https://github.com/puma/puma/issues/2808
> Revert "Always send lowlevel_error response to client (#2731)"

- lib/puma/state_file.rb
- test/test_state_file.rb
Until 5.5.2, empty values were read as `nil`.
Since 5.6.0, empty values are read as `""`.
This PR fixes the incompatibility.
This incompatibility affects [here](https://github.com/puma/puma/blob/e0753de846a1651401343687a22bfd52c97bc72a/lib/puma/control_cli.rb#L271-L272) for example.
> Fix `Puma::StateFile#load` incompatibility

- .github/workflows/non_mri.yml
- test/test_puma_server.rb
* Should workaround https://github.com/oracle/truffleruby/issues/2586
> Use the bundler shipped with ruby for non-MRI

- CONTRIBUTING.md
Drop a stray character which seems to be a slip of the keyboard.
> CONTRIBUTING.md: Drop stray backslash in Markdown [ci skip]

- README.md
Drop a badge which 404'd, in README.
Seems like the feature is no longer there. The link 404s. Dependabot is now a feature of GitHub and not its own organisation.
> Drop defunct "SemVer compliance" badge [ci skip]

- lib/puma/launcher.rb
This PR refactors Launcher#run to increase code readability. It does **not** change any logic or ordering of operations.
Reason: When reading the code of Launcher, initially it wasn't obvious to me how the `@status` variable was used. This makes the control flow much more obvious.
Things to watch out for:
- I added methods `do_run_finished`, `do_graceful_stop`, etc. I'm happy to name these methods something other than `do_xxx`
- I've removed the `# do nothing` condition for `@status == :exit`. Not only is there no need to have a `# do nothing` condition for it, it doesn't appear `@status = :exit` is actually set anywhere in Puma.
> Refactor Launcher#run to increase readability (no logic change)

- lib/puma/cluster.rb
- lib/puma/runner.rb
Add read accessors for `Puma::Cluster`'s `@workers` and `Puma::Runner`'s `@options`.
Somewhat related to #2773, these accessors would make it easier to implement a rolling restart strategy from a thread.
> Add a couple of accessors

- lib/puma/launcher.rb
- lib/puma/launcher/bundle_pruner.rb
- test/test_bundle_pruner.rb
- test/test_launcher.rb
This PR is a refactor which does not change any logic.
Currently, the code related to `prune_bundler` is co-mingled into the `Launcher` class. It can easily be extracted into its own class (I've named it `BundlePruner`) which will increase readability / reduce coupling in `Launcher`.
> Refactor: Extract prune_bundler code into its own class (no logic change)

- test/test_binder.rb
Previous to the PR, `TestBinder#test_ssl_binder_sets_backlog` could cause intermittent failures in itself and other tests.  `TestBinder` is run parallel.
Split `TestBinder` into `TestBinderParallel` and `TestBinderSingle`, and move the test to Single.
The test was stubbing a method, and that can cause issues with parallel testing.  Note that the issue is more common on systems with a high number of cores, and the CI systems are VM's with two cores.
Closes #2825.
> test_binder.rb - split out test causing issues when run parallel

- lib/puma/binder.rb
- test/test_integration_cluster.rb
Closes #2816 
Please review. This change fixes the issue but there are some concerns.
So, the issue was that when reloading the server, the socket was inherited, and it was added to the list of unix sockets, to be removed later (unlike on startup, when pre-existing sockets are excluded from that list).
The problem is that, as it seems to me, for inherited socket there is no way to tell if it was pre-existing or not. Hence the inadvertent result of my fix is that even not pre-existing socket will be preserved. Now, this may be acceptable. As you can see in the table in #2816, in single mode socket file is always preserved.
Another option: I may be mistaken, but from the subsequent code it seems possible to detect if the socket is activated, so it may be possible to prevent activated …
> Do not remove pre-existing socket after USR2+TERM (#2816)

- ext/puma_http11/mini_ssl.c
patch by Theo Buehler <tb@openbsd.org>
Signed-off-by: Aisha Tammy <floss@bsd.ac>
Patch currently used in OpenBSD - https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/www/ruby-puma/patches/
> Fix build with Opaque DH in LibreSSL 3.5.

- ext/puma_http11/puma_http11.c
Fix a mis-understanding in a name.
When I made a small PR to fix a typo, I myself had misunderstood the word used. dentarg, eagle-eye, saw through these typos & mistypes. https://github.com/puma/puma/pull/2502#issuecomment-1065474880
This changes the name of the locally-used `define` to be correctly spelled, and meaning the original thing.
> Re-fix my mistaken typo [changelog skip]

- lib/puma/minissl.rb
- test/test_minissl.rb
Previously if an SSL cert or key could not be read, Puma would bind to
the configured SSL port but not accept any connections. The only
indication that something went awry is an obscure log message:
```
#<Puma::MiniSSL::SSLError: OpenSSL error: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher - 193>
```
We now fail hard with an exception if this happens to make it clear
that the permissions need to be fixed.
Relates to https://github.com/puma/puma/issues/1339
> Fail hard if SSL certs or keys cannot be read by user

- ext/puma_http11/mini_ssl.c
- test/test_puma_server_ssl.rb
Previously if an invalid SSL cert or key (e.g. blank file, mismatching
private and public key, etc.) were specified, Puma would quietly
accept them, bind to the port, and mysteriously fail with an error
only after a client initiates a connection:
```
SSL error, peer: ::1, peer cert: : #<Puma::MiniSSL::SSLError: OpenSSL error: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher - 193>
```
We now check the OpenSSL return values and raise an exception if the
cert or key cannot be loaded. For example:
```
puma/lib/puma/minissl.rb:330:in `initialize': SSL_CTX_use_certificate_chain_file: error in file '/tmp/cert.txt': error:0909006C:PEM routines:get_name:no start line (Puma::MiniSSL::SSLError)
```
> Fail hard if SSL certs or keys are invalid

- lib/puma/dsl.rb
- lib/puma/util.rb
- test/test_config.rb
Filenames with `+` would fail to load because it would be
misinterpreted as a space. Since Puma already unescapes the query
string, we should escape the value to fix this.
We also make `cert` and `key` conditional in the query string because
that gives a clearer error message:
```
ERROR: Please specify the SSL key via 'key=' or 'key_pem='
```
Rather than:
```
puma/lib/puma/minissl.rb:218:in `check_file': Key file '' does not exist (ArgumentError)
```
> Escape SSL cert and filenames

- lib/puma/request.rb
- test/test_rack_server.rb
Currently, when a `rack.after_reply` callable raises an exception we
attempt to handle it like other client errors by responding with an HTTP
500 response. This however doesn't work because `rack.after_reply`
callbacks are called after the response body has already been written to
the client.
This can cause issues with re-used connections. This is because 2 HTTP
responses are being returned for a single request. If a second HTTP
request is made before the error handling logic completes the timing can
line up causing the second HTTP response to be served a 500 from the
first HTTP requests `rack.after_reply` callbacks raising.
That may look roughly like:
1. Request 1 starts, opening a reusable TCP connection
2. Request 1 is written to and "completed"
3. Request 1 `rack.after_reply` …
> Fix rack.after_reply exceptions breaking connections

- Gemfile
- lib/puma/launcher.rb
- test/config/prune_bundler_with_deps.rb
- test/test_bundle_pruner.rb
- test/test_config.rb
- test/test_integration_cluster.rb
1. Circular require issues with Launcher::BundlePruner, which is not always used. Rather than requiring it, autoload it.
2. RDoc is in the Gemfile, which has dependencies on Psych, and StringIO.  Both are extension gems, both may have pre-release gems in Ruby master, etc.  RDoc is used as a 'checked gem' with various Bundler tests.  Remove RDoc and use minitest in its place.
3. Fix two 'warning: assigned but unused variable' from test_config.rb
> Autoload BundlePruner, fix CI

- ext/puma_http11/extconf.rb
- ext/puma_http11/mini_ssl.c
The link for `SSL_CTX_set_dh_auto` is at https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set_dh_auto.html.  But, it doesn't show links to other OpenSSL versions, which many functions do show.
It is defined for OpenSSL 1.1, so change to use function detection.
Closes #2863
> MiniSSL - detect SSL_CTX_set_dh_auto

- README.md
This explains `WEB_CONCURRENCY` as an alternative to the `-w` flag, and how `WEB_CONCURRENCY` can automatically enable preloading.
This also includes some minor edits to "Clustered mode" section for improved flow and clarity.
> Explain `WEB_CONCURRENCY` and relation to preloading [ci skip]

- .github/workflows/ragel.yml
- .github/workflows/tests.yaml
- Gemfile
- Rakefile
- ext/puma_http11/extconf.rb
1. Setting `ENV['PUMA_NO_RUBOCOP']` disables installation and use of RuboCop.  Since we're now doing RuboCop as a separate workflow, the other workflows do not need to install RuboCop and it's dependencies.  This lightens the resolution Bundler needs to do, and makes the bundle caches smaller.  Note that the extension gem [jaro_winkler](https://rubygems.org/gems/jaro_winkler) is a dependency of RuboCop, and it will not compile on mswin.
2. Small changes to allow Puma to build using Ruby Windows mswin build. Add to Actions CI.
> Add ENV['PUMA_NO_RUBOCOP'] to disable RuboCop install, add mswin ci

- lib/puma/null_io.rb
- test/test_null_io.rb
if you try to proxy a request in rails with `rest-client` 
```ruby
RestClient::Request.execute(method: request.method, url: SOME_URL, payload: request.body)
```
if fails with `NoMethodError - undefined method closed? for <#Puma::NullIO:xxx>` because the library does this at the end of the request phase:
```ruby
class RestClient::Payload::Base
def close
@stream.close unless @stream.closed?
end
end
```
> Expose Puma::NullIO#closed?

- lib/puma/cluster.rb
- lib/puma/runner.rb
- lib/puma/single.rb
- test/test_cli.rb
I added puma/ruby versions to the /stats endpoint this way when monitoring puma we have an easy way to know which versions are running, here is an example:
> Minor: Export puma/ruby versions in /stats

- lib/puma/log_writer.rb
- test/helpers/integration.rb
- test/test_integration_pumactl.rb
CI intermittently fails with "log_writer.rb:59:in `write': deadlock; recursive locking (ThreadError)".  This is happening in log writes/puts, and this code maybe called in signal handlers.  Mutex and other locking mechanisms cannot be used in signal handlers, so this PR is an attempt to fix the problem.
Example log:
```
/Users/runner/work/puma/puma/lib/puma/log_writer.rb:59:in `write': deadlock; recursive locking (ThreadError)
from /Users/runner/work/puma/puma/lib/puma/log_writer.rb:59:in `puts'
from /Users/runner/work/puma/puma/lib/puma/log_writer.rb:59:in `log'
from /Users/runner/work/puma/puma/lib/puma/launcher.rb:329:in `log'
from /Users/runner/work/puma/puma/lib/puma/launcher.rb:205:in `close_binder_listeners'
from /Users/runner/work/puma/puma/lib/puma/cluster.rb:329:in `block in …
```
> Fix "log_writer.rb:59:in `write': deadlock; recursive locking (ThreadError)"

- ext/puma_http11/extconf.rb
If installing Puma with `--with-openssl-dir`, `pkg_config('openssl')` may locate the system OpenSSL, which is not desirable.
Hence, only use `pkg_config('openssl')` when `--with-openssl-dir` is not used.
See https://github.com/ruby/openssl/pull/486
This problem has generated a few issues with macOS.  If anyone with multiple OpenSSL installs (and a Ruby that is not using the system OpenSSL), can check this, it would be appreciated.
Note that this PR only affects using `--with-openssl-dir` with a Puma install.
Closes #2839. Not.sure
> extconf.rb - don't use pkg_config('openssl') if '--with-openssl-dir' is used

- .github/workflows/tests.yaml
- test/helpers/integration.rb
- test/test_out_of_band_server.rb
After reviewing far too many CI logs, many retries and intermittent failures/errors were due to problems with error handling in teardown methods, along with a timing related issue in `wait_for_server_to_boot`.  Fixed, and added a CI step to update RubyGems, removing all the extraneous logging of the below:
```
Your RubyGems version (<2.5 and earlier>) has a bug that prevents `required_ruby_version` from working for Bundler
```
> [CI] rescue more errors in teardown & wait_for_server_to_boot methods, RubyGems

- ext/puma_http11/org/jruby/puma/MiniSSL.java
- lib/puma/minissl.rb
- test/test_puma_server_ssl.rb
Puma did not have TLS 1.3 support on JRuby, the feature is now enabled and the protocol is usable by default. Note that TLS 1.3 is available with Java >= 8 (has been backported), current LTS Java version is 11 which was shipped with TLS 1.3 since day 1.
> [jruby] enable TLSv1.3 support

- lib/puma/app/status.rb
- lib/puma/control_cli.rb
- lib/puma/launcher.rb
- test/test_integration_cluster.rb
- test/test_integration_pumactl.rb
- test/test_pumactl.rb
Currently, the refork command will only be sent as a signal by `Puma::ControlCLI`.  Change to allow it be sent as a request if the control server is setup with a uri.
Closes #2866
> Puma::ControlCLI - allow refork command to be sent as a request

- lib/puma/null_io.rb
- test/test_null_io.rb
> NullIO#closed? should return false

- lib/puma/detect.rb
- lib/puma/log_writer.rb
- lib/puma/minissl.rb
- lib/puma/server.rb
In Ruby 3.1 and earlier versions, IO#wait_* methods were contained in the standard library gem `io/wait`.  Ruby 3.2 has moved the methods to the main IO code.  See 'Move wait* methods to io.c' https://github.com/ruby/ruby/pull/6036.
So, `io/wait` does not need to be required for Ruby 3.2 and later.  Adjust code to only require it when needed.
> Ruby 3.2 will have native IO#wait_* methods, don't require io/wait

- lib/puma/launcher.rb
- test/config/rack_url_scheme.rb
- test/rackup/url_scheme.ru
- test/test_integration_single.rb
- test/test_puma_server.rb
Hi 👋 ! Thanks for your work on maintaining Puma!
- ### Problem
The feature to manually set the "rack.url_scheme" header with
Puma's `rack_url_scheme` option (introduced in commit https://github.com/puma/puma/commit/32852f715af9e6eb809284d910e647b8fd6e2ea6) has no effect.
The Configuration object is not yet loaded at the time it's being
passed to the Binder so any options set inside the config file (i.e.
`config/puma.rb`) remains nil.
https://github.com/puma/puma/blob/6a5bda5b4eeb8c86c64468d6916f7d3917e5640a/lib/puma/binder.rb#L45
Worth noting that this is only true for options set inside the
config file. Options passed as args to the CLI
(i.e. `puma -t min_thread:max_thread`) are correctly set
(they get loaded differently).
https://github.com/puma/puma/blob/6a5bda5b4eeb8c86c64468d6916f7d39 …
> Load the configuration before passing it to the binder:

- .github/workflows/tests.yaml
- .rubocop.yml
- Gemfile
- puma.gemspec
1. The Puma 5 gemspec sets Ruby version compatibility to Ruby 2.2 and later.  Update that to Ruby 2.4.
2. Remove Ruby 2.3 and 2.4 from CI testing.
3. This allows using a newer version of RuboCop.  Updated the versions used, and disabled a few Cops to keep CI passing.  
See Issue #1811 'Rev the minimum Ruby Version >= Ruby 2.5' from June 2018.
We could jump to 2.5...
> Puma 6 gemspec - required_ruby_version to Ruby 2.4, RuboCop updates

- .github/workflows/rack2.yaml
- Gemfile
- lib/puma/app/status.rb
- test/helper.rb
- test/test_cli.rb
- test/test_config.rb
- test/test_rack_handler.rb
- test/test_rack_server.rb
Rack 3.0.0 was released today, and breaks CI.
This PR makes the minimal changes needed to pass CI with Rack 3.0.0.
Currently, the Gemfile is `gem "rack", ">= 1.6.13"`.  Not sure if we should add an Actions workflow that runs a couple of jobs with Rack 2.2.x?
> Rack 3.0.0 release

- ext/puma_http11/http11_parser.c
- ext/puma_http11/http11_parser.h
- ext/puma_http11/http11_parser.java.rl
- ext/puma_http11/http11_parser.rl
- ext/puma_http11/http11_parser_common.rl
- ext/puma_http11/org/jruby/puma/Http11.java
- ext/puma_http11/org/jruby/puma/Http11Parser.java
- ext/puma_http11/puma_http11.c
- lib/puma/binder.rb
- lib/puma/request.rb
- test/rackup/env-dump.ru
- test/test_http10.rb
- test/test_http11.rb
The code for the headers HTTP_VERSION & SERVER_PROTOCOL has existed and essentially remained unchanged since possibly the original Puma commit [2011-Sep-22  'Name change: Mongrel => Puma'](https://github.com/puma/puma/tree/190a81c55a1cbf215658b8fd6bb7ce2a0326b6c6).
Currently, SERVER_PROTOCOL is fixed as [`HTTP_11`](https://github.com/puma/puma/blob/20df56b7cabb4e4cada493d51894b08c7406bc4a/lib/puma/binder.rb#L54).  HTTP_VERSION is first set to the protocol from the request 'first line', but if a client defines the header, the value is appended.  Many would consider it to be a mistake to use a header name that could also be used by a client, but that decision was made a long time ago...
For a summary of app servers responses, see @jeremyevans PR comment in …
> Fixup SERVER_PROTOCOL & HTTP_VERSION headers

- lib/puma.rb
Drop the thread name assignment check for Ruby < 2.4. Puma 6 will support Ruby 2.4 so we don’t need to check any more.
> Remove thread name respond to check for Puma 6

- lib/puma/binder.rb
Remove this extra `require 'openssl'` that was introduced 09be7ce92 to help an issue with Ruby 2.3 and Windows.
> Remove the extra require for OpenSSL for Ruby 2.3 on Windows

- .github/workflows/rack2.yaml
- .github/workflows/ragel.yml
- .github/workflows/tests.yaml
- CONTRIBUTING.md
- Rakefile
- test/helper.rb
- test/test_preserve_bundler_env.rb
- test/test_puma_server_ssl.rb
New output:
```
install -c -p -m 755 puma_http11.so /host/nateberkopec/Documents/Code.nosync/upstream/puma/lib/puma
Run options: --seed 52639
SSS................................................................................................................................................................................................S...................................S...............................................S.S...S...........................................S..........................................................................................................................................................................................................
Fabulous run in 133.758721s, 3.9773 runs/s, 11.5731 assertions/s.
532 runs, 1548 assertions, 0 failures, 0 errors, 9 skips …
```
> Removes debug info from tests by default

- benchmarks/local/bench_base.rb
- benchmarks/local/bench_base.sh
- benchmarks/local/puma_info.rb
- benchmarks/local/response_time_wrk.rb
- benchmarks/local/response_time_wrk.sh
- docs/testing_benchmarks_local_files.md
- docs/testing_test_rackup_ci_files.md
- test/rackup/ci_array.ru
- test/rackup/ci_chunked.ru
- test/rackup/ci_io.ru
- test/rackup/ci_select.ru
- test/rackup/ci_string.ru
- test/rackup/hello.ru
Puma handles four types of response bodies:
* Single element Array
* Multi-element Array
* Enum
* File/IO
This PR provides a shell script and additional files to start a Puma server, then collect and summarize data from one or more 'wrk' runs, varying the body type and size.  Arguments for the shell script allow one to specify one or more body types/sizes.  Default creates 28 wrk runs, using all four above body types and sizes ranging from 1kB to 2,048 kB.
This PR only add files to a new 'benchmarks/local' directory and adds rackup files to 'test/rackup'
> Benchmarks - add ResponseTimeWrk files

- test/rackup/ci_select.ru
- test/rackup/ci_string.ru
Interesting problem.  Ruby 3 doesn't throw a 'frozen string' error, but Ruby 2.7 does.  Fixed.
> test/rackup/ci_*.ru files - fix frozen string issue

- lib/puma/const.rb
- lib/puma/request.rb
- test/test_web_server.rb
Closes https://github.com/puma/puma/issues/1441
I'm trying to fix https://github.com/puma/puma/issues/1441 and to do this I've prepare a proof of concept. I've done two things:
1. Don't raise error on empty `REQUEST_PATH` - it's a completely valid request to send CONNECT without a request path.
2. Handle the fact that puma doesn't support `CONNECT` gracefully by responding with 501.
I'm not sure if I handle both things in the right places. Right now I have a working code with a simple test. I'd be grateful for feedback and hints how to improve the code to make it mergeable.
> Do not raise error on CONNECT

- test/rackup/ci_array.ru
- test/rackup/ci_chunked.ru
- test/rackup/ci_select.ru
- test/rackup/ci_string.ru
When using the test/rackup/ci_*.ru files, previous (original) versions did not cache response bodies.  Larger bodies may use a lot of memory, causing gc issues, etc.  This affects performance benchmarks.
Hence, cache bodies so benchmark results are more accurate.
> test/rackup/ci_*.ru files - cache response bodies

- lib/puma/client.rb
- lib/puma/io_buffer.rb
- lib/puma/request.rb
- test/test_persistent.rb
- test/test_puma_server.rb
- test/test_rack_server.rb
- test/test_response_header.rb
This PR refactors response generation, speeding up operations with various body types and sizes.  It also adds code to better handle the various body types returned by Rails and/or Rack.  Much of this has been worked on by @guilleiguaran, so thanks for his work on it (see #2892).  Essentially, body types fall into five categories:
1. An Array - Puma will determine the content-length if not provided.
2. An Enum - this would be chunked by Puma or sent as is if chunked encoding has already been applied.
3. A File object - dependent on its size, it will either be sent with the headers, or sent after the headers using `IO.copy_stream`.
4. An object that responds to `to_path` - Puma will attempt to open the file, and if successful, will send as above.
5. An object that responds to `call`.
This …
> Response refactor, increase requests-per-second, body type handling

- ext/puma_http11/extconf.rb
- ext/puma_http11/mini_ssl.c
- lib/puma/dsl.rb
- lib/puma/minissl.rb
- lib/puma/minissl/context_builder.rb
- test/test_integration_ssl_session.rb
This PR allows enabling OpenSSL TLSv1.2 session reuse.
This PR only affects code related to https connections and does not change current behavior.
OpenSSL and TLSv1.2 support session reuse via what is referred to as session id.  Opening a tls connection with 'reuse' uses less network resources but requires additional memory on the server.  It may also take cpu time when the session cache is flushed, which happens every 255 connections.
Note that session reuse on TLSv1.3 uses what is referred to as a session ticket, rather than a session id.
Switching session reuse on can be done in a config file, using the `:reuse` key in the options hash passed to [DSL#ssl_bind](https://msp-greg.github.io/puma/Puma/DSL.html#ssl_bind-instance_method).  Using a value of `true` turns on reuse with default …
> OpenSSL - allow session reuse via a 'reuse' ssl_bind method or bind string query parameter

- lib/puma/client.rb
- test/test_puma_server.rb
Why? I was reading the `architecture` document and looked at `request_body_wait`. I remember concurrent-ruby has a change https://github.com/ruby-concurrency/concurrent-ruby/pull/915 that powers Rails to have float milliseconds in some places (https://github.com/rails/rails/pull/43502). 
Thought it will be useful for people to have better precision for this metric.
After this PR, People will get more precisions for this metric (3 more digits)
```ruby
> Process.clock_gettime(Process::CLOCK_MONOTONIC, :millisecond)
=> 391179141
> Process.clock_gettime(Process::CLOCK_MONOTONIC, :float_millisecond)
=> 391181147.258
```
This metric was first introduced at https://github.com/puma/puma/pull/1569.
> Support request_body_wait metric with higher precision

- docs/fork_worker.md
- lib/puma/cluster.rb
Followup: https://github.com/puma/puma/pull/2099
So far it was incompatible because true phased restart are incompatible with `preload_app`.
But `fork_worker` doesn't do a phased restart per say, it just piggy back on the implementation to ask worker #0 to refork its siblings.
So we can just bypass that check and it works.
> Allow to use `preload_app!` with `fork_worker`

- ext/puma_http11/mini_ssl.c
Spent most of this evening working with [ruby_memcheck](https://github.com/Shopify/ruby_memcheck).  Code in this PR fixes a few memory leaks, some of which occur when improper data is used to create an SSL connection/listener.
All of the other results were calling `rb_define_` functions, which may be false positives.  Or, these are Ruby functions that are called when one requires Puma, as they are the functions that allow Ruby to know that a `Puma` module, or a `Puma::Server` class exist.
Note that the changes fix leaks in an object that is created once for each SSL listener.  I believe there are no leaks on the client/ request/accepted socket level.
I need to spend some more time working with ruby_memcheck...
> minissl.c - immediate ruby_memcheck fixes

- lib/puma/server.rb
- test/test_integration_ssl.rb
- test/test_persistent.rb
- test/test_puma_server.rb
- test/test_response_header.rb
from https://github.com/puma/puma/pull/2918#issuecomment-1247089134.
> Remove unused attr_writer

- lib/puma/control_cli.rb
Remove unused `Puma::ControlCLI::COMMANDS` for Puma 6.
> Remove unused Puma::ControlCLI::COMMANDS for Puma 6

- lib/puma/state_file.rb
Remove unused `StateFile::FIELDS` for Puma 6.
> Remove unused StateFile::FIELDS for Puma 6

- lib/puma/request.rb
The code says make it private for Puma 6. Complete this todo.
Make Request `normalize_env` method private for Puma 6.
> Make Request normalize_env private for Puma 6

- lib/puma/cli.rb
- lib/puma/launcher.rb
Remove unused `KEYS_NOT_TO_PERSIST_IN_STATE` for Puma 6.
> Remove unused KEYS_NOT_TO_PERSIST_IN_STATE for Puma 6

- lib/puma/cluster/worker.rb
- lib/puma/configuration.rb
- lib/puma/dsl.rb
- test/config/hook_data.rb
- test/helpers/integration.rb
- test/test_integration_cluster.rb
See #2915 'Callbacks for app lifecycle?'.
When one calls DSL methods to register callbacks **inside of the fork block** (`on_worker_boot`, `on_worker_shutdown`, & `on_refork`), adds a parameter that is used as a key.  It can be a String or a Symbol, and it defines which callbacks a Hash object is passed to.
This allows the hooks to access objects stored in a hook called earlier.
See comments added to the DSL class.
Closes #2915
> Allow `run_hooks` to pass a hash to blocks for use later

- lib/puma/launcher.rb
- lib/puma/runner.rb
- lib/puma/server.rb
- test/test_busy_worker.rb
- test/test_integration_ssl.rb
- test/test_log_writer.rb
- test/test_out_of_band_server.rb
- test/test_persistent.rb
- test/test_puma_localhost_authority.rb
- test/test_puma_server.rb
- test/test_puma_server_ssl.rb
- test/test_request_invalid.rb
- test/test_response_header.rb
- test/test_web_server.rb
#2798 introduced a change to the paramenters passed to `Server#initialize`.  This may affect repo's using Puma for testing.
Revert the change and adjust other lib files & test files.
> Revert change to Server#initialize (new) method signature from #2798

- lib/puma.rb
- lib/puma/app/status.rb
- lib/puma/binder.rb
- lib/puma/cli.rb
- lib/puma/client.rb
- lib/puma/cluster.rb
- lib/puma/configuration.rb
- lib/puma/control_cli.rb
- lib/puma/dsl.rb
- lib/puma/error_logger.rb
- lib/puma/launcher.rb
- lib/puma/log_writer.rb
- lib/puma/minissl.rb
- lib/puma/plugin/tmp_restart.rb
- lib/puma/rack/builder.rb
- lib/puma/rack_default.rb
- lib/puma/reactor.rb
- lib/puma/runner.rb
- lib/puma/server.rb
- lib/puma/single.rb
- lib/puma/thread_pool.rb
- lib/rack/handler/puma.rb
Change use of `require` to `require_relative` where appropriate.
Closes #2902
Actions macOS runners seem to be having some issues.
> require to require_relative

- .github/workflows/rack2.yaml
- .github/workflows/ragel.yml
- .github/workflows/tests.yaml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- lib/puma.rb
- lib/puma/cli.rb
With the change in PR #2965, if a 'non-standard' (normally directly creating a `Server`) Puma use needs a specific type of LogWriter, it may be created before `Server.new` is called, as it's passed an option value.  In normal Puma initialization, the LogWriter is loaded earlier, and also in `Server`.  And for these applications, `Server` is autoloaded.
Hence, autoload `LogWriter` to cover 'non-standard' Puma uses.
Note that previous uses (before `Events` was 'split' into `LogWriter` and `Events`), with `Events` as a possible parameter, it was called as a parameter to `Server.new`, so `Events` was loaded by the autoloaded `Server`.
> puma.rb - autoload LogWriter for non-standard loading

- lib/puma/cluster.rb
- lib/puma/cluster/worker.rb
- lib/puma/runner.rb
- lib/puma/single.rb
Runner & subclasses - @launcher is duplicated, other instance variables in Runner are not used in subclasses and should be.
> Runner & subclasses - instance variable cleanup

- lib/puma/binder.rb
- lib/puma/cluster.rb
- lib/puma/runner.rb
`Binder.new` sets a `LogWriter` instance variable, and `Binder.parse` also takes a `LogWriter` as a parameter.  Cleanup, make it optional in `#parse`.
> Updates for LogWriter

- lib/puma/error_logger.rb
- lib/puma/log_writer.rb
Fixes intermittent errors when logging.  Changes to LogWriter & ErrorLogger.  Writing to io from multiple threads needs some form of locking so deadlock errors do not occur.
Appreciate anyone else testing/checking it.
> Stop 'deadlock; recursive locking (ThreadError)' in LogWriter

- test/helpers/integration.rb
- test/test_integration_cluster.rb
- test/test_integration_single.rb
- test/test_plugin.rb
- test/test_puma_server.rb
- test/test_rack_server.rb
1. **'Fix wait_for_server_to_boot failures when restarting'** - Most CI failures (excluding platform failures) seem to be due to logging issues (see #2967) or issues with reading the log when booting, often when restarting.  Add code to better account for IO issues when restarting.
2. **'[CI] Update hot_restart tests for Windows'**
3. **'[CI] test_rack_server.rb - require "rack/body_proxy"'** - Rack autoloads the file, issues when run parallel in tests.
4. **'[CI] fixups for test teardown code'** - teardown code closes IO objects, add better error handling if they've been closed or destroyed.
'
> [CI] - fixup various test suite issues

- test/test_puma_server.rb
Minitest stub is generic, we have the object we need to stub, so use singleton_class.
Fixes intermittent errors like:
```
1) Failure:
TestPumaServer#test_accept_emfile [test/test_puma_server.rb:1292]:
Expected EMFILE error not logged.
Expected "" to not be empty.
```
> [CI] test_puma_server.rb - running parallel, fixup tests that stub

- test/config/plugin1.rb
- test/helper.rb
- test/helpers/integration.rb
- test/test_persistent.rb
- test/test_plugin.rb
- test/test_puma_server.rb
The last CI run failed in a JRuby job. `test_plugin.rb` uses a control server, and it was being started via `IO.popen`.  We should keep the calls to `IO.popen` to a minimum, as they're slow.  `integration.rb` has code to start the control server in the test process, and grabs the output with a pipe.  Fixed up the file.
Also, changed several instances of `IO.select` that were operating on a single io to use `IO#wait_*`.
> [CI] fixup test_plugin.rb, change IO.select to IO#wait_*

- test/test_integration_cluster.rb
Incorrect code in one of the 'Performance/ChainArrayAllocation' updates.
`#compact!` returns `nil` if no changes were made.
Or, several Array bang methods may not return the array operated on.  Hence, when rewriting chained array methods, never use the return value of a bang method call.
Sorry, I was working on #2976 intermittently yesterday, and should have waitied until this morning to check the code...
> [CI] PR #2976 - Fix RuboCop mistake - test/test_integration_cluster.rb

- test/helper.rb
- test/helpers/integration.rb
- test/test_puma_server_ssl.rb
There are still intermittent failures in CI.  These changes may help.  There are also two file updates, one is just a refactor, the other changes the debug logging output.
Recent jobs in my fork, showing one job with a test step failure:
```
Load
Run  OS / Ruby      Ruby   Compile   Test
195  macOS-12 3.0   0:22      0:11    3:21 passed
196  macOS-12 3.0   7:31      3:30   10:12 failed (timed out)
196  macOS-12 3.1   0:21      0:12    3:20 passed
```
Notice the increased times in the failed job.
Tests are random and parallel, which can affect test time.  Conversely, the 'Load Ruby' and 'Compile' steps should have consistent times.  In the failing job, those times are well over an order of magnitude slower...
I don't think we can accommodate variances like that in CI.  Although everyone …
> [CI] misc updates to test files

- test/test_integration_cluster.rb
- test/test_integration_single.rb
- test/test_launcher.rb
- test/test_pumactl.rb
Some of the tests requiring disk files will intermittently fail, and code may stop before `unlink` calls.  This may hinder test 'retry'.
Place all `File.unlink` calls in an ensure section of the test method.
> [CI] test files - use unlink in ensure when appropriate

- CONTRIBUTING.md
We link to https://wilsonmar.github.io/maximum-limits/, which still looks like a good resource, but it is ~4 years old now and talks a lot about older macOS versions. I found that `sudo launchctl limit maxfiles ...` didn't do anything for me in macOS Monterey. Let's just include the simple command to change the limit for the current session in our guide.
> CONTRIBUTING: spell out how to change ulimit [ci skip]

- lib/puma/client.rb
- lib/puma/cluster/worker.rb
- lib/puma/cluster/worker_handle.rb
- lib/puma/request.rb
Use `:nodoc:` and add a comment that isn't parsed (note the two blank lines after it) to the following classes/modules:
* Client
* Cluster::Worker
* Cluster::WorkerHandle
* Request
The comment is added to clarify the API status, especially if people are unfamiliar with `:nodoc:`.
Some classes/modules really shouldn't be part of the public API, as changes to the public API should only be done with major version updates.
A super top secret, double overtime folder exists at https://msp-greg.github.io/puma_test/ which shows how these changes would appear in docs.
Comments?  Add more classes/modules?
> Use :nodoc: to limit public API [ci skip]

- 6.0-Upgrade.md
- History.md
> Document that `DefaultRackup` et al. was removed [ci skip]

- 6.0-Upgrade.md
Remove confusing note about non-existent change in server initialization method signature.
Change to `Puma::Server#initialize` signature was reverted in https://github.com/puma/puma/pull/2965, however entry about it was left in upgrading notes.
> Remove outdated entry from 6.0-Upgrade.md about server initialization signature [ci skip]

- .github/workflows/tests.yaml
Brownouts are occurring from now until then, CI shows failing.  See https://github.com/actions/runner-images/issues/5583
> [CI] - remove macOS 10.15 jobs, unsupported as of 01-Dec-2022

- test/helper.rb
- test/test_puma_server.rb
When I ran the test `bundle exec ruby test/test_puma_server.rb` locally with `ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]` on macOS, I got two failing tests which complains path is `nil`<sup>[1]</sup>.
With the rewrite the use of `Tempfile`, now it works for my local dev env `for i in $(seq 1 10); do bundle exec ruby test/test_puma_server.rb; done` and CI seems happy, too. 
<details>
<summary>For references docs on <code>Tempfile</code> and <code>IO</code></summary>
- Ruby 2.4: [Tempfile](https://rubyapi.org/2.4/o/tempfile), [IO#binmode](https://rubyapi.org/2.4/o/io#method-i-binmode) and [IO#write](https://rubyapi.org/2.4/o/io#method-i-write)
- Ruby 2.5: [Tempfile](https://rubyapi.org/2.5/o/tempfile), [IO#binmode](https://rubyapi.org/2.5/o/io#method-i-binmode) and …
> Fix path could be nil in test_puma_server tests

- test/helper.rb
- test/test_bundle_pruner.rb
These two test would fail when running tests from a directory not named "puma", e.g. running from docker/podman like this:
podman run -it --rm -v $(pwd):/app -w /app ruby:3.1.2 bash
> TestBundlePruner: do not hard code directory name

- lib/puma/request.rb
- test/test_puma_server.rb
- test/test_rack_server.rb
1. At present, some code paths will not close the app body.  Add code to always hold a reference to the app body, so when code calling `lowlevel_error` is executed, the reference to the app body is maintained.
2. test_rack_server.rb - add test_hijack_body_close - test for above
3. Small refactor of test_puma_server.rb.  Takes too damn long.
4. test_puma_server.rb - add `test_lowlevel_error_body_close` to verify body close call when lowlevel_error
Closes #2999.
> Correctly close app body for all code paths

- lib/puma/reactor.rb
This Pull Request rescues `IOError` when we try to wake up a closed selector.
I noticed there are `IOError`s from this code path (see below). It may be auto-scaling scale up/down an instance. It does not seems to relate to during deployment / restart. I am not really sure. It only happens 4-5 times for the past 30 days in an app (with reasonable, constant traffic) I am working on.
```ruby
vendor/bundle/ruby/2.7.0/gems/puma-5.6.4/lib/puma/reactor.rb:51:in `wakeup': selector is closed (IOError)
from vendor/bundle/ruby/2.7.0/gems/puma-5.6.4/lib/puma/reactor.rb:51:in `add'
from vendor/bundle/ruby/2.7.0/gems/puma-5.6.4/lib/puma/server.rb:470:in `process_client'
from vendor/bundle/ruby/2.7.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```
Seems like similar to …
> Handle waking up a closed selector in Reactor#add

- lib/puma/client.rb
- lib/puma/request.rb
- lib/puma/server.rb
- lib/puma/thread_pool.rb
Currently, an [IOBuffer](https://github.com/puma/puma/blob/f323d129bc16/lib/puma/io_buffer.rb) object is created in each thread in each ThreadPool (one per worker).  This object is used to assemble response headers, and also may contain parts or all of the response body.
It is shared among all clients/connections processed in the thread.  The data is cleared after every request.  But, given all the code paths, etc, if it was not cleared, it could leak headers between responses from different clients.
No one has reported this occurring.  Regardless, it is a relatively lightweight object subclassed from StringIO (a default gem in Ruby), so rather than share an instance with clients in a thread, remove it from the thread, and add it to the Client class.  Doing so makes it impossible for data …
> Add IOBuffer to Client, remove from ThreadPool thread instances

- test/helpers/integration.rb
- test/test_rack_server.rb
**Update test_rack_server.rb** - when working with `test_hijack_body_close` in my fork, it seemed that Window and non_MRI jobs needed a small delay.  Recently I saw the same error on a macOS job.  So, add a smaller delay for Ubuntu & macOS.
**test/helpers/integration.rb** - in several methods that read the `IO.popen` IO from the server, a log keyword parameter exists for debugging.  The parameter was not passed thru `wait_for_server_to_boot`. Fix.
> [CI] two small CI fixes

- SECURITY.md
Puma 4.x no longer eligible for security fixes since the release of Puma 6.
> SECURITY: Puma 4.x no longer supported [ci skip]

- .github/workflows/turbo-rails.yml
- lib/puma/const.rb
- lib/puma/io_buffer.rb
- lib/puma/request.rb
- test/test_cli.rb
- test/test_puma_server.rb
PR #2896 added code to collect members of response bodies that are Arrays or Enums, and allow a size threshold that waits to send the collected bytes only when they exceed it.  Previously, if the response body consisted of many small strings, each string was written.  #2896 collects them, and only writes when they exceed the threshold.  This may affect TTFB (time-to-first-byte).  The limit value was also too high in #2896.
This causes issues with Enum bodies that mimic a streaming body.  The size threshold has been removed for Enum bodies, but remains for true Array bodies.
Previously, due to the handling of Enum bodies, test code in Sinatra failed.  The code is checked in an added test, `test_streaming_enum_body'.
Using the benchmarks in benchmark/local, this PR shows:
```
Puma repo …
```
> Fixup response processing, enumerable bodies

- lib/puma.rb
- test/helper.rb
@ioquatix added UNIXSocket support for Windows in ruby/ruby.  Many thanks to him for that.
Windows file system is different that Unix/macOS, and the URI gem may need changes re Windows path syntax.
Both issues can be dealt with in Puma, but it will take changes to both lib and test files.
So, for now, disable UNIXSocket tests in Puma...
> Skip Windows UNIXSocket tests for now

- History.md
> Correct date for Puma 6.0.1 in History

- lib/puma/const.rb
Ruby 2.3 implemented the magic comment `# frozen_string_literal: true`.  The below shows one interesting result, `join`:
```ruby
v1 = "Frozen?"
v2 = %w[HEAD GET POST PUT DELETE OPTIONS TRACE PATCH].freeze
v3 = v2.join ' '
v4 =  {501 => "HTTP/1.1 501 Not Implemented\r\n\r\n",
503 => "HTTP/1.1 503 Service Unavailable\r\n\r\nBUSY"}
puts v1.frozen?      # -> true
puts v2[0].frozen?   # -> true
puts v3.frozen?      # -> false
puts v4[501].frozen? # -> true
```
So, remove `.freeze` when not needed in const.rb.  Also, remove extra constants (`GET POST PUT DELETE OPTIONS TRACE PATCH`) that were added in https://github.com/puma/puma/commit/1b6b8adfaeb4.
> Refactor const.rb - freeze

- lib/puma.rb
- lib/puma/cluster.rb
- lib/puma/runner.rb
- lib/puma/single.rb
- test/test_integration_cluster.rb
Several years ago the `etc` and `time` gems were added to Puma's requirements.  They are no longer needed, as a small code change replaces `time`, and I can't find any reference to `etc`.
Closes #3033.
> Remove use of etc and time gems in Puma

- .github/workflows/tests.yaml
- lib/puma/const.rb
Related to https://github.com/puma/puma/issues/3046
Also fix the lint offense that slipped through.
> CI: always run RuboCop lint job

- .github/workflows/tests.yaml
The image has been deprecated and the brownout period have started
already: https://github.com/actions/runner-images/issues/6002
Close https://github.com/puma/puma/issues/3045
> CI: remove ubuntu-18.04 jobs

- .github/workflows/rack2.yaml
- .github/workflows/tests.yaml
- .github/workflows/turbo-rails.yml
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
> CI: add Ruby 3.2.0 jobs

- .github/workflows/turbo-rails.yml
The turbo_rails workflow currently hardcodes the Ruby ABI version.  Compute the value in the bash script.  A fix for code I wrote...
Note that the tests will intermittently fail on the first test running a websocket connection.  Haven't found a good fix, it seems to be caused by all the assets not being loaded by the client before the test code sends client websocket data.
> [CI] Cleanup turbo_rails.yml

- lib/puma/client.rb
- lib/puma/configuration.rb
- lib/puma/dsl.rb
- lib/puma/request.rb
- lib/puma/server.rb
- test/test_config.rb
- test/test_puma_server.rb
When receiving large payload objects, the server can often slowdown or get fully exhausted if bunch of requests with large payload body size come in. When request with large payload comes in, lot of the time is spent reading the body into buffer, writing it to the IO for rack, before the request is passed to the rails app for further processing.
While there are some workarounds around limiting large request sizes, like at nginx layer by setting `client_max_body_size`, which would return a `413` back to the client, today that is not possible with puma.
This would be a very nice feature to have, especially when there is no reverse proxy in between client and server.
This approach - allows a user to set `http_content_length_limit` via  a config variable (defaults to `nil`). This value is …
> Introduce the ability to return 413: payload too large for requests

- Gemfile
- docs/systemd.md
- lib/puma/launcher.rb
- lib/puma/sd_notify.rb
- lib/puma/systemd.rb
- test/test_integration_systemd.rb
This PR aims to remove the need to install the [sd_notify gem](https://github.com/agis/ruby-sdnotify) by vendoring its code, thus, making the support for systemd notify built-in.
I have considered what @mperham have done with [Sidekiq](https://github.com/mperham/sidekiq/blob/ebeff59/lib/sidekiq/sd_notify.rb) and said about `sd_notify` https://github.com/puma/puma/pull/2438#issuecomment-735950804:
> With Sidekiq I decided to vendor the code for the sd_notify gem because it's only ~50 lines of stable code. I didn't want to require the user to add the gem to their gemfile manually, that shouldn't be something they need to care about IMO.
> Add built-in systemd notify support

- lib/puma/cluster.rb
- lib/puma/cluster/worker.rb
- lib/puma/log_writer.rb
- lib/puma/runner.rb
- lib/puma/single.rb
- test/helpers/integration.rb
- test/test_integration_cluster.rb
- test/test_integration_pumactl.rb
- test/test_integration_single.rb
This implements the feature requested in https://github.com/puma/puma/issues/3020, printing the loaded extensions if PUMA_DEBUG is set.
When Puma is running 'single' (no workers), the log is done in the main Puma process, after `Server#run` has been called, as some extensions maybe loaded in that call. For Puma running 'clustered' (workers used), the log is generated in Worker index 0, after `Server#run` is called and also in the master process.
Log is also generated on phased-restarts.
Added a test for both, small refactor (moved functionality to `intergration.rb`) for using a control server in CI.
Closes #3020
> Log loaded extensions when `PUMA_DEBUG` is set

- .github/workflows/tests.yaml
Current CI is showing warnings when using Ruby 2.6, update RubyGems
> [CI] - update RubyGems for Ruby 2.6, eliminate warnings

- test/test_rack_server.rb
Recently there was a failure (with IO), when using Open3 in test_rack_server.rb.  Remove use of Open3, use net/http instead.  Note that net/http ignores `content-type` encoding, so we have to force it.
'curl' was used with Open3, and it does recognize encoding.
> [CI] test_rack_server.rb - remove use of Open3, set HOST constant

- .github/workflows/ensure_pull_requests_are_labeled.yml
Closes #3038
Attempt at ensuring PRs are labeled! Apologies for the generic branch name, I was creating the file via the github UI 🙈. 
Some additional thoughts:
- The workflow runs on PR opening, or if a label is added or removed. Are there other parts of the PR lifecycle I might be missing?
- It's a bit "ick" to have a big red ❌ on your PR just because you forgot to add a label, is there maybe a default label we could automatically add instead?
> Add workflow for ensuring PRs are labeled

- benchmarks/local/sinatra/Gemfile
- benchmarks/local/sinatra/README.md
- benchmarks/local/sinatra/config.ru
- benchmarks/local/sinatra/puma.rb
- lib/puma/client.rb
The motivation for this change is to reduce memory used by a Rails application running on Heroku that handles large file uploads (~100Mb). In it's current state the application (running Puma 6.0.2 + Rails 5.2.8 + Ruby 2.7.6) starts using swap and triggering "memory quota exceeded errors" on the Heroku dyno after only a few file uploads.
This PR is a proof of concept that appears to significantly reduce the memory used by Puma during the data phase of the HTTP request. The change I made was to re-use a single read buffer in `Puma::Client#read_body` and `Puma::Client#read_chunked_body` vs allocating a new buffer on each call to `read_nonblock()`.
I proved this change worked locally by throttling the network speed in Chrome dev tools and watching application memory usage as Puma received the …
> Reduce memory usage for large file uploads

- .github/workflows/rack_conform.yml
- lib/puma/const.rb
- lib/puma/request.rb
- test/test_puma_server.rb
- test/test_puma_server_partial_hijack.rb
I've rebased @MSP-Greg's branch https://github.com/MSP-Greg/puma/tree/00-size-to-first-byte-ws
With these changes, Puma passes the [Rack::Conform](https://github.com/socketry/rack-conform) ["Basic WebSocket connection test"](https://github.com/socketry/rack-conform/pull/12), see https://github.com/dentarg/rack-conform/actions/runs/3928289028/jobs/6715741130
Needs some tests 
Close https://github.com/puma/puma/issues/3007
> WebSocket support?

- .github/workflows/turbo-rails.yml
Turbo-Rails had an async issue that caused intermittent failures in CI.  That has been fixed, so the workflow can have the 'continue-on-error'/'allow-failure' code removed.
Turbo-Rails uses 'full hijacking' to create a websocket connection.
> [CI] turbo-rails is now passing

- lib/puma/binder.rb
- lib/puma/dsl.rb
- lib/puma/request.rb
- test/rackup/hello-bind_rack3.ru
- test/test_binder.rb
- test/test_config.rb
Started with the following warnings in Ruby 2.4:
```
lib/puma/binder.rb:254: warning: assigned but unused variable - optimize_for_latency
lib/puma/request.rb:334: warning: shadowing outer local variable - part
lib/puma/request.rb:343: warning: shadowing outer local variable - part
lib/puma/request.rb:357: warning: shadowing outer local variable - part
lib/puma/request.rb:365: warning: shadowing outer local variable - part
```
Fixed the above, rather trivial.
Then, while looking at the 'optimize_for_latency' warning, discovered that the TCPServer started for an SSL connection was not passed the 'low_latency' argument.
Fixed, and added tests to `test_binder.rb` & `test_config.rb`, which is the last commit.  Cherry-pick the test commits to master, it shows the following three failures:
``` …
```
> Allow setting TCP low_latency with SSL listener, minor fixes

- test/test_plugin_systemd.rb
Fixup so TruffleRuby passes.  Reverse parameters so `assert_equal(exp, act, msg = nil)` calls have 'expected' as the first parameter.
> Refactor test_plugin_systemd.rb, fix for TruffleRuby

- Gemfile
- lib/puma/rack_default.rb
- lib/rack/handler/puma.rb
- test/test_rack_handler.rb
Rack v2 included the files needed to use `rackup` from the command line.  With Rack v3, it is now a separate gem, and the namespace has changed.
Re tests, when Rack v3 was released, we (ok, I) blocked  [test/test_rack_handler](https://github.com/puma/puma/blame/3f4e3c8ca689e39218459836b939c39fa81e2692/test/test_rack_handler.rb#L5) from running with Rack v3, so tests do exist.  This PR unblocks the tests.
The changes to `lib/rack/handler/puma.rb` look excessive.  This PR is taking the previous code, and turning it into a HEREDOC, so it can be used in `module_eval`.  This is the work-around to allow it to be placed in either the `Rack::Handler` or the `Rackup::Handler` namespace.
Adjust code to work with both.
**Note:** labeled as a 'bug', not sure...
Closes #3057
> Fixup code for use with rackup gem (may be used with rack 3)

- test/helpers/integration.rb
- test/test_plugin_systemd.rb
`test_plugin_systemd.rb` should be able to run parallel, except one test is setting `ENV["WATCHDOG_USEC"]` in the test process.
Add an `env` keyword parameter to `TestIntegration#cli_server` so it can set ENV values in the sub-process.
This allows `test_plugin_systemd.rb` to run parallel.
> [CI] Integration tests - add parameter to allow TestIntegration#cli_server to change ENV

- lib/rack/handler/puma.rb
- test/test_rack_handler.rb
- test/test_rack_server.rb
PR #3061 fixed the use of the `rackup` bin file for use with either Rack 2 or Rack 3.  It broke the use of `::Rack::Handler::Puma.run` when used stand-alone, which is used to start Puma in some CI frameworks.
Fix the above issues, add a test for running the `rackup` bin file using `IO.popen`, which isolates it (and what it requires) from the main test process.  Note that the test only runs on MRI Ruby, as non-MRI Rubies take time when using `IO.popen`.
The 'Tests' workflow uses the Rackup (includes the rackup bin) & Rack v3 gems, and the 'Rack_v2' workflow uses Rack v2 gem (includes the rackup bin).
See https://github.com/puma/puma/pull/2990#issuecomment-1428060309
> Allow ::Rack::Handler::Puma.run to work regardless of whether Rack/Rackup are loaded

- test/test_puma_server.rb
Ruby master has changed an error message, which causes TestPumaServer#test_lowlevel_error_body_close to fail.
Adjust the asserts checking that the error message is included in the log.
> [CI] Fix error message change in Ruby master

- README.md
- lib/puma/cli.rb
- lib/puma/dsl.rb
- lib/rack/handler/puma.rb
- test/config/event_on_booted.rb
- test/config/event_on_booted_exit.rb
- test/test_integration_cluster.rb
- test/test_integration_single.rb
- test/test_rack_handler.rb
Closes https://github.com/puma/puma/issues/2635
I'm not sure if exactly that is what was intended. But I'm happy to get a feedback :)
> Add on_booted event

- lib/puma/detect.rb
- lib/puma/launcher.rb
- test/helper.rb
- test/test_jruby_skip_plugin_systemd.rb
- test/test_plugin_systemd.rb
- test/test_plugin_systemd_jruby.rb
The systemd integration will fail for JRuby at https://github.com/puma/puma/blob/e3d5794a7ebe47577ced4d4dfdd6a6cc969ded01/lib/puma/sd_notify.rb#L140, because JRuby doesn't support UNIX datagram sockets yet, and won't for a while. See https://github.com/jruby/jruby/issues/6504. So turning it off here, so that JRuby users can integrate with systemd on their own if they wish without errors.
> Don't use the systemd plugin on JRuby

- lib/puma/configuration.rb
- lib/puma/dsl.rb
- test/test_config.rb
Address https://github.com/puma/puma/issues/2950
- Add a default warning log when clustered-only hooks are defined but puma is booted in single mode.
- Add an config option to opt-out the default warning
> Warn when clustered-only hooks are defined in single mode

- lib/puma/commonlogger.rb
Current log output from a request and a 'full-hijacked' request:
```
127.0.0.1 - - [08/Feb/2023:18:47:21 -0600] "GET /users/profiles HTTP/1.1" 200 - 0.1126
127.0.0.1 - - [08/Feb/2023 18:47:22] "GET /cable HTTP/1.1" HIJACKED -1 0.6079
```
Note the hijack log line doesn't have a time zone offset...
Fixed and used constants for the env keys instead of strings.  Not sure if local constants are better than using one from `Puma::Const`?
> commonlogger.rb - fix HIJACK time format, use constants, not strings

- test/test_rack_server.rb
Change
```ruby
require "rack/chunked" if Rack::RELEASE.between?('3', '3.1')
```
to
```ruby
require "rack/chunked" if Rack::RELEASE.start_with? '3.0'
```
Closes #3097
> [CI] test_rack_server.rb - fix rack/chunked code

- lib/puma/error_logger.rb
- lib/puma/log_writer.rb
The following appeared in a recent CI job:
```
D:/a/puma/puma/lib/puma/log_writer.rb:75:in `flush': Invalid argument (Errno::EINVAL)
from D:/a/puma/puma/lib/puma/log_writer.rb:75:in `internal_write'
from D:/a/puma/puma/lib/puma/log_writer.rb:62:in `log'
from D:/a/puma/puma/lib/puma/launcher.rb:321:in `log'
from D:/a/puma/puma/lib/puma/launcher.rb:414:in `rescue in setup_signals'
```
The error raised can happen in the `internal_write` method of both `LogWriter` & `ErrorLogger`.  Error should be caught...
> Loggers - internal_write - catch Errno::EINVAL

- lib/puma/dsl.rb
The message could either be in the positive `but Puma is configured to run in single mode (worker count = 0 )` or the negative `but Puma is not configured to run in cluster mode (worker count > 0 )`. I went with negative because it explicitly instructs what is required in order for hooks to run.
> Fix warn_if_in_single_mode incorrect message

- lib/puma/request.rb
- test/test_puma_server.rb
Root of the issue is that you can get into the `if chunked` branch when `body.each` has nothing in it, so the previously populated `io_buffer` is never written to the socket.
This used to be the case but was changed on [#3072](https://github.com/puma/puma/pull/3072/files#diff-b58a5aaef75ecf535b6fc4546c848b0f576f9cf27e37b27c59015251097d5736L361).  I'm just moving this line back.
Closes #3112.
> Always write io_buffer when in "enum bodies" branch.

- Gemfile
- Rakefile
it's a similar issue as https://github.com/puma/puma/issues/1772 unfortunately, that PR didn't fix all usage of buffers
since https://github.com/rake-compiler/rake-compiler/issues/200 does support the ```--release``` flag for compatibility with older java versions, it's cleaner and safer to fix it this way instead of explicitly casting buffer methods as `(Buffer) buffer`
the downside is, it requires at least Java 9 for building the extension, but I guess it won't be a problem.
closes https://github.com/puma/puma/issues/3108
the only way to test it would be to build the extension with Java 9+, but run tests with Java 8.
> fix java 8 compatibility

- test/test_rack_handler.rb
PR #3118 did not include a test, probably best to check for the issue.
This PR doesn't add a test, but modifies one.  It raises `NameError` with #3118 reverted, as below:
```
1) Error:
TestRackUp::TestOnBootedHandler#test_on_booted:
NameError: uninitialized constant Puma::Rack::CommonLogger
/mnt/c/Greg/GitHub/puma/lib/rack/handler/puma.rb:35:in `block in config'
/mnt/c/Greg/GitHub/puma/lib/puma/configuration.rb:195:in `configure'
/mnt/c/Greg/GitHub/puma/lib/puma/configuration.rb:188:in `initialize'
```
> [CI] Modify test for PR #3118

- README.md
By now Puma has gained all systemd integrations that puma-plugin-systemd used to provide. While I didn't check, there's a good chance the plugin now conflicts with the integrated features conflict. Users should prefer native support.
> [ci skip] Add a note that puma-plugin-systemd is redundant now

- lib/puma/client.rb
- test/test_puma_server.rb
Current code breaks when a form uploads a file with "\r\n" line endings.
Currently `client.rb` uses a string buffer that is initialized as UTF-8, it should be initialized as ASCII-8BIT.  UTF-8 can be 'character/line-ending' sensitive, while ASCII-8BIT is just bytes...
Add two tests, both with "\r\n" line endings, one as BOM|UTF-8.
Closes Discussion #3131
Running the two new tests on master has the below errors:
```
1) Error:
TestPumaServer#test_form_data_encoding_windows:
NoMethodError: undefined method `split' for nil
puma/test/test_puma_server.rb:1629:in `test_form_data_encoding_windows'
2) Error:
TestPumaServer#test_form_data_encoding_windows_bom:
NoMethodError: undefined method `split' for nil
puma/test/test_puma_server.rb:1598:in `test_form_data_encoding_windows_bom'
```
> Fixup req form data file upload with "r\n" line endings

- .github/workflows/tests.yaml
Recently had a JRuby test timeout failure in Actions, as below.  This is rare, but it shows the tests finished, but essentially in the same time as the Actions test step timout.  So, all the tests passed, but the job failed.
Hence, increase the JRuby test step timouts just a bit....
```
TestRackServer#test_common_logger = 20.23 s = .
Finished in 344.920221s, 1.4525 runs/s, 3.3892 assertions/s.
Skips:
501 runs, 1169 assertions, 0 failures, 0 errors, 80 skips
Error: The action has timed out.
```
> [CI] test.yaml - update non-MRI Test Timeout - tto

- lib/puma/binder.rb
- lib/puma/reactor.rb
- lib/puma/server.rb
- lib/puma/thread_pool.rb
All files except `thread_pool.rb` have additional handling added.  These errors have intermittently been seen in CI.
`thread_pool.rb` allows setting `options[:pool_shutdown_grace_time]` during CI, as stubbing a constant is difficult when running parallel CI.  At present, it is not exposed via the DSL, but could be added in the future.
Hence, no API or functionality changes.
These commits were originally part of PR #3128.
> Misc lib file fixes - trapping additional errors, CI helper

- .github/workflows/turbo-rails.yml
We run a CI workflow using turbo-rails test suite, which uses Puma for sending websocket data.
It is currently failing, and I'm getting tired of receiving an email every time the workflow fails.
turbo-rails has a hierarchy of dependencies, so a change in one may affect others.  Recently, a change in selenium-webdriver broke release versions of capybara.  This has been fixed in capybara, but the fix hasn't been released.
This PR changes the line in turbo-rails Gemfile from
```ruby
gem 'capybara'
```
to
```ruby
kw =
if RUBY_VERSION.start_with? '3'
{git: 'https://github.com/teamcapybara/capybara.git', ref: '43e32a8495'}
else
{}
end
gem 'capybara', **kw
```
When a new release of capybara is available, rather than reverting this PR, the following lines should be left but commented out:
``` …
```
> [CI] temporary fix for Capybara, use recent commit

- test/test_integration_ssl_session.rb
- test/test_plugin_systemd_jruby.rb
test_integration_ssl_session.rb was originally committed about 8-1/2 months ago in PR #2846, which was my PR.  It used curl (via `IO.popen` with a block) to generate SSL requests, running asserts on the output.
I think it's preferred to not 'shell out' unless absolutely necessary, and I also started seeing intermittent failures while working on test updates.
This PR removes the use of curl, and uses SSLSockets.
test_plugin_systemd_jruby.rb has a small fix as teardown was running regardless of whether a test was skipped, which was throwing 'undefined' warnings.
> [CI] test_integration_ssl_session.rb - use SSLSockets instead of curl

- test/helpers/tmp_path.rb
On my machine, tempfile directories end up being rather long, and tests actually fail!
```
/Users/nateberkopec/Documents/Code.nosync/upstream/puma/lib/puma/binder.rb:421:in `initialize': too long unix socket path (106bytes given but 104bytes max) (ArgumentError)
s = UNIXServer.new path.sub(/\A@/, "\0") # check for abstract UNIXSocket
```
Storing in ./tmp solves the issue.
> Store Tempfiles in ./tmp

- lib/puma/request.rb
- test/test_web_server.rb
Bad Request is returned
```
$ printf 'GET :/ HTTP/1.1\r\n\r\n' | nc localhost 8080
HTTP/1.1 400 Bad Request
```
and it is logged like this
```
2023-05-14 11:54:28 +0200 HTTP parse error, malformed request ("GET " - (-)): #<Puma::HttpParserError: Puma::HttpParserError>
```
Close #3148
> Handle malformed request path

- test/helpers/tmp_path.rb
See PR #3153, which is due to a macOS limitation causing an error:
```
too long unix socket path (106 bytes given but 104 bytes max) (ArgumentError)
```
The above is added to comments in `test/helpers/tmp_path.rb`
> [CI] helpers/tmp_path - use './tmp' for temp file root only on macOS

- .github/workflows/tests.yaml
- Gemfile
- lib/puma/rack_default.rb
- lib/rack/handler/puma.rb
- test/helper.rb
- test/test_config.rb
- test/test_puma_server_hijack.rb
- test/test_rack_server.rb
The constant `Rack::RELEASE` was introduced "only" (I know, it's a long time ago) in rack version 2 (specifically: https://github.com/rack/rack/commit/a2fe30a5e70371c89c1b29fdc2dc5f8027bc5fe6). Earlier versions provided the class method `Rack.release` which still exists.
https://github.com/puma/puma/pull/3061 has introduced usage of `Rack::RELEASE` and therefore broke compatibility with rack 1.6.X. Since this was released with a minor or patch version update of *puma* I feel it would be nice to fix and restore compatibility with rack 1.6.X.
So this PR changes usage of `Rack::RELEASE` to `Rack.release`. Since none of the occurrences seem to be in any code that is called per request I assume it's fine to introduce a potential tiny performance overhead of a method call vs. constant lookup. …
> Use Rack.release over Rack::RELEASE (rack 1..6.X compatibility)

- test/test_integration_cluster.rb
- test/test_integration_ssl.rb
- test/test_puma_server.rb
Ruby 2.2 did not support `<<~` for heredocs, so many used in the test files are indented all the way to the left.
Call me AR, but I hate that, as I often place debug code on the left margin.
So, this PR replace heredocs with `<<~`, and indents them.  If on uses the 'Hide whitespace' option in the 'diff/patch' view, it makes things much clearer...
> [CI] Use <<~ for heredocs

- test/test_redirect_io.rb
Puma's test suite runs with 'retry', which is helpful when CI systems are not 'resource robust'.  Recent additions to CI log all test 'retry' failures.  `test_redirect_io.rb` appears intermittently in these logs.
Hence, fixup with the hope of reducing or eliminating 'retry' failures.
1. This file is about log files.  Currently, it opens the file, checks if it can be read, then closes it, only to perform a `File.read` later.  The `read` operation should be contained in the `File.open` block.
2. The current `File.open` block may run forever, as it has no limit on the retry count.
3. Reduce redundant code.
> [CI] test_redirect_io.rb - fixup for intermittent failures

- .github/workflows/tests.yaml
CI updates RubyGems/Bundler for Ruby versions 2.4 thru 2.6.  Currently it's pinned to 3.3.14, which was released May 18, 2022.
Update to version 3.3.26, which was released November 17, 2022.
Noticed this while working on test suite stability, and old Ruby versions were intermittently failing running `test_worker_gem_independence.rb`, which tests Gemfile changes when restarting Puma.
For those of you not following RubyGems/Bundler, @deivid-rodriguez and others have been doing a lot of good work there...
> [CI] - Use RubyGems 3.3.26 for Ruby 2.4 thru 2.6 (was 3.3.14)

- lib/puma/request.rb
- test/test_response_header.rb
While reviewing code in `test\test_response_header.rb`, I noticed that when invalid headers are returned by the app with 'early hints', the first line of an 'early hints' response (`HTTP/1.1 103 Early Hints`) is sent without any data/headers.
This PR modifies the code in `puma/request.rb` to only send the 'early hints' response if at least one header is valid.
Note that with the test changes, current master has the following errors:
```
TestResponseHeader#test_illegal_character_in_key_when_early_hints [test/test_response_header.rb:128]:
Expected # encoding: ASCII-8BIT
"HTTP/1.1 103 Early Hints\r\n\r\n" to not include "HTTP/1.1 103 Early Hints".
2) Failure:
TestResponseHeader#test_illegal_character_in_value_when_early_hints [test_response_header.rb:139]:
Expected # encoding: ASCII-8BIT …
```
> Don't send 103 early hints response when only invalid headers are used

- lib/puma/const.rb
Puma may generate error responses both before and after the app is called, some of which are contained in the `Puma::Const::ERROR_RESPONSE` hash.  Some use a `Server` header whose value is 'Puma \<version\>'.  Some also contain a brief body.
Both of these may 'fingerprint' the response as being generated by Puma.  One commit removes the `Server` header, another removes the body text.
These error responses are for request errors and also server errors.  Request error handing is contained in a few places, and could be moved to `Puma::Client` code, as the request is received in full before calling code outside of `Client`.
Another issue is how to log request errors.  I suspect most would prefer them in the request/response logging, but whether additional error info should be logged is …
> Puma error responses - remove fingerprints to indicate Puma

- 6.0-Upgrade.md
- lib/puma/const.rb
- lib/puma/dsl.rb
- lib/puma/request.rb
- lib/puma/server.rb
- test/test_puma_server.rb
- test/test_web_server.rb
Adds `Puma::DSL#supported_http_methods`, which allows overriding defaults in `Puma::Const::SUPPORTED_HTTP_METHODS`.
Turbo-Rails CI is currently broken.
Closes #3014
> Add dsl method `supported_http_methods`

- .github/workflows/tests.yaml
- Gemfile
- Rakefile
- lib/puma.rb
- test/helper.rb
- test/test_integration_single.rb
See commit comments.
Takes quite a while to run, but we won't be running that often, and there are a lot of Ruby versions.
The time is due to all the macos jobs.  Not sure if macos is used much in production, but I'm sure it's used in development.  I set the CI matrix up so no Ruby version is run on all three macos versions (11,12,13).
> Fix and update 5-6-stable CI, two backports

- lib/puma/rack/urlmap.rb
- test/test_url_map.rb
- test/url_map_test/Gemfile
- test/url_map_test/config.ru
Ruby v3.3.0-preview1 doesn't support passing 3 arguments to `Regexp.new`, so update `Puma::Rack::URLMap#remap` to use a 2 argument version instead.
I didn't notice where `Puma::Rack::URLMap#remap` was currently tested and could use some advice on the testing front. Syntactically, I've tested the change going back as far as the current minimum supported Ruby, v2.4.
> update URLMap Regexp usage for Ruby v3.3

- lib/puma.rb
- lib/rack/version_restriction.rb
- test/bundle_rack_3/Gemfile
- test/bundle_rack_3/config.ru
- test/helpers/integration.rb
- test/test_rack_version_restriction.rb
- test/test_version_restriction.rb
- test/test_worker_gem_independence.rb
WIP tests are failing
See https://github.com/puma/puma/pull/3164
Puma 5 is not compatible with Rack 3. App generated with the default Rails 6.1 and 7.0 app template will hit [this error](https://github.com/rails/rails/issues/48195) when they  run `bundle update`.
This check ensures affected users will get a meaningful error message pointing them toward a fix.
> Prevent loading with rack 3

- lib/puma/binder.rb
- lib/puma/control_cli.rb
- test/helper.rb
- test/test_pumactl.rb
Creating a server listener with an IPv6 host is working, but using an IPv6 host for the control server is not.
Fix, and add tests for both tcp & ssl connections.  This involves trimming the surrounding brackets from the URI format (eg `[::1]`) to the IP address format (eg `::1`).
See https://github.com/puma/puma/commit/097641274be50adee4b5764057959454197ece05 
Tests fail on current master.
> Fix using control server with IPv6 host

- lib/puma/control_cli.rb
- test/helpers/integration.rb
- test/test_integration_pumactl.rb
`control_cli.rb` may create Some Puma objects, dependent on the setup used (config, pid, or state file).
It may create a `Puma::Configuration`, which uses `Puma::DSL`, which may create a `Puma::LogWriter`,  a `Puma::LogWriter`is also created when using the `start` method.
When used in a 'Puma' process, `puma.rb` autoloads `Puma::LogWriter`, but that file isn't required in `control_cli.rb`.
Closes #3186.
> control_cli.rb - add `require_relative 'log_writer'`

- README.md
The current README.md describes how to use the localhost gem in development, but implies that one can require it in a rackup file.  That is incorrect, as it needs to be required in a configuration file.
Updated README.md to clarify.
Closes #2818
Closes #3068
> README.md - clarify use of localhost gem [ci skip]

- lib/puma/server.rb
- test/test_puma_server.rb
- test/test_response_header.rb
Closes #2341
Currently, when Client I/O operations raise any exceptions, we build a fallback rack response (either by `lowlevel_error_handler` or by default puma's hard-coded response), but doesn't do anything with it. This commit ensures that this response is sent back to client.
To verify:
1. `bundle exec puma -C test/config/lowlevel_error_handler.rb test/rackup/hello.ru`
2. `curl -i GET localhost:9292`
```
HTTP/1.1 500 Internal Server Error
Content-Length: 24
something wrong happened
```
> Make sure low level error response is sent to the client

- lib/puma/dsl.rb
- lib/puma/thread_pool.rb
- test/test_config.rb
- test/test_thread_pool.rb
This PR closes #3192
It provides a `before_thread_start` hook which can be used to execute code before a thread starts.
> Add on_thread_start_hook

- lib/puma/client.rb
- lib/puma/server.rb
[Forwardable](https://github.com/ruby/forwardable) is currently used by server.rb & client.rb.
It is part of the standard library, but it's also available as a gem. Hence, it could be 'converted' to a bundled gem, especially since it's nor an extension gem.
Bundled gems need to be included as dependencies in gemspec files.
Since removing it is relatively trivial (5 methods are delegated), lets do so now.
Closes #3190
Closes https://github.com/puma/puma/issues/3218
> Remove `Forwardable` dependency (possible conversion to bundled gem)

- README.md
Searching the internet for "Truffle" vs "TruffleRuby" yields quite different results.
[ci skip]
> Use the correct name for TruffleRuby

- lib/puma/dsl.rb
When writing a test for https://github.com/puma/puma/pull/3225 I set the `worker_timeout` to be `2s` to avoid a test timeout. To do that, I needed to reduce the `worker_check_interval` to `1s` to comply with [this validation](https://github.com/puma/puma/blob/04b8b09ad20ace1a3a5cfe06375dc24818697d19/lib/puma/dsl.rb#L908-L910).
However, the docs imply that the minimum `worker_timeout` **can only be** `6s`, since it is greater than the default `worker_check_interval` of `5s`.
I've updated the docs to clarify that the minimum simply needs to comply with this validation, and removed any mention of a specific value as it can be infered from either the default `worker_check_interval` in the docs or the user configured value.
> [ci skip] | Docs | Clarify `worker_timeout` minimum value

- lib/puma/dsl.rb
Simple commit fixing RoboCop white space issues.  I meant to do this from my fork.
I tried to push a commit directly to the repo, can't due to branch restrictions.  Then, I forgot to switch to my fork...
> dsl.rb - fix white space for RuboCop, see 7a0e0c2763

- ext/puma_http11/mini_ssl.c
- lib/puma/minissl.rb
- lib/puma/minissl/context_builder.rb
- test/helpers/integration.rb
- test/helpers/test_puma.rb
- test/helpers/test_puma/puma_socket.rb
- test/test_integration_ssl.rb
Current code in `MiniSSL::Socket#peercert` contains the following line:
https://github.com/puma/puma/blob/188f5da1920ff99a8689b3e9b46f2f26b7c62d66/lib/puma/minissl.rb#L194
The above statement only runs when `MiniSSL::Context#verify_mode` is not equal to `MiniSSL::VERIFY_NONE`.  So, we need to require openssl when needed.
Note that `MiniSSL::Socket#peercert` was added in PR #709 'ssl: Add Client Side Certificate Auth'.  The cert subject is used in `LogWriter#ssl_error`, and the cert object is set to `env['puma.peercert']`.  The app environment key doesn't seem to be 'publicly' listed.
Current tests only check this with an in-process server, and since the client sockets are ssl, `openssl` is loaded for the clients.
I added some additional spawned tests (Integration) that showed the problem, …
> context_builder.rb - require openssl if verify_mode != 'none'

- .github/workflows/tests.yaml
- test/config/event_on_booted_exit.rb
- test/helpers/integration.rb
- test/test_integration_cluster.rb
- test/test_integration_single.rb
- test/test_plugin_systemd_jruby.rb
- test/test_puma_server.rb
In the `TestIntegration` class, two methods, `wait_for_server_to_include` and `wait_for_server_to_match` may block.  Decrease blocking, and accumulate the server log into a string.
Other commits are CI related, several decreasing blocking.  I can make separate if people would prefer that...
> integration.rb - less blocking in wait_for_server_to_* methods

- lib/puma/cluster.rb
- test/helper.rb
- test/test_integration_cluster.rb
Closes https://github.com/puma/puma/issues/2786.
Ensures that worker 0 is pinged on every forked worker's post-boot ping to prevent it from timing out.
~An integration test for this would be something like https://github.com/puma/puma/issues/2786#issuecomment-1704766900 but might not be practical considering the time it takes. I'll add some unit tests when I get a chance unless anyone has a better idea.~
I've added a regression test with a lowered worker timeout to simulate a high worker count + high worker timeout real world scenario.
> [Fix #2786] Worker 0 timing out during phased restart

- lib/puma/detect.rb
- test/helpers/integration.rb
- test/helpers/tmp_path.rb
Previously. `RUBY_PLATFORM.include? 'darwin'` was used for macOS detection.  When using JRuby on macOS, the value of `RUBY_PLATFORM` is `java`.  Fix in both lib code and test code.  I could not find `Puma::IS_OSX` or `Puma.osx?` anywhere in the lib files...
Also since all supported Ruby versions have `String#match?` available, replace `=~` with it.
See the most recent workflow at https://github.com/MSP-Greg/github-actions-ruby-info/actions/workflows/ruby.yml for info on various Ruby versions/builds.
> Fixup macOS detection

- test/test_rack_handler.rb
Currently, logs warning when skipped, as `kill` has no pid
> [CI] test_rack_handler.rb - fix test ensure when skipped

- test/config/app.rb
- test/helpers/test_puma/puma_socket.rb
- test/test_pumactl.rb
Remove Minitest `capture_subprocess_io`, use a pipe since it is accounted for in Puma code...
> [CI] test_pumactl.rb - use port 0 on server, misc

- tools/Dockerfile
This PR updates the "minimal repro" Dockerfile to use latest supported Ruby version, AND it assumes that Bundler exists in the container, since Ruby 3.x ships with it, and it is used on line 6.
> Dockerfile for minimal repros: use Ruby 3.2, expect bundler installed [ci skip]

- lib/puma/cluster/worker.rb
- lib/puma/runner.rb
- lib/puma/server.rb
- test/test_integration_cluster.rb
- test/test_integration_single.rb
Closes https://github.com/puma/puma/issues/3228.
Ensures that a worker kills the master process if its server shut down due the the idle timeout elapsing. The master will gracefully shut down the rest of the workers and then itself.
~I wonder if we should backport this to https://github.com/puma/puma/tree/v6.4.0 🤔~
Stupid question 🤦🏽‍♂️
> [Fix #3228] `idle-timeout` not working in cluster mode

- .github/workflows/tests.yaml
Currently, all NON-MRI jobs have a test timout of 8 minutes, except 'ubuntu-22.04 jruby no SSL', which is 7.
Increase to 8, so false failures don't happen.
> [CI] test.yaml 'NON-MRI: ubuntu-22.04 jruby no SSL' test timeout

- test/test_puma_server_ssl.rb
Add Errno::ECONNABORTED to assert_ssl_client_error_match as allowed error for client cert missing/incorrect
> [CI] test_puma_server_ssl.rb - add Errno::ECONNABORTED to invalid cert errors

- test/helpers/test_puma.rb
`Array#sort` takes a block that accept 2 parameters.
The intent here was to use `sort_by`.
```
test/helpers/test_puma.rb:14:in `length': wrong number of arguments (given 1, expected 0) (ArgumentError)
.uniq.sort(&:length)
^^^^^^^^
from puma/test/helpers/test_puma.rb:14:in `sort'
from puma/test/helpers/test_puma.rb:14:in `<module:TestPuma>'
from puma/test/helpers/test_puma.rb:5:in `<top (required)>'
from puma/test/helpers/test_puma/puma_socket.rb:4:in `require_relative'
from puma/test/helpers/test_puma/puma_socket.rb:4:in `<top (required)>'
from puma/test/test_cli.rb:4:in `require_relative'
from puma/test/test_cli.rb:4:in `<top (required)>'
from /rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `require'
from /rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
from …
```
> Fix TestPuma::HOST4

- lib/puma/dsl.rb
- test/test_integration_cluster.rb
About seven months ago, code was added that logged warnings if worker hooks were added in a config file, but workers were not used (workers = 0).  The code only checks for workers being set in the config file.  So, if one uses `-w2` as a cli argument, the warnings are incorrectly shown.
Running the additional test in master fails, with the following:
```
1) Failure:
TestIntegrationCluster#test_worker_hook_warning_cli [/mnt/c/Greg/GitHub/puma/test/test_integration_cluster.rb:518]:
Warning below should not be shown!
Warning: You specified code to run in a `on_worker_boot` block, but Puma is not configured to run in cluster mode (worker count > 0 ), so your `on_worker_boot` block did not run
```
Found while working with the new test framework server files...
> DSL#warn_if_in_single_mode - fixup when workers set via CLI

- .github/workflows/tests.yaml
- ext/puma_http11/extconf.rb
macOS TruffleRuby has been failing with backtraces showing a OpenSSL build/runtime problem.  Or, Puma is compiling with one version, but running with another.
This fixes the issue by adding a conditional to not use pkg_config only when running on Actions with macOS TruffleRuby.  Example from a log:
```
Error reached top of thread-pool: External LLVMFunction SSL_get1_peer_certificate cannot be found. (Polyglot::ForeignException)
TestCLI#test_control_for_ssl = [MinitestRetry] retry 'test_control_for_ssl' count: 1,  msg: EOFError: EOFError
/Users/runner/work/puma/puma/test/helpers/test_puma/puma_socket.rb:271:in `block (2 levels) in <module:PumaSocket>'
```
There are still intermittent failures with macOS TruffleRuby,
> [CI] Fix macOS TruffleRuby

- lib/puma/cli.rb
- test/test_cli.rb
Closes https://github.com/puma/puma/issues/3253
This PR adds a `--plugin PLUGIN` option which loads the mentioned Puma plugin.
USAGE:
```sh
bundle exec puma --plugin tmp_restart
```
> [#3253] Adds --plugin option to the CLI

- .github/workflows/ragel.yml
Rake 13.1.0 has been released, and the ragel CI is failing in my fork.
`BUNDLE_PATH` is set by setup/ruby using `bundle config --local path <path>`, so the gems installed by it are not accessible unless `bundle exec` is used.  Hence, one should always use `bundle exec` or `require 'bundler/setup'`.
> ragel.yml - use 'bundle exec rake' instead of 'rake'

- .github/workflows/tests.yaml
- test/runner
- test/runner.cmd
Currently `rake` is used to run tests.  `rake` creates a main process, and runs tasks in sub-processes.  This allows chaining tasks, as we do, allowing `compile` to run before `test`.
CI systems' resources are limited, and probably much smaller than most dev's local PC's.
The PR creates two files for test runners (`test_runner.cmd` is used only on Windows) and uses them in the Actions CI test.yaml script.
Note that `test_runner` runs the full test suite.  So, for local testing, using other code should still be used, unless one is very familiar with minitest, etc.  More functionality can be added in the future.
> Use test_runner for tests

- ext/puma_http11/org/jruby/puma/MiniSSL.java
While working on the test framework, there have been consistent intermittent failures with JRuby, but never with the job that did not use SSL.  The failures were much more consistent in CI, but much less common locally.  But, I've got a lot of RAM.
The failures showed that all tests passed, but the test process freezes, and the CI step times out.
For quite a while, the following has been logged in the JRuby compile step.  There are also case fall-thru warnings, but the case statements have integer switches, so multiple matches cannot happen:
```
ext/puma_http11/org/jruby/puma/MiniSSL.java:503: warning: [deprecation] RaiseException(Ruby,RubyClass,String,boolean) in RaiseException has been deprecated
RaiseException ex = new RaiseException(runtime, errorClass, message, true);
^ …
```
> MiniSSL.java - set serialVersionUID, fix RaiseException deprecation

- ext/puma_http11/extconf.rb
A common problem with gems that link to OpenSSL is determining which OpenSSL to use if the system has more than one version installed.  One can use `--with-openssl-dir`, but we'd like to not require its use if possible.
MRI Ruby may contain info in its `RbConfig::CONFIG['configure_args']` string that we can use to determine where OpenSSL is.  Also, TruffleRuby often embeds the OpenSSL source.
What often happens is that the code in `extconf.rb` finds the `openssl.pc` file, but it is for the wrong OpenSSL version.
Update `extconf.rb` to take the above into account.
Note that  `--with-openssl-dir` is still available, which overrides everything.
Closes #3266.  Also see #2790, etc
> extconf.rb - fixup to detect openssl info in Ruby build

- lib/puma/null_io.rb
- test/test_null_io.rb
This isn't a big deal, but every small difference has a chance to let a bug slip as it's likely not every scenario is tested with both NullIO and a real IO.
> Improve Puma::NullIO consistency with real IO

- ext/puma_http11/mini_ssl.c
Fixes:
```
compiling ../../../../ext/puma_http11/mini_ssl.c
../../../../ext/puma_http11/mini_ssl.c: In function ‘raise_error’:
../../../../ext/puma_http11/mini_ssl.c:569:50: error: ‘%s’ directive output may be truncated writing up to 511 bytes into a region of size 497 [-Werror=format-truncation=]
569 |       snprintf(msg, sizeof(msg), "OpenSSL error: %s - %d", buf, err & mask);
|                                                  ^~        ~~~
../../../../ext/puma_http11/mini_ssl.c:569:34: note: directive argument in the range [0, 4095]
569 |       snprintf(msg, sizeof(msg), "OpenSSL error: %s - %d", buf, err & mask);
|                                  ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:867,
from /home/runner/.rubies/truffleruby-head/lib/cext/include/ruby/de …
```
> mini_ssl.c - fix TruffleRuby compile error

- lib/puma/configuration.rb
See issue https://github.com/puma/puma/issues/2922, which led to PR https://github.com/puma/puma/pull/2928, which made the EOF require unnecessary.
Closes #3287
> configuration.rb - move dsl require back to top

- CONTRIBUTING.md
I fixed the typo in the URL for when to schedule a meeting with Nate. He linked to his Calendly event type edit page and I switched it to his booking page.
> [ci skip] Update CONTRIBUTING.md to fix Calendly link

- lib/puma/state_file.rb
- test/test_puma_server.rb
Recent RuboCop fails with a similar error in four places:
```
lib/puma/state_file.rb:63:21: C: [Correctable] Performance/StringIdentifierArgument: Use :"#{f}=" instead of "#{f}=".
define_method "#{f}=" do |v|
^^^^^^^
```
We've used a string parameter for `define_method`, but Ruby's docs show it as a symbol.  Also, an interpolated symbol could be used, but it's not commonly used, and these aren't 'hot' paths.
Fixed all occurrences.
> fix define_method calls, use Symbol parameter instead of String

- .github/workflows/ragel.yml
See comments.  This only affects when errors are thrown, as the line directives pass information about error locations.
See Actions job log at https://github.com/puma/puma/actions/runs/7290009317/job/19866006642#step:5:49
Sample of diff:
```diff
diff --git a/ext/puma_http11/http11_parser.c b/ext/puma_http11/http11_parser.c
index 388a098..fa298f2 100644
--- a/ext/puma_http11/http11_parser.c
+++ b/ext/puma_http11/http11_parser.c
@@ -38,7 +38,7 @@ static void snake_upcase_char(char *c)
/** Data **/
-#line 42 "ext/puma_http11/http11_parser.c"
+#line 37 "ext/puma_http11/http11_parser.c"
```
> ragel.yml - remove Windows due to incorrect line directives

- docs/restart.md
Hi! I recently tried to set up puma with hot restart, deployed with capistrano to a symlinked directory, and ran into the problem that after deploy changes to the app were not picked up. I have only glanced over the phased restart section before and didn't realize that the "cd to `directory` on startup" mechanism is also relevant for hot restarts. Here's a minor doc change to clarify that.
> [ci skip] Note symlink mechanism in restart documentation for hot restart

- lib/puma/server.rb
Add `attr_reader :options` for Puma::Server.
On the one hand, it can reduce the use of instance variables. 
Using the reader method can more clearly indicate that this is a read-only attribution and will not be changed in other methods.
On the other hand, It allows `Puma::Server` to expose `@options` for external use.
I have a scenario that requires this feature: Fetch PUMA Workers count of options in Rails runtime.
When using PUMA Cli to start the service, we can indeed do this `::Puma.cli_config.options[:workers]`,
but if we start the server through `rails server`,  `Puma` can not response `cli_config` method.
```ruby
Puma::Server.current.instance_variable_get('@options').fetch(:workers)
```
> Draft: Add attr_reader options for Puma::Server

- lib/puma/cluster.rb
- lib/puma/cluster/worker.rb
- lib/puma/server.rb
- test/test_integration_cluster.rb
Closes https://github.com/puma/puma/issues/3282
Ensures that the master process (and therefore the entire cluster) is only gracefully shut down when all workers have reached the idle timeout when in cluster mode, as opposed to any worker (current implementation).
<details>
<summary>Also adds a log to indicate that the idle time out has been reached in both modes</summary>
```
* Puma version: 6.4.0 (ruby 3.2.2-p53) ("The Eagle of Durango")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 70263
* Listening on http://0.0.0.0:9292
Use Ctrl-C to stop
- Idle timeout reached # 👈🏽
- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2023-11-29 16:15:05 +1000 ===
- Goodbye!
```
```
[70332] Puma starting in cluster …
```
> [Fix #3282] `idle-timeout` not waiting on all workers in cluster mode

- docs/systemd.md
Since NoDelay apparently is no longer the default, the example in the systemd docs should also reflect this. This follows up https://github.com/puma/puma/pull/2631.
If the line should be removed instead of commented out (or if the added comment is unclear or unhelpful), please let me know!
(This is my first PR here, and I hope I've ticked the right boxes. Sorry if I overlooked anything!)
> Add comment about `NoDelay=true` in systemd docs

- lib/puma/cluster.rb
- test/config/process_detach_before_fork.rb
- test/test_integration_cluster.rb
Starting with Puma v6.4.1, we observed that killed Puma cluster workers were never being restarted when the parent was run as PID 1. For example, I issued a `kill 44` and PID 44 remained in the `defunct` state:
```
git@gitlab-webservice-default-78664bb757-2nxvh:/var/log/gitlab$ ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
git            1       0  0 Jan09 ?        00:01:39 puma 6.4.1 (tcp://0.0.0.0:8080) [gitlab-puma-worker]
git           23       1  0 Jan09 ?        00:05:46 /usr/local/bin/gitlab-logger /var/log/gitlab
git           41       1  0 Jan09 ?        00:01:55 ruby /srv/gitlab/bin/metrics-server
git           44       1  0 Jan09 ?        00:02:41 [ruby] <defunct>
git           46       1  0 Jan09 ?        00:02:38 puma: cluster worker 1: 1 [gitlab-puma-worker] …
```
> Fix child processes not being reaped when `Process.detach` used

- test/runner
We had (rack2) tests fail on 2.4 like this:
/home/runner/work/puma/puma/lib/rack/handler/puma.rb:140:in `<top (required)>': undefined method `register' for Rack::Handler:Module (NoMethodError)
from /home/runner/work/puma/puma/test/test_rack_handler.rb:6:in `require'
from /home/runner/work/puma/puma/test/test_rack_handler.rb:6:in `<module:TestRackUp>'
from /home/runner/work/puma/puma/test/test_rack_handler.rb:5:in `<top (required)>'
from test/runner:32:in `require'
from test/runner:32:in `block in <main>'
from test/runner:32:in `each'
from test/runner:32:in `<main>'
https://github.com/puma/puma/actions/runs/7672076948/job/20911807383#step:10:13
> Deterministic `require`s in `test/runner`

- lib/puma/server.rb
- test/helper.rb
- test/helpers/test_puma/assertions.rb
- test/test_puma_server.rb
- test/test_web_server.rb
The third commit fixes the error.  If one runs the test suite with the first two commits, the following failures occur:
```
TestPumaServer#test_large_chunked_request_header [/mnt/c/Greg/GitHub/puma/test/test_puma_server.rb:917] 
WebServerTest#test_bad_path [/mnt/c/Greg/GitHub/puma/test/test_web_server.rb:72]
```
Also, the 2nd error above generates a log of the below, which is a pita to read:
```
1) Failure:
WebServerTest#test_bad_path [/mnt/c/Greg/GitHub/puma/test/test_web_server.rb:72]:
Expected /\.rb:\d+:in `[^']+'\z/ to match # encoding: ASCII-8BIT
"HTTP/1.1 400 Bad Request\r\nContent-Length: 491\r\n\r\nPuma caught this error: Puma::HttpParserError (Puma::HttpParserError)\n/mnt/c/Greg/GitHub/puma/lib/puma/request.rb:426:in `rescue in …
```
> Fix response repeated status line when request is invalid or errors are raised

- .github/workflows/turbo-rails.yml
Context:
- https://github.com/ruby/ruby/commit/d16f992e1bfacb638b8a9b8b5a7ef8149ee1d50d
- https://github.com/ruby/ruby/commit/1500946ce4ed7d89ed33059e3629e526b1dc207a
Experiment to see if this fixes [a failing CI worflow](https://github.com/puma/puma/actions/runs/7529388305/job/20493515442#step:6:22) since [`mutex_m` was added to the relevant Rails gemfiles](https://github.com/rails/rails/pull/48907) and [included in the `7.1` release](https://github.com/rails/rails/releases/tag/v7.1.0). It has also [since been dropeed](https://github.com/rails/rails/commit/bcdeea5da7657375df21a856135ae7a66a8c3812) on Rails edge.
~Even if this passes, the root cause is that it's missing from the gemfiles in https://github.com/ruby-concurrency/concurrent-ruby. I'm hoping to resolve that in …
> Use Rails `7.1` with Ruby head in `turbo-rails` CI

- test/test_error_logger.rb
- test/test_puma_server.rb
- test/test_web_server.rb
CI only changes to account for Ruby head error logging changes.  Current head builds are failing.
> [CI] - Ruby head changed 'odd' backtick in error messages to apostrophe / single quote

- test/test_plugin_systemd_jruby.rb
- test/test_thread_pool.rb
Fixes common failures in JRuby & TruffleRuby.
1. [[CI] Fix test_thread_pool.rb (TestThreadPool#test_trim_thread_exit_hook)](https://github.com/puma/puma/commit/fac1c9af928ff3d7bbf6ce938925e715dd3eac74) - give non-MRI jobs some time to process.
2. [[CI] FIx test_plugin_systemd_jruby.rb](https://github.com/puma/puma/commit/5d30be8d31b33fb35eece4c390142db1c91c86b9) - test was checking a value in the main test process, but JRuby is running in a sub-process.
> [CI] non MRI fixes - test_thread_pool.rb, test_plugin_systemd_jruby.rb

- lib/puma/configuration.rb
A minor thing I noticed when looking into something unrelated. We seem to always be requiring the builtin rack builder even when it isn't used. This PR ensures that `Puma::Rack::Builder` is only required when `Rack::Builder` cannot be loaded.
> Lazily require `Puma::Rack::Builder`

- lib/puma/cluster.rb
An oversight on my part in #3283. `Puma::Cluster#run` constantly checks if all workers have reached their idle timeout even when the feature isn't being used. This change ensures that this check only runs when `idle_timeout` is configured.
Also includes a micro-optimisation which ensures the idle workers state hash isn't unnecessarily initialised until actually required (either a worker indicates timeout reached via pipe or `Puma::Cluster#run` checks if `all_workers_idle_timed_out?`).
All of these changes are covered by existing tests.
> Avoid checking if all workers reached timeout unless idle timeout is configured

- README.md
Improve documentation of `lowlevel_error_handler`
Closes #3345
> Improve `lowlevel_error_handler` docs

- test/test_log_writer.rb
- test/test_worker_gem_independence.rb
- test/worker_gem_independence_test/new_nio4r/Gemfile
- test/worker_gem_independence_test/old_nio4r/Gemfile
Ruby head has been failing in CI, and also noticed more failures locally with Ubuntu & Windows.
Two issues:
1. Failures in:
https://github.com/puma/puma/blob/87fd289503c16bf794c7a1a5c6e622bca2b4a071/test/test_worker_gem_independence.rb#L16-L21
With recent changes in Ruby head, nio4r previous to 2.6.0 won't compile, fixed in https://github.com/socketry/nio4r/commit/3c1f9b83250df696f1c7d055a9a4d7bd7fee126e.  Solution was updating the nio4r versions.
2. Failures in:
https://github.com/puma/puma/blob/87fd289503c16bf794c7a1a5c6e622bca2b4a071/test/test_log_writer.rb#L151-L181
Fixed by only using LogWriter to to write to itself...
Closes #3342
> [CI] - Fix Ruby head failures

- benchmarks/local/response_time_wrk.rb
Using a different build of `wrk` is tricky without this.
> Allow specifing `wrk` using environment variable.

- .github/workflows/tests.yml
This PR only changes the tests.yml workflow file.
GitHub Actions has deprecated macOS 11, and macOS 14 is now available and runs on arm systems.
1. Add macOS 14, drop macOS 11
2. Standard GHA allow 5 concurrent macOS jobs to run.  Adjust jobs so we run 15 macOS jobs.  Currently, the last jobs running are macOS jobs.
Interestingly, the tests.yml workflow in my fork passed...
> [CI] Add macOS 14, remove 11, adjust so tests.yml runs 15 macOS jobs

- lib/puma/client.rb
- test/test_puma_server.rb
In client.rb code for processing chunked request bodies, `chunk.size` was used.  This may contain both portions of the body and also hex size data.  Hex size data may also contain 'headers'.  Use `line.size`, as it only contains hex size data.
The first commit contains a new test (`test_chunked_body_pause_within_chunk_size_hex`), which fails on master with the below.  Note that there are several `test_chunked_body_pause` tests, this adds another where a pause exists within the hex encoded length of the next chunk.  Thanks to @skliew, who opened issue #3337.
```
1) Failure:
TestPumaServer#test_chunked_body_pause_within_chunk_size_hex [test/test_puma_server.rb:1168]:
--- expected
+++ actual
@@ -1,5 +1,15 @@
-"HTTP/1.1 200 OK\r
+# encoding: ASCII-8BIT
+#    valid: true
+"HTTP/1.1 400 Bad …
```
> client.rb - fix request chunked body handling

- README.md
- ext/puma_http11/extconf.rb
- ext/puma_http11/mini_ssl.c
- lib/puma/dsl.rb
- lib/puma/minissl.rb
- lib/puma/minissl/context_builder.rb
- test/test_binder.rb
- test/test_config.rb
- test/test_puma_server_ssl.rb
Closes https://github.com/puma/puma/issues/3343
As described in the linked issue, it's desirable to be able to restrict the ciphersuites used for TLSv1.3 connections for security reasons, but Puma doesn't yet support that. https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_cipher_list.html explains that OpenSSL has a different setting for TLSv1.3 ciphers than for TLSv1.2 and below. 
This pull request adds a new option to pass in TLSv1.3 ciphersuites config - `ssl_ciphersuites`. I've explained its usage in the README. This is intentionally similar to the existing `ssl_cipher_filter` option, which does the same job for TLSv1.2 and below.
- [n/a] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
> Add `ssl_ciphersuites` option for TLSv1.3 ciphers

- ext/puma_http11/extconf.rb
This PR only changes logging when compiling with OpenSSL.
Currently, `extconf.rb` has comments about which functions exist in various OpenSSL versions.  This PR changes the comments to ouput logging.  Example below, all lines beginning with three dashes are new:
```
checking for pkg-config for openssl... [" ", "", "-lssl -lcrypto"]
──── Using OpenSSL pkgconfig (openssl.pc) ────
checking for openssl/bio.h... yes
──── Below are yes for 1.0.2 & later ────
checking for DTLS_method() in openssl/ssl.h... yes
checking for SSL_CTX_set_session_cache_mode(NULL, 0) in openssl/ssl.h... yes
checking for SSL_CTX_set_ecdh_auto(NULL, 0) in openssl/ssl.h... yes
──── Below are yes for 1.1.0 & later ────
checking for TLS_server_method() in openssl/ssl.h... yes
checking for …
```
> extconf.rb - add logging for OpenSSL versions

- lib/puma/dsl.rb
`wait_for_less_busy_worker` was enabled by default with #2940 and included in the [6.0.0 release](https://github.com/puma/puma/releases/tag/v6.0.0). The DSL docs do not reflect this however unlike other config options that are enabled by default.
> [ci skip] Indicate that `wait_for_less_busy_worker` is enabled by default in DSL docs

- lib/puma/server.rb
- test/test_puma_server_current.rb
The current implementation of `Puma::Server.current` will break inside fibers, e.g. lazy enumerators because it's fiber local, not thread local. If the intention is to have an actual thread local, this is the best fix.
> Use actual thread local for `Puma::Server.current`.

- lib/puma/dsl.rb
I decided to audit the DSL docs as a follow up to #3371.
This adds missing defaults similar to the PR above that I've cross checked with the [configuration defaults](https://github.com/puma/puma/blob/7a999de2f0da5648c30f62a6e11d74c7ddbe4e00/lib/puma/configuration.rb#L128-L173), makes the wording and formatting for defaults consistent, adds some missing docs and examples, and makes the formatting for all tags (`@note`, `@example`, `@see` and `@version`) consistent.
> [ci skip] Update DSL docs with consistent defaults, tags and formatting

- .github/workflows/turbo-rails.yml
turbo-rails CI is broken, the problem probably is an issue there or Rails, but this is a temp fix.
**Note:** when turbo-rails CI is run, the workflow file patches its Gemfile, etc to work with Puma master.  So, Puma's Gemfile isn't used...
Closes #3400
> [CI] Fix turbo-rails sqlite3 problem

- .github/workflows/skip_duplicate_workflow_runs.yml
From https://github.com/fkirc/skip-duplicate-actions?tab=readme-ov-file#concurrent_skipping
> Skip a workflow run if the same workflow is already running
but it does not seem reliable, for example, this workflow run https://github.com/puma/puma/actions/runs/9386209788 looks 100% green but that is because everything was skipped
https://github.com/fkirc/skip-duplicate-actions/issues has many reports about problems with `concurrent_skipping`
https://github.com/celerity/celerity-runtime/pull/148 is an example of another project disabling it.
[ci skip]
> CI: disable `concurrent_skipping` for skip-duplicate-actions

- test/rackup/hello.ru
Rack 3 requires headers to be an unfrozen hash. This appears to be causing some problems, e.g.
```
3) Failure:
TestIntegrationSingle#test_usr2_restart [test/test_integration_single.rb:25]:
--- expected
+++ actual
@@ -1 +1,6 @@
-"Hello World"
+"Puma caught this error: can't modify frozen Hash: {\"Content-Type\"=>\"text/plain\"} (FrozenError)
+/home/runner/work/puma/puma/lib/puma/request.rb:111:in `delete'
+/home/runner/work/puma/puma/lib/puma/request.rb:111:in `handle_request'
+/home/runner/work/puma/puma/lib/puma/server.rb:467:in `process_client'
+/home/runner/work/puma/puma/lib/puma/server.rb:248:in `block in run'
+/home/runner/work/puma/puma/lib/puma/thread_pool.rb:155:in `block in spawn_thread'"
```
> Headers must not be frozen.

- test/helpers/integration.rb
This is another experimental branch to try and fix race conditions in CI.
```
/home/runner/work/puma/puma/lib/puma/dsl.rb:135:in `read': No such file or directory @ rb_sysopen - /home/runner/work/_temp/config20240605-2615-l1fl0k.rb (Errno::ENOENT)
from /home/runner/work/puma/puma/lib/puma/dsl.rb:135:in `_load_from'
from /home/runner/work/puma/puma/lib/puma/configuration.rb:238:in `block in load'
from /home/runner/work/puma/puma/lib/puma/configuration.rb:238:in `each'
from /home/runner/work/puma/puma/lib/puma/configuration.rb:238:in `load'
from /home/runner/work/puma/puma/lib/puma/launcher.rb:54:in `initialize'
from /home/runner/work/puma/puma/lib/puma/cli.rb:66:in `new'
from /home/runner/work/puma/puma/lib/puma/cli.rb:66:in `initialize'
from /home/runner/work/puma/puma/bin/puma:8:in `new' …
```
> Don't let the config file go out of scope while it's still in use.

- test/test_integration_ssl_session.rb
I haven't seen any of these tests fail, but I have seen some retry.  All of the tests create two ssl requests, and the SSLSockets have `OpenSSL::SSL::SSLContext#session_new_cb` set.
This PR adds code so the second request waits for the callback.  The tests haven't failed/retried in the limited CI testing I've done.
Note that, like many of the tests involving 'retry', I've never had these tests fail locally.
> [CI] test_integration_ssl_session.rb - wait for session callback

- test/helpers/integration.rb
Hopefully more stable:
- https://github.com/puma/puma/pull/3408#issuecomment-2153329320
Similar change as https://github.com/puma/puma/pull/3296
> CI: Use `Tempfile.create` in `TestIntegration`

- lib/puma/client.rb
- lib/puma/request.rb
- test/test_puma_server.rb
Currently, `Tempfile.new` is used in `Client` when a request contains content (a body) that is either very large or indeterminate (chunked).  `Tempfile.new` creates a finalizer that removes the `Tempfile`, so its removal is dependent on GC.
Recently, Windows head builds started logging the following in CI, a log is [here](https://github.com/puma/puma/actions/runs/7301425484/job/19898046945#step:11:433).  Note that Ruby head (3.3) has had many changes re GC, and one might call it more agressive...
```
D:/a/puma/puma/lib/puma/thread_pool.rb:113: warning: Exception in finalizer #<Tempfile::Remover:0x000001939f62dc50 @pid=2472, @path="D:/a/_temp/puma20231222-2472-94nq5x">
D:/ruby-mswin/lib/ruby/3.3.0+0/tempfile.rb:319:in `unlink': Permission denied @ apply2files - …
```
> lib/client.rb - use Tempfile.create instead of Tempfile.new for request bodies

- lib/puma/dsl.rb
- test/config/event_on_booted.rb
- test/config/event_on_booted_and_on_stopped.rb
- test/test_integration_cluster.rb
- test/test_integration_single.rb
This is how it is described in [README.md](https://github.com/puma/puma/tree/f027b319bcc72db27841d389d1efc6fc7d921634?tab=readme-ov-file#master-process-lifecycle-hooks)
However, using `on_stopped` in fact leads to an exception because the `on_stopped` method is not defined in `Puma::DSL`.
_PS: English is not my native language; please excuse typing errors._
Ref: https://github.com/puma/puma/discussions/3379
Close https://github.com/puma/puma/pull/3380
> Define the on_stopped method in Puma::DSL

- .github/workflows/rack_conform.yml
CI message from rack_conform:
> Because every version of rack-conform depends on Ruby >= 3.1
> [CI] rack_conform.yml - change Ruby 2.7 job to 3.1

- docs/signals.md
The signals.md doc referenced Ruby 2.1, but that version is no longer supported for Puma. This change updates the references to latest Ruby version's docs.
> [ci skip] Update signals.md to reference a newer Ruby version's docs

- .github/workflows/ragel.yml
From https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
> The macos-11 label has been deprecated and will no longer be available
> after 28 June 2024.
> CI: use `macos-12` in ragel workflow

- .github/workflows/turbo-rails.yml
This error is common in CI:
1) Error:
BroadcastsTest#test_Message_broadcasts_with_renderable:_render_option:
Ferrum::ProcessTimeoutError: Browser did not produce websocket url
within 10 seconds, try to increase `:process_timeout`. See
https://github.com/rubycdp/ferrum#customization
It is possible to control this timeout (and another one) via ENV vars: https://github.com/rubycdp/ferrum/blob/v0.15/lib/ferrum/browser/options.rb#L10-L11
"timeout" is
> The number of seconds we'll wait for a response when communicating with browser. Default is 5.
"process_timeout" is (defaults to 10)
> How long to wait for the Chrome process to respond on startup.
Both ferrum CI and cuprite CI has the timeouts set to 25 and 15:
* https://github.com/rubycdp/ferrum/blob/19767d0885afbebc95574eda685e04dc9da2b47d/.gi …
> CI: bump Ferrum/Chrome timeouts (for turbo-rails tests)

- .github/workflows/tests.yml
This was lowered from 10 to 6 min in https://github.com/puma/puma/pull/3130
Generally this steps takes a little bit over 3 min, but when tests are retried, this steps takes more time, I think CI should account for that.
The one I observed added 2+ min at https://github.com/puma/puma/actions/runs/9928834870/job/27425817733?pr=3426#step:10:213 and it looks like it was canceled mid-flight.
That one would still have been a failure (looks like all retries exhausted for that test case), but I guess in theory if many things are retried (but eventually pass) we could have runs that would pass, being canceled.
> CI: give MRI tests more time

- test/test_integration_pumactl.rb
- test/test_integration_single.rb
CI tests often use `assert_match` to check that errors are thrown.  Curl recently changed "Couldn't" to "Could not", and a proper space was added to a Ruby error message.
> [CI] - fixup failures due to 'error' message changes

- .github/workflows/tests.yml
The most recent workflow run in a PR failed on the [NON MRI: macos-13 jruby](https://github.com/puma/puma/actions/runs/10374918870/job/28723479842) job.  Currently, there is a step in the workflow setting the JDK version to 17.  After reviewing code in the build repos, this code is no longer proper, and will cause issues when we move/add jobs using macos arm64 runners.  Additionally, new OS's have been added, and they default to newer JDK versions.
Hence, remove the step code.  I ran it four times in my fork, and the 'NON MRI: macos-13 jruby' job passed four times.
> [CI] tests.yml - remove step setting JDK version

- .github/workflows/tests.yml
- test/helper.rb
CI broke with the release of Minitest 5.25.0.
Two commits:
1. test/helper.rb - allow to run with new and old Minitest - See https://github.com/minitest/minitest/commit/8cd3b1c749c778038ead3ddf7894dc19c1fe4797.  This conflicts with our prepending a method to allow our tests to fail on a timeout.
2. [CI] fix Minitest bug - revert when Minitest 5.25.1 is released - See https://github.com/minitest/minitest/pull/1010.  Previously Minitest had code that could be equivalent to:
```ruby
nil ~= /broken/
```
it was replaced by:
```ruby
nil.match?(/broken/)
```
`match?` is not defined on `nil`, so an error is thrown.  This commit is a temporary fix until the next Minitest release.  It defines an `ENV` variable in the Actions workflow so that the value isn't `nil`.
> [CI] Fixes for Minitest 5.25.0 - used with Ruby 2.6 and later

- test/test_example_cert_expiration.rb
`test/test_example_cert_expiration.rb` checks for expiring certs.
1. Updated to show the addition of the the 'generate_all_certs' scritp and md file.
2. Currently, it generates an error for each expired cert.  Updated to only generate one error, example:
```text
1) Failure:
TestExampleCertExpiration#test_certs_not_expired [test/test_example_cert_expiration.rb:45]:
** The below certs in the 'examples/puma' folder are expiring soon.
See 'examples/generate_all_certs.md' for instructions on how to regenerate.
cert_puma.pem
client_certs/ca.crt
client_certs/client.crt
client_certs/client_unknown.crt
client_certs/server.crt
client_certs/unknown_ca.crt
chain_cert/ca.crt
chain_cert/cert.crt
chain_cert/intermediate.crt
```
> [CI] Update test_example_cert_expiration.rb

- test/test_worker_gem_independence.rb
- test/worker_gem_independence_test/new_json/Gemfile
- test/worker_gem_independence_test/new_json_with_puma_stats_after_fork/Gemfile
- test/worker_gem_independence_test/new_nio4r/Gemfile
- test/worker_gem_independence_test/old_json/Gemfile
- test/worker_gem_independence_test/old_json_with_puma_stats_after_fork/Gemfile
- test/worker_gem_independence_test/old_nio4r/Gemfile
The files used with the 'worker_gem_independence' tests were added to Puma 5, which was compatible with Ruby 2.2.
Update json & nio4r versions to more current versions, and add checks in Gemfiles to remove Ruby 3.4 (current head) warninga like the below, which is due to the common 'bundled gems' issue:
```text
warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
```
> [CI] test/worker_gem_independence_test - update versions, fix for Ruby 3.4/head

- test/helpers/integration.rb
- test/test_integration_cluster.rb
- test/test_integration_pumactl.rb
- test/test_integration_single.rb
- test/test_integration_ssl.rb
The comments for the new `wait_server` method:
Most integration tests do not stop/shutdown the server, which is handled by `teardown` in this file.
For tests that do stop/shutdown the server, use this method to check with `wait2`, and also clear variables so `teardown` will not run its code.
Close https://github.com/puma/puma/pull/3457
> [CI] test/helpers/integration.rb - add wait_server, use in other test files

- test/config/hook_data.rb
- test/test_integration_cluster.rb
There have been intermittent failures reading the files written by the tests.  Update to use `STDOUT` instead of files.
> [CI] test_integration_cluster - use STDOUT for test_hook_data

- test/helpers/integration.rb
`TestIntegration#hot_restart_does_not_drop_connections` cycles thru server 'restart' commands and checks request handling.  A thread (`restart_thread`) does the cycling.  It calls `wait_for_server_to_boot`, checking for a log of `Ctrl-C`.  This may timeout on CI servers, and raises an error inside the thread.  `abort on exception` is true, so CI stops cold.
This PR catches the error, and retries seem to pass.
> [CI] test/integration.rb - catch 'exception in thread'

- test/helpers/integration.rb
- test/test_worker_gem_independence.rb
Updates pid handling.  If `cli_server` fails `wait_for_server_to_boot`, current code errors before `@pid` is set, which means the process can't be shut down.  Added code to set `@pid` equal to the Puma process's pid via the server log.
Refactor `cli_server` command line, since test process sets `RUBYOPT` to load `bundler/setup`.
> [CI] integration.rb - update @pid value by reading server log, revise BASE

- test/test_puma_server_ssl.rb
test_puma_server_ssl.rb - add rejection helper, use for protocol rejection tests
test_puma_server_ssl.rb - don't share STDOUT & STDERR for logging when running parallel
> []CI] Fix up test_puma_server_ssl.rb - protocol rejection and log_writer setup

- .github/workflows/turbo-rails.yml
Noticed a timeout at https://github.com/puma/puma/actions/runs/10930536404/job/30343630502?pr=3491#step:6:262
Better tests run slow and green than quick and red (they aren't quick anyway so ...)
> CI: bump turbo-rails browser timeouts

- .github/workflows/turbo-rails.yml
turbo-rails added Ruby 3.0 syntax: https://github.com/hotwired/turbo-rails/issues/681
> CI: remove turbo-rails ruby 2.7 job, does not work

- lib/puma/dsl.rb
Other methods mention worker index being a block argument to the callback. Now, this one does, too.
> [doc] Mention worker index in on_worker_shutdown docs

- lib/puma/control_cli.rb
This PR changes the help output for pumactl's --quiet option to match the way it reads puma --help.
This cosmetic wording fix makes the line perhaps read easier.
> [doc] control_cli.rb: Harmonize help message for -Q with bin/puma [ci skip]

- test/rackup/sleep.ru
- test/rackup/sleep_pid.ru
- test/rackup/sleep_step.ru
There are three test/rackup/sleep*.ru files, all do not accept a float value.  Modify them to do so.
Since a lot of the recent testing of 'keep-alive' connections has used 200mS app delay, having these in master would make things easier.
> [CI] test/rackup/sleep*.ru - allow float values

- Gemfile
No need to lock it down, seems to only cause issues.
Close https://github.com/puma/puma/issues/3490
> Always use latest `rake-compiler`

- lib/puma/binder.rb
- lib/puma/cli.rb
- lib/puma/configuration.rb
- lib/puma/control_cli.rb
- lib/puma/error_logger.rb
- lib/puma/launcher.rb
- lib/puma/log_writer.rb
Puma makes use of ENV settings in several files.  This can cause isolation issues when running tests.  Add parameters to methods to allow ENV to be set in CI with isolation.
A keyword parameter `env: ENV` has been added where it will work, there are a few methods accepting hash parameters that required a different approach.  Some methods without parameters were changed by adding `env = ENV`.
This passes the 'turbo-rails' and 'rack conform' workflows.  I ran Capybara CI with this branch in my fork, and most jobs using Puma seemed to pass.  There are some issues with RuboCop and warnings.
See https://github.com/MSP-Greg/capybara/actions/runs/10820642778/job/30021090682#step:4:14
**Note:** this PR only includes library file changes and shows that current CI passes.  A later PR with have test …
> Add parameters to Puma methods to allow CI to change ENV in isolation

- test/helpers/test_puma/puma_socket.rb
- test/test_busy_worker.rb
Removes blocking request socket.read calls
This test file does cause CI retries and failures.
> [CI] - test_busy_worker.rb - use TestPuma::PumaSocket

- test/test_launcher.rb
The recent test PR's have several job failures, and one test failed in this file.
1. One test created a thread, and the thread contained an assert.  If the assert fails, the job stops.  Fixed.
2. One test set an ENV variable, but if the test failed, it wasn't unset.  Fixed using `ensure`.
3. One test used Minitest's `capture_io`, which should be avoided.  Removed.
Additionally, some refactoring.
> [CI] test/test_launcher.rb - fixups

- .github/workflows/tests.yml
- lib/puma/jruby_restart.rb
- lib/puma/launcher.rb
Also adds macos-14 jruby job to the CI, which is running on ARM64.
See https://github.com/puma/puma/issues/3446
Thanks to @headius for the help.
> Fixup jruby_restart.rb & launcher.rb to work with ARM64 macOS JRuby

- lib/puma/configuration.rb
- lib/puma/dsl.rb
- lib/puma/request.rb
- lib/puma/server.rb
- test/test_config.rb
- test/test_puma_server.rb
Puma does not currently support a configuration option for enabdling/disabling keep-alive connections to the server. Because a thread can only handle a single connection at a time, the Puma server under default config will end up serving requests out of order, preferring to process requests off it's already in flight connection. See https://github.com/puma/puma/issues/3487 for more details.
To get around this issue, Puma will close connections every `max_fast_inline` requests. When `max_fast_inline=1`, the server should close the connection after each request, but this only happens _most of the time_. It does not happen all the time, due to the following conditional:
https://github.com/puma/puma/blob/48b89b5f595f4cd72b5e60a3cb49f4f2949afec3/lib/puma/request.rb#L163-L169
Thus it's still …
> Add opt to enable keep-alives

- lib/puma/binder.rb
- lib/rack/handler/puma.rb
- test/test_rack_handler.rb
allows binding to abstract namespace sockets from rack as implemented in https://github.com/puma/puma/pull/2564. rails example: `bin/rails server -b "@/socks/rails.sock"`
errors without either change:
```
/usr/local/lib/ruby/3.3.0/uri/generic.rb:601:in `check_host': bad component(expected host component): [unix://@/socks/rails.sock] (URI::InvalidComponentError)
```
```
/usr/local/bundle/gems/puma-6.4.3/lib/puma/binder.rb:186:in `realdirpath': No such file or directory @ realpath_rec - /usr/src/rails/@ (Errno::ENOENT)
```
> add support in rack handler & fix regression in binder for linux abstract namespace sockets

- lib/rack/handler/puma.rb
- test/test_rack_handler.rb
There is currently no test in `test_rack_handler` for an ssl connection/host.
Add a test, and replace
```ruby
elsif host && host =~ /^ssl:\/\//
```
with
```ruby
elsif host&.start_with? 'ssl://'
```
in lib/rack/handler/puma.rb
> rack/handler/puma.rb - ssl - use `start_with?`, add test

- lib/puma/null_io.rb
- test/test_null_io.rb
As per the title.
We have code like this in a library I'm working on:
``` ruby
def body
pos = request.body.pos
request.body.rewind
@request_body = request.body.read
ensure
request.body.rewind
request.body.seek(pos)
end
```
This works fine for normal request bodies, but chokes on empty requests because `NullIO` does not implement `#seek` or `#pos`. My understanding is that these methods are part of the IO interface, and so should be implemented here. 🤔
> Implement NullIO#seek and #pos to mimic IO

- lib/puma/cluster/worker.rb
- lib/puma/cluster/worker_handle.rb
i was making another PR to add another type of stat (busy_threads), and noticed this
it's the heroes like me which keep this project afloat.
- [ x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x ] I have updated the documentation accordingly.
- [? ] All new and existing tests passed, including Rubocop.
> normalize whitespace in worker stats string

- test/test_null_io.rb
CI has been failing on TruffleRuby, one needs to look at the bottom of the main job page to see.  I believe is it stable and passing, but this PR doesn't not remove the 'allow failure' logic.
Error message in TruffleRuby is different.
> [CI] - fix up test_null_io.rb TruffleRuby failure

- test/test_rack_handler.rb
If you have something running on port 9292 and try to run the Puma tests, they fail like this
```shell
$ ./test/runner test_rack_handler.rb
Run options: --seed 57070
...#<Thread:0x00000001201860c0 /Users/dentarg/src/puma/test/test_rack_handler.rb:24 run> terminated with exception (report_on_exception is true):
/Users/dentarg/src/puma/lib/puma/binder.rb:335:in `initialize': Address already in use - bind(2) for "0.0.0.0" port 9292 (Errno::EADDRINUSE)
from /Users/dentarg/src/puma/lib/puma/binder.rb:335:in `new'
from /Users/dentarg/src/puma/lib/puma/binder.rb:335:in `add_tcp_listener'
from /Users/dentarg/src/puma/lib/puma/binder.rb:164:in `block in parse'
from /Users/dentarg/src/puma/lib/puma/binder.rb:147:in `each'
from /Users/dentarg/src/puma/lib/puma/binder.rb:147:in `parse'
from …
```
> CI: Use random port in `test_on_booted`

- test/test_persistent.rb
I've seen intermittent failures in JRuby, as below:
```text
1) Failure:
TestPersistent#test_no_chunked_in_http10 [test/test_persistent.rb:126]:
--- expected
+++ actual
@@ -1,4 +1,6 @@
+# encoding: ASCII-8BIT
+#    valid: true
"HTTP/1.0 200 OK\r
X-Header: Works\r
\r
-HelloChunked"
+Hello"
```
This test sets the body as an enumeration, and JRuby intermittently reads only the first element.  Split the write and read operations, and add a small delay only for JRuby jobs.
Note that I ran the test several times locally, it never failed.
> [CI] test_persistent.rb - fix intermittent fail in test_no_chunked_in_http10

- lib/puma/null_io.rb
- test/test_null_io.rb
See https://github.com/rack/rack/pull/2115, which identifies a bug that occurs with `Rack::MockRequest.env_for`.
See also [Rack Spec: The Input Stream](https://msp-greg.github.io/rack/file.SPEC.html#label-The+Input+Stream).
More IO instance methods may need to be added to `Puma::NullIO`.
> null_io.rb - add external_encoding, set_encoding, binmode, binmode?

- lib/puma/server.rb
- test/helper.rb
- test/test_busy_worker.rb
Great job on the #2079 PR!
#2079 PR added the `wait_for_less_busy_worker` method, which improves request allocation to avoid being assigned to busy workers. However, for a single model, there are no multiple workers, so there is no need to call the `wait_for_less_busy_worker` method.
_PS: English is not my native language; please excuse typing errors._
> Single mode skip wait_for_less_busy_worker

- test/helpers/integration.rb
Adds `Errno::EBADF` to `thread_run_refused` in `integration.rb` as allowed error to macos unix socket tests.
Some tests create client http requests in threads, and every error needs to be caught, otherwise the CI favorite message of 
```text
terminated with exception (report_on_exception is true)
```
occurs, which stops the tests from completing.  Currently, an array of socket related errors is used.
To make things interesting, different OS/Platform combinations may raise different errors, and it also may depend on the socket type.
I've wondered if there is a better way, maybe we could simplify `thread_run_refused` to simply be an array of socket errors.  Not.sure.  The code hasn't been touched for approx two years.
> [CI] integration.rb - update `thread_run_refused` for additional errors

- Gemfile
- lib/rack/handler/puma.rb
- test/test_rack_handler.rb
This almost falls in the category of "Don't get me started...".
It will break things.
Previous versions of `Rackup` also defined `Rackup::Handler`, and Puma assumed that if `Rackup` was defined, so was `Rackup::Handler`.  That is not the case with v1.0.1.  All it defines is `Rackup::VERSION`.  It's simply a Rack 2 compatible version that makes Gemfile logic simpler.  Its gemspec also contains:
```ruby
spec.add_dependency "rack", "< 3"
spec.add_dependency "webrick"
```
This PR now checks for the existence of `Rackup::Handler`
Closes #3531
> lib/rack/handler/puma.rb - fix for rackup v1.0.1, adjust Gemfile

- .github/workflows/tests.yml
Currently, when CI runs the tests.yml workflow, the main jobs are all prefaced with `MRI:` or `NON-MRI:`. On smaller devices (tablets), this often truncates the job title, which contains the OS, Ruby version/platform, etc.
I don't think the `MRI:` or `NON-MRI:` text adds any helpful information, so let's remove them.
After this PR, I can now see the full job title when viewed on an iPad.
This PR only changes the workflow file.
Before PR: https://github.com/puma/puma/actions/runs/11508915225
After PR: https://github.com/puma/puma/actions/runs/11508748300
> [CI] tests.yml - remove 'MRI' and 'NON-MRI' from job titles

- lib/puma/server.rb
- lib/puma/thread_pool.rb
Many of the variables in ThreadPool are locked when changing their values.  Current stats code may enter that lock more than once. See https://github.com/puma/puma/pull/3517#discussion_r1799652829.
This PR creates a `ThreadPool#stats` method that returns a hash of the stats data that comes from ThreadPool, using a single lock.
> Add ThreadPool#stats and adjust Server#stats to use it

- test/test_launcher.rb
* `test_puma_stats_clustered` - recently there was one CI failure, logged as the below.  Fixup to (hopefully) consistently pass.
```text
1) Error:
TestLauncher#test_puma_stats_clustered:
TimeoutEveryTestCase::TestTookTooLong: execution expired
lib/puma/cluster.rb:242:in 'Process.waitall'
lib/puma/cluster.rb:242:in 'Puma::Cluster#stop_blocked'
lib/puma/launcher.rb:274:in 'Puma::Launcher#do_graceful_stop'
lib/puma/launcher.rb:259:in 'Puma::Launcher#do_run_finished'
lib/puma/launcher.rb:198:in 'Puma::Launcher#run'
test/test_launcher.rb:116:in 'TestLauncher#test_puma_stats_clustered'
```
* `test_log_config_enabled` - current code only checked the config 'keys'.  Update code to check keys and values, and also an exact match of key/value pairs.  Remove use of `ENV`.
> [CI] test_launcher.rb - fixup

- README.md
- lib/puma/configuration.rb
- test/helpers/integration.rb
- test/test_web_concurrency_auto.rb
- test/test_worker_gem_independence.rb
- test/web_concurrency_test/Gemfile
- test/web_concurrency_test/config.ru
Implements the `WEB_CONCURRENCY=auto` feature described in #3437.
This implementation does not `require` `concurrent-ruby` at all (in puma).
An alternative could be to `require "concurrent/utility/processor_counter"` inline. I'd be happy to adapt 👍
Closes #3437.
> Set the worker process count automatically with WEB_CONCURRENCY=auto

- .github/workflows/ragel.yml
The macos-12 job is going away, currently brownouts are happening: https://github.com/actions/runner-images/issues/10721
Ubuntu 20.04 will go away at some point soon too (next year?), so let's up that too while at it.
> CI: Bump OS versions used for ragel jobs

- Gemfile
- test/helpers/integration.rb
- test/test_web_concurrency_auto.rb
- test/web_concurrency_test/Gemfile
- test/web_concurrency_test/config.ru
1. Add `concurrent-ruby` to the main Gemfile.
2. Fixup `test_web_concurrency_with_concurrent_ruby_available`
3. Add `test_web_concurrency_with_concurrent_ruby_unavailable`
4. Remove files in `test/web_concurrency_test` folder
> CI: fixup test/test_web_concurrency_auto.rb

- test/helpers/integration.rb
`cli_server` is used to start a Puma instance in a sub process using `IO.popen`.  It has a keyword parameter `config:` that sets the contents of a Puma config file.  This is often used for short config files, as it allows the test code to contain the config file code.
PR #3545 fixed a test that was consistently failing, and I ran the PR thru GHA (GitHub Actions) several times in my fork.  No failures.
After it was merged, I was working on another PR, and the test stopped the CI job in my fork, as in `did not finish`, with no summary, error of failure, etc.
These are difficult to determine the cause, possibly a 'noisy neighbors' issue.
This PR changes writing and closing the config file when the config string is specified.  Hopefully more robust...
As mentioned previously, these also never …
> integration.rb - fix up writing config file

- test/test_puma_server.rb
Add a 'pipeline' test using chunked request bodies, misc updates to helper functions
> [CI] test_puma_server.rb - update & add tests for back-to-back requests

- test/test_puma_server.rb
This PR contains two tests from PR #3251 as mentioned in https://github.com/puma/puma/pull/3251#issuecomment-2365181689
The two tests are simple tests that checked `env['SERVER_PROTOCOL']` for both HTTP/1.0 & HTTP/1.1.  They checked thru to the values passed to the app.
PR #3251 also duplicates some of the work already done in #3470, which has been merged.
Similar tests also exist in the `test_http10.rb` and `test_http10.rb`, but those check the return from the parser.  Not sure if these are needed, but they don't take long to run.
> [CI] test_puma_server.rb - add HTTP/1.0 & HTTP/1.1 checks thru to app env

- test/helpers/integration.rb
I think this was an error I caused last year, where `unless` was used, but `until` was intended.
This may help with errors like:
```text
Error: Errno::EBADF: Waiting for server to log /(?:Master| ) PID: (\d+)$/
```
> CI: fix TestIntegration#server_gets - until, not unless

- docs/java_options.md
- ext/puma_http11/org/jruby/puma/Http11.java
- test/test_http11.rb
Refactor the code to configure HTTP length constants through environment variables or system properties. 
For this purpose, I added helper methods `getEnvOrProperty` and `getConstLength`, with default values and error handling for invalid inputs.
The changes consider the following three constants described in [docs/compile_options.md](https://github.com/puma/puma/blob/master/docs/compile_options.md):
- PUMA_QUERY_STRING_MAX_LENGTH
- PUMA_REQUEST_PATH_MAX_LENGTH
- PUMA_REQUEST_URI_MAX_LENGTH
Documentation added as **/docs/java_options.md**
closes #3512
> Make HTTP length constants configurable for JRuby

- lib/puma/configuration.rb
- test/test_config.rb
Sometimes (usually for overriding values temporarily) shells can unset environment variables by setting them to a blank value, ruby interprets this as an empty string. Doing so with Puma's default environment parsing would previously blow up because `Integer("")` is not valid.
$ WEB_CONCURRENCY= bundle exec puma
bundler: failed to load command: puma (/Users/caius/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/bin/puma)
<internal:kernel>:307:in `Integer': invalid value for Integer(): "" (ArgumentError)
> Handle blank environment variables when loading config

- test/test_request_invalid.rb
Update for use with `TestPuma::PumaSocket`, update comments to refer to RFC 9112, the current document.
Add several commented out tests, these deal with "oversize path length" and "have http_content_length_limit set" issues. These involve future PR's addressing #3540 and #3552.  These will fail on master.
> CI: test/test_request_invalid.rb - use TestPuma::PumaSocket, RFC 9112

- lib/puma/client.rb
- lib/puma/const.rb
While looking into #3540, I noticed that the `read_nonblock` calls used for requests were either 4k or 16k.  For large request bodies, this causes a large number of loops to read them.
Using curl, I increased the value to 128k, and checked the bytes read.  They were 64k for both `content-length` and chunked bodies.
Also, the 16k value in `Puma::Const` dates back to at least 2007, and networks are much different now.
> Request body - increase read size to 64 kB

- lib/puma/launcher.rb
- test/test_worker_gem_independence.rb
Fixes #3290 
During phased restart updated the tag name with folder base name if tag is not set in puma config.
> fix update phased restart symlink folder

- docs/plugins.md
- lib/puma/binder.rb
- test/test_binder.rb
Allows for adding `before_parse` hooks to the `Binder#parse` method.
* tests went thorugh on my fork: https://github.com/tomurb/puma/actions
Closes #3302
>  Allow alternative schemes in Binder

- lib/puma/dsl.rb
- test/test_config.rb
Noticed some inconsistencies with how the DSL processes hooks while working on #3375, this was also opened as a split up prerequisite for https://github.com/puma/puma/pull/3377.
Ensures all hook DSL methods utilise `#process_hooks` + some minor changes (see comments).
> Update DSL hook processing logic to be consistent

- test/test_puma_server.rb
Fixup failing tests in test/test_puma_server.rb
@joshuay03 
Look ok to you?  If I revert the changes to `server.rb` in #3384, `test_auto_trim_with_fixed_pool_size` fails.  Also, one of the current tests raises in a thread, which stops CI...
> CI: test/test_puma_server.rb - fixup auto_trim tests

- test/runner
Allows test/runner to show warnings, with or without running tests.
This only works on the test files, a future PR may add a warnings check for both lib and test files.
> CI: test/runner - add `-w` and `z` options for test file warnings

- test/test_binder.rb
- test/test_request_invalid.rb
- test/test_web_concurrency_auto.rb
Addresses these minor warnings:
```
/puma/test/test_binder.rb:86: warning: ambiguous `&` has been interpreted as an argument prefix
/puma/test/test_request_invalid.rb:272: warning: assigned but unused variable - lleh_called
/puma/test/test_request_invalid.rb:303: warning: assigned but unused variable - lleh_called
/puma/test/test_request_invalid.rb:301: warning: assigned but unused variable - req_body_length
/puma/test/test_request_invalid.rb:338: warning: assigned but unused variable - lleh_called
/puma/test/test_web_concurrency_auto.rb:56: warning: assigned but unused variable - out
```
> Address some warnings in tests

- docs/stats.md
- lib/puma/cluster/worker.rb
- lib/puma/cluster/worker_handle.rb
- lib/puma/server.rb
- lib/puma/thread_pool.rb
- test/test_cli.rb
- test/test_integration_pumactl.rb
adds busy_threads to stats and also DRYs related code
the DRYing code (worker_handle.rb and worker.rb) can go into another PR or removed if preferred
> Add busy threads stat

- test/helpers/integration.rb
- test/helpers/test_puma/assertions.rb
- test/test_cli.rb
- test/test_integration_pumactl.rb
A few of the stats tests have very long strings/regex's used with assert statements.  These make it difficult to update the tests, and also are quite a pita to work with when a test fails.
The docs state that "[Puma.stats](https://msp-greg.github.io/puma/Puma.html#stats-class_method) produces a JSON string, and the same is returned via `Puma::ControlCLI`.  JSON strings are just that, so we can change the text representation as long as they parse with the same key/value pairs.
Updates the tests to work with 'expectation' hashes, rather than 'expectation' strings/regex's.  Hopefully, others will feel that the updated tests are easier to follow.
Adds a helper method (`assert_hash`) to `test/helpers/test_puma/assertions.rb`
> [CI] Update stats tests

- lib/puma/cluster.rb
- lib/puma/cluster/worker.rb
- lib/puma/const.rb
- lib/puma/runner.rb
- lib/puma/server.rb
`Puma::Const::PipeRequest::` appears in code in quite a few places, and thought that including the class in `Runner` would be beneficial.  Prefixed all the constants in the class with `PIPE_` to avoid future collisions.
> Fixup use of Puma::Const::PipeRequest constants

- test/helper.rb
- test/helpers/integration.rb
Currently GitHub CI systems have both a HDD and a SSD.  The OS and related files are on the HDD, files installed for the CI jobs are on the SSD.
The HDD seems to be at least 5 times slower than the SSD, and may be more affected by 'noisy neighbors'.
Set `ENV['TMPDIR']` to point to a known SSD 'temp' folder on the GHA runners.  `ENV['TMPDIR']` is the first ENV value that Ruby checks to determine a temp dir location.
These changes only are used when `ENV['GITHUB_ACTIONS'] == 'true'`.
This may help with intermittent test failures/retries.
> CI: fixup temp dir used in CI

- test/helpers/integration.rb
- test/test_integration_cluster.rb
- test/test_integration_single.rb
There are frequent intermittent failures and retries with the shared restart code used in the clustered and single integration tests.  Also, the phased/USR1 code used a different set of code that wasn't as rigorous as the hot/USR2 code.
Updated code.
Also, refactored the assert code.  Locally, with some hacks to Puma, I forced both `Errno::ECONNRESET` and EOFError in client connections.  When tried with various browsers, they all very quickly retried the connections.
Unfortunately, even though retries are much less common with these changes, other tests started failing...
> CI: refactor restart_does_not_drop_connections code

- .github/workflows/rack_conform.yml
- .github/workflows/tests.yml
- .github/workflows/turbo-rails.yml
Explicitly run CI against Ruby 3.4 now that it's out and [`setup-ruby` has been updated](https://github.com/ruby/setup-ruby/commit/bfefad842bb982ff05b233bcbc1571d97a87e69f).
> Add Ruby 3.4 to CI

- docs/java_options.md
- lib/puma/launcher.rb
- test/test_skip_sigusr2.rb
This option is necessary for compatibility with Java Flight Recorder, a performance monitoring and diagnostic tool used with JRuby and TruffleRuby
Closes https://github.com/puma/puma/issues/3567
> Option to turn off SIGUSR2 trapping

- ext/puma_http11/org/jruby/puma/Http11.java
- ext/puma_http11/puma_http11.c
- test/test_request_invalid.rb
A long time ago (02-April-2006), `HttpParserError` was [added](https://github.com/puma/puma/commit/3c804d5e15f0), and it was a subclass of `IOError`.  Today, `IOError` is more associated with errors at the `IO` level.
Puma should differentiate between socket level errors and HTTP request validity errors.  Hence, change `HttpParserError` to be subclass of `StandardError`.  This change will stop `HttpParserError` from being 'swallowed' in:
https://github.com/puma/puma/blob/f5e4b77db927628e60dfb323d06a12c96883c462/lib/puma/client.rb#L184-L190
This PR also uncomments two tests in `test/test_request_invalid.rb`, which fail on master.
Note that `@to_io.wait_readable` may throw other socket related errors.  Something to keep an eye on...
Closes #3552
> Change `HttpParserError` to be subclass of `StandardError`

- .github/workflows/tests.yml
Many of the CI runs have intermittent failures and/or intermittent retries.  These often happen when tests involving clustered servers are running parallel.  Currently, Windows & Ubuntu CI runs on x86-64 systems with two h/t cores.  macOS 13 runs on the same.  macOS 14 and 15 run on three arm cores.
This PR limits the number of Minitest threads running parallel testing to two (MT_CPU = 2).  It will probably slow testing down, but we should have fewer failures and fewer test retries, which saves time.
> CI: tests.yml - try MT_CPU: 2

- test/helpers/integration.rb
- test/test_integration_single.rb
JRuby returns a `Process::Status` that is different than the object returned by other Ruby platforms.   If one uses the below, the 'exit code' is the same.
```ruby
status = status.exitstatus % 128
```
Fixup tests to account for this...
> CI: test_integration_single.rb - fixup exit status tests when using JRuby

- test/helpers/integration.rb
- test/test_integration_cluster.rb
Context:
- https://github.com/puma/puma/pull/3297#issuecomment-2509608503
- https://github.com/puma/puma/pull/3557#discussion_r1864735186
With `fork_worker` un-commented and the original `sleep` the test times out for me locally, but doesn't on this branch. We go from ~10 restarts to ~3 restarts in a non-`fork_worker` test like [this one](https://github.com/puma/puma/blob/52757c8bf96bdc07044b7243c0851a46c06c5fec/test/test_integration_cluster.rb#L23-L26), which I think is perfectly reasonable for what these tests are asserting.
Fixing this is necessary to unblock https://github.com/puma/puma/pull/3297.
cc/ @MSP-Greg
> Reduce `TestIntegration#restart_does_not_drop_connections` restart frequency

- Gemfile
Ruby 3.5 (master) has changed `logger` to a bundled gem.  Fixed CI failures on Ruby master (head) builds.
> Gemfile - add logger for Ruby 3.5 and later

- lib/puma/sd_notify.rb
- test/test_plugin_systemd.rb
The tests in this file fail and/or retry intermittently.  The changes involve code that parses the notify socket.  On GHA CI, there are status messages interlaced with other messages.  These are due to delays common on GHA, but not reproducible locally.
It seems to help...
> CI: test_plugin_systemd.rb - fixups for intermittent retries

- lib/puma/app/status.rb
- test/test_app_status.rb
Originally added back in https://github.com/puma/puma/commit/a91d64a560743d130ec0930640aa364ab187ce36 - I believe the intention is to support splitting on either `&` or `;` between query params.
If nobody has run into a problem with this maybe it can be simplified down to only support the single param, but as I stumbled across it reading through the code I thought I'd propose this change as something simple.
~I did hit a CI error due to https://github.com/hotwired/turbo-rails/issues/681 in the [ubuntu-20.04 Ruby 2.7 Rails 6.1](https://github.com/AnthonyClark/puma/actions/runs/11085382537/job/30801738684#logs) run~ Heh, of course I was just behind on the rebase and it was already taken care of.
> Fix multi-delimiter split to get status app token

- test/test_request_invalid.rb
Both OS's and Ruby type may affect what errors are raised by various socket conditions.
MacOS TruffleRuby is currently silently failing with
```text
652 runs, 1749 assertions, 16 failures, 0 errors, 42 skips
```
These failures are all due to one test file, which was using the wrong error for macOS TruffleRuby.  The current code set them correctly for macOS MRI, but not macOS TruffleRuby.
Fixed.
> CI: test/test_request_invalid.rb - fix macOS TruffleRuby failures

- test/helpers/integration.rb
Recently, two jobs (both using old Rack versions), froze when `Errno::EBADF` was raised in the restart thread of `restart_does_not_drop_connections`.  Odd failure.
This PR catches the error in the thread.
> CI: integration.rb - catch Errno::EBADF in restart thread

- lib/puma/cluster.rb
- test/test_integration_cluster.rb
Not the root cause, but a contributing factor to https://github.com/puma/puma/issues/3599
When a refork happens, worker 0 is untouched and all other workers are terminated and forked from it. Since the fork worker logic piggy backs off phased restart, `workers_not_booted` is used by the master to determine if the refork cycle has been completed. However, [the initial value for this is always set to the configured worker count](https://github.com/puma/puma/blob/edd2a1728e39d055545fd12ffdfa42d5d4ccbc58/lib/puma/cluster.rb#L454), which is incorrect for refork as worker 0 doesn't need to be booted up. This means that on every refork, [`in_phased_restart` is never set to `false`](https://github.com/puma/puma/blob/edd2a1728e39d055545fd12ffdfa42d5d4ccbc58/lib/puma/cluster.rb#L519), as …
> Fix incomplete worker boot state on refork

- test/test_integration_cluster.rb
- test/test_launcher.rb
`Puma::Cluster` calls `Process.waitall` when shutting down.  The tests in `test_launcher.rb` are not run in a sub-process, so `Process.waitall` may affect other tests now or in the future.
Move the test to `test_integration_clustered.rb`, which runs Puma in a sub-process.
> CI: test_launcher.rb - move `test_puma_stats_clustered` to test_integration_clustered.rb

- test/test_integration_cluster.rb
- test/test_plugin_systemd.rb
- test/test_plugin_systemd_jruby.rb
- test/test_preserve_bundler_env.rb
- test/test_skip_systemd.rb
- test/test_worker_gem_independence.rb
My original intent was to correct an incorrect guard I added [here](https://github.com/puma/puma/pull/3601/files#diff-355b57e321e1a1fb604586cd830ccb12f20f8198e2e4b3c191b8cfb7fa6ef902R160) (should check for URG).
However, seeing as CI was green, I realised that all except one (for INFO) of these guards is redundant in that suite as it [only runs on fork-compatible OSs](https://github.com/puma/puma/blob/801d292e174d1b32b7b95bafef498ea44c8f2a83/test/test_integration_cluster.rb#L14).
This motivated me to find similar redundant guards in other suites and remove them, which I've done here.
> Remove redundant signal exists guards in tests

- lib/puma/dsl.rb
Closes https://github.com/puma/puma/issues/3431
It seems the only version comments are from v5 i.e. they haven't been used before v5 and haven't been kept up in v6. IMO the mention of new features in the changelog/upgrade guide is sufficient to know when they were introduced. Even without these, I would expect that users are reading the DSL at a specific tag if they are in the process of upgrading. Also, options may be added in minor versions (e.g. [this](https://github.com/puma/puma/pull/3496)), I don't think we have to tag every single one as such.
This PR removes the handful of existing version comment notes, and mentions in a comment note that fork_worker is experimental.
> Remove DSL version comments, note fork_worker as experimental

- test/test_puma_server_ssl.rb
`OpenSSL::SSL::SSLContext#set_minmax_proto_version` was removed in Ruby head/3.5.
See:
https://github.com/ruby/openssl/pull/849
https://github.com/ruby/ruby/commit/5a14f536958d20e98c58606bd44bd2c0bed6da4b
Currently, Windows head builds are failing.  But, the Windows ucrt & mswin builds are built three times a day, the Ubuntu & macOS builds are done once a day.
Hence, this affects all OS's.  The removed method was a Ruby method, so the extension code is ok, as it doesn't use any Ruby OpenSSL methods...
> CI: test_puma_server_ssl.rb -fix for  `set_minmax_proto_version` removal

- test/helper.rb
Addresses https://github.com/puma/puma/pull/3613/files#r1940084990
> Remove unused global $debugging_hold in test helper

- lib/puma/single.rb
- test/test_launcher.rb
It might happen the luncher stats are called before the server even starts resulting in NoMethodError (e.g. metrics plugin). This change prevents the exception and returns default stats only.
The metrics plugin might call `stats` on the launcher before the server is instantiated resulting in `NoMethodError`. 
https://github.com/harmjanblok/puma-metrics/issues/49
It seems like the plugin is not actively maintained since [the PR](https://github.com/harmjanblok/puma-metrics/pull/68) has not been responded to in a few months.
I see that `server` is already treated like `Maybe` type, so the change only aligns this one call with the reset of the class.
> Fix single runner stats before the server start

- .github/workflows/tests.yml
See #3632
We currently allow non-MRI jobs to fail without causing a 'red X' CI status.  This is currently done on the 'test' step.  Since JRuby-head is not compiling, this PR adds the 'allow-failure' CI flag to also work with jobs that won't compile.
We can probably remove some of the current `allow-failure: true` settings, as (I think) many of the non-MRI are stable.  This PR leaves them unchanged.
> [CI] test.yml - allow non-MRI failure on compile

- Gemfile
Currently, Windows Ruby head builds show the warning shown below, not sure what's loading `Win32::Registry`.
With Ruby 3.5 (head), `fiddle` has been changed to a bundled gem.  Previously, it was a default gem.
Update the Gemfile to remove the warning.
```text
▶ Run test/runner --verbose
D:/ruby-ucrt/lib/ruby/3.5.0+0/win32/registry.rb:2: warning: fiddle/import is found in fiddle, which is not part of the default gems since Ruby 3.5.0.
You can add fiddle to your Gemfile or gemspec to fix this error.
ruby 3.5.0dev (2025-03-27T07:57:10Z master df08cc629e) +PRISM [x64-mingw-ucrt]
▶ Run test/runner --verbose
D:/ruby-mswin/lib/ruby/3.5.0+0/win32/registry.rb:2: warning: fiddle/import is found in fiddle, which is not part of the default gems since Ruby 3.5.0.
You can add fiddle to your Gemfile or …
```
> Gemfile - add fiddle for Windows Ruby >= 3.5

- .github/workflows/rack_conform.yml
- .github/workflows/tests.yml
- .github/workflows/turbo-rails.yml
Ubuntu-20.04 has been removed from GHA. 
See Issue ["The Ubuntu 20.04 Actions runner image will begin deprecation on 2025-02-01 and will be fully unsupported by 2025-04-15"](https://github.com/actions/runner-images/issues/11101).
> [CI] GHA workflows - remove Ubuntu 20.04

- lib/puma/dsl.rb
The documentation used to say 'The default is 60 seconds.' for
`worker_shutdown_timeout` but the actual default value is 30 as defined
in `lib/puma/configuration.rb` https://github.com/puma/puma/blob/bc648da28d4332276293b6ae21157c0b892ec392/lib/puma/configuration.rb#L170
> Update docs to show correct default value for worker_shutdown_timeout

- docs/signals.md
ruby-doc.org is not official documentation.
By using master, we always link to the latest version.
> Link to official Ruby documentation

- lib/puma/request.rb
- test/helpers/test_puma/puma_socket.rb
- test/test_puma_server.rb
The rack spec now supports bodies responding with `nil` for `to_path`.
This is the default behavior of IO objects made with `IO.pipe`.
This PR has a commit to prevent puma from crashing when `to_path` returns nil.
It also has a test for pipe response bodies which tests the presence of this bug.
https://github.com/puma/puma/issues/3634
https://github.com/rack/rack/pull/2318
Closes #3634
> accept to_path to be nil on bodies

- .github/workflows/turbo-rails.yml
- Gemfile
Ruby master/head recently removed the cgi gem, and left `cgi/escape` in the std-lib.  This affected erb, rack, etc.  It also breaks Puma CI.
So, use the Rack main branch when running Ruby head jobs in CI.
See https://github.com/rack/rack/pull/2327
> ci: Fix Gemfiles for cgi removal in ruby head

- test/test_web_concurrency_auto.rb
Close https://github.com/puma/puma/issues/3659
Tested with `docker run --cpus 1 ...` (see the issue). Without `silence_single_worker_warning` in the config, the test took 30s to pass. I don't think that config value hurts and I think it is fine to only wait for 1 worker to boot. We're just interested in that `Workers: <n>` from the server log matches what `Concurrent.available_processor_count` reports.
> CI: make `WEB_CONCURRENCY=auto` test pass on single core systems

- lib/puma/dsl.rb
Closes #3668. Just a simple typo fix.
> Fix variable typo in `dsl.rb`: stategy > strategy

- lib/puma/request.rb
- test/test_rack_server.rb
Previously, if one proc in `rack.after_reply` raised, the entire chain would be halted.
I think this isn't great behavior, because it means a misbehaving low-criticity proc can cause a reliable but high criticity proc not to be called.
> `rack.after_reply` don't interrupt chain on error

- .github/workflows/tests.yml
- lib/puma/detect.rb
- test/test_puma_server.rb
GHA now supports arm64 runners on Ubuntu & Windows.
Added jobs for both.
Note that the Ubuntu jobs are affected by an unsigned vs signed char bug, probably in ragel, as the failures related to the c source code generated by it. I tried a few things, and got Ruby 2.7 passing, but the other versions failed. Gave up.
Disabled the 'PUMA_MAKE_WARNINGS_INTO_ERRORS=true' workflow step in the Ubuntu arm64 jobs, and the jobs passed...
Windows arm had issues with `TestPumaServertest_accept_emfile` (retries & intermittent failures), added a `Puma::IS_ARM` constant, add used it to add a small sleep for the test.
> ci: Add Ubuntu and Windows arm jobs

- test/helpers/integration.rb
- test/helpers/test_puma/puma_socket.rb
- test/test_puma_server.rb
- test/test_puma_server_hijack.rb
While working on other PR's, I noticed that all TruffleRuby jobs were silently failing.  Some of the failures were in `test_puma_server_hijack.rb`.  This also required small changes in two other files.
After this PR, TruffleRuby jobs are passing, TruffleRuby-head jobs are failing on two gc related tests.  More work later.
> ci: test_puma_server_hijack.rb - use puma_socket.rb, fixups

- .github/workflows/rack_conform.yml
See https://github.com/puma/puma/pull/3416#issuecomment-3166068205
@ioquatix Thanks for the notification.
> ci: rack_conform.yml - Ruby 3.1 no longer supported

- test/test_integration_pumactl.rb
Currently, TruffleRuby head (not release TruffleRuby) is silently failing on two tests shown below.  Fix the tests.
```
TestIntegrationPumactl#test_control_gc_stats_tcp
Failure: [test/test_integration_pumactl.rb:300]:
make sure a gc has happened.
Expected 0 to be < 0.
TestIntegrationPumactl#test_control_gc_stats_unix
Failure: [test/test_integration_pumactl.rb:300]:
make sure a gc has happened.
Expected 0 to be < 0.
```
> ci: test_integration_pumactl.rb - fix control_gc_stats for TruffleRuby head

- .github/workflows/tests.yml
Having recently jumped back into Puma, I've noticed that non-MRI jobs (JRuby & TruffleRuby) seem to be stable, so I think it's time to remove the 'allow-failure' that happens with many non-MRI jobs.
The PR changes the setting from `true` to `false`, rather than removing the key value.
Additionally, people involved with both JRuby & TruffleRuby have contributed to Puma, so it seems appropriate to support both platforms, especially their head builds.
> ci: tests.yml - set 'allow-failure' to false for non MRI jobs

- lib/puma/dsl.rb
- test/test_config.rb
Prerequisite: https://github.com/puma/puma/pull/3376
I don't see why hooks should be processed if a block is not given, and if it's being called that way it could be due to user error. This ensures an `ArgumentError` is raised unless a block is given when configuring hooks.
> Raise an `ArgumentError` unless a hook is called with a block

- lib/puma/client.rb
- lib/puma/request.rb
Currently, `Puma::Request` sets `env['rack.hijack']` to the `Puma::Client` instance.  Instead of using the client instance, pass a method object that responds to `call`.
The Rack spec for the object passed in `env['rack.hijack']` is that it must respond to `call`.  Also, `Puma::Client` is a ':nodoc:` class, so it shouldn't be considered part of Puma's public API.  Hence, there is no reason to pass it to the app.
> Set env['rack.hijack'] to client.method(:full_hijack) instead of client instance

- lib/puma/client.rb
- test/test_request_single.rb
- `chunked,gzip` case was handled incorrectly. It should be reported as an unknown (unsupported) value.
- spaces were not stripped so something like `chunked, gzip, chunked` also was handled incorrectly.
> Fix handling of invalid Transfer-Encoding header errors

- History.md
- lib/puma/configuration.rb
- lib/puma/dsl.rb
- lib/puma/server.rb
- lib/puma/thread_pool.rb
- test/helper.rb
- test/test_fiber_local_application.rb
- test/test_fiber_storage_application.rb
- test/test_thread_pool.rb
This enables the correct scope of `Fiber.storage` per request.
`Fiber[]` and `Fiber[]=` are recently introduced features in Ruby 3.2. They are designed to provide per-operation or per-request state handling.
Using a thread pool, `Fiber.storage` is retained beyond a single request, which can leak information from one request into another. The simplest way to avoid this is to wrap each request itself in a fiber. The overhead should be minimal as these fibers are cached and reused, so once warm, the overhead is a single Ruby VALUE allocation per request.
The benefit is that code which uses `Fiber[]=` will be scoped correctly to a single request.
> Introduce support for fiber-per-request.

- lib/puma/server.rb
- test/test_log_writer.rb
<details>
<summary>Script</summary>
This script runs all test files one by one and reports which cannot be run via being focused
```bash
#!/bin/bash
cd "$(dirname "$0")/.."
failed_tests=()
for test in test/test_*.rb; do
if bundle exec m "$test" >/dev/null 2>&1; then
echo "✓ $(basename "$test")"
else
echo "✗ $(basename "$test")"
failed_tests+=("$test")
fi
done
echo
if [ ${#failed_tests[@]} -eq 0 ]; then
echo "All tests passed! ✨"
else
echo "Failed tests:"
printf '%s\n' "${failed_tests[@]}"
echo
echo "The above tests cannot be focused with 'bundle exec m <test-name>' fix them"
exit 1
fi
```
</details>
I was trying to focus test a specific file for a PR and I couldn't due to errors. I wrote a script to print out all the files that couldn't be focused, turns out they were all due to one …
> Fix the ability to focus individual tests

- lib/puma/runner.rb
Remove deprecated method from runner.
> runner.rb - remove `ruby_engine` method, deprecated Nov-2024

- lib/puma.rb
- lib/puma/dsl.rb
- test/config/max_fast_inline_infinity.rb
- test/config/max_keep_alive_infinity.rb
- test/test_cli.rb
- test/test_config.rb
- test/test_puma_server.rb
See title
Closes #3708.
Should we turn warnings on in CI?  Not included in this PR.
Also, the warnings for method name changes do not show a file/line number.  Should they?
> Dry up deprecation warnings and fix deprecation warnings when running CI.

- lib/puma/configuration.rb
- lib/puma/dsl.rb
Follow-up to https://github.com/puma/puma/pull/3438 and https://github.com/puma/puma/pull/3616.
In #3438, hooks were renamed and aliases were added for their deprecated names. The `process_hook` calls were also updated to pass the new method names as the fourth positional argument. Looking back, that PR probably should have passed `__callee__`/`__method__` instead, so that cluster-only hook warnings in single mode would use the correct method name. However, I think it's acceptable that only the new method name is shown, since users will see a deprecation warning with the old name before they encounter the single mode warnings, so they won't be entirely confused about what's being referenced.
In #3616, I refactored the warning logic. This PR follows up on that work because the key used to …
> Simplify `Puma::DSL#process_hook` logic

- lib/puma/server.rb
See [comment](https://github.com/puma/puma/pull/3711#issuecomment-3235392044), or
> Also the order that ivars are set can affect JIT caching. If we are going to set an ivar outside of initialize, we should define it as nil inside of initialize so the order of ivars is the same for every instance.
The above comment was directed at adding `@env_set_http_version` without initializing it.
I tried to audit whether any other ivars needed the same, and only noticed `@reactor`.
> server.rb - initialize ivars `@reactor` and `@env_set_http_version`

- lib/puma/configuration.rb
- lib/puma/dsl.rb
- test/test_puma_server.rb
When we initially merged #3678, we discussed the appropriate setting for this default `max_keep_alive` value and determined we didn't have a terribly good method for setting it. Therefore, we picked a magic number.
With #3715, I discovered that the setting `export RUBY_MN_THREADS=1` had disastrous effects on Puma 7.0.0.pre1 performance, but increasing this `max_keep_alive` value dramatically increased performance. The default value with nginx is 1000 http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests. Why not go full nginx and use 1000? Prudence is a virtue.
The test was modified to not require sending 1000 requests to observe the keepalive max behavior. This change effectively duplicated the behavior of `test_set_max_keep_alive`, so I removed the redundancy.
> Set default keepalive connections to 999

- lib/puma/events.rb
- test/test_config.rb
- test/test_events.rb
The PR #3438 renamed callback methods from on_* to before_*/after_* pattern but only added aliases in DSL, not in Events class. This broke applications that call these methods directly on Events instances (e.g., [SolidQueue](https://github.com/rails/solid_queue/pull/635)).
Added on_booted, on_restart, on_stopped aliases with deprecation warnings
Fixes compatibility issue reported in #3724
> Add backward compatibility aliases for Events class methods

- lib/puma/cluster/worker_handle.rb
- lib/puma/server.rb
- test/test_integration_cluster.rb
Previously if queue_requests were disabled, Puma would crash at startup:
```
puma-7.0.1/lib/puma/server.rb:688:in `stats': undefined method `reactor_max' for nil (NoMethodError)
stats[:reactor_max] = @reactor.reactor_max
^^^^^^^^^^^^
```
Fix this by checking the presence of `@reactor`.
Thank you for contributing! You're the best.
We can read your code, so consider leaving some comments here that are more about your motivations and decision making. Some things that may be helpful to address in your description:
- What original problem led to this PR?
- Are there related issues / prior discussions?
- What alternatives have been tried? Does this supersede previous attempts?
- Why do you make the choices you did? What are the tradeoffs?
- [X ] All new and existing tests passed, including …
> Fix Puma not booting if queue_requests disabled

- lib/puma/request.rb
For the case when https is not being used, this reduces the amount of time it takes to run this method.
From ruby-prof while executing wrk for 15s:
Before
```
1.35% 0.60% 0.21  0.09  0.00  0.12  76881 Puma::Request#default_server_port 267
0.04  0.02  0.00  0.02  76881/76881 Array#include?  268
0.03  0.03  0.00  0.00  307524/1082376  Hash#[] 268
0.02  0.02  0.00  0.00  76881/76883 String#[] 268
0.01  0.01  0.00  0.00  153762/155270 BasicObject#==  268
0.01  0.01  0.00  0.00  76881/76881 NilClass#to_s 268
0.01  0.01  0.00  0.00  76881/384407  String#== 268
```
After: 
```
0.89% 0.49% 0.14  0.08  0.00  0.06  78559 Puma::Request#default_server_port 268
0.03  0.03  0.00  0.00  314236/1106188  Hash#[] 269
0.02  0.02  0.00  0.00  235677/237265 BasicObject#==  269
0.01  0.01  0.00  0.00 …
```
> Optimize Puma::Request#default_server_port

- lib/puma/server.rb
Puma 7 introduced new bahavior for keep-alive connections.  Some of the changes were in
`Server#process_client`.  After a response has been sent, below is the current behavior.
| Socket State                                                                | Puma Action       |
|:----------------------------------------------------------------------------|:------------------|
| 1. Socket has text in it's read buffer, and a full request is available     | add to ThreadPool |
| 2. Socket has text in it's read buffer, and a full request is not available | add to Reactor    |
| 3. Socket is readable and has a full request                                | add to Reactor    |
| 4. Socket is readable and does not have a full request                      | add to Reactor    |
| 5. Socket is not …
> `Server#process_client` - add ka request to ThreadPool if readable & complete (prev sent to Reactor)

- lib/puma/configuration.rb
- test/test_config.rb
The `PUMA_PERSISTENT_TIMEOUT` should have been converted into an integer, but it was not which resulted in failures. This commit fixes the issue and adds a test.
Problem originally reported in this comment https://github.com/puma/puma/pull/3378#issuecomment-3284390738. 
```
Read: #<TypeError: String can't be coerced into Float>
```
> Convert PUMA_PERSISTENT_TIMEOUT to an Integer

- lib/puma/cluster_accept_loop_delay.rb
- lib/puma/server.rb
- lib/puma/thread_pool.rb
- test/test_cluster_accept_loop_delay.rb
Thank you for contributing! You're the best.
Aww stop, no YOU're the best.
Simplify the calculations: Puma 6.6.1 behavior documented here https://gist.github.com/schneems/cef38e9448dfb72943d13050a7da0869
This changes the puma 7 behavior to:
- Starts sleeping the event loop before being overloaded (the prior `pool.busy_threads` included in the ready @todo queue) and would only fire. This is closer to puma 6.6.1 behavior
- Sleeps a consistent proportional amount, closer to puma 7 behavior, versus puma 6 used a static value.
- Sleeping behavior is restricted to 2 or more workers, verus puma 7 was accidentally enabled for clusters with only 1 worker (This is an alternative to #3723.)
- Modifies the `busy_threads` method from the thread pool to be clamped between 0 and max_threads. 
Fixes …
> Move sleep cluster logic to its own class

- ext/puma_http11/org/jruby/puma/Http11.java
- ext/puma_http11/puma_http11.c
- test/test_http11.rb
When Puma receives a header with tabs before the value, it doesn't strip them.
For example, when Puma receives the following request:
```
GET / HTTP/1.1\r\n
Host: whatever\r\n
Test: \t\t whatever\r\n
\r\n
```
...it sees the `Test` header as having value `\t\t whatever`. This is incorrect according to spec, because the OWS preceding a header value should consume the `\t` characters, leaving a value of just `whatever`.
Puma is (to my knowledge) the only web server that doesn't strip the tabs appropriately. I've tested the full list [here](https://github.com/narfindustries/http-garden?tab=readme-ov-file#targets).
This PR basically makes 2 changes:
1. Checks for leading whitespace and skips past it during header value parsing.
2. Updates the way that trailing whitespace is skipped to avoid …
> Strip whitespace from the beginnings of header values

- ext/puma_http11/mini_ssl.c
- lib/puma/server.rb
- test/helper.rb
- test/test_puma_server_ssl.rb
`SSL_shutdown()` call may result in error and in OpenSSL every error should be consumed by the valler via `SSL_get_error()` or a similar func.
`MiniSSL` implementation was breaking this convention so it resulted in cryptic bugs like SSL clients (not related to Puma in any way) return errors with text like `"SSL_read: shutdown while in init"` that is initially generated by the Puma reactor but not consumed by it.
Such bugs are really hard to debug...
Thank you for contributing! You're the best.
We can read your code, so consider leaving some comments here that are more about your motivations and decision making. Some things that may be helpful to address in your description:
- What original problem led to this PR?
- Are there related issues / prior discussions?
- What alternatives have …
> Fix SSL_shutdown error handling

- test/test_puma_server_ssl.rb
Errors raised in threads are not retried and will abort CI.  A recent failure
```
#<Thread:0x00000001273d3588 /Users/runner/work/puma/puma/test/test_puma_server_ssl.rb:202 run> terminated with exception (report_on_exception is true):
from /Users/runner/work/puma/puma/test/test_puma_server_ssl.rb:203:in 'block in TestPumaServerSSL#test_http_rejection'
```
Add a begin/rescue block so the error is caught, allowing retry.
> ci: test_puma_server_ssl.rb - catch error in thread

- benchmarks/local/bench_base.rb
- benchmarks/local/bench_base.sh
- benchmarks/local/long_tail_hey.rb
- test/rackup/sleep_fibonacci.ru
Two commits, neither change any 'lib' code.
Currently, the benchmark tests default to using `test/rackup/sleep.ru`.  This looks at the request's path and sleeps for a given amount of time.  The sleep uses virtually no CPU.  Add another file `test/rackup/sleep_fibonacci.ru` which runs a few loops of some fibonacci code, the sleeps for the balance.  Every PC is different, so the code may need changes to run on different systems.  If the 'fibonacci' code runs longer than the expected request delay time, it will error in Puma.  See comments in the file to adjust.
Formatting changes to the hey benchmarking code.  Example output below:
```
Branch: 00-bench-hey-update
Puma: -w4  -t3:3  dly 0.005  sleep.ru                                  RPS      50%       99%
6.00 hey -c  72 -n  7200 -cpus 8 …
```
> Add test/rackup/sleep_fibonacci.ru, update benchmark hey files

- test/test_thread_pool.rb
You can validate this by running this command in a loop with jruby
```
$ chruby jruby 10.0.2.0                                                             
$ while be m test/test_thread_pool.rb; do echo "Test passed, running again..."; done
```
If it exits, we missed a flappy test.
Close #3771
> Fix flappy `test/test_thread_pool.rb` tests 

- .github/workflows/tests.yml
Having spent too much time paying attention to Actions CI logs, often the failures are on macos-13 (which is x86_64-darwin).
That runner is being deprecated, with removal on 04-Dec-2025.  It is being replaced by macos-15-intel.
PR switches all macos-13 jobs to macos-15-intel
> ci: macos-13 to macos-15-intel
