- examples/config.rb
Add the documentation for the on_worker_shutdown hook.
> Update config.rb with on_worker_shutdown.

- ext/puma_http11/extconf.rb
> Update extconf.rb to compile correctly on OS X

- lib/puma/configuration.rb
- test/hello-bind.ru
- test/test_config.rb
see b8c087d967e6f018713cc4f444358754cc7dacba
see #684
see #689
> Added tests for bind configuration on rackup file

- README.md
How's this look?
I'm still in the process of trying this in my app -- I'm not 100% sure if the lazy-loading behavior is
what I expect (nothing in the rails environment and no libraries are loaded at this point).
> update Readme with example of custom error handler

- lib/puma/cli.rb
> Make puma -v and -h return success exit code

- .travis.yml
Fixes 'This job ran on our legacy infrastructure.'
> Convert to container infrastructure for travisci

- lib/puma/capistrano.rb
Modify capistrano task, add additional env when start(restart) rails, such as : secret key, db username, db pwd or other what you want.
> Add additional env when start rails app or restart app

- lib/rack/handler/puma.rb
Now I left a typo in the commit message. How do I fix typos in Github pull requests?
> fix for typo mentioned in #803

- lib/puma/events.rb
- lib/puma/server.rb
Fixed two instances of the same minor typo in two different files.
> Fix typo (it's -> its)

- lib/puma/cluster.rb
- lib/puma/single.rb
Fix spelling errors in output.
> Fix spelling errors.

- DEPLOYMENT.md
- README.md
- docs/nginx.md
Some small spelling corrections for markdown files.
> Spelling corrections

- README.md
This was missed when writing the actual implementation
> Add before_fork explanation in Readme.md

- lib/puma/dsl.rb
> Exit if max_threads == 0

- lib/puma/control_cli.rb
- lib/puma/state_file.rb
f788af0c8f7993899e35994d9c63dce4dd6de299 moved YAML related code to
state_file.rb but didn't move the require from control_cli.rb to
state_file.rb
> Move require 'yaml' to state_file.rb

- README.md
Context: #878
@evanphx Let me know if you have any feedback on wording or placement in the doc.
Also fixed a typo :wink:
> Add Directory Configuration Docs

- lib/puma/cluster.rb
- test/test_cli.rb
It'd be nice to be able to tell the status of each of the workers for metrics collection. Other ways people have solved this is in #811, but this approach seems more complete.
> Improves the clustered stats to report worker stats

- .travis.yml
> Test on rbx-3 as well

- README.md
This makes it easier to quickly get signals info for people that need it in a pinch (like I just did).
> Add signals documentation to README.md

- lib/puma/binder.rb
- lib/puma/dsl.rb
> Fix puma/puma#968 Cannot bind SSL port due to missing verify_mode option

- tools/jungle/init.d/puma
- tools/jungle/init.d/run-puma
these changes have been run on my production environments for months.
> NEW: add phased-restart support to init.d script

- lib/puma/configuration.rb
- lib/puma/tcp_logger.rb
- test/test_tcp_logger.rb
> Fix `TCPLogger` log error in tcp cluster mode.

- README.md
Add clarification to documentation regarding the control server.
> Add section to control/status app documentation

- tools/jungle/init.d/README.md
It seems to be supported by the script, but not documented anywhere.
> Document usage of environment variables

- .travis.yml
2.1.8 ---> 2.1.9
2.2.4 ---> 2.2.5
2.3.0 ---> 2.3.1
> Bump Ruby versions.

- lib/puma/rack/urlmap.rb
Backport of https://github.com/rack/rack/pull/1042
> Compare host and server name only once per call.

- test/test_integration.rb
Skip this until we can fix it, too racey right now.
> Skip test_phased_restart_via_pumactl

- lib/puma/configuration.rb
- test/test_config.rb
> fix access priorities of each level in LeveledOptions

- lib/puma/client.rb
It was introduced here:
https://github.com/puma/puma/pull/451/files#diff-9faf7093e45c4c686939f8f0c5464aa7R107
> Remove unused var from Puma::Client.

- lib/puma/binder.rb
This typo was causing the issue #1182.
> Fix a typo

- .travis.yml
This PR keeps up with latest releases of Ruby.
> Travis: use latest rubies in CI

- ext/puma_http11/mini_ssl.c
This fixes running an SSL server built against LibreSSL.
Fixes parts of #1181
> LibreSSL fix

- test/test_integration.rb
fixes https://github.com/puma/puma/issues/1292
> fix jruby bug

- test/test_integration.rb
> fix jruby deleting env vars

- lib/puma/launcher.rb
fixes https://github.com/puma/puma/issues/1312
> support older and future versions of bundler that do not have clean_env

- Rakefile
- lib/puma/launcher.rb
- test/helper.rb
- test/test_integration.rb
> simplify test shellout and make sure no other version of puma is available so we know our tests work

- test/test_integration.rb
> get rid of test sleep ... hopefully it is not necessary

- test/test_integration.rb
> unify skips

- docs/systemd.md
Minor refinements and note that socket activation doesn't work on jruby, with reference to #1367.
> Additional docs/systemd refinements (3)

- README.md
https://github.com/puma/puma/pull/1374
> Appveyor badge

- ext/puma_http11/http11_parser.c
- ext/puma_http11/http11_parser.rl
- ext/puma_http11/mini_ssl.c
- ext/puma_http11/org/jruby/puma/Http11Parser.java
> Compiler warnings fixes

- lib/puma/const.rb
Reference: https://www.ietf.org/rfc/rfc2324.txt
> Implement rfc2324 section 2.3.2, Status 418: I'm a teapot.

- puma.gemspec
Add a line to puma.gemspec as specified in #1428
> Add msys2_mingw_dependencies to puma.gemspec

- lib/puma/runner.rb
> leak_stack_on_error in test environment

- appveyor.yml
- lib/puma/binder.rb
- test/test_pumactl.rb
Several updates to Appveyor.yml
> appveyor.yml - fix casing, OpenSSL 1.1.0h, convert to ps

- examples/plugins/redis_stop_puma.rb
Puma checks in lib/plugin/<file_name> for plugins https://github.com/puma/puma/blob/master/lib/puma/plugin.rb#L90
> Fix minor typo for including plugins

- README.md
> README.md - minor cosmetics

- docs/restart.md
Added a note about current limitations of hot and phased restarts.
(Is there any way around these btw? Currently running on JRuby, on Linux.)
> restart.md: Added note about JRuby and Windows

- lib/puma/reactor.rb
Hello,
This is just a tiny follow up to #1575 to fix a few typos.
Have a nice day !
> Tiny documentation fixes for `Puma::Reactor`

- test/test_puma_server_ssl.rb
Found with Ruby 2.4.4 & OpenSSL 1.0.2o
> test_ssl_v3_rejection another error string

- README.md
Per #1724, add a README section with a list of community plugins.
> Add Plugins to README

- README.md
Small update.  It seems the badge isn't refreshing correctly, as CI is passing.  I posted a message on the Appveyor forum...
> README.md - update badges [skip ci]

- lib/puma/server.rb
Nothing fancy, just fixing a typo in doc
> fix doc typo

- lib/puma/app/status.rb
- test/test_cli.rb
Credits of this patch should be for @jdsundberg, who reported the issue
but never sent a patch. Link to his bug report is below.
Closes #1687.
> Fix: Invalid JSON on gc-stats

- lib/puma/client.rb
- lib/puma/reactor.rb
Hi @schneems,
I'm sending this PR as per your suggestion in https://github.com/puma/puma/pull/1806#issuecomment-500509845
By the way, personally I'm annoyed by long lines in source code.  Would you be interested in another PR trimming down these lines to a max of 80? I've seen some parts of Puma respect this limit while others just don't. What's the preference of the maintainers?
And one last thought, your long texts in the source code have helped me a lot recently while researching this codebase, so MANY THANKS!
> Updates docs, removes refs. to IO.select()

- README.md
> Revert "Remove known bugs section from README.md"

- .rubocop.yml
- .travis.yml
- History.md
- lib/puma/binder.rb
- lib/puma/configuration.rb
- lib/puma/server.rb
- puma.gemspec
- test/shell/t1.rb
- test/test_integration.rb
- test/test_persistent.rb
- win_gem_test/puma.ps1
> Revert "[close #1811] Minimum Ruby version >= 2.5"

- lib/puma/control_cli.rb
- test/shell/t2.rb
- test/test_pumactl.rb
ref https://github.com/puma/puma/pull/1767
fix https://github.com/puma/puma/issues/1765
First PR adding status output when using pidfile option
cc @nateberkopec
> Add status to pumactl with pidfile

- lib/puma/launcher.rb
> Remove RUBY_VERSION checks

- History.md
hi! the feature #1824 is not included in the 4 release, cheers!
> Add missing feature to history on v4.0.0

- History.md
- lib/puma/const.rb
> 4.0.1 notes and version change

- README.md
Fixes: #1548
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/puma/puma/1866)
> Add lowlevel_error_handler documentation back to README

- test/test_unix_socket.rb
Fix to work reliably on platforms without UNIXSockets
> fix test/test_unix_socket.rb

- test/test_web_server.rb
Intermittent errors may be related to OS buffering, etc.  Seems to fix issue.
> test_web_server.rb - fix intermittent errors

- test/test_integration.rb
+ remove unused signal helper
Replaces #1900
> Msp greg zombie test fix intermittent

- .travis.yml
This PR updates the build matrix.
> CI: Use Ruby 2.4.7, 2.5.6, 2.6.4

- test/helper.rb
- test/test_integration_pumactl.rb
Closing #1945 and just taking the tests from it
> Add ignored assertion

- .travis.yml
Closes https://github.com/puma/puma/issues/1954
> Remove jruby-stable from list of allowed failures

- README.md
Follow-up to https://github.com/puma/puma/pull/1991
> [changelog skip] Document the changelog check in README

- .travis.yml
…e it or line 47
Line is being ignore when YAML is parsed. One or the other should be removed or they should be merged. 
@olleolleolle @nateberkopec
> this line gets overwritten when the YAML is parsed so we should removed [changelog skip]

- .travis.yml
Aligned jobs to use OpenSSL versions not available in Actions.
> travis.yml - allow JRuby jobs to start first

- .github/workflows/ruby.yml
Timeout will need to be changed if JRuby is added to this workflow.
> Actions CI - Allow CI from branches other than master (forks), add test timeout

- README.md
Documentation update addressing my issue (Closes #1795).
Specifically, around the side effects of setting the rack environment on the library.
Adding how it could affect middleware, and how it will show stack traces in dev & test. Also specifying the default value with a link to show all config default values.
> Update README With More Explanation of Setting RACK_ENV [ci skip]

- CONTRIBUTING.md
Not a big deal, but the provided test file does not exist anymore :wink:
> [ci skip] fix readme single file test example

- History.md
- ext/puma_http11/extconf.rb
Updates extconf.rb for use on Windows with ssp and varied Ruby/MSYS2 combinations
> Windows update extconf.rb

- .github/pull_request_template.md
https://github.com/puma/puma/blob/75e2179e61ab3d8a66d407be14fc61886bb3008b/.github/workflows/check_changelog.yml#L13
> Changelog check checks PR title [ci skip]

- lib/puma/dsl.rb
> fix typo in documentation - remove duplicate word [changelog skip][ci skip]

- .travis.yml
2.7.0-preview3 is not found: https://travis-ci.org/puma/puma/jobs/630376705
> Test with Ruby 2.7.0 on Travis CI [changelog skip]

- README.md
We use puma-status https://github.com/ylecuyer/puma-status to monitor our puma instances from the CLI. We add the link to the repo so that other users can easily discover it
> [changelog skip][ci skip] Add puma-status to the community extensions

- .github/workflows/ruby.yml
- .travis.yml
Current Rubies, 2.4 thru 2.7 on all platforms, plus 2.3 on Ubuntu & macOS
Ubuntu 2.3, macOS 2.3, & Windows 2.4 use OpenSSL 1.0.2, all others are 1.1.1
JRuby fails tests
> Update Actions ruby.yml [changelog skip]

- .github/workflows/ruby.yml
This action was transferred to ruby/setup-ruby: https://github.com/ruby/setup-ruby/releases/tag/v1.13.0
> Actions: Use the new action name [changelog skip]

- .github/workflows/ruby.yml
Using a directory for `bundle install` may help in the future with CI caching.  It may also help with the issues with Bundler integration.
> workflows/ruby.yml - use 'bundle install' with '--path=.bundle/puma' [changelog skip]

- .travis.yml
To get the latest fixes, e.g., for https://github.com/oracle/truffleruby/issues/1964
> Switch to truffleruby-head in TravisCI [changelog skip]

- README.md
Tests are no longer running on Travis CI (since #2185).
> Remove the Travis badge from README [changelog skip]

- .github/workflows/ruby.yml
Either via pull request title or commit message (for docs fixes on master).
> Be able to skip tests [ci skip]

- docs/systemd.md
Remove link to docs that were removed in 636732c44774a3dc49474f3fb0627fb3a6aaafb3
Close #2196
> Remove daemonization trace in docs [ci skip]

- .github/workflows/puma.yml
1. Extend test timeout (8 to 10) - macOS truffleruby - maybe intermittent or test order dependent
2. Refactor, shortened job descriptions for Web UI, etc
> ruby.yml - misc updates & renamed puma.yml [changelog skip]

- .github/workflows/puma.yml
See https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/
Follow-up to #2224
> The new way of allowing failures on GitHub Actions [changelog skip]

- README.md
> README.md - fix the Actions badge [changelog skip] [ci skip]

- 5.0-Upgrade.md
I think it is meant to read `of puma` instead of `on puma` :)
> Fix typo [ci skip]

- test/test_binder.rb
> test_binder.rb - add teardown to close sockets [changelog skip]

- test/test_integration_single.rb
#test_term_not_accepts_new_connections - check correct pid, typo
> test_integration_single.rb - single test - minor fixes [changelog skip]

- lib/puma/dsl.rb
I was using on_worker_fork instead of on_worker_boot
> Fix example for on_worker_boot

- lib/puma/server.rb
as requested by @headius in https://github.com/puma/puma/pull/2349
those two functions don't depend on each other
> split TCP_CORK and TCP_INFO [changelog skip]

- CONTRIBUTING.md
I was perusing the docs and found this dead link, so I updated it!
> Updates Rack specification link [ci skip] [changelog skip]

- History.md
Add links to History.md.
Leave the title attribute (date & user)?
I've got code for the first pass, I'll get it working for updates (grabs repo pr/issue info with GraphQL call).
> History.md - add links [skip ci]

- test/test_integration_cluster.rb
The test seems to have been accidentally removed in commit 525ecca.
Closes #2322
> Restore test that was previously removed [changelog skip]

- History.md
While I was at it I notices a super small typo.
> [changelog skip] Small typo in History.md

- .github/workflows/mri.yml
- .github/workflows/non_mri.yml
Adjust Actions workflows for new syntax. See:
[GitHub Actions: Deprecating set-env and add-path commands](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)
> Adjust Actions workflows for new syntax [changelog skip]

- docs/restart.md
Closes #2366. 
I re-wrote the existing documentation for restarts for more clarity, making sure to incorporate my own comments on the topics in https://github.com/puma/puma/issues/2018#issuecomment-708624433 and https://github.com/puma/puma/issues/2366#issuecomment-704008216. The goal is to make it more clear to users what the different options are so they can make informed decisions about how they operate Puma.
> Update restart documentation [changelog skip] [ci skip]

- CONTRIBUTING.md
Noticed a broken markdown link while reading the contributing guide.
~- [ ] All new and existing tests passed, including Rubocop.~
> Fix broken link [ci skip] [changelog skip]

- lib/puma/app/status.rb
Replace multiple regexes with single, consolidate responses, add some comments.
> Refactor status.rb - dry it up a bit [changelog skip]

- test/helpers/integration.rb
> test/helpers/integration.rb - #cli_pumactl - replace popen with thread [changelog skip]

- History.md
update links, add missing issues.
> Update History.md [ci skip]

- 5.0-Upgrade.md
- docs/fork_worker.md
See the discussion in https://github.com/puma/puma/issues/2467
Related to #2466
Close #2467
> fork_worker does not work with preload_app! [changelog skip]

- 5.0-Upgrade.md
- README.md
Various doc fixes.  Several were replacing absolute uri's with relative, which are interpreted correctly by both GitHub and most Ruby doc software.
> Update docs [skip ci]

- History.md
> Mention WEB_CONCURRENCY in History.md [ci skip]

- History.md
- lib/puma/const.rb
Fixes a warning in test coming from `ILLEGAL_HEADER_KEY_REGEX`. [Square bracket](https://thepugautomatic.com/2012/09/brackets-in-regular-expressions/) may not match what we wanted.
> Fix warning of ILLEGAL_HEADER_KEY_REGEX

- lib/puma/control_cli.rb
- lib/puma/launcher.rb
- lib/puma/state_file.rb
File.open creates an IO object, which may appear when looking at 'leftover' IO objects.
> File.open -> File.read, File.write [changelog skip]

- lib/puma/const.rb
> Bump version to 5.1.0 [changelog skip]

- docs/compile_options.md
Grammar change.
This change tries to improve the flow of the sentences, and to improve scannability.
> [docs] compile_options.md: Mention option in heading [ci skip]

- docs/deployment.md
The default value was changed in #2143
> Update default number of threads for MRI in docs [ci skip]

- History.md
Added #2300 link to the Deprecations, Removals and Breaking API Changes section of 5.0.0 in History.md
> Add #2300 link to History.md [ci skip]

- docs/stats.md
As far as I can tell there aren't any docs for a) accessing stats b) what individual stats mean
maybe we can flesh that out a bit in this ticket, and then i'll make a PR with a new document in /docs ?
i threw together this very rough doc - please give comments, or point me to existing docs/discussion where i can draw from
> Docs for stats

- History.md
- lib/puma/binder.rb
- test/test_binder.rb
Binder - add/fix ssl 0.0.0.0/localhost logging, use tertiary
test_binder.rb - remove skips for:
test_correct_zero_port_ssl
test_logs_all_localhost_bindings_ssl
> Binder - add/fix ssl 0.0.0.0/localhost logging, use ternary operator

- lib/puma/const.rb
> Bump version to 5.2.0 [changelog skip]

- History.md
> 5.2 - update History links [ci skip]

- README.md
I know, it's a small change. I promise I'm not doing it just to get a commit into the repository. 🙈
> Fixes markdown link syntax in README.md [ci skip]

- CONTRIBUTING.md
Closes https://github.com/puma/puma/issues/2598
> Adds instructions on referencing local gem to CONTRIBUTING [ci skip]

- CONTRIBUTING.md
1. Update contributing to mention running CI in one's fork.
2. Misc updates for Windows.
Much appreciate suggestions re wording, additions, etc.
> CONTRIBUTING.md - Running CI, Windows, misc [ci skip]

- lib/puma/const.rb
Bump version to 5.3.0 'Sweetnighter'
> Bump version to 5.3.0 [ci skip]

- .github/workflows/non_mri.yml
Allow failure for head version of truffleruby, test on the release ones for ubuntu and mac os.
Hopefully it will reduce the number of CI failures that are independent to the puma changes themselves.
> Test on truffleruby, allow failure for truffleruby-head

- CONTRIBUTING.md
I'm making an effort to make the contributing document a bit more
readable by decreasing redundant phrasing and adding a few links.
> Update contributing.md [ci skip]

- CONTRIBUTING.md
I think the location of this setting moved!
> Update instructions for GitHub actions [ci skip]

- test/test_http11.rb
See https://docs.ruby-lang.org/en/2.2.0/Object.html#method-i-Digest
Close #2743
> test_http11: make `Digest` use thread-safe

- lib/puma/cli.rb
Noticed that this comment wasn’t clear.
> Fix confusing comment typo [ci skip]

- lib/puma/dsl.rb
- test/config/custom_logger.rb
- test/test_config.rb
Closes #2511
Still in draft mode - have not gone through the checklist, but was wondering if this solves the problem in #2511.
> Add ability to specify custom logger

- lib/puma/cluster/worker.rb
Whitespace is incorrect. Refer to diff
> Fix indentation in Worker class

- README.md
not my finest prose, any feedback welcome
> note about on_worker_boot behavior when app is not preloaded

- lib/puma/cluster.rb
- lib/puma/cluster/worker_handle.rb
Cleanup: Add WorkerHandle#term! method to remove usage of instance_variable_set
> Cleanup: Add WorkerHandle#term! method to remove usage of instance_variable_set

- CONTRIBUTING.md
> Fix typo in CONTRIBUTING [ci skip]

- lib/puma/request.rb
- test/test_puma_server.rb
Proof of concept streaming bodies without using `rack.hijack`.
> Add support for streaming bodies.

- test/test_http11.rb
> Remove the skip the test semicolon in path with jruby

- test/test_binder.rb
- test/test_request_invalid.rb
1. Backport PR #2830 to 5-6-stable
2. Commit ["Merge pull request from GHSA-h99w-9q5r-gjq9"](https://github.com/puma/puma/commit/5bb7d202e24dec00a898dca4aa11db391d7787a5)  added a test file, but it needed a few changes to run in 5-6-stable.
> 5-6-stable branch - fix tests

- lib/puma/dsl.rb
This was an oversight in #2855.
> Clean up key/cert assignment in DSL

- .github/workflows/ragel.yml
- ext/puma_http11/http11_parser.c
Two files are generated with ragel.  These files may not match the source files.  Add a workflow to test, and save CI generated files if they do not match what is in the repo.
PR opened as a draft with existing workflows disabled, and tests are failing.  See https://github.com/puma/puma/actions/runs/2173139081
Note that all of the puma workflows have 'workflow_dispatch' enabled, so they can be run at anytime on any branch by a member.
Closes #2858
> [CI] Add workflow to test ragel generation

- .github/workflows/ragel.yml
- .github/workflows/tests.yaml
> Github Actions. Add rubocop and running condition for the ragel pipeline.

- .github/workflows/tests.yaml
> [CI] Add OpenSSL 3 testing - Ubuntu-22.04 - 3.1 & head

- lib/puma/log_writer.rb
> log_writer.rb - refactor, add internal_write method

- .github/workflows/tests.yaml
- Rakefile
- ext/puma_http11/extconf.rb
- test/config/cpu_spin.rb
Add `PUMA_` fix to all the puma specific environment variables in preparation for Puma 6 release.
Close #2853. 
<details>
<summary>List of all environment variables in Puma codebase</summary>
- puma
- PUMA_BUNDLER_PRUNED
- PUMA_DEBUG
- PUMA_LOG_CONFIG
- PUMA_NO_RUBOCOP
- PUMA_DISABLE_SSL (formerly DISABLE_SSL)
- PUMA_MAKE_WARNINGS_INTO_ERRORS (formerly MAKE_WARNINGS_INTO_ERRORS)
- PUMA_WAIT_FOR_LESS_BUSY_WORKERS (formerly WAIT_FOR_LESS_BUSY_WORKERS)
- commit_info
- systemd
- LISTEN_FDS
- LISTEN_PID
- NOTIFY_SOCKET
- WATCHDOG_USEC
- rack, rails
- APP_ENV 
- RACK_ENV
- RAILS_ENV
- ruby, rubygems, bundler
- BUNDLE_APP_CONFIG
- BUNDLE_GEMFILE
- GEM_HOME
- RUBYOPT
- heroku
- PUMA_MAX_THREADS, MAX_THREADS
- PUMA_MIN_THREADS, MIN_THREADS
- WEB_CONCURRENCY
- others
- CI
- DYNO
- GITHUB_ACTIONS
- …
> Prefix all environment variables with `PUMA_`

- lib/puma/cluster.rb
- lib/puma/cluster/worker.rb
- lib/puma/dsl.rb
- lib/puma/util.rb
- test/test_integration_cluster.rb
Because it's not performant as expected. Closes #2925.
> Remove nakayoshi GC

- lib/puma/request.rb
- test/helper.rb
- test/test_response_header.rb
> Allow header values to be arrays (Rack 3)

- lib/puma/configuration.rb
> Make wait_for_less_busy_worker default

- lib/puma/configuration.rb
- lib/puma/server.rb
- lib/puma/thread_pool.rb
- test/test_busy_worker.rb
- test/test_out_of_band_server.rb
- test/test_puma_server.rb
- test/test_thread_pool.rb
> Move threadpool init out of server

- .github/workflows/tests.yaml
https://github.com/oracle/truffleruby/issues/2700
> Allow fail on truffle for now

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
I added `.devcontainer` directory to use GitHub Codespaces. You can try GitHub Codespaces by follwing the steps below. Closes #2934.
1. Ensure that the correct branch is selected. https://github.com/cafedomancer/puma/tree/github-codespaces
2. Click the "Code" button.
3. Click the "Codespaces" tab.
4. Click the "Create codespace on github-codespaces" butotn.
5. Run `bundle exec bin/puma test/rackup/hello.ru` or `bundle exec rake` in Terminal (`bundle install` and `bundle exec rake compile` are automatically run after creating a codespace).
You can manage your codespaces on https://github.com/codespaces.
ref: [Add a dev container configuration to your repository](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/setting-up-your-project-for-codespaces)
> GitHub Codespaces

- .github/workflows/tests.yaml
> [CI] - Allow failure on macOS TruffleRuby for now

- test/test_integration_cluster.rb
Fix my dumb mistake.  Note to self - always assume tests fail...
I've been running the test workflow in my fork (yes, I'm on a mission), and this test intermittently failed.
> [CI] TestIntegrationCluster#test_hook_data - use ensure for removing files

- test/test_puma_server.rb
This PR rewrote the `test_lowlevel_error_message ` test into two tests.
* First test that raises an `NoMethodError` with backtrace and message `"Oh no an error"`<sup>[1]</sup>. Update the `assert_match` regexp to assert `error.message`, `error.class` and `error.backtrace.join("\n")`. Use `//m` multiline mode so `.` matches a newline.
* Second test that raises an custom error of `WithoutBacktraceError` with message `"no backtrace error"`<sup>[2]</sup> which its backtrace is `nil` (I tried to use `set_backtrace(nil)` but `backtrace` always present, so had to create an custom error class) and check we did go through the code path without backtrace by updating assert_match regexp.
I think with the changes we could possibly not needed to skip tests on Windows and TruffleRuby.
<sup>[1] error …
> Rework low level error tests

- History.md
Ref: https://github.com/puma/puma/pull/2798#issuecomment-1278940243
> Mark #2798 as a breaking change in the changelog

- test/test_puma_server.rb
> [CI] Fix TruffleRuby - TestPumaServer#test_lowlevel_error_message_without_backtrace

- .github/workflows/rack2.yaml
- .github/workflows/ragel.yml
- .github/workflows/skip_duplicate_workflow_runs.yaml
- .github/workflows/tests.yaml
Hi! this closes #2929
Skip conditions have been added at the step level for matrix jobs because of: https://github.com/marketplace/actions/skip-duplicate-actions#how-to-use-skip-check-with-required-matrix-jobs
> Skip duplicate Github Actions runs (#2929)

- lib/puma/dsl.rb
In digging through the SSL options in code I noticed that it supports more use cases than documented, this doesn't cover all of them but expands a bit.
> [ci skip] Include `ca` option for SSL bind and mTLS example

- test/test_integration_single.rb
Fix regex used to test curl output message when connection refused.
> [CI] - test_integration_single.rb - fix curl msg regex

- 6.0-Upgrade.md
- History.md
> Add note about HTTP method change in 6.0

- docs/nginx.md
> [ci skip] Adding nginx syntax highlighting

- README.md
Add a link to another community plugin
> [ci skip] Add link to a community plugin

- README.md
> Update README and add a link to puma-daemon gem [skip ci]

- lib/rack/handler/puma.rb
Closes #3117 by adding `::` operator.
> Fix NameError by adding ::operator

- test/helper.rb
Collapse 'Skips' section when running CI in Actions.
> [CI] helper.rb - collapse 'Skips' section in Actions test logs

- .github/workflows/github_actions_info.rb
- .github/workflows/rack2.yaml
- .github/workflows/tests.yaml
Add tto matrix variable to set test step timeout in non-MRI
github_actions_info.rb is temporary, will use info to log repo/branch/commit info in test logs
Pulled from PR #3128
> CI workflows - add 2 macos-13 jobs, reduce macOS jobs, timeouts, add git ref info

- .github/workflows/turbo-rails.yml
Capybara 3.39.1 was released a few hours ago.  It's got a fix for the change in selenium-webdriver.
> [CI] turbo-rails - Capybara is fixed

- History.md
[ci skip]
https://github.com/puma/puma/pull/3182#issuecomment-1600034911
> Correct change log entry for 5.6.6

- test/helpers/test_puma/puma_socket.rb
- test/test_cli.rb
> [CI] test_cli.rb - use PumaSocket, remove native sockets, net/http

- test/test_puma_server_ssl.rb
> [CI] test_puma_server_ssl.rb - add PumaSocket, remove net/http

- test/test_puma_localhost_authority.rb
> [CI] test_puma_localhost_authority.rb - use PumaSocket, remove net/http

- lib/puma/cluster.rb
We recently ran into an issue in production where our puma containers had thousands of zombie (defunct) processes.
This was caused by the web application spawning some multi-process command (Google Chrome) and sometimes interrupting it hard.
```
- pid=1 puma cluster
\- pid=2 puma worker
\- pid=3 google chrome
\- pid=4 google chrome subprocess
```
In such scenario if `pid=3` dies without first reaping `pid=4`, then `pid=4` get reparented as a child of `pid=1`, and `pid=1` is responsible to reap it.
On classic style hosting, PID 1 is the init system (e.g. systemd), but with containers PID 1 is the container initial command, in our case the Puma cluster process.
Some people uses [some minimal init implementations like `tini`](https://github.com/krallin/tini) to handle this, but I believe …
> Make puma cluster process suitable as PID 1

- lib/puma/dsl.rb
- test/test_integration_cluster.rb
Test fails on master...
Closes #3264
> dsl.rb - fix warn_if_in_single_mode when WEB_CONCURRENCY is set

- test/test_null_io.rb
See comments in PR #3276, only test file fixes.
> test_null_io.rb - fix up for Ruby 2.4 FrozenError, TruffleRuby

- .github/workflows/rack_conform.yml
- .github/workflows/tests.yaml
- .github/workflows/turbo-rails.yml
Recent update to setup-ruby allows using 'rubygems: latest'
> [CI] Add Ruby 3.3, use 'rubygems; latest' in tests.yaml MRI

- README.md
Hello, I have created a new plugin for puma that handles SSL certificate provisioning & setup with an ACME CA. This PR lists the plugin in the README.
> Add puma-acme plugin to the README

- lib/puma/dsl.rb
> Add missing punctucation in DSL comment

- lib/puma/cluster.rb
- lib/puma/cluster/worker.rb
- lib/puma/const.rb
- lib/puma/runner.rb
- lib/puma/server.rb
- lib/puma/util.rb
Actioning [this comment](https://github.com/puma/puma/pull/3283#discussion_r1429309469).
> Refactor | Constantize worker pipe request types

- lib/puma/client.rb
- test/test_puma_server.rb
Reported by Ben Kallus: When two requests are seen in the initial buffer passed to the parser, puma incorrectly treats the second request as the body of the first request.
> Properly handle two requests seen in the initial buffer

- README.md
- docs/fork_worker.md
Hopefully this will help users avoid heartbreak in https://github.com/puma/puma/issues/3134
> Improve documentation for hooks, including on_refork hook

- .github/workflows/tests.yml
> [CI] tests.yml - add Ubuntu 24.04, test Ruby 3.1 thru head

- test/test_integration_pumactl.rb
> Skip gc test refutation on JRuby.

- README.md
> README.md: Spell "comma" [ci skip]

- test/test_integration_cluster.rb
As with other recent CI related PR's, these tests intermittently failed locally.  Small refactors, add logging, increase time for tests if clustered, etc.
> [CI] test_integration_cluster.rb - test_worker_timeout, logging, heredocs

- test/test_app_status.rb
There have been intermittent failures when run parallel, and the file doesn't take any time when run 'serial'.
> [CI] test/test_app_status.rb - don't run parallel, only takes 0.07 sec

- CONTRIBUTING.md
- test/runner
1. Updated the comments in `test/runner` after using on macOS.
2. Mentioned the file in CONTRIBUTING.md
> Updates regarding test/runner [ci skip]

- test/test_integration_cluster.rb
Naked `@server.gets` calls are blocking.  Parallel testing will always be unstable (and unpredictable) with blocking calls.
But, due to the resources used by runner VM's and not used by 'local' testing, a test file that runs fine locally may be unstable when run on a multi VM CI system.
Hence, remove all `@server.gets` calls and replace with helper methods that are not blocking.
> [CI] test_integration_cluster.rb - remove blocking @server.gets

- test/helpers/integration.rb
- test/test_preserve_bundler_env.rb
integration.rb - add `env` keyword to `restart_server_and_listen`
test_preserve_bundler_env.rb - use updated `restart_server_and_listen`
> [CI] test_preserve_bundler_env.rb - Replace IO.popen with cli_server

- test/test_integration_ssl.rb
Current file uses `IO.popen` and also duplicates code that is contained in `helpers/integration.rb`.
Replace `IO.popen` with `cli_server` and refactor here and there.
> [CI] Fix up test_integration_ssl.rb - use cli_server, refactor

- test/test_plugin_systemd.rb
Currently, this test file reliably passes locally.  But when running in GHA, failures/retries like the following are common:
```text
TestPluginSystemd#test_systemd_notify_usr1_phased_restart_cluster
Failure: [test/test_plugin_systemd.rb:37]:
--- expected
+++ actual
@@ -1 +1,3 @@
-"STOPPING=1"
+# encoding: ASCII-8BIT
+#    valid: true
+"STATUS=Pum"
```
This shows an unexpected status message written to the notify socket, which is happening due to slow CI runners.  Fix up code to read thru these.  Running CI in my fork showed no failures like the above.
> [CI] test_plugin_systemd.rb - CI systems may log STATUS messages

- test/test_cli.rb
- test/test_integration_pumactl.rb
Repeated failures, so it should run Puma in a subprocess.  Seems to be more stable.  As with other, current test works fine locally, but fails regularly on GHA.
> [CI] Move TestCLI clustered stats test to TestIntegrationPumactl file

- lib/rack/handler/puma.rb
In the current location, it's considered a comment attached to `Puma`.
Apologies, I placed the comment in the wrong location in a commit from Feb of 2023...
> lib/rack/handler/puma.rb - relocate and fixup module comment [ci skip]

- test/rackup/sleep.ru
When revising the variable names for #3497, accidentally included a 'debug' puts.  Removed
> [CI] test/rackup/sleep.ru - remove accidentally commit debug line

- test/helpers/test_puma/puma_socket.rb
- test/test_persistent.rb
File uses blocking request socket.gets calls.
> [CI] test_persistent.rb - use TestPuma::PumaSocket

- test/test_launcher.rb
While running updates to the test suite, this test failed in two macOS jobs.  I then noticed that it reliably failed on my desktop.
See below, job logs are only held for a few weeks:
https://github.com/MSP-Greg/puma/actions/runs/10974547240/job/30473181379#step:10:912
https://github.com/MSP-Greg/puma/actions/runs/10974547240/job/30473181329#step:10:967
`test_launcher.rb` does not create client requests, so there are no changes to it in the new test framework.
Use a queue to let the launcher stop.  Seems to fix the issues with thread contention...
> [CI] test_launcher.rb - fixup test_puma_stats_clustered, small refactor

- ext/puma_http11/puma_http11.c
> Mark as ractor-safe

- .github/workflows/tests.yml
macos-15 is now available in GitHub Actions.
> [CI] tests.yml - add three macos-15 jobs - 3.1, 3.3, head

- docs/stats.md
> stats.md improvements

- test/test_busy_worker.rb
Fix #3325, needs method rename
> [CI] fix #3325, needs method rename

- test/test_web_concurrency_auto.rb
recent CI failure:
```text
1) Failure:
TestWebConcurrencyAuto#test_web_concurrency_with_concurrent_ruby_available [/Users/runner/work/puma/puma/test/test_web_concurrency_auto.rb:31]:
--- expected
+++ actual
@@ -1,3 +1,3 @@
-# encoding: ASCII-8BIT
+# encoding: US-ASCII
-"4"
+"2"
```
The failed assert compares the value (`@options[:workers]`) that `concurrent_ruby` sets to the stats value for the key `:workers`.  During boot or restarts, the stats key may not be equal to `@options[:workers]`.
This PR reads the server log, and checks the value of the `*      Workers:` line, which is set with:
https://github.com/puma/puma/blob/521c6c65bfd80168286f6496ea87c202f0335568/lib/puma/cluster.rb#L354
Also, `get_worker_pids 0, 2` is added to check that at least two workers have booted before sending a …
> test_web_concurrency_auto.rb - fixup part II - wait

- Rakefile
The task `rake test:all` is the same as `rake test`. Is there any reason it still needs to exist, aside from the different description? Does anybody still use `rake test:all` for running tests?
> Delete unnecessary task

- benchmarks/local/bench_base.rb
- benchmarks/local/bench_base.sh
- benchmarks/local/long_tail_hey.md
- benchmarks/local/long_tail_hey.rb
- benchmarks/local/long_tail_hey.sh
- benchmarks/local/response_time_wrk.rb
Add `./benchmarks/local` files for using hey to check high request volumes.
[`benchmarks/local/long_tail_hey.md`](https://github.com/MSP-Greg/puma/blob/00-hey-bench/benchmarks/local/long_tail_hey.md) provides a brief description of use.
> Add benchmark hey files and md description [ci skip]

- lib/puma/dsl.rb
> Remove extra whitespace in single mode hook warning

- .github/workflows/tests.yml
Temp fix for Ruby 3.0 Actions jobs.
> CI: Temp fix for https://github.com/ruby/setup-ruby/pull/676

- .github/workflows/tests.yml
setup-ruby has been updated.
This reverts commit ca9005093375aa528840b16d7f1c5a83e10acbe1.
Thank you for contributing! You're the best.
> Revert "CI: Temp fix for https://github.com/ruby/setup-ruby/pull/676 (#3581)"

- test/runner
> CI: test/runner - fix test/runner:92: warning: syswrite for buffered IO

- .github/workflows/tests.yml
See subject.  One line change to `.github/workflows/tests.yml`
> CI: Add Windows Ruby 3.4

- lib/puma/cluster/worker.rb
Makes things more greppable, had a hard time finding this myself
> Change ping to use const

- test/test_integration_cluster.rb
Addresses https://github.com/puma/puma/pull/3568#issuecomment-2542731536
> Add test for worker 0 ping with `SIGURG`

- lib/puma/cluster.rb
Addresses https://github.com/puma/puma/pull/3579#discussion_r1910381176
Since the refork implementation piggy backs off the phased restart logic, all refork related logs are the same as when performing a phased restart i.e. don't mention refork at all. This PR adds distinct logs in all places where we log anything phased restart related.
With fork worker enabled and sending a `SIGURG` (refork):
Before | After
:-:|:-:
With fork worker enabled and sending a `USR1` (phased restart):
Before | After
:-:|:-:
With fork worker disabled and sending a `USR1` (phased restart):
Before | After
:-:|:-:
> Update refork logs

- README.md
> Fix GHA badge in README.md [ci skip]

- History.md
- lib/puma/const.rb
Thanks for all the great work @MSP-Greg. New codename is an album from Return to Forever.
> v7.0.0.pre1

- test/helpers/test_puma/puma_socket.rb
While working on the [long-tail PR](https://github.com/puma/puma/pull/3678), I added some tests at the last minute, and changed some code in `puma_socket.rb`.  WTF was I thinking...
Fixed it here.
> CI: puma_socket.rb - fixup socket/request writes

- lib/puma/dsl.rb
> [ci skip] Improve the DSL `preload_app!` doc

- benchmarks/local/bench_base.rb
- benchmarks/local/bench_base.sh
- benchmarks/local/long_tail_hey-0-2-4-8.sh
- benchmarks/local/long_tail_hey.rb
Updates the code used for hey benchmarks.  Adds a 6x overload job to the matrix in `long_tail_hey.sh`, outputs four digits in hey summary section, etc.
> hey benchmark updates [ci skip]

- test/test_web_concurrency_auto.rb
This test asserts that when certain configuration options are specified that a custom load error is raised if concurrent-ruby cannot be found. It does this by: 
- finding the real file on disk
- renaming the file
- running code and asserting an error with a specific message
- ensuring the file rename is reverted
Most developers would be surprised that running the test suite of one project might cause other code running on the same machine to fail, but because these modifications to disk are global, that's what happens.
Instead of making a real system change, this mocks the interface where that file is loaded i.e. the "require" call:
```ruby
def require_processor_counter
require 'concurrent/utility/processor_counter'
rescue LoadError
```
This is done by monkey patching the `require` method …
> Remove global side effect from test

- test/test_http11.rb
In `test_http11.rb` the `test_get_const_length` seems to hang often.  Currently, it requires json in the app.
Use `JSONSerialization.generate` to generate the json string in the app.  The test needs to parse the json string, but that's loaded in the test process.  Also, some reformatting.
> ci: test_http11.rb - test_get_const_length - remove json require, misc

- lib/puma/cluster_accept_loop_delay.rb
Some minor follow-ups to https://github.com/puma/puma/pull/3746.
> `ClusterAcceptLoopDelay` docs and style follow-ups
