puma/puma

- lib/puma/client.rb
- lib/puma/configuration.rb
- lib/puma/server.rb
- lib/puma/thread_pool.rb
Issue https://github.com/puma/puma/issues/612
This adds a configuration option queue_requests
With queue_requests set to true (the default), workers accept all
requests and queue them before passing them to the handlers.
With it set to false, each worker process accepts exactly as
many requests as it is configured to simultaneously handle.
In combination with threads 1, 1 this ensures that requests
are balanced across workers in a single threaded application.
This can avoid deadlocks when a single threaded app sends a
request to itself. (For example, to generate a PDF.)
> Add a configuration option that prevents puma from queueing requests.

- .gitignore
- lib/puma/cli.rb
- lib/puma/cluster.rb
- lib/puma/events.rb
- test/hello-stuck.ru
- test/test_integration.rb
This pull request fixes phased restart with worker shutdown timeout.
This is from our production stderr log:
```
.../bundle/ruby/2.1.0/gems/puma-2.10.2/lib/puma/cluster.rb:76:in `term': undefined method `[]' for nil:NilClass (NoMethodError)
from .../bundle/ruby/2.1.0/gems/puma-2.10.2/lib/puma/cluster.rb:169:in `check_workers'
from .../bundle/ruby/2.1.0/gems/puma-2.10.2/lib/puma/cluster.rb:408:in `run'
from .../bundle/ruby/2.1.0/gems/puma-2.10.2/lib/puma/cli.rb:507:in `run'
from .../bundle/ruby/2.1.0/gems/puma-2.10.2/bin/puma-wild:31:in `<main>'
```
This bug was introduced in 2.10 with [#566](https://github.com/puma/puma/pull/566/files#diff-c2ca2259d38a531715284b3ec3f4b698R76)
lib/puma/cluster.rb:76:
```ruby
if @first_term_sent && (Time.new - @first_term_sent) > …
```
> Fix phased restart with worker shutdown timeout

- lib/puma/cli.rb
lowlevel_error_handler should be ignored when writing state, otherwise the state file will contain: `:lowlevel_error_handler: !ruby/object:Proc {}` the user will see the infamous "allocator undefined for Proc" error when using pumactl
> Don't write lowlevel_error_handler to state

- lib/puma/server.rb
The first time I saw this message, I thought "Why the fuck is the computer telling me about washing machines?". It took a bit of Googling and source reading to find out what exactly this meant. Here's a better message, slightly more informative, and one that will hopefully reduce confusion for others.
> Update lowlevel error message to be more meaningful.

- lib/puma/app/status.rb
- lib/puma/cli.rb
- lib/puma/cluster.rb
- lib/puma/control_cli.rb
This allows to renew the code directory for newly spawn workers from the master process, all from `pumactl`. 
Provides a harmless workaround to https://github.com/puma/puma/pull/469 and https://github.com/puma/puma/issues/468.
This way when I perform a deploy with a `phased-restart` (using symlink deployment), and only after I _ensure this is a good release_, then I do `pumactl reload-worker-directory`. All workers automatically spawn by the master process will use the new code.
I perform two checks to _ensure this is a good release_. First I poll `pumactl stats` until I see the number of `workers` equal the number of `booted_workers`. Then I make a call to some private `\release` path to get the code git release it's running. Then I'm sure every worker is up and they are running the new …
> Add reload_worker_directory to pumactl

- lib/puma/cluster.rb
I got the following crash on my production platform :
/home/deploy/.rbenv/versions/2.2.0/gemsets/e82ef14dcf8086bc79b93c8607436f02/gems/puma-2.10.1/lib/puma/cluster.rb:298:in `block in run': undefined method `first' for nil:NilClass (NoMethodError)
from /home/deploy/.rbenv/versions/2.2.0/gemsets/e82ef14dcf8086bc79b93c8607436f02/gems/puma-2.10.1/lib/puma/cluster.rb:297:in `each'
from /home/deploy/.rbenv/versions/2.2.0/gemsets/e82ef14dcf8086bc79b93c8607436f02/gems/puma-2.10.1/lib/puma/cluster.rb:297:in `run'
from /home/deploy/.rbenv/versions/2.2.0/gemsets/e82ef14dcf8086bc79b93c8607436f02/gems/puma-2.10.1/lib/puma/cli.rb:507:in `run'
from /home/deploy/.rbenv/versions/2.2.0/gemsets/e82ef14dcf8086bc79b93c8607436f02/gems/puma-2.10.1/bin/puma:10:in `<top (required)>'
from …
> Avoid crash in strange restart conditions

- lib/puma/configuration.rb
- test/config/app.rb
- test/test_config.rb
Right now if you specify a port via `-p $PORT` and via a `config/puma.rb` then puma will incorrectly try to bind to the same port twice and will fail.
This PR calls `uniq!` on the array to remove duplicate ports from the `binds` array. It also emits a warning when `binds` or `port` is called with an already existing port specified:
```
Warning :binds or :port specified twice: "test/config/app.rb:1:in `_load_from'"
```
> Ignore multiple duplicate port declarations

- lib/puma/cli.rb
Current [`NEWRELIC_DISPACHER` default value](https://github.com/puma/puma/blob/3c93cc423f8e3a1a438b3a528b2c342c753dae3d/lib/puma/cli.rb#L38) is not works in Rails 4.2 with Puma, New Relic on Heroku.
Not works:
$ heroku config:add NEWRELIC_DISPACHER=puma
Works:
$ heroku config:add NEWRELIC_DISPACHER=Puma
So I've updated the default of  `NEWRELIC_DISPACHER`.
> Update default of NEWRELIC_DISPACHER for New Relic

- lib/puma/server.rb
- test/test_persistent.rb
- test/test_puma_server.rb
- test/test_unix_socket.rb
Hi,
I hope you find this pull request useful. It includes a fix which makes puma handle the 'Connection' header properly. 
In the current state, when you make an HTTP/1.1 request with the 'Connection' header set to 'close', you expect it to always respond with the 'Connection: close'. It's not the case if the server responds with a 204 status code or any other code without a body. The response won't include the 'Connection' header at all. This behavior can cause potential issues, such as writing to a socket that's already closed if some proxy server rewrites the 'Connection' header to 'close' and a client expects the connection to last for more than one request. Even though the [HTTP/1.1 Message and Routing RFC - Persistence](http://tools.ietf.org/html/rfc7230#section-6.3) states that …
> Proper 'Connection' header handling compatible with HTTP/1.0 and HTTP/1.1

- lib/puma/cli.rb
- lib/puma/cluster.rb
- lib/puma/configuration.rb
http://bogomips.org/unicorn.git/tree/lib/unicorn/configurator.rb#n154
http://unicorn.bogomips.org/Unicorn/Configurator.html#method-i-before_fork
After reading both unicorn and puma cluster implementations,
I think  this hook is required when `preload_app` is used to drop
ActiveRecord connections, established in master process.
> Add `on_worker_fork` hook, which allows to mimic Unicorn's behavior

- puma.gemspec
```diff
diff --git a/puma.gemspec b/puma.gemspec
index 9243cd6..4f3ce34 100644
--- a/puma.gemspec
+++ b/puma.gemspec
@@ -17,7 +17,7 @@ Gem::Specification.new do |s|
s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
s.authors = ["Evan Phoenix"]
s.date = `git log --pretty="%ai" -n 1`.split(" ").first
-  s.description = "Puma is a simple, fast, threaded, and highly concurrent HTTP 1.1 server for Ruby/Rack applications. Puma is intended for use in both development and production environments. In order to get the best throughput, it is highly recommended that you use a  Ruby implementation with real threads like Rubinius or JRuby."
+  s.description = "Puma is a simple, fast, threaded, and highly concurrent HTTP 1.1 server for Ruby/Rack …
```
> [ci skip] Fix an extra space in a sentence in gemspec description.

- ext/puma_http11/mini_ssl.c
- ext/puma_http11/org/jruby/puma/MiniSSL.java
- lib/puma/minissl.rb
- test/test_puma_server_ssl.rb
Both the C and JRuby SSL implementations would hang on a bad handshake because they were not producing the EOF expected in that case.  Update their error handling to behave correctly here (`test_ssl_v3_rejection` covers this for both impls).
This was the root cause of the recent hanging JRuby tests.  With the hang fixed, the test would fail because the SSLv3 handshake became "bad" when java updated to a version with SSLv3 disabled by default (see [here](http://www.oracle.com/technetwork/java/javase/documentation/cve-2014-3566-2342133.html)).  Fix this by removing `enable_SSLv3` support from JRuby (the C minissl implementation doesn't support it either since #591, so it clearly won't be missed).
Fixes #603, replaces #605.
Thanks again @evanphx.  Let me know if you have any questions.
> Fix C/JRuby hang on bad SSL handshake (fixes JRuby travis)

- lib/puma/configuration.rb
Fixes:
```
/opt/test/releases/20150505084239/vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/configuration.rb:102:in `load_rackup': cannot load such file -- rack/builder (LoadError)
from /opt/test/releases/20150505084239/vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/configuration.rb:69:in `app'
from /opt/test/releases/20150505084239/vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/runner.rb:123:in `app'
from /opt/test/releases/20150505084239/vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/runner.rb:130:in `start_server'
from /opt/test/releases/20150505084239/vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/cluster.rb:213:in `worker'
from /opt/test/releases/20150505084239/vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/cluster.rb:109:in `block (2 levels) in spawn_workers' …
```
> Require Rack::Builder

- tools/jungle/upstart/puma.conf
The Jungle Upstart script breaks if rbenv is installed system-wide rather than for a specific user so have added an extra check (for `/usr/local/rbenv/bin`) in order to set `PATH` correctly.
Also, many applications use environment variables for their config (eg. `/etc/environment`) instead of an `application.yml` or similar, but Upstart doesn't pick up on these even from common locations (` /etc/environment`,  `/etc/profile.d/*.sh`) so they need to be sourced manually in the Upstart script. Have added in a commented an example of this.
> Check for system-wide rbenv install in Upstart script

- .travis.yml
- JDK 7 is default on Travis
- cache dependencies
- use always the latest Ruby 2.1.x
> Improve Travis settings

- lib/puma/server.rb
- lib/puma/thread_pool.rb
- test/test_thread_pool.rb
Hi there.
As already discussed in #691 and #681 Puma does not recover from dead threads. Even though this is a fairly uncommon state and might only happen in edge cases. One of these edge cases seems to be using [rack-timeout](https://github.com/heroku/rack-timeout) as you can see in https://github.com/heroku/rack-timeout/issues/76 and https://github.com/rails/rails/issues/1627#issuecomment-76172622.
To reproduce this behavior use the following example rack app:
```ruby
class SimpleRacktimeout # stand-in for a more complex Rails app using all kind of different non rubycode ressouces
def initialize(app)
@app = app
end
def call(env)
p '########### HELLO FROM APP ###########'
begin
app_thread     = Thread.current
timeout_thread = Thread.start do
app_thread.raise(Exception)
end
`sleep 1` …
```
> Add thread reaping to thread pool

- examples/config.rb
Update example config with correct text for `on_worker_*` blocks
> Fix example config text

- lib/puma/server.rb
- test/test_puma_server.rb
The partial hijack API does not mandate that the server
handler will be removing any headers from the response, so if
the app has set a Content-Length header it should be kept intact.
Closes #710
> Do not suppress Content-Length on partial hijack (fixes #710)

- lib/puma/const.rb
- lib/puma/server.rb
We're intermittently seeing the following error in Puma's [server.rb](https://github.com/puma/puma/blob/v2.11.3/lib/puma/server.rb#L460) when an IE client disconnects:
```
Read error: #<Errno::ENOTCONN: Transport endpoint is not connected - getpeername(2)>
```
This appears to be happening because the TCP socket is disconnected while Puma processes the request; in the `normalize_env` method, Puma expects the client to be connected and able to deliver remote address information via `client.peeraddr`.
The most graceful fix I could come up with here is to look for that error and set the `REMOTE_ADDR` simply to localhost. As far as I can tell, there's no graceful way in TCP/Ruby to check if the socket is connected and able to retrieve address information.
While the error is intermittent, we …
> Handle ENOTCONN when setting REMOTE_ADDR

- lib/puma/control_cli.rb
`config/puma/#{env}.rb` isn't tried because there is no environment option for pumactl, though this could be added.
> Make pumactl load config/puma.rb by default

- README.md
- lib/puma/events.rb
- lib/puma/server.rb
This PR fixes a minor misspelling of the word 'occurred'.
> typo fix: occured -> occurred

- lib/puma/reactor.rb
Otherwise I continuously get the error
```
Error in reactor loop escaped: uninitialized constant
Puma::MiniSSL::SSLError (NameError)
/path/to/puma-2.12.2-java/lib/puma/reactor.rb:72:in `block in run_internal'
/path/to/puma-2.12.2-java/lib/puma/reactor.rb:41:in `each'
/path/to/puma-2.12.2-java/lib/puma/reactor.rb:41:in `run_internal'
/path/to/puma-2.12.2-java/lib/puma/reactor.rb:137:in `block in run_in_thread'
```
It does not seem to affect functionality but it's annoying.
> Fix uninitialized constant error

- lib/puma/server.rb
- test/test_persistent.rb
A zero-length chunk has a protocol-significant meaning: it signals the end of the response. An empty part in a Rack body has no such meaning, so we should just skip it.
Currently, the empty part will get sent to the client, terminating the response -- and any following response parts, plus the real terminator, will be left buffered for the next request.
> Skip empty parts when chunking

- lib/puma/configuration.rb
- test/test_config.rb
- test/test_puma_server.rb
Enumerable in 1.8.7 doesn't have each_with_object
rand() doesn't accept ranges in 1.8.7
Caught a 1.9 hash syntax in tests.
> Ruby 1.8.7 compatibility fixes

- lib/puma/cluster.rb
- lib/puma/configuration.rb
- lib/puma/dsl.rb
This is usefull to close database or other remote connections
that were opened during the preload_app phase of the master process.
Fixes #303
> Add before_fork hooks option.

- ext/puma_http11/mini_ssl.c
Trying to build puma > 2.9.2 on CentOS 6 gives the following errors due to lack of OpenSSL EC support in RHEL (patent issues):
```
Installing puma 2.12.3 (was 2.9.2) with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
/usr/bin/ruby extconf.rb
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
creating Makefile
make "DESTDIR=" clean
make "DESTDIR="
compiling mini_ssl.c
In file included from mini_ssl.c:3:
/usr/include/ruby/ruby-2.1.0/ruby/backward/rubyio.h:2:2: warning: #warning use "ruby/io.h" instead of "rubyio.h"
mini_ssl.c: In function ‘engine_init_server’:
mini_ssl.c:150: error: ‘EC_KEY’ undeclared (first use in this function)
mini_ssl.c:150: error: (Each undeclared identifier is reported only once
mini_ssl.c:150: …
```
> Check for OPENSSL_NO_ECDH before using ECDH

- ext/puma_http11/org/jruby/puma/MiniSSL.java
Previously, even when not debugging, we were doing work to compose the log messages.  Delete these diagnostic messages to keep things as fast and lean as possible.
> Eliminate logging overhead from JRuby SSL

- examples/config.rb
- lib/puma/cli.rb
- lib/puma/cluster.rb
This allows you to use `tag ""` in the config file to avoid
inferring a tag.
This is useful for example in cluster mode with phased restarts
where you might want the master process to just specify the puma
version and nothing else.
Later in `on_worker_boot` you would manually modify the process
title to suit your needs if you need more specific tags.
> configuration: allow empty tags to mean no tag desired

- lib/puma/dsl.rb
An equal number of min and max threads is fine by the code around this
message.
> Fix error message in DSL that was slightly inaccurate

- examples/config.rb
- lib/puma/dsl.rb
Had a customer who thought setting this was preventing against long running requests (it doesn't). These docs clarify the purpose of setting this value, that it is used to detect hung processes.
> [ci skip] More explicit docs for worker_timeout

- lib/puma/control_cli.rb
Fix bug when pumactl restart not working
> Pumactl: set correct process name. Fixes #563

- lib/puma/thread_pool.rb
The following backtrace appeared in my error logs:
```
Exception handling servers: undefined method `join' for nil:NilClass (NoMethodError)
/var/lib/gems/2.2.0/bundler/gems/puma-2.14.0/lib/puma/thread_pool.rb:250:in `shutdown'
/var/lib/gems/2.2.0/bundler/gems/puma-2.14.0/lib/puma/server.rb:814:in `graceful_shutdown'
/var/lib/gems/2.2.0/bundler/gems/puma-2.14.0/lib/puma/server.rb:338:in `handle_servers'
/var/lib/gems/2.2.0/bundler/gems/puma-2.14.0/lib/puma/server.rb:296:in `block in run'
```
This signals a problem in thread_pool.rb:250, where the code below lives:
```ruby
if !@workers.empty?
@workers.first.join until @workers.empty?
end
```
Since at that point `@mutex` is not held, `@workers` can and does in fact get modified by threads shutting down. There is a race condition where the …
> thread_pool: fix race condition when shutting down workers

- ext/puma_http11/mini_ssl.c
Mitigates the CRIME attack:
https://community.qualys.com/blogs/securitylabs/2012/09/14/crime-information-leakage-attack-against-ssltls
> Disable SSL Compression

- ext/puma_http11/mini_ssl.c
Allows Puma to parse SSL certificate files that contain multiple chained
certificates, ordered from your certificate down to the root (like nginx).
Forgive me if there was already a way to do this. I couldn't figure it out. Previously without this patch, if I specified a chained certificate file, we would only send the top level cert and my browser would reject it.
> Use SSL_CTX_use_certificate_chain_file for full chain

- examples/config.rb
- lib/puma/cluster.rb
- lib/puma/configuration.rb
- lib/puma/dsl.rb
In some cases, booting workers can take a bit too long, specially if they contend for some scarce resource. If other than this you set up your workers to have a rather low ping timeout, you are in for some problems, because that timeout also applies to the booting phase.
This PR introduces a `worker_boot_timeout` option to control the timeout for workers to boot. This way you don't tie the boot timeout to the ping timeout. Not specifying it defaults to the previous behavior of killing a worker that has not pinged in time (by setting it to `worker_timeout`).
> cluster: add worker_boot_timeout option

- tools/jungle/init.d/puma
Hi
Inspired by jungle/upstart/puma.conf, I modified jungle/init.d/puma, make it supporting rbenv.
Conditions about rvm and chruby are commented out because I haven't test them.
This commit have passed `bundle exec rake` tests.
Hope it helps event if you decide to support rbenv by different approach and reject this PR.
Best,
Snow
> CHG: make jungle for init.d support rbenv

- lib/puma/cli.rb
Fix for issue #770 
The @cli_options variable is used to reflect the options passed from the command line.
The @options variable is the final set of options that will be used by the Runner instance
for configuration. When generating the restart data, we want to set the value in the @options
hash and not in the @cli_options hash.
> Fix bug setting worker_directory when using a symlink directory

- lib/puma/binder.rb
The CA setting is how we can include intermediate keys, but the binder won't set it unless you force client certs.
> Allow setting CA certificates without setting a verify mode

- lib/puma/cli.rb
Currently the only way to specify stdout/stderr redirections is through Puma's config file. This can be cumbersome in some environments where you would rather use a command line switch. Do this for both and also add a boolean option for append mode.
> puma/cli: support specifying STD{OUT,ERR} redirections and append mode

- ext/puma_http11/org/jruby/puma/Http11.java
- ext/puma_http11/puma_http11.c
Puma's HTTP parser does not currently respect duplicate headers. Those are specified in section 4.2 of RFC2616. Basically, when duplicate headers exist, their order is significant and their values are required to be semantically equivalent to a list of comma separated values. Thus a request with:
```
Single-Header: somevalue
Repeated-Header: value1
Repeated-Header: value2
```
is equivalent to:
```
Single-Header: somevalue
Repeated-Header: value1, value2
```
This happens in the real world when, for example, you put an HAProxy in front of Puma. HAProxy will happily add an `X-Forwarded-For` header to requests passed on by other proxies instead of appending the new header's value to the previous header instance. This is legal according to the RFC.
However, current Puma will just collect the …
> puma/http_parser: support duplicate headers

- lib/puma/binder.rb
ctx.ca does not deal well with being set to nil, which will be the case if
verify_mode is none and the ca param was not present in the bind line.
Specifically, you get this backtrace:
<path>/gems/ruby/2.1.0/gems/puma-2.15.0/lib/puma/minissl.rb:138:in `exist?': no implicit conversion of nil into String (TypeError)
from <path>/gems/ruby/2.1.0/gems/puma-2.15.0/lib/puma/minissl.rb:138:in `ca='
from <path>/gems/ruby/2.1.0/gems/puma-2.15.0/lib/puma/binder.rb:169:in `block in parse'
from <path>/gems/ruby/2.1.0/gems/puma-2.15.0/lib/puma/binder.rb:84:in `each'
from <path>/gems/ruby/2.1.0/gems/puma-2.15.0/lib/puma/binder.rb:84:in `parse'
from <path>/gems/ruby/2.1.0/gems/puma-2.15.0/lib/puma/runner.rb:119:in `load_and_bind'
from <path>/gems/ruby/2.1.0/gems/puma-2.15.0/lib/puma/single.rb:79:in `run' …
> Only set ctx.ca iff there is a params['ca'] to set with.

- lib/puma/dsl.rb
- lib/puma/runner.rb
this lets us rely on unix permissions to control access to the control_url.
cc @zendesk/rules
> allow umask for unix:/// style control urls

- lib/puma/cluster.rb
This allows one to write a script that waits for the result of a phased-restart command to complete.
cc @zendesk/rules
> expose `old_worker_count` in stats url

- lib/puma/cluster.rb
Have the worker send the master "tPID" immediately before it shuts down; this lets the master move on to booting the next worker immediately, instead of waiting for the next iteration of the select() loop.
cc @zendesk/rules
> make phased restarts faster

- lib/puma/cli.rb
- test/config/state_file_testing_config.rb
- test/test_cli.rb
Fixes #830 and adds a test to see that all relevant keys are not persisted.
> Don't persist before_fork hook in state file

- lib/puma/server.rb
- lib/rack/handler/puma.rb
We are using `puma` in `cucumber` tests as a backend server for our `Rails` application. And currently it pollutes the cucumber logs. This fix allows to start puma in silent mode. Later this fix will allow to normally do the following [fix](https://github.com/watir/watir-rails/pull/15/files). Thanks!
> Allow to run puma in silent mode

- ext/puma_http11/mini_ssl.c
- test/test_persistent.rb
Nothing significant, just trying to silence some of the output from running the tests.
> Fix some warnings

- lib/puma/configuration.rb
use case:
```
$: puma -C puma.rb -d
```
but in puma.rb:
```
if @options[:daemon]  # *got nil, can not work*
log_path = File.join(app_root,"log/stdout.log")
stdout_redirect log_path , log_path
end
```
> DSL need cli_options

- examples/config.rb
- lib/puma/dsl.rb
> Support passing JRuby keystore info in ssl_bind DSL

- lib/puma/cli.rb
It looks like this environment variable was originally [added in 2012](https://github.com/puma/puma/commit/2280b68d987bfe17f00bb92c772b971a4f073ca6) to get the newrelic_rpm gem to automatically start. Since then, built-in methods for discovering the dispatcher in an environment were added (see [here](https://github.com/newrelic/rpm/blob/master/lib/new_relic/local_environment.rb) generally, and [this commit](https://github.com/newrelic/rpm/commit/8536128d90f54c2b3c93e9608f5aeed5dddf1663) for adding dispatcher detection for Puma specifically). As a result, I think this environment variable no longer needs to be set in Puma.
There was [a change](https://github.com/puma/puma/commit/542919771a249dbccda37c7fd636025c22778a06) by @Tomohiro merged to Puma a few months ago that changed this …
> Remove NEWRELIC_DISPATCHER env variable

- ext/puma_http11/http11_parser.java.rl
- ext/puma_http11/org/jruby/puma/Http11Parser.java
`rake ragel` failed due to renaming the ragel machine from
`http_parser` to `puma_parser` in 3726b7ef198e.
The problem was probably overseen since the file
http11_parser.java.rl has not been touched at this commit
and therefore the rake task did not invoke the parser
generation for the java parser.
> Fix java parser generation

- lib/puma/binder.rb
- lib/puma/server.rb
- test/test_puma_server.rb
The tests all use a port which may not be available (it isn't always open on travis). Instead we can tell the tcp server to bind to port 0 which means it will find a free port, since the tests rely on sending data to that port, we must record the actual port connected to and retrieve that information from the server.
> Fix server tests

- lib/puma/binder.rb
- test/test_puma_server.rb
We were accidentally connecting to a `nil` port, in my previous tests. MRI will interpret this the same as port 0. Jruby will not and throws an error
```
Error: test_very_large_return(TestPumaServer): TypeError: can't convert nil into String
org/jruby/ext/socket/RubyTCPServer.java:102:in `initialize'
org/jruby/RubyIO.java:851:in `new'
```
This tests makes sure we're using a port number instead of nil.
> Fix jruby server tests

- lib/puma/null_io.rb
- test/test_null_io.rb
It's useful to inspect `request.body.size` to see if there's anything to parse (e.g. a JSON payload), but sometimes `request.body` is a Puma::NullIO.
> Add NullIO#size and test

- lib/puma.rb
- lib/puma/cli.rb
- lib/puma/detect.rb
- lib/puma/launcher.rb
- lib/rack/handler/puma.rb
- test/test_cli.rb
- test/test_rack_handler.rb
- test/test_rack_server.rb
- test/test_ws.rb
This is a WIP. This was the minimum I could do to get all tests to pass without changing any tests. Eventually I think we want all high level process controls to come from launcher, I also think we want another separate object that gets passed to Runner/Single/Cluster that will maintain a relationship with the Launcher. We could use this as the object that also gets exposed to the app like the Embeddable class we talked about earlier. 
Moving forwards i'm planning to port out the CLI tests to only test that they are parsing the correct config and launching servers. I'll port all low level unit tests over to the launcher. Making this change we could either keep all the public methods in CLI that delegate to `@launcher`, I'm guessing not many people are using the internals of CLI and we can …
> Initial Seperation of CLI and Server Launcher work

- lib/puma/server.rb
This PR introduces `env['async.callback']` support for async responses.
What I did to achieve this is;
- Split `handle_request` method in two,
- initial `handle_request` to determine to process response immediately or not
- `handle_app_response` to process/deliver response
- Inserted a lambda into `env['async.callback']` (in `handle_request` method)
Not sure if I followed required patterns while doing this, please let me know if anything is weird.
Example working rails application code:
https://gist.github.com/furkanmustafa/2d9edefcaa0336ed982b
> env['async.callback'] support

- lib/puma/thread_pool.rb
Fixes #876.
With:
```
threads 0,1
queue_requests false
```
Sequence:
* work is added ([calling `<<` in server.rb](https://github.com/puma/puma/blob/f048f38416be48ff6a7bb2a5b192c7d7a4a4e7d1/lib/puma/server.rb#L337))
* next [`wait_until_not_full` is executed](https://github.com/puma/puma/blob/f048f38416be48ff6a7bb2a5b192c7d7a4a4e7d1/lib/puma/server.rb#L338) (and it starts waiting on `@not_full`)
* in another thread, `trim` is executed (because `@waiting` is still > 0, `@trim_requested` gets incremented, marking the worker to be trimmed)
* finally, the worker thread wakes up, decrements `@waiting`, execute the work (removing the last item from `@todo`), finishes it, an then hits the `@trim_requested` check, exiting the loop before signaling `@not_full`, so `wait_until_not_full` never exits …
> Signal not full on worker exit #876

- .travis.yml
Rubinius 1.x is unavailable through rvm anymore.
> Remove Rubinius 1.x from .travis.yml and update JRuby to 9.0.5.0

- lib/puma/binder.rb
You specify the backlog similar to a TCP socket with "?backlog=1024". This way we can change net.core.somaxconn to a higher value if we want, and use an appropriate backlog to the socket.
> Backlog parameter for unix sockets

- lib/puma/control_cli.rb
```
$ RAILS_ENV=production SECRET_KEY_BASE=xxxx  bundle exec pumactl -F /var/www/app/current/config/puma.rb status
uninitialized constant Puma::ControlCLI::StateFile
```
> fix uninitialized constant Puma::ControlCLI::StateFile

- lib/puma/control_cli.rb
```ruby
$ bundle exec puma --pidfile tmp/pids/puma.pid -d
* Version 3.0.1 (ruby 2.3.0-p0), codename: Plethora of Penguin Pinatas
* Min threads: 0, max threads: 16
* Environment: development
* Daemonizing...
$ bundle exec pumactl --pid tmp/pids/puma.pid stop
undefined method `windows?' for Puma:Module
```
Uhm...
This [commit](https://github.com/corrupt952/puma/commit/a90c77aacd1458e65c99cf73ce8e19e2cc05ab70) fixed it.
```
$ bundle exec pumactl --pid tmp/pids/puma.pid stop
undefined local variable or method `pid' for #<Puma::ControlCLI:0x007f185fcef968>
Did you mean?  @pid
```
This [commit](https://github.com/corrupt952/puma/commit/2a2f8dd31d67c1659a9d4831e17adfd2b650840b) fixed it.
> Fix undefined method and variable when execute pumactl

- lib/puma/plugin.rb
It won't allow `touch tmp/restart.txt` work correctly in windows, but at least will make out of stock `config/puma.rb` file behavior correct.
```ruby
plugin :tmp_restart
```
Inspired by below PR.
https://github.com/rails-api/active_model_serializers/pull/1014
> Make `plugin :tmp_restart` behavior correct in Windows.

- lib/puma/binder.rb
- lib/puma/const.rb
When you need to have a switch in an infrastructure middleware (streaming, events and sockets) you might have to make runtime decisions based on the server that is being used. The Rack env header is the only way for the underlying Rack app to see which server it is being run on. Previously it would only contain the puma version string, which is insufficient.
Concrete example - in one of my middleware gems I need to switch based on the server used, and also need to output the server name and version to the log which is output from within the application.
This adds 1 frozen and preallocated constant.
> Set a more explicit SERVER_SOFTWARE Rack variable

- .travis.yml
This is a missing update of 0d56a311.
> Fix the JRuby version in `allow_failures` section of `.travis.yml`

- lib/puma/const.rb
Line 103 contains the unicode character ñ which causes this to break rake for ruby 1.9.3. 
Specifying the encoding for the file fixes this error.
> Fixes #922 - Correctly define file encoding as UTF-8

- lib/puma/cluster.rb
Bundler has been supporting both `Gemfile` and `gems.rb` variants for quite some time.
> Allow cluster.rb to work with gems.rb too

- docs/systemd.md
- lib/puma/binder.rb
Socket activation didn't work for SSL or any listeners specifying additional parameters.
These commits  begin with some logging and basic cleanup of the prior socket activation additions. 3030870 fixes socket activation for the additional listener types.  And finally I add a docs/systemd.md to give a more complete example of the whole setup.
> Socket activation cleanup, fixes, and a doc

- lib/puma/configuration.rb
- lib/rack/handler/puma.rb
- test/test_config.rb
- Currently it's not possible to override the default options for
Puma::Configuration with user provided options.
- I came across this issue while working on fixing server restart for
Rails.
- Rails can send it's own restart command to Puma and Puma should store
it in it's configuration object. So that Puma::Launcher can use it.
- After this patch it will be possible as user provided options will be
taken into account in Configuration object.
> Allow overriding options of Configuration object

- README.md
- docs/systemd.md
Improved docs/systemd and also added a Process Monitor section to top-level README.md.
> systemd docs refined

- lib/puma/events.rb
> Update comment for Puma::Events#unknown_error (does not take an `env` anymore)

- lib/puma/events.rb
- lib/puma/server.rb
Error backtraces should really come with this context (makes pinpointing where we should look much easier). Would be open to some discussion about how best to do the printing. Puma::Events#unknown_error could handle it... but I'd have to pass in the `env` request object.
> Add request info to standard error rescue

- Manifest.txt
- lib/puma/thread_pool.rb
- test/test_thread_pool.rb
Supports multithreaded logging and problem diagnosis.
> Set worker thread name.

- DEPLOYMENT.md
Default number of threads is 16 in puma. So I think DEPLOYMENT.md needs to be fixed.
(English is not my native language, so I'm sorry if I misunderstood.)
> [ci skip]Update default number of threads

- lib/puma/configuration.rb
- lib/puma/dsl.rb
- lib/puma/server.rb
@evanphx This is in response to #957. When using puma directly behind an Amazon ELB, ELB will issue a 504 if the server closes a connection sooner than the "idle timeout". This PR let's you configure puma's timeout for persistent connections.
> Allow persistent_timeout to be configured via the dsl.

- lib/puma/server.rb
I got some errors in a project that uses Puma because persistent_timeout doesn't get set, and arithmetic with nil explodes.
> Don't let persistent_timeout be nil

- puma.gemspec
I'm not sure it runs on 1.9.3, but it doesn't compile on 1.8.7:
mini_ssl.c:4:26: error: ruby/version.h: No such file or directory
mini_ssl.c:9:21: error: ruby/io.h: No such file or directory
> Bump required_ruby_version to 1.9.3

- tools/jungle/init.d/puma
It's in the usage instructions for the whole jungle, but missing for just one puma.
> Add phased-restart to usage of one puma

- test/shell/t1_conf.rb
- test/shell/t2_conf.rb
These tests depend on log_requests being enabled, but this was turned
off by default in 03ed48ca903879f3b9a649f5df1cf9d6577ef3d2
> Enable log_requests for integration tests

- lib/puma/const.rb
Looks like these constants are not used. Is it here for backwards compatibility? (Some come from mongrel's codebase)
> Remove unused constants.

- lib/puma/const.rb
The code actually checks if status is between 100 and 199:
```ruby
no_body ||= status < 200 || STATUS_WITH_NO_ENTITY_BODY.include?(status)
```
> Remove 100-199 status codes from constant.

- tools/jungle/init.d/puma
+start+ did not read the environment variables. However, e.g. +phased-restart+
did. Also +start+ was implemented quite differently from other actions.
Now +start+ is implemented like the other actions, it respects environment
variables and there's a lot less code duplication going on.
> Fix Puma init.d start

- Gemfile
- Rakefile
Hi,
This patch is to support a rack latest version 2.0.1, as I want to use it.
https://rubygems.org/gems/rack
Could you merge this?
Thanks.
> Support rack 2.

- test/test_tcp_logger.rb
Sorry about this. My previous change broke the build. This test file needs Minitest because it's using the `capture_subprocess_io` method. I updated my PR to change `MiniTest::Unit::TestCase` to `Minitest::Test`. This removes the warning.
> Fix warning: MiniTest::Unit::TestCase is now Minitest::Test.

- test/test_http11.rb
This fixes isolated test.
For example.
```
$ bundle exec ruby -Ilib:. \
-r 'rubygems' -r 'minitest/autorun' \
-e 'Dir.glob "./test/test_http10.rb", &method(:require)'
...
1 tests, 11 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
```
$ bundle exec ruby -Ilib:. \
-r 'rubygems' -r 'minitest/autorun' \
-e 'Dir.glob "./test/test_http11.rb", &method(:require)'
/home/jaruga/git/puma/test/test_http11.rb:4:in `require': cannot load such file -- testhelp (LoadError)
from /home/jaruga/git/puma/test/test_http11.rb:4:in `<top (required)>'
from -e:1:in `require'
from -e:1:in `glob'
from -e:1:in `<main>'
```
Check testhelp paths in the tests.
```
$ grep -r testhelp test/
test/test_rack_server.rb:require 'test/testhelp'
test/test_http10.rb:require …
```
> Modify a require path for testhelp to pass the test.

- lib/rack/handler/puma.rb
No need to require Puma::CommonLogger.
> Rack handler uses ::Rack::CommonLogger.

- .travis.yml
- Gemfile
- gemfiles/2.1-Gemfile
CI build is failing due to https://github.com/puma/puma/pull/1068
This add a gemfile for Ruby 2.1 fixing rack to ~1.6 release
Cheers
> Travis fix 2.1

- lib/puma.rb
- lib/puma/launcher.rb
- test/test_cli.rb
I made some benchmarks with derailed_benchmarks:
Before:
```
allocated memory by gem
-----------------------------------
1572863  rake-11.2.2
1071797  2.3.1/lib
74852  bundler-1.12.5
18833  puma/lib
12232  rack-2.0.1
80  derailed_benchmarks-1.3.1
```
```
$ bundle exec derailed bundle:mem
TOP: 1.4336 MiB
rake: 0.8711 MiB
rake/rake_module: 0.6094 MiB
rake/application: 0.5938 MiB (Also required by: rake)
rake/file_list: 0.4141 MiB (Also required by: rake)
puma: 0.5195 MiB
yaml: 0.4883 MiB
psych: 0.4883 MiB
```
After:
```
$ bundle exec derailed bundle:mem
TOP: 0.9023 MiB
rake: 0.8477 MiB
rake/rake_module: 0.5586 MiB
rake/application: 0.5586 MiB (Also required by: rake)
rake/file_list: 0.4219 MiB (Also required by: rake)
```
```
allocated memory by gem
----------------------------------- …
```
> Require StateFile if needed.

- test/testhelp.rb
When we would run test, the load path "lib:bin:test:." is loaded by Hoe test default settings.
https://github.com/seattlerb/hoe/blob/master/lib/hoe.rb#L106
So, I think we do not need to set load path in test/testhelp.rb again.
How do you think?
```
$ bundle exec rake test
...
/usr/local/ruby-2.3.1/bin/ruby -w -Ilib:bin:test:. -e 'require "rubygems"; require "minitest/autorun"; require "test/test_thread_pool.rb"; require "test/test_puma_server.rb"; require "test/test_app_status.rb"; require "test/test_rack_server.rb"; require "test/test_minissl.rb"; require "test/test_tcp_logger.rb"; require "test/test_unix_socket.rb"; require "test/test_tcp_rack.rb"; require "test/test_null_io.rb"; require "test/test_http10.rb"; require "test/test_rack_handler.rb"; require "test/test_persistent.rb"; …
```
> Duplicated load path

- test/test_http10.rb
- test/test_http11.rb
- test/test_rack_handler.rb
- test/test_rack_server.rb
- test/test_ws.rb
Last time I sent pull-request to change testhelp.rb path, and it was merged. (https://github.com/puma/puma/commit/73bf56cf8b375f1b9abc1ec30ae64561cebedfd5).
I think it might be my mistake.
Because it looks usual to set "lib" and "test" as a ruby path than "lib" and ".".
Though it may be small thing.
For example, below Rake TestTask is using both "lib" and "test" below page.
http://rake.rubyforge.org/classes/Rake/TestTask.html
`t.libs << "test"`
Maybe hoe that is used in our Rakefile, its test way is kind of special, because of "lib:bin:test:.". "." is set as a Ruby load path.
```
bundle exec rake test
...
/usr/local/ruby-2.3.1/bin/ruby -w -Ilib:bin:test:. -e 'require "rubygems"; require "minitest/autorun"; require "test/test_thread_pool.rb"; require "test/test_puma_server.rb"; require …
```
> Improve required testhelp.rb path.

- tools/jungle/init.d/puma
It's been sort of a pain to look at:
```
Starting LSB: Example initscript...
```
in the logs and wondering where the Puma stuff actually is ;-)
> stub description files updated

- lib/puma/client.rb
- test/test_puma_server.rb
- OSX Finder sends 'Chunked' which resulted in failed WebDAV uploads due to
matching against 'chunked'
> Transfer encoding header should be downcased before comparison

- .travis.yml
Travis builds on PR and push, this changes it so it will only trigger the "PUSH" event on the master branch.
> Stop travis double-builds

- test/testhelp.rb
One or two of them keep hanging, should just blow up.
> Add 60 second timeout to all test cases

- lib/puma/const.rb
- lib/puma/thread_pool.rb
- test/test_thread_pool.rb
- Puma::Threadpool uses only one constant from the constants file. At the beginning, I was thinking to add the missing require to const.rb to the ThreadPool, but I think it's better to just move the constant to where it's used.
- I removed the check for `timeout == 0` since the `times` block will not be executed if it's zero.
> Minor refactor on Thread pool

- .travis.yml
This PR changes to use latest stable jruby in Travis.
> Travis: jruby-9.1.6.0 is latest stable

- lib/puma/binder.rb
- test/test_binder.rb
- test/testhelp.rb
- `add_tcp_listener` and `add_ssl_listener` return `nil` now for
localhost addresses and it was getting added to the `@listeners`.
- Later on the file descriptor `nil` was getting converted to 0 and
resulting into `BadFileDescriptor` error as per this gist -
https://gist.github.com/prathamesh-sonpatki/bc0cac8929dbf17316e8b4b7dda93e20.
- This issue is now fixed and added test case.
- This fixes `rails restart` command on Rails 5 + Puma 3.5 and above.
> Fixed the issue of @listeners getting nil io

- ext/puma_http11/mini_ssl.c
This removes the following warnings:
```
$ bundle exec rake compile:puma_http11
../../../../ext/puma_http11/mini_ssl.c:332:11: warning: unused variable 'err' [-Wunused-variable]
int ok, err;
^
../../../../ext/puma_http11/mini_ssl.c:333:8: warning: unused variable 'buf' [-Wunused-variable]
char buf[512];
^
../../../../ext/puma_http11/mini_ssl.c:349:7: warning: unused variable 'ok' [-Wunused-variable]
int ok, err;
^
../../../../ext/puma_http11/mini_ssl.c:349:11: warning: unused variable 'err' [-Wunused-variable]
int ok, err;
^
../../../../ext/puma_http11/mini_ssl.c:350:8: warning: unused variable 'buf' [-Wunused-variable]
char buf[512];
^
```
> Remove unused vars from mini_ssl.c.

- test/mime.yaml
This file was introduced here:
https://github.com/puma/puma/commit/ee957121c79aece77cda025514cebde9b09fd91a
for this:
https://github.com/puma/puma/commit/da9243cdce5b11e4c5afb443ac8d1c35bc32eefd#diff-7ee96311dc36271ccfacc6239007f63fL67
the file that was requiring was deleted here:
https://github.com/puma/puma/commit/000deba3c186532b62bac80d77ea9b053491dd00#diff-7ee96311dc36271ccfacc6239007f63fL1
> Remove unused file from test suite.

- lib/puma/events.rb
Callbacks were introduced after Puma::Events#on_booted.
https://github.com/puma/puma/commit/b24920d3eda7a7f60da99c006f0d4f082b69d752#diff-af46a0af8a5e391324bbe812613b44a8R25
> Use hooks for on_booted event.

- docs/systemd.md
I found that the configuration proposed doesn't fit very well when Puma is daemonized, that is a common situation when Capistrano is used for deployment. I added my configuration which seems to work pretty well together with the default capistrano3-puma gem settings.
>  Add background process configuration

- lib/puma/null_io.rb
- test/test_null_io.rb
Rack appears to be counting on eof? being defined on objects passed into its multipart parser, e.g. https://github.com/rack/rack/blob/master/lib/rack/multipart/parser.rb#L68 , but this method is not defined on Puma::NullIO.  This created a problem for rack-2.0.1 and puma-3.6.0.
Perhaps, I am missing the full context, but it seems that it should simply return true.
> Add eof? method to NullIO?

- lib/puma/control_cli.rb
- test/test_integration.rb
This pull request has two small fixes for issues I experienced with puma 3.6.0
1. Using pumactl (3.6.0) on OSX it was possible to come cross uninitialised constant Puma::StateFile. I have rectified this.
2. On some platforms (specifically encountered on OpenBSD) Process.getpgid which is backed by the POSIX.1 getgpid implementation does not behave in a fashion which the original implementer expected. 
Process.getpgid is being used to confirm the existence of a running process before proceeding on to act upon said process. 
Using this man page as a [reference](http://man.openbsd.org/getpgid.2) one can see that unless getpgid is called from within the same session as the running process a permission error will be returned. Considering the main uses cases; running in the same session will not …
> Replace use of Process.getpgid which does not behave as intended on all platforms

- lib/rack/handler/puma.rb
It then allow rails to start puma and pass the TLS/SSL configuration:
~~~
bin/rails server puma -b "ssl://0.0.0.0?key=/path/to/example.key&cert=/path/to/example.crt"
~~~
> Allow rack handler to accept ssl host

- lib/puma/control_cli.rb
```
$ bin/bundle exec pumactl -S tmp/puma.state restart
uninitialized constant Puma::StateFile
```
requiring puma doesn't require puma/state_file
Related: #901
> Really fix `uninitialized constant Puma::StateFile`

- lib/puma/launcher.rb
Ruby 2.0 changed this behaviour so fds are closed by default during an exec. If using socket activation from systemd however this closes the fds before they can be activated (with some extra debug output added into `Puma::Binder#import_from_env`):
```
systemd[1]: Started puma.
puma[11696]: {"LISTEN_FDS"=>"1", "LISTEN_PID"=>"11696"}
puma[11696]: fd=3 sock=#<TCPServer:fd 3>
puma[11696]: % Registered unix:/app/tmp/sockets/puma.sock for activation from LISTEN_FDS
puma[11696]: * Pruning Bundler environment
puma[11696]: {"LISTEN_FDS"=>"1", "LISTEN_PID"=>"11696"}
puma[11696]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:64:in `for_fd': Bad file descriptor - not a socket file descriptor (Errno::EBADF)
puma[11696]:         from …
```
> Prune bundler should inherit fds

- lib/puma/launcher.rb
This PR amends a "probable typo". 
Everywhere ELSE in the file, it's `argv` but on the next line, we use `args`.
**Credit**: @parhs
- see #1114
> Launcher: Typo: argv should be args here

- ext/puma_http11/mini_ssl.c
Fixes the following error:
```
../../../../ext/puma_http11/mini_ssl.c: In function ‘get_dh1024’:
../../../../ext/puma_http11/mini_ssl.c:90:5: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
dh->p = BN_bin2bn(dh1024_p, sizeof(dh1024_p), NULL);
^~
```
These changes are based on the following patch to nginx:
<https://github.com/nginx/nginx/commit/789abf2b8cfd184555a09f7001b59e82c003c43c>
("SSL: default DH parameters compatible with OpenSSL 1.1.0").
Relevant parts of the nginx source code in their full context can be
found here:
<https://github.com/nginx/nginx/blob/release-1.10.2/src/event/ngx_event_openssl.c#L954-L980>.
For reference:
> *) Made DH and DH_METHOD opaque. The structures for managing DH objects
>    have been moved out of the public header files. New …
> Make `get_dh1024` compatible with OpenSSL v1.1.0

- lib/puma/runner.rb
This PR make you detect wrong arguments for `stdout_redirect` option easily.
> Raise error when `stdout` or `stderr` is not writable

- lib/puma/cluster.rb
This pull request changes a few things in the cluster:
- Move the check worker interval into a constant (please check to see if all occurrences of 5 were indeed meant to indicate the same interval)
- Move the killing of workers out of the signal handler into a #cull_workers method called from the #check_workers method
- Skip processing of #spawn_workers and #cull_workers if there is no difference in the number of workers to the expected number of workers (to deal with diff now being able to be < 0 in #spawn_workers)
- When a worker is culled, it is logged (takes care of #1147)
This of course changes the behaviour of puma in dealing with TTOU signals, as they are no longer processed immediately, but there is a delay until the next WORKER_CHECK_INTERVAL expires. On the upside, multiple TTOU …
> Move TTOU processing

- .travis.yml
This PR bumps the jruby used to latest stable.
> Travis: jruby-9.1.7.0

- lib/puma/configuration.rb
- test/config/settings.rb
- test/test_config.rb
Fix issue #1199, #1200, #1201 by allowing specified parameters to overwrite those loaded from config files.
> Specified parameters should overwrite loaded config files

- lib/puma/server.rb
Have you ever wondered what happens when a client refreshes their browser really fast? According to [Wireshark](https://cloud.githubusercontent.com/assets/97400/23059914/71170e90-f4c9-11e6-8f10-fd8c135bb479.png), Chrome (I haven't tested other browsers) will properly send an RST packet. At Shopify, we see this pattern a lot during flash sales where people are refreshing their browsers aggressively at the top of the hour pending a release.
This will propagate through your reverse proxies and finally update the state in the TCP backlog to a closing state. Your Ruby webserver, however, is less fortunate—it'll pick up the client, go through the Rack middleware stack, render the response, and write it to the client. Only then it'll find out that it's doing all of this on a one-directional …
> Abort closed clients to save capacity

- test/test_helper.rb
Hello,
Is it possible not to use "bundler/setup" in tests?
Because I am managing `puma`'s RPM package in Fedora project.
https://admin.fedoraproject.org/pkgdb/package/rpms/rubygem-puma/
And we are running the `puma` unit tests without Bundler like this.
Though not using `bundler` is kind of our Fedora project's custom.
```
ruby \
-r 'minitest/autorun' \
-e 'Dir.glob "./test/**/test_*.rb", &method(:require)' \
-- -v
```
I know Bundler is useful for travis or local environment.
However I am happy that the tests do not depends on Bundler.
Thanks!
> Remove Bundler dependency from tests.

- test/test_helper.rb
We got following error on travis now:
https://travis-ci.org/puma/puma/jobs/207434226
```
1) Error:
WebServerTest#test_simple_server:
NameError: uninitialized constant Net
/home/travis/build/puma/puma/test/test_helper.rb:24:in `block in hit'
/home/travis/build/puma/puma/test/test_helper.rb:20:in `each'
/home/travis/build/puma/puma/test/test_helper.rb:20:in `hit'
/home/travis/build/puma/puma/test/test_web_server.rb:36:in `test_simple_server'
```
I confirmed test passed with bundler 1.14.4 but errored with 1.14.5.
https://github.com/bundler/bundler/compare/v1.14.4...v1.14.5
The cause is https://github.com/bundler/bundler/commit/984f64d8a5771b214136b1bc5ffdfa83d4503252
because `rubygems/spec_fetcher` requires `net/http` internally but is deferred now.
I think we should require stdlibs …
> Fix test error

- lib/puma/cli.rb
- lib/puma/configuration.rb
- lib/puma/convenient.rb
- lib/puma/dsl.rb
- lib/puma/launcher.rb
- lib/rack/handler/puma.rb
- test/test_config.rb
- test/test_helper.rb
- test/test_rack_handler.rb
This is the Puma side of rails/rails#28137 
When options are passed to the Puma rack handler it is unknown if the options were set via a framework as a default or via a user. Puma currently has 3 different sources of configuration, the user via command line, the config files, and defaults.
Rails 5.1+ will record the values actually specified by the user versus the values specified by the frameworks. It passes these values to the Rack handler and now it's up to Puma to do something with that information.
When only framework defaults are passed it will set
```
options[:user_supplied_options] = []
```
When one or more options are specified by the user such as `:Port` then those keys will be in the array. In that example it will look like this
```
options[:user_supplied_options] = [:Port]
``` …
> Implement user_supplied_options behavior.

- lib/puma/plugin/tmp_restart.rb
Before this fix if you have an application that uses Puma and this
plugin it is impossible to start 2 servers at once even if they are
using separate pidfiles and ports. The reason is because this plugin
will overwrite the pidfiles no matter.
To reproduce:
Start a regular Rails server which points to the pidfile in
`tmp/pids/server.pid`
```
rails s
```
Start a second Rails server which points to a new pidfile and port
```
rails s -p 4000 -P tmp/pids/new_server.pid
```
The first server will be stopped and claim that the pid is being used by
another process.
What really is happening is the restart plugin is writing over the
original pidfile which stops the server.
If we check the file exists first this will prevent the problem from
occuring. Touching tmp/restart.txt will still work but …
> Only write if file doesn't exist

- lib/puma/control_cli.rb
- test/test_pumactl.rb
`Puma::Configuration._from_file` was removed in https://github.com/puma/puma/commit/89f37432deb499ce6cb72a7e7cba5a55430efacd. It was still being used by the `Puma::ControlCLI` class which was previously not being tested while being called with a `--config-file` option.
This PR reintroduces the previous behavior of loading a config file when specified via `pumactl` command.
cc/ @nateberkopec
> [close #1238] Don't call non-existent method

- lib/puma/server.rb
In [this unit test](https://github.com/ysbaddaden/prax.cr/blob/52242e6e4fd8026693c87c8b97185cd86e1c3d21/test/failures_test.rb#L24), sending a request like "GET http://example.dev:20557/ HTTP/1.1" would cause "Rack::Lint::LintError: env variable QUERY_STRING has non-string value nil" and eventually "Read error: #<NoMethodError: undefined method `empty?' for nil:NilClass>", due to there being no query string in the "dumbass full host request header."
> Ensure env[QUERY_STRING] is not set to nil when there is no query.

- lib/puma/server.rb
- test/test_puma_server.rb
Some servers might return empty HTTP header values.  For example:
```
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
Access-Control-Expose-Headers:
Access-Control-Max-Age: 1728000
```
We are trying to write a test for a Rack proxy server, and in the tests we are using Puma.  Because Puma won't send headers with empty values, [our test is failing](https://github.com/ysbaddaden/prax.cr/blob/0517efd69dc6b67da1772948efb3e92a32bb7b93/test/proxy_test.rb#L67).  Our proxy server may be used with Rack configurations that use other handlers, such as WEBrick, which do send empty header values, so testing this case matters to us.
This change ensures that headers with empty values aren't omitted from the response.
> Don't omit empty header values.

- lib/puma/launcher.rb
- test/hello-env.ru
- test/test_integration.rb
- prevents apps from forever poisoning the ENV by doing bad things (something overrides PATH/HOME etc)
- allows use of Dotenv to load new ENV settings from disk (they do not override)
Test:
```
puts "THIS SHOULD CHANGE #{ENV["TEST"] ||= rand.to_s}"
```
then restart the server
fixes https://github.com/puma/puma/issues/1258
> restore environment to original state before restarting

- lib/puma/server.rb
- lib/puma/thread_pool.rb
Talking through this with @nateberkopec, @schneems, @FoobarWidget, and others at RailsConf , we realized that accepting new clients without taking account for the available capacity of the thread pool doesn't improve throughput, it only hurts it in the case of multiple workers. If a worker pauses (or starts up before other workers), then a worker can accidentally suck up a high number of
clients and leave unused capacity inside the other workers.
This change will smooth out this issue, with a minor penalty to maximum throughput.
> Meter calling accept(2) with available pool capacity

- lib/puma/minissl.rb
This implementation of `write_nonblock` is not technically correct because it can block, but at least it gets past #1189 for the time being. 
The situation is that implementing it properly means having to be able to rewind the state of OpenSSL, which is hardly trivial.
> Make write_nonblock available under SSL

- lib/rack/handler/puma.rb
- test/test_rack_handler.rb
To build a "binds" we need a host IP (via Host) and a port. We were running into a problem where a Host was being explicitly set via user but the Port was being defaulted to by Rails. When this happened the Host was used, but Puma would accidentally use it's own default port 9292 instead of Rail's port of 3000.
The fix was to use the "default" port passed in from a framework (if available) when no explicitly set Port is provided.
> [Close #1255] Prefer user supplied defaults

- lib/rack/handler/puma.rb
There was a mistake previously where if both host and port were passed in as "default" they would take precedence of any values from the puma config "file". 
We can fix this by checking to make sure there were values explicitly passed before setting the config.
> Fix rack handler logic

- lib/puma/events.rb
Environment hash can contain headers, parameters, and much more about the request
This unfortunately means that we may be logging authentication credentials, such as basic auth
And a lot more without the users' knowledge.
This only happens during a log to stderr, but it is still worth noting.
> Remove environment from parse_error

- test/helper.rb
- test/test_integration.rb
takes restart tests from 40s -> 0.4s @nateberkopec 
there is 1 20s test left over ... but we don't run that on CI ... and it has a `sleep 20` will take a stab at that later if it bites me ...
> make tests fast by using readpartial and not blocking read

- test/helper.rb
- test/test_integration.rb
@nateberkopec 
not setting random global state and making variables a bit more limited in scope ... fails when changing 20s -> 19s ... so I'd guess that is why travis had issues ... let's see if this is more stable
> make restart via pumactl more robust

- .rubocop.yml
- .rubocop_todo.yml
- .travis.yml
- Gemfile
- Rakefile
- examples/qc_config.rb
- gemfiles/2.1-Gemfile
- lib/puma/jruby_restart.rb
- lib/puma/plugin/tmp_restart.rb
- test/config/state_file_testing_config.rb
- test/shell/t1.rb
- test/shell/t3.rb
- test/test_rack_handler.rb
- tools/trickletest.rb
Closes #1149.
I've added very basic, all-off-by-default, Rubocop config, which passes. It contains mostly Performance and Layout cops.
Also, I've added a TODO config which contains cops producing a small number of offenses – so, we can easily fix them and make the code style more consistent.
There is the output of the `rubocop -f o -c .rubocop_todo.yml` command:
```
29   Layout/SpaceAroundOperators
21   Layout/SpaceInsideBlockBraces
18   Metrics/LineLength
16   Layout/SpaceAroundEqualsInParameterDefault
15   Layout/SpaceBeforeBlockBraces
15   Layout/SpaceInsideHashLiteralBraces
8    Layout/EmptyLines
6    Layout/EmptyLinesAroundMethodBody
Layout/EmptyLinesAroundModuleBody
5    Layout/IndentationWidth
4    Layout/EmptyLinesAroundClassBody
3    Layout/AccessModifierIndentation
2 …
```
> Let's use Rubocop!

- .gitignore
- gemfiles/2.1-Gemfile
- lib/puma/launcher.rb
- test/helper.rb
- test/test_integration.rb
@nateberkopec would have caught https://github.com/puma/puma/issues/1308 early
does not change a lot since we previously ran the test with `bundle exec` and so already had all the load-paths etc setup with bundler
> run tests with bundler since that is what our users run

- lib/puma/minissl.rb
> fix #1214 Puma >= 3.6.1 + SSL + Persistent Connections. Puma Hangs :(

- .travis.yml
This PR updates the CI matrix to use latest JRuby.
http://jruby.org/2017/06/15/jruby-9-1-12-0.html
> Travis: JRuby 9.1.12.0

- README.md
- docs/systemd.md
- tools/jungle/README.md
* Section renamed Alternative Forking Configuration with explanation given for when to use this.
* capistrano3-puma in sub-section with consolidated dry-run shell commands
* Section Service Configuration contrasts and references Forking section
* Streamline config samples and highlight configs using ini format
Cc: @mdesantis, @nateberkopec as a courtesy and in the hope you might cross-review my edits to the forking config. section you added.  Any errors here?
> Additional docs/systemd refinements

- lib/puma/server.rb
Refreshed pull request with changes from https://github.com/puma/puma/pull/1206, but with the merged master.
> Mri gli pipe bug

- Rakefile
I noticed some typos when running `bundle exec rake`.
> Fix typos in Rakefile

- docs/systemd.md
Add missing `WorkingDirectory` directive in Alternative Forking Configuration template
> Add missing `WorkingDirectory` directive

- Gemfile
- README.md
- appveyor.yml
- test/helper.rb
- test/test_binder.rb
- test/test_integration.rb
- test/test_rack_handler.rb
@nateberkopec @evanphx @stereobooster 
I've made it work, except for the tests with SSL or restarting functionality. The configuration of the environment in Appveyor does not allow to use that straightforwardly, but with some effort, it can be fixed, in case we deem it necessary.
Below is the precise list of problematic tests, if some one will need to get back to them. I've disabled them for Appveyor so far.
Tests that try unhappy path with SSL get uncaught exceptions:
```
TestPumaServerSSLClient#test_verify_fail_if_client_expired_cert = Error reached top of thread-pool: OpenSSL certificate verification error: certificate has expired - 10 (Puma::MiniSSL::SSLError)
1.87 s = E
TestPumaServerSSLClient#test_verify_client_cert = 0.16 s = E …
```
> Appveyor CI

- lib/puma/dsl.rb
- lib/rack/handler/puma.rb
- test/test_rack_handler.rb
The "default" configuration puma level is initialized with a "binds" of `tcp://0.0.0.0:9292`. Puma is designed to be able to bind to multiple ports. 
When a `:port` is sent from Rails along with an empty `user_supplied_options` then the port is treated as a "default". This is merged in with the system defaults, and then later converted into a "binds" via calling `config.port` in the `set_host_port_to_config` method. 
The bug comes due to the "level" of the configuration. Since both are being set on the same "level" the `port` call does not over-write the existing binds but instead prepends to the array. We can fix by ensuring that any binds in a given "level" are empty before setting it.
> [close #1327] Fix double port bind in Rails

- lib/puma/thread_pool.rb
Fix incorrect thread name.
Before:
```shell
$ puma -t 5:5
$ ps -eT | grep puma
148652 148652 pts/0    00:00:00 puma
148652 148681 pts/0    00:00:00 puma 004
148652 148682 pts/0    00:00:00 puma 004
148652 148683 pts/0    00:00:00 puma 004
148652 148684 pts/0    00:00:00 puma 004
148652 148685 pts/0    00:00:00 puma 005
```
After:
```shell
$ puma -t 5:5
$ ps -eT | grep puma
148951 148951 pts/0    00:00:00 puma
148951 148980 pts/0    00:00:00 puma 001
148951 148981 pts/0    00:00:00 puma 002
148951 148982 pts/0    00:00:00 puma 003
148951 148983 pts/0    00:00:00 puma 004
148951 148984 pts/0    00:00:00 puma 005
```
> Fix incorrect thread name

- lib/puma/binder.rb
This will fix #1167 
[See JRuby bug](https://github.com/jruby/jruby/issues/4333)
Need some guidance from @evanphx here: is binder supposed to bind to *only loopback* interfaces by default (as I've done in this PR) or is it supposed to bind to *linklocal addresses* as well?
Here's what this method returned before (my machine, CRuby):
```
["::1", "fe80::1%lo0", "127.0.0.1"]
```
Now:
```
["127.0.0.1", "::1"]
```
Note the omission of an ipv6 link-local interface. The reason I removed it was that there are several other link-local interfaces on my machine which I don't think puma should bind to: 
```
irb(main):013:0> Socket.ip_address_list.select do |addrinfo|
irb(main):014:1* addrinfo.ipv6_linklocal?
irb(main):015:1> end
=> [#<Addrinfo: fe80::1%lo0>, #<Addrinfo: fe80::4b:c017:51b5:cd33%en0>, …
```
> Use Socket.ip_address_list to get loopback addresses

- lib/puma/cluster.rb
- lib/puma/configuration.rb
- lib/puma/launcher.rb
- test/test_http11.rb
- test/test_persistent.rb
These changes allow the tests to run with `RUBYOPT="--enable-frozen-string-literal"` - well, except for the last three tests in `test/test_integration.rb`, which were hanging for me, so I added temporary skip statements in (though this happens without the env variable too - a quirk of my system, I guess).
At the current point in time, Rubocop is not frozen-string-literal friendly, as it depends on parser (which I've got a pending PR submitted for), but parser depends on racc (which has existing PRs from quite some time ago, not yet merged). So, if anyone knows anything about racc, would love your input there, as the maintainer of parser is happy enough with my patch but wants racc patched first. Due to the compiling nature of parser, it can't be used as a git reference in Gemfiles, so …
> Updates for frozen string literal compatibility.

- lib/puma/app/status.rb
- lib/puma/control_cli.rb
- test/test_cli.rb
Should now be filthy-tab-free with an appropriate test in test_cli.rb.
> Add /gc URL to status server to do a major GC. Add a /gc-status URL for GC.stats.

- test/shell/t1.rb
- test/shell/t2_conf.rb
- test/shell/t3.rb
I fixed below failed tests for "rake test:integration".
```
$ bundle exec rake test:integration
cd test/shell; sh run.sh
t1 FAIL
t2 FAIL
t3 FAIL
rake aborted!
Command failed with status (3): [cd test/shell; sh run.sh...]
/home/jaruga/git/puma/Rakefile:160:in `block (2 levels) in <top (required)>'
/home/jaruga/git/puma/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/ruby-2.4.1/bin/bundle:22:in `load'
/usr/local/ruby-2.4.1/bin/bundle:22:in `<main>'
Tasks: TOP => test:integration
(See full trace by running task with --trace)
```
It works after this modification.
```
$ bundle exec rake test:integration
cd test/shell; sh run.sh
t1 OK
t2 OK
t3 OK
```
But why is this "test:integration" test not included in Travis and Appveyor CI test?
> Fix failed tests for "rake test:integration"

- puma.gemspec
About latest stable version 3.9.1 gem, `test`, `example` directories was not included in the gem file.
```
$ gem fetch puma
$ gem unpack puma-3.9.1.gem
$ ls puma-3.9.1
bin/           docs/  Gemfile    .github/    lib/     Manifest.txt  Rakefile   Release.md
DEPLOYMENT.md  ext/   gemfiles/  History.md  LICENSE  puma.gemspec  README.md  tools/
```
But about latest master branch, seeing `puma.gemspec`, all the file is included in gem files including `test` and `example` directory.
```
$ gem build puma.gemspec
Successfully built RubyGem
Name: puma
Version: 3.9.1
File: puma-3.9.1.gem
$ gem unpack puma-3.9.1.gem
$ ls puma-3.9.1/
appveyor.yml   examples/  .github/    lib/          Rakefile           .rubocop.yml
bin/           ext/       .gitignore  LICENSE       README.md          test/ …
```
> Include source and documdnts files only in the gem file.

- lib/puma/launcher.rb
tried to run from master ... kaboom :D
```
NoMethodError: undefined method `include?' for nil:NilClass
puma-0d7a8bb5f377/lib/puma/launcher.rb:171:in `run'
```
> do not blow up when RUBYOPT is not defined

- lib/puma/launcher.rb
This way, when you send `SIGINT` to a server, when running via
`rails s`, a graceful shutdown/stop will be performed.
Before this, not trapping `SIGINT` would mean that either `Rails::Server#start`
or `::Rack::Server#start` would be trapping `SIGINT` and exiting the process.
Fix for: https://github.com/puma/puma/issues/1362
**References**:
- [`::Rack::Server#start`](https://github.com/rack/rack/blob/5c36acac4d298dcf04c58a10014c849a478da53f/lib/rack/server.rb#L289)'s trapping of`SIGINT`.
**Replication of current/fixed behavior**:
```
rails s
=> Booting Puma
=> Rails 5.1.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
* Version 3.9.1 (ruby 2.3.3-p222), codename: Private Caller
* Min threads: 5, …
```
> Setup signal to trap SIGINT and gracefully stop server

- lib/puma/cluster.rb
- lib/puma/launcher.rb
- test/test_integration.rb
Attempt at returning the proper exit code (128+15) when TERM signal
is sent to the server, for both single and clustered mode.
The changes are achieved by restoring signal from within the trap
and accordingly killing the process using TERM event.
Added plus, stopping single mode gracefully now.
Potential fix for : https://github.com/puma/puma/issues/1183
> Return proper exit code for TERM signal

- Gemfile
- Rakefile
This fixes https://github.com/puma/puma/issues/1328 . Maybe.
```
$ bundle install --path vendor/bundle
$ bundle exec rake -T
rake changelog             # Print the current changelog
rake clean                 # Remove any temporary products
rake clobber               # Remove any generated files
rake compile               # Compile all the extensions
rake compile:puma_http11   # Compile puma_http11
rake ragel                 # Generate extension code (C and Java) using Ragel
rake rubocop               # Run RuboCop
rake rubocop:auto_correct  # Auto-correct RuboCop offenses
rake test                  # Run tests
rake test:all              # Run all tests
rake test:integration      # Run the integration tests
$ bundle exec rake compile:puma_http11
install -c …
```
> Remove Hoe

- Release.md
This PR makes the Release.md list less quirky by **renumbering the steps** in a list which had been changed since it started.
> Release.md: Renumber steps

- ext/puma_http11/mini_ssl.c
This warning appeared in AppVeyor output:
https://ci.appveyor.com/project/nateberkopec/puma/build/job/wiq5ep0b2r1oqdj9
This PR heeds the warning, and does not declare an unused variable name.
> mini_ssl.c: Avoid warning: unused variable 'eng'

- .travis.yml
This PR updates the `before_install` step to not peg to a specific version of Bundler, but to use latest stable release.
> Travis: Use latest bundler

- .travis.yml
This PR tries once more to make the Travis CI configuration smaller and more defaults-based.
- The default script step is `bundle exec rake` for `language: ruby`.
- This PR moves `TESTOPTS=-v` to a matrix-global env instead
- Use latest versions of Ruby from `rvm` in the matrix
> Travis: Use default script step; latest versions in matrix

- test/helper.rb
- test/test_binder.rb
- test/test_events.rb
- test/test_puma_server_ssl.rb
- test/test_tcp_logger.rb
- test/test_tcp_rack.rb
Moves the require for puma/events from the individual test files and
into the main test helper.
The reason for this was while I was debugging the `test_puma_server.rb`
tests I was getting an error for an uninitialized constant for
`Puma::Event`.
Moving the require from the individual files to the test help means the
`puma/events` will always be included instead of having to remember to
do that. It makes debugging individual tests locally easier.
> Require puma/events in test helper

- README.md
> add Puma internal threads explaining

- lib/puma/cli.rb
- lib/puma/const.rb
- lib/puma/dsl.rb
- lib/puma/runner.rb
- lib/puma/server.rb
- test/test_puma_server.rb
Worked with @tenderlove on adding early hints. This is still a work in progress as there are a few things we need to address, but this PR is to start the conversation.
This commit adds the early hints lambda to the headers hash. Users can
call it to emit the early hints headers. For example:
```
class Server
def call env
if env["REQUEST_PATH"] == "/"
env['rack.early_hints'].call([{ link: "/style.css", as: "style" }, { link: "/script.js" }])
[200, { "X-Hello" => "World" }, ["Hello world!"]]
else
[200, { "X-Hello" => "World" }, ["NEAT!"]]
end
end
end
run Server.new
```
In this example, the server sends stylesheet and javascript early hints
if the proxy supports it, it will send H2 pushes to the client.
Of course not every proxy server supports early hints, so to enable the
early hints …
> Add early hints feature

- lib/puma/launcher.rb
I noted this while trying to apply suggestions from #1363.
The previous example causes exceptions when you try to run it:
```
FATAL [2017-10-05 11:11:17.535] UxFactory::Server: A fatal error occurred. Details below.
FATAL [2017-10-05 11:11:17.535] UxFactory::Server: no implicit conversion of Puma::Events into Array (TypeError)
/Users/plundberg/.rvm/gems/ruby-2.4.2/gems/puma-3.10.0/lib/puma/launcher.rb:370:in `generate_restart_data'
/Users/plundberg/.rvm/gems/ruby-2.4.2/gems/puma-3.10.0/lib/puma/launcher.rb:64:in `initialize'
/Volumes/extra/git/ecraft/ecraft.uxfactory.server-8.x/src/server/lib/server/uxfactory_server.rb:32:in `new'
/Volumes/extra/git/ecraft/ecraft.uxfactory.server-8.x/src/server/lib/server/uxfactory_server.rb:32:in `start_server' …
```
> puma/launcher: Fixed typo

- puma.gemspec
To help out RubyInstaller2 and provide hints to MSYS2 about required dependencies, `msys2_mingw_dependencies` metadata was added to the gemspec.
This change aims to correct the typo around the new metadata field.
Ref #1434
Ref #1428
Thank you.
:heart: :heart: :heart:
> gemspec: correct msys2 metadata typo

- appveyor.yml
- ext/puma_http11/mini_ssl.c
- lib/puma/minissl.rb
Also, dummy def for RDoc & YARD in mini_ssl.c
> Add ssl support to Windows builds, Appveyor

- lib/puma/configuration.rb
- test/test_config.rb
This PR should fix #1327 issue. 
Could someone tell me if we need [this](https://github.com/ViliusLuneckas/puma/commit/fb3fc019d2ad68ea73f3e17e08c05257389c865e) kind of backward compatibility or just [CLI test](https://github.com/puma/puma/blob/master/test/test_cli.rb#L202) misuse configuration protocol?
> Fix environment file loader

- test/shell/run.rb
- test/shell/t1.rb
- test/shell/t2.rb
- test/shell/t3.rb
Should allow Travis head to pass (?)
> No more ubygems.rb in trunk / 2.5.  Change -rubygems to -rrubygems

- lib/puma/launcher.rb
The problem is this:
```
2.4.2 :001 > [nil, 'foo'].join(' ')
=> " foo"
```
Note the leading space character. By `lstrip`:ing the result of the join, we avoid this altogether.
(This is a fix for the underlying problem that triggered https://github.com/jruby/jruby/issues/4849.)
> Puma::Launcher: avoid a leading space character in RUBYOPT

- test/test_integration.rb
bundle exec puma was causing a lot of problems in development for me,
and uninstalling puma constantly was getting on my nerves. AFAIK bundle
exec ruby <puma script> is the same as bundle exec puma.
> Don't rely on Bundler, but use Bundler env

- .rubocop.yml
- .rubocop_todo.yml
- Gemfile
- examples/puma/client-certs/generate.rb
- gemfiles/2.1-Gemfile
- lib/puma/cluster.rb
- lib/puma/configuration.rb
- lib/puma/thread_pool.rb
- lib/rack/handler/puma.rb
- test/test_rack_handler.rb
That's the small follow-up for #1325.
Initially I decided not to correct `SpaceBeforeBlockBraces` cop offences but update the cop itself to comply with Puma style (more precisely this syntax `->{}` for no-op lambdas).
The patch has been released in 0.50.0.
There is also new cop `Performance/HashEachMethods`, which detected one typo (?) and one false negative)
By the way, that's the last version of Rubocop which supports 1.9.3.
@nateberkopec Maybe it make sense to reduce the number of TODO items within along with Rubocop upgrade? (I.e. within this PR)
> Use Rubocop 0.50

- docs/architecture.md
* `syncronously` -> `synchronously`
* `necessarry` -> `necessary`
> Fix typo in Architecture's doc [ci skip]

- lib/puma/control_cli.rb
- Before, we would remove any non-yielding
args, but missed to actually parse them.
Resulting in issues like, `--pidfile` or
similar args not taking any effect.
**Before**
```
pumactl start -P ~/puma.pid
...
cat ~/puma.pid
=> No such file or directory
```
**Now**
```
pumactl start -P ~/puma.pid
...
cat ~/puma.pid
=> 131232
```
-----
- Remove misleading message of puma starting on pumactl exit: This way, when puma shuts down (running from pumactl), it does not end
with "Puma is started" message. Because, the copy is dependent
on the value of `@command`, the same will always point
to `start`, if pumactl was issued a `start`, hence during
exit, this message appeared as misleading.
**Before**
```
* Version 3.10.0 (ruby 2.3.3-p222), codename: Russell's Teapot
* …
```
> Parse command-line options for pumactl

- .travis.yml
- lib/puma/dsl.rb
- test/config/with_integer_convert.rb
- test/test_config.rb
When passing a character string of seconds to worker_timeout etc.,
In order to prevent the occurrence of the following error, we convert it to an integer like other options.
```
/Users/mitto/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:89:in `>': comparison of Float with String failed (ArgumentError)
from /Users/mitto/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:89:in `ping_timeout?'
from /Users/mitto/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:179:in `block in check_workers'
from /Users/mitto/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:177:in `each'
from /Users/mitto/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:177:in …
```
> worker_timeout, worker_boot_timeout, worker_shutdown_timeout fix integer convert

- tools/jungle/init.d/run-puma
Redirect from stderr to stdout should be before redirect to a log file.
> Fix the order of redirects in run-puma script

- docs/restart.md
This PR updates some documentation which mentions `preload_app!`.
The previous wording ("see below") seemed to refer to content which was not there.
This PR updates that wording to link to the _Clustered Mode_ section of the README, which explains `preload_app!` in context.
> restart.md: Link to the Clustered Mode section instead of spurious See Below

- appveyor.yml
- lib/puma/minissl.rb
- test/test_puma_server_ssl.rb
This PR stabilizes Appveyor testing, along with removing Ruby 2.1, and adding Ruby 2.5.  I realize that using Puma in a Windows production environment is probably uncommon, but it may be used for development.
Also, current windows Ruby builds (2.5 & trunk) are compiled with gcc 7.3.0 and using OpenSSL 1.1.0.  Since Travis is using an older toolset, Appveyor testing may show issues due to the newer 'toolset' used to build & test Puma.
Since:
1. I am not familiar with using Puma in a production environment
2. Testing may not show all issues, and often cannot duplicate production loading 
3. Some of my previous PR's required patching (sorry @evanphx )
4. I do use Puma locally, but normally without SSL.
I thought I'd describe what issues were involved and my solutions.  They are probably not …
> Appveyor fixes

- test/test_puma_server_ssl.rb
If SSL is not used, the tests might be silently passing, while they are
not executed at all.
Let me explain.
The think is that you might not be testing some functionality of Puma and you might not even notice it, because the behavior of test suite apparently depends on load order.
E.g. the test suite is failing for me when I try to execute the test suite like this:
~~~
$ ruby -e 'Dir.glob "./test/**/test_*.rb", &method(:require)' -- -v
... snip ...
1) Failure:
TestPumaServerSSL#test_ssl_v3_rejection [/builddir/build/BUILD/puma-3.11.0/usr/share/gems/gems/puma-3.11.0/test/test_puma_server_ssl.rb:119]:
Expected /wrong\ version\ number/ to match # encoding: ASCII-8BIT
"OpenSSL error: error:1417D102:SSL routines:tls_process_client_hello:unsupported protocol - 337105154".
177 runs, 372 …
> Skip SSL tests instead silently passing them.

- tools/jungle/README.md
- tools/jungle/rc.d/README.md
- tools/jungle/rc.d/puma
- tools/jungle/rc.d/puma.conf
I'm a FreeBSD Rails user, and ran into the issue of not having the service start at (re)boot. I only have recent experience with rbenv, but someone else should be able to make sense and add other environment systems like rvm.
It kind of takes a different approach in the config file by using json, but I felt it would be a little less cumbersome to process that instead of writing overly complex shell logic to parse configs.
> Freebsd rc.d jungle for puma

- docs/systemd.md
I think this would be good to know for systemd users, we lost a lot of time on this problem before pin-pointing the real issue.
> Add a notice for systemd with socket path in release path

- lib/rack/handler/puma.rb
When requiring only the handler puma.rb is not loaded. This defines a method that is used in the launcher https://github.com/puma/puma/pull/1532#discussion_r176171578.
> Ensure Puma.stats_object available using handler

- tools/jungle/README.md
- tools/jungle/init.d/README.md
Using init.d script in a systemd environment will work for jobs start/stop, but restart will not be managed as expected with old init.d system. This may cause confusion, pain and a lot of systemd search time.
Also move `init.d` last in the jungle documentation.
> Add warning about init.d being replaced by systemd

- tools/jungle/init.d/puma
I think that It is appropriate to use `ps -p` in that place.
I think that under certain conditions, existing code ``[ "`ps -A -o pid=
| grep -c $PID`" -eq 0 ]`` may behave incorrectly.
For example, if the content of $PID happens to be a short string(such as `199`), and another process includes the string(process such as `2199`), then unfortunately `grep -c` will return
positive number even if `199` is not running.
> jungle: Using `ps -p` will check correctly whether $PID exists

- lib/puma/server.rb
Oops this was using `v` instead of `vs` here which means it couldn't
have been working.
Ref https://github.com/rails/rails/issues/32329
and https://github.com/puma/puma/pull/1403/files#r176663645
> Use correct var in early hints

- lib/puma/server.rb
This workaround for https://bugs.ruby-lang.org/issues/13632 was applied to all places where IOError is rescued explicitly in https://github.com/puma/puma/pull/1345, but the inline `rescue nil` here will also catch IOError and needs the fix too.
The underlying bug has been fixed upstream in Ruby, but the patch was never backported to the 2.2 branch. I realise that Ruby 2.2 is EOL tomorrow, but it would be great if there was a version of Puma that fully fixed this issue on Ruby 2.2 even if support for it will be dropped at some point.
See https://github.com/rails/rails/pull/31955 for the discussion where this problem was tracked down (by @matthewd 🙇‍♂️)
👋 @nateberkopec @NickolasVashchenko
> Purge interrupt queue when closing socket fails

- lib/puma/thread_pool.rb
As part of the work in #1278 we refactored the conditional in
`ThreadPool#wait_until_not_full` because we found it difficult to reason about
at the RailsConf '17 roundtable. We broke it up a bit and everyone went away
happier. However it turns out that you need to account for both `@waiting` and
`@todo.size` together to make a determination on whether to accept more work
from the socket and the refactor was not equivalent to the old code.
There are no guarantees that request threads that have been signalled due to
work being added to the thread pool's queue will become active, take the mutex
and decrement `@waiting` before the main worker's thread runs
`ThreadPool#wait_until_not_full`. If we run that before the request thread
decrements `@waiting` we end up hitting the early exit of …
> Meter accept(2) while taking into account races around thread pool mutex

- appveyor.yml
- lib/puma/minissl.rb
- lib/puma/server.rb
- test/test_puma_server_ssl.rb
I wanted to run the tests locally so I can understand how `puma` works better. But I would consistently get a hang on the `server.stop(true)` call in the teardown of the `ssl_v3_rejection` test.
The change in https://github.com/puma/puma/commit/d03b125640efa46e539f053996515b28bc62c13f seems to fix it.
In order to reproduce the problem in CI, so you can see the error, I figured I could remove all the Windows specific tweaks in the test, since they seemed to be written specifically to avoid the issue from happening. I came to think that because the hang was happening on the test teardown, and those tweaks seemed to try to prevent that specific teardown from being run. My guess was right and the hang reproduced on Windows after doing that (see …
> Fix ssl_v3_rejection test hanging

- README.md
- lib/puma/cli.rb
- lib/puma/control_cli.rb
- test/test_pumactl.rb
- deprecate `--control`
- add new option `--control-url`
- https://github.com/puma/puma/pull/1416 introduced a bug in pumactl the puma cli does not respond to `control-cli` option. On puma it is called `control`
- this commit https://github.com/puma/puma/commit/a8f54f74cde910b2bf93260a113b057ba6ec40b5 was correct, but it looked like a typo since the names of the options are not consistent across versions
- the best option for fixing this seems to be to support both options in the cli
- we don't want to stop supporting `control` in the cli for backwards-compatibility
> Add support for --control-url in cli

- lib/puma/cluster.rb
- lib/puma/server.rb
- lib/puma/single.rb
- lib/puma/thread_pool.rb
- test/test_cli.rb
This PR introduces the `pool_capacity` stat which can be used as a “negative back pressure metric”. 
What does a “negative backpressure metric” mean? It means when this number is low, we have a higher amount of backpressure. When it is zero it means that our worker has no ability to process additional requests. This information could be used to scale out by adding additional servers. When that happens the requests should be re-distributed between the extra server and the “pool capacity” number for each individual server should go up.
> [close #1577] Negative Backpressure Metric

- test/test_binder.rb
This change will fix the [failing JRuby CI build](https://travis-ci.org/puma/puma/jobs/399748817). I suspect this test never worked, and something in how event errors were handled has changed.
In any case, I've added a keystore-pass url param to make MiniSSL happy (the `examples/puma/keystore.jks` has an empty password, which is fine).
I've also added a port to the URL string to fix a `no implicit conversion of nil into String` error that cam after fixing the keystore-pass (further supporting my suspicion that this never worked).
> Update url for binder parsing test for JRuby

- .travis.yml
I think Puma would be tested against Ruby JIT since Puma is one of the most important Ruby projects. And it'd be nice to have it prepared to work with JIT in the advance.
> Add ruby-head with enabled JIT option into Travis matrix

- lib/puma/client.rb
- test/test_puma_server.rb
As stated in #1480 according [to the spec](https://tools.ietf.org/html/rfc7230#section-3.3) a valid chunked body is formatted like this:
```
4.1.  Chunked Transfer Coding
The chunked transfer coding wraps the payload body in order to
transfer it as a series of chunks, each with its own size indicator,
followed by an OPTIONAL trailer containing header fields.  Chunked
enables content streams of unknown size to be transferred as a
sequence of length-delimited buffers, which enables the sender to
retain connection persistence and the recipient to know when it has
received the entire message.
chunked-body   = *chunk
last-chunk
trailer-part
CRLF
chunk          = chunk-size [ chunk-ext ] CRLF
chunk-data CRLF
chunk-size     = 1*HEXDIG
last-chunk     = 1*("0") [ chunk-ext ] CRLF
chunk-data     = …
```
> Fix chunked ending check

- lib/puma/launcher.rb
So that it also triggers for TruffleRuby which currently doesn't support `fork`.
Methods can have `respond_to?` => `false` if they are "unimplemented"/"not supported on this platform", but yet be actually defined and be part of `Module#methods`.
Those methods usually just raise a NotImplementedError like
`fork is not available (NotImplementedError)`.
This is what MRI does and it's also supported in at least JRuby, Rubinius and TruffleRuby.
The error message is made generic and now looks like this:
```
ERROR: worker mode not supported on truffleruby on this platform
ERROR: worker mode not supported on jruby on this platform
```
Related: I wonder, why does the cluster mode of Puma needs `fork` and not just `spawn`?
> Make the check for the availability of fork() more precise

- test/test_rack_handler.rb
Adds two skipped tests to Windows/Appveyor testing.  Windows often has issues with 0.0.0.0...
> windows add two tests - test\test_rack_handler.rb

- lib/puma/binder.rb
- lib/puma/cli.rb
- lib/puma/client.rb
- lib/puma/cluster.rb
- lib/puma/commonlogger.rb
- lib/puma/configuration.rb
- lib/puma/const.rb
- lib/puma/control_cli.rb
- lib/puma/convenient.rb
- lib/puma/daemon_ext.rb
- lib/puma/delegation.rb
- lib/puma/detect.rb
- lib/puma/dsl.rb
- lib/puma/events.rb
- lib/puma/io_buffer.rb
- lib/puma/java_io_buffer.rb
- lib/puma/jruby_restart.rb
- lib/puma/launcher.rb
- lib/puma/minissl.rb
- lib/puma/null_io.rb
- lib/puma/plugin.rb
- lib/puma/reactor.rb
- lib/puma/runner.rb
- lib/puma/server.rb
- lib/puma/single.rb
- lib/puma/state_file.rb
- lib/puma/tcp_logger.rb
- lib/puma/thread_pool.rb
- lib/puma/util.rb
Reduces runtime allocation by freezing string literals by default.
We could also remove a ton of manual `.freeze` calls, however the ruby supported version is 2.2 and the magic comment only targets 2.3+.
> Freeze all the strings!

- Gemfile
```
$ bundle exec m test/test_rack_handler.rb:34
```
If it's not in the Gemfile, then you can't execute `m` with `bundle exec`.
> Allow running individual tests via the `m` gem.

- lib/puma/dsl.rb
- lib/rack/handler/puma.rb
- test/test_rack_handler.rb
This issue is somewhat tricky. When Rails is booted via `rails server` there are two types of configuration options passed, ones specified directly by a user like `rails s -p 3001` will always "win".
For any other config that is not explicitly passed in, puma will consider it a "default". For example when you run `rails s` (without -p) then the default port will be 3000.
There is one other way to configure puma though, and that is via a config file:
```
port 3002
```
This is the order of precedence for configuration
1) Anything the user explicitly passes to `rails s`
2) Config specified in `config/puma.rb` file
3) Default values passed in via `rails s`
4) Defaults values stored in puma
This fallback mechanism works well except in the case of calling `port` in a `config/puma.rb` file. To …
> Rack handler should use provided default host

- docs/deployment.md
I was reading through the documentation and found a couple spelling errors. Just thought you may be interested in the corrections. No worries if you're not interested.
Thanks!
Tanner J.
> Fixes a few spelling errors in docs/deployment.md

- lib/puma/server.rb
- test/rackup/10seconds.ru
- test/test_integration.rb
Related to https://github.com/puma/puma/pull/1186
**Problem:**
When puma process receives `TERM` signal it tries to finish all current requests and terminate. But... it also accepts "new requests" and these requests are hanged. When the processing of all current requests (which was made before shutdown signal is received) are finished, all "new requests" are closed with error `Connection reset by peer`.
This error prevents load balancers (like nginx) to forward these requests to other web-server, because this error does not guarantee that the request was not processed, but this guarantee is required to forward not idempotent HTTP request (like POST).
Seems like puma should refuse new requests by closing a socket that accepts new connections.
Read …
> Do not accept new requests on shutdown

- lib/puma/client.rb
- test/test_puma_server.rb
I have found and fixed 3 cases when puma does not read a chunked body correctly.
In the first case it hangs.
In the second and third cases it adds extra bytes to the body.
Please see the individual commit messages for more information.
> Fix 3 corner cases when request body is chunked

- README.md
- ext/puma_http11/mini_ssl.c
- ext/puma_http11/org/jruby/puma/MiniSSL.java
- lib/puma/binder.rb
- lib/puma/dsl.rb
- lib/puma/minissl.rb
- test/test_binder.rb
Many organizations run their applications using in environments that fall into scope of PCI-DSS compliance audits. One of the requirements set out by standard is to migrate to more secure protocols if possible.
PCI Security Standards council has advised to migrate away from TLSv1.0 over last few years and recently set a migration deadline of 30 June 2018 (see [this article](https://blog.pcisecuritystandards.org/are-you-ready-for-30-june-2018-sayin-goodbye-to-ssl-early-tls) for more details).
Change proposed in this commit gives an user option to disable `TLSv1.0` during bind, while still leaving the `TLSv1.1` and `TLSv1.2` enabled. `SSLv2` and `SSLv3` are permanently disabled (as they should).
Default behaviour is not changed if the `no_tls` option is not defined.
Related: #980
> add support for disabling TLSv1.0

- docs/architecture.md
- docs/deployment.md
- lib/puma/client.rb
- test/test_puma_server.rb
Measure the time spent reading the HTTP request body and expose it to the Rack app as `env['puma.request_body_wait']`.
This can be combined with a timestamp from a upstream proxy to get an indication of how long a request was waiting for a Puma thread to become available.
Fixes https://github.com/puma/puma/issues/1541
> Request body read time metric

- Rakefile
I was really surprised that puma would ask me to remove every single gem matching /puma/ from my system, just to be able to run puma's tests.... Whatever problem this was fixing, it feels like the wrong solution for it... I mean, this is what `bundler` is for, right?
> Friendlier dev setup

- lib/puma/dsl.rb
- lib/puma/server.rb
- lib/puma/thread_pool.rb
This PR adds an `out_of_band` hook that is invoked when the worker is idle.
The hook runs immediately after a request has finished processing and there are no busy threads on the worker. The worker doesn't accept new requests until this code finishes.
This hook can be used for running out-of-band garbage collection as a solution to #450, e.g.:
```
require 'gctools/oobgc'
out_of_band {GC::OOB.run}
```
It could also be useful for scheduling/deferring other asynchronous tasks to be run during idle periods on the server.
> add out_of_band hook

- tools/jungle/init.d/puma
Pull request https://github.com/puma/puma/pull/1545 broke the ability to stop and restart running instances. The old version of checking $PID existence was truthy **on non-existence**, now it's truthy **on existence**.
Example in case of existing PID 1209:
```sh
$ if [ "`ps -A -o pid= | grep -c 1209`" -eq 0 ]; then echo true; else echo false; fi;
true
```
```sh
$ if ps -p 1209 > /dev/null; then echo true; else echo false; fi;
false
```
> fix(jungle): change pid existence check's condition branches

- lib/puma/single.rb
Ignore the branch name - this turns out to work! Fixes #1523 for us on 3.12.0.
Issue we had was a misconfiguration was causing puma to be SIGTERM'd by ECS before it could set `@server` to anything, which meant that as it tried to graceful stop it hit #1523, confusing our debugging efforts.
> Don't call .stop on a server that doesn't exist

- lib/puma/minissl.rb
This warns on puma (3.12.0):
`% ruby -wrpuma/minissl -ep`
> ⚠ mismatched indentations at 'rescue' with 'begin'

- ext/puma_http11/mini_ssl.c
Implemented NID_X9_62_prime256v1 (P-256) curve over P-521 in order to support Chrome 70 and Edge
> Implemented NID_X9_62_prime256v1 (P-256) curve over P-521

- ext/puma_http11/mini_ssl.c
mini_ssl.c is currently using `DTLSv1_method`, which is a version specific method that is deprecated as of OpenSSL 1.1.0.
[`DTLS_method`](https://www.openssl.org/docs/man1.1.0/ssl/DTLS_method.html) is a 'version-flexible DTLS method'.
This also eliminates compile warnings in both Appveyor & Travis when compiling with OpenSSL 1.1.0 or greater.
> mini_ssl.c - DTLSv1_method -> DTLS_method

- lib/puma/minissl.rb
- test/test_puma_server_ssl.rb
This PR avoids two **Ruby warnings** output when running the test suite.
```
/Users/olle/opensource/puma/lib/puma/minissl.rb:5: warning: mismatched indentations at 'rescue' with 'begin' at 3
```
and
```
/Users/olle/opensource/puma/test/test_puma_server_ssl.rb:150: warning: assigned but unused variable - ssl_listener
```
> Avoid Ruby warnings

- .gitattributes
Fixes #1672.
Locally I'm seeing 
```
mkent@mkvps01 ~/git/puma % git diff
warning: CRLF will be replaced by LF in docs/images/puma-connection-flow-no-reactor.png.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in docs/images/puma-connection-flow.png.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in docs/images/puma-general-arch.png.
The file will have its original line endings in your working directory.
diff --git a/docs/images/puma-connection-flow-no-reactor.png b/docs/images/puma-connection-flow-no-reactor.png
index 05ef8d0..99926a8 100644
Binary files a/docs/images/puma-connection-flow-no-reactor.png and b/docs/images/puma-connection-flow-no-reactor.png differ …
```
> Stop the CRLF warnings

- examples/config.rb
- lib/puma/dsl.rb
Fixes #1714.
Abort on startup if the worker_timeout is too low and mention the limit.
6 is a bit awkward though, might be cleaner to set the minimum at 2 * the WORKER_CHECK_INTERVAL.
> Min worker timeout

- .travis.yml
- test/helper.rb
- test/rackup/hello-stuck-ci.ru
- test/test_cli.rb
- test/test_integration.rb
- test/test_puma_server_ssl.rb
- test/test_unix_socket.rb
Commit 'Update travis & tests':
1. JRuby still using Trusty, as Xenial was broken.
2. Adds skip functionality for fork, UNIXSocket, available Signals.
3. A few test updates
4. TestCLI#test_control_gc_stats - create two tests, one unix, one tcp
Commit: 'fix TestIntegration#test_phased_restart_via_pumactl':
5. Test had a sixty second timeout, which exceeds the CI test timeout.  Changed to 10 for CI.  The test now takes a bit over ten seconds to complete...
**NOTE: Ruby 2.6.0 & ruby-head/trunk are not passing.**
Replaces PR #1713.
> Travis - update Ruby/MacOS to Xenial, add skips based on functionality, misc test fixes

- .travis.yml
Recent Travis 'CRON' jobs are failing on JRuby 9.2.5.0.
I don't use JRuby.  I looked at `ruby/psych`, both of it's JRuby jobs are 'allow failure'.  Couldn't find a repo/gem using OpenSSL that tests on JRuby.
The PR allows Travis to pass.  Note that jruby-head normally passes.  I don't know enough about JRuby to know why 9.2.5.0/9.2.6.0 is failing.  Also, http://rubies.travis-ci.org/
> JRuby - move to Xenial, set all to 'allow_failures'

- lib/puma/dsl.rb
- test/config/ssl_config.rb
- test/test_config.rb
When using mutual TLS, you must specify the CA certificate chain to use
for verifying the peer. Using Puma's `ssl_bind` DSL did not give you the
option of doing so, which lead to confusing errors when attempting to
use it.
Now, when specifying the `verify_mode` as either `peer` or `force_peer`,
you can use the DSL to set the `ca` value [as needed within the `Binder`][binder].
This allows you to use the DSL instead of falling back to the default
`bind` syntax via the URI-style configuration pattern.
[binder]: https://github.com/puma/puma/blob/2668597ec1dd9546d83db9f2ec5ad092add483e6/lib/puma/binder.rb#L180-L184
> Allow mutual TLS CA to be set using `ssl_bind` DSL

- lib/puma/client.rb
- test/test_puma_server.rb
Ran into an issue when keepalive is used where the REMOTE_ADDR of a previous request was used instead of the current users IP.
Place where it is called and not currently reset: https://github.com/puma/puma/blob/50b23bb2c1942b6a1a38f7c6da1aa26df83b8b64/lib/puma/server.rb#L480
> Fixing issue with remote_addr persisting between requests

- .travis.yml
- lib/puma/cluster.rb
Ruby 2.6 introduced a change that affects worker shutdown.  I believe the change occurred between 'commits' r64316 and r64376 of ruby trunk.
1. Added code using `Process::WNOHANG` along with needed logic.  Adds worker status (via `$?`) and total shutdown time to log.
2. Logged status matches status returned by current code (exit 0) for Ruby 2.5.x and lower.
Co-authored-by: MSP-Greg <greg.mpls@gmail.com>
Co-authored-by: guilleiguaran <guilleiguaran@gmail.com>
> cluster - worker shutdown - use WNOHANG with nil return tests

- README.md
Removes warning in Chrome about loading an http resource from an https file.
> Change README.md URI to https [skip ci]

- docs/restart.md
Use the terms used in the explanation in the signals.
> Make restart explanation clearer

- lib/puma/cluster.rb
Simplify deleting workers responding to waitpid.  One loop instead of several.
> Cluster#check_workers - waitpid logic

- README.md
Apologies, I did a previous PR for this, but missed a few `http` links.  Converted to `https`.
Updated the URI for the Appveyor badge, which is now (correctly) showing 'passing'.
> README.md - remove missed http, Appveyor update [skip ci]

- .travis.yml
xcode10.2 uses OpenSSL 1.1.1 for Ruby 2.4 and later.
Hence, changes testing on Travis so some jobs are using OpenSSL 1.1.1 & TLSv1.3.  Ubuntu 16.04 is still using 1.0.2 for Ruby builds.
> travis.yml - xcode10.2 & osx matrix update

- lib/puma/binder.rb
- lib/puma/client.rb
- test/test_integration.rb
Fixes errors/warning shown in CI.
`binder.rb` fix removes error in CI when using a tempfile (which also rescues `Errno::ENOENT`), but not sure about rescue in general use...
> small fixes - binder.rb client.rb test_integration.rb

- lib/puma/server.rb
It was referencing some non-existing params and some behavior that I
don't think is present anymore in this method.
> Updates documentation for Server#handle_request

- lib/puma/dsl.rb
- lib/puma/runner.rb
- test/config/control_no_token.rb
- test/test_pumactl.rb
This recovers PR #1321 by @manishval. Closes #1193 
It's the same code as the original PR but it also includes a test to cover the reported bug.
> Fixes the bug that wouldn't allow no_token be set to true

- lib/puma/cluster.rb
- lib/puma/launcher.rb
- test/rackup/1second.ru
- test/test_integration.rb
Currently when a SIGTERM is sent to a puma cluster, the signal is trapped, then sent to all children, it then waits for children to exit and then the parent process exits. The socket that accepts connections is only closed when the parent process calls `exit 0`. The problem with this flow is there is a period of time where there are no child processes to work on an incoming connection, however the socket is still open so clients can connect to it. When this happens, the client will connect, but the connection will be closed with no response. Instead, the desired behavior is for the connection from the client to be rejected. This allows the client to re-connect, or if there is a load balance between the client and the puma server, it allows the request to be routed to another node.
This PR …
> [close #1802] Close listeners on SIGTERM

- README.md
since default ruby version is now 2.5 hence `Known Bugs` section can be removed as mentioned by @schneems on https://github.com/puma/puma/pull/1813#issuecomment-500611515
> Remove known bugs section from README.md

- History.md
Just noticed that the markdown formatting was off.
Also, is it 8 or 9 features? I count 8 bullet points, but I noticed the tag mentions 9 features as well: https://github.com/puma/puma/releases/tag/v4.0.0
> Clean up 4.0.0 changelog

- .travis.yml
- History.md
- Rakefile
- ext/puma_http11/extconf.rb
- ext/puma_http11/mini_ssl.c
2nd commit changes a require in Rakefile to require_relative...
> Use OpenSSL DTLS_method & TLS_server_method when available

- lib/puma/dsl.rb
While reading the pull request that added a minimum worker_timeout I've stumbled across [this yellow line in it](https://github.com/puma/puma/pull/1716/files#diff-d9e00ab028817951ecfdbbe7e661a141R444) and asked myself
> Shouldn't this use the already casted timeout here now? Why cast again?
This is what this pull request is about, it changes this line as well. Nothing more.
Disclaimer: I only created this PR through the UI and didn't test ANYTHING and am not aware of the puma code base. Feel free to discard this PR for that reason.
> Avoid casting worker_timeout twice

- Rakefile
+ Remove unnecessary gemspec definition
> Cleanup Rakefile

- lib/puma.rb
- lib/puma/accept_nonblock.rb
- lib/puma/app/status.rb
- lib/puma/plugin/tmp_restart.rb
- lib/puma/rack/builder.rb
- lib/puma/rack/urlmap.rb
- lib/puma/rack_default.rb
- lib/rack/handler/puma.rb
- test/helper.rb
- test/test_app_status.rb
- test/test_binder.rb
- test/test_integration.rb
Cleans up tests, parallelizes. 
Adds frozen string literal everywhere it wasn't already in lib/
> Test cleanup and parallelization

- README.md
This [comment](https://github.com/puma/puma/pull/1491#issuecomment-511566664) made me think that it may not be obvious for some developers how to run a single test case.
Hopefully this'll help newcomers.
> Adds instructions on how to use `m`

- lib/puma/configuration.rb
- lib/puma/reactor.rb
- test/test_integration.rb
- tools/jungle/init.d/puma
Fix typos across **puma repository**
**Fixed files**
```
puma/lib/puma/configuration.rb:23:18: "prefered" is a misspelling of "preferred"
puma/lib/puma/configuration.rb:35:52: "prefered" is a misspelling of "preferred"
puma/lib/puma/reactor.rb:26:68: "apropriate" is a misspelling of "appropriate"
puma/test/test_integration.rb:213:21: "accidently" is a misspelling of "accidentally"
puma/test/test_integration.rb:279:37: "reponse" is a misspelling of "response"
puma/tools/jungle/init.d/puma:401:20: "specifiy" is a misspelling of "specify"
```
> Fix typos across puma repository

- lib/puma/events.rb
- test/test_events.rb
- test/test_tcp_logger.rb
The current behavior prevents apps from benefitting from `STDOUT.sync = false` during configuration phases, since the initial call to `Event.stdio` is relatively late in the boot cycle.
> Avoid mutating global STDOUT & STDERR

- lib/puma/events.rb
- test/test_events.rb
Request get `/plop` and query string bigger than 1024*10
```
2019-07-01 21:31:08 +0200: HTTP parse error, malformed request (127.0.0.1/plop): #<Puma::HttpParserError: HTTP element QUERY_STRING is longer than the (1024 * 10) allowed length (was 20481)>
```
ref https://github.com/puma/puma/issues/1768
> Add REQUEST_PATH on parse error message

- win_gem_test/puma.ps1
Allows Appveyor Ruby 2.2 jobs to install a compatible nio4r version.
> update puma.ps1 for nio4r & Ruby 2.2 [skip travis]

- lib/puma/server.rb
- test/test_puma_server.rb
I've been thinking on how Puma should behave when the early hints
can't be sent because the connection has been lost.
I first thought that it should behave the same way it does when the
connection is lost before main response is sent, I've seen that it
swallows those errors (https://git.io/fjVtg) so perhaps we should do
the same here.
There's one consideration though. Because the early hints are sent at
the very beginning of the app execution, we may want to abort this
request altogether and save resources by throwing an exception and
causing Rails to interrupt execution.
Finally I decided to overlook that case just because I believe it's
least surprising from the Rack app point of view. Also
I haven't seen any other example of the web server interrupting
the apps execution due to an …
> Swallow connection errors when sending early hints

- lib/puma/minissl.rb
- test/test_puma_server_ssl.rb
> Avoid blocking on SSL's `#read_nonblock`

- lib/puma/client.rb
- test/test_puma_server.rb
The last CRLF of chunked body is checked by #1607. But it's
incomplete. If a client sends the last CRLF (or just LF) after Puma
processes "0\r\n" line, the last CRLF (or just LF) isn't dropped in
the "0\r\n" process:
https://github.com/puma/puma/blob/675344e8609509b0d767ae7680436b3b382d8394/lib/puma/client.rb#L183-L192
if line.end_with?("\r\n")
len = line.strip.to_i(16)
if len == 0
@body.rewind
rest = io.read
rest = rest[2..-1] if rest.start_with?("\r\n")
@buffer = rest.empty? ? nil : rest
set_ready
return true
end
The unprocessed last CRLF (or LF) is used as the first data in the
next request. Because Puma::Client#reset sets `@parsed_bytes`
to 0.
https://github.com/puma/puma/blob/675344e8609509b0d767ae7680436b3b382d8394/lib/puma/client.rb#L100-L109
def reset(fast_check=true) …
> Fix a bug that the last CRLF of chunked body may be used in the next request

- lib/puma/control_cli.rb
Resolves #1769. Remove backtrace output when invalid `pumactl` commands are run. Originally added as a debugging measure in #1239.
> Remove debug backtrace from pumactl

- .travis.yml
- ext/puma_http11/mini_ssl.c
- ext/puma_http11/org/jruby/puma/MiniSSL.java
- lib/puma/binder.rb
- lib/puma/dsl.rb
- lib/puma/minissl.rb
- test/test_binder.rb
- test/test_config.rb
- test/test_puma_server_ssl.rb
**1st commit - OpenSSL 1.1.1 updates, add `#no_tlsv1_1`**
1.1 Adds three constants to MiniSSL, as many OpenSSL builds cannot/will not connect with older protocols:
```
OPENSSL_NO_SSL3
OPENSSL_NO_TLS1
OPENSSL_NO_TLS1_1
```
1.2 Uses `SSL_CTX_set_min_proto_version` when available
1.3 Add `#no_tlsv1_1` method to `Puma::MiniSSL::Context`
**2nd commit - travis.yml - add bionic 18.04 job**
2.1 Add Ubuntu bionic 18.04 job with Ruby 2.6.3.  This tests with OpenSSL 1.1.1
**3rd commit - test_puma_server_ssl.rb - add tests for `#no_tlsv1`, `#no_tlsv1_1`**
3.1 Adds tests for `#no_tlsv1` and `#no_tlsv1_1`
3.2 Changes setup (via adding a `start_server` method), allowing the context to be passed to a block
**4th commit - add no_tlsv1_1 to binder, config, etc**
4.1 Adds use of `#no_tlsv1_1` with binder.rb …
> Openssl updates

- README.md
https://github.com/puma/puma/pull/1883 removed the config example file, but the readme still refered to it. I figure the broken link can be removed.
> Remove example config reference from readme

- lib/rack/handler/puma.rb
`private` method doesn't make class methods private.
(To make class methods private, use `private_class_method`.)
That was confusing so it's removed.
> Remove confusing `private` call

- .travis.yml
- lib/puma/cluster.rb
- test/test_integration.rb
Commits:
1. **'cluster.rb - fixup for Cluster#check_workers, removes zombies?'** - reverts problematic code in `Cluster#check_workers` to a simplified version of what was used for several years, thru 3.12.1.  Current code has been revised from previous due to issues with newer Ruby versions, etc.  Simplified version appears to be working correctly.
2. **'test_integration.rb - add zombie test'** - uses test from PR #1864 (not merged, closed)
3. **'travis.yml - misc updates'** - updates a few items to make use of current/newer releases.  Hoping to fix some issues with intermittent failures.
> cluster.rb - no zombies

- test/test_cli.rb
- test/test_http11.rb
test files only - fixes warning for RegExp as first parameter in method call, unused variables
> Fix test warnings

- lib/puma/control_cli.rb
- test/test_pumactl.rb
Ref https://github.com/puma/puma/issues/1445
Allow to pass env for pumactl and mimic config loading with first `config/puma/<env>.rb` then `config/puma.rb` when no config provided from command line
> Check puma config environment file on control_cli

- test/helper.rb
- test/helpers/apps.rb
- test/rackup/10seconds.ru
- test/rackup/1second.ru
- test/rackup/hello-delay.ru
- test/rackup/hello-map.ru
- test/rackup/hello-post.ru
- test/rackup/hello-stuck-ci.ru
- test/rackup/hello-stuck.ru
- test/rackup/hello-tcp.ru
- test/rackup/hijack.ru
- test/rackup/hijack2.ru
- test/rackup/sleep.ru
- test/rackup/slow.ru
- test/test_cli.rb
- test/test_integration.rb
1. Commit 'tests - cleanup rackup folder, add sleep.ru, add helpers/app.rb' - Cleans up rackup folder, adds sleep.ru, which allows setting request 'sleep' time via the URI.  Add companion 'app' in `TestApps::SLEEP`.  See Issue #1902.
2. Commit 'tests - change nextport to UniquePort.call, remove nextport, mutex' - helper.rb currently has two methods to select an unused port.  Removed the `nextport` method, and added a mutex to `UniquePort.call` for parallel testing.
3. Commit  'test_integration.rb - make UNIXSocket file names unique` - for parallel testing
> tests - clean up - three commits

- puma.gemspec
Add changelog uri to spec metadata so that there is a "Changelog" link on https://rubygems.org/gems/puma. I went looking for this when comparing an update recently.
> Gemspec Changelog URI

- test/test_integration.rb
Fixes test_sigterm_closes_listeners_on_forked_servers
When the test was added in PR #1802, it used the rackup/1second.ru file, which provided a fixed one second delay.
PR #1903 removed the 1second.ru file and added a sleep.ru file, which allowed variable timing.  But, the 'sleep1' path was added to only one of the test's two connect calls.
The test has passed most of the time, but intermittently fails.  This adds the 1 second delay to the 2nd connect call, which should make it stable.
The 2nd connect call loaded the next_replies array, which was the array that was failing in it's assert.
PR #1903 was my PR, so apologies for the mistake.
> test_integration.erb - fix intermittent test

- lib/puma/cluster.rb
- test/test_integration.rb
Hopefully fixes issues with correct handling of workers when:
1. Using phased-restart
2. externally SIGTERM'd workers
'Misbehaving' workers may not have been previously handled correctly.
Commit 'cluster.rb - fixup worker wait in Cluster, add Worker#term?' - relatively simple code that changes the handling of workers, making sure to trigger SIGKILL if `@options[:worker_shutdown_timeout]` has been exceeded, correct `wait` logic, and does not remove `dead?` workers from Cluster `@workers` array
Commit 'Adds two tests for worker SIGTERM/respawn and phased-restart' - adds two tests for the above.  They're somewhat brittle, and may fail, but not often.  They take about 30 seconds each.
I added the tests to current master and on top of PR #1892, and both of the new tests failed in every job. …
> Fixes Cluster worker shutdown/restart

- lib/puma/cluster.rb
While working on PR #1908, I added a Worker method `#term?` to indicate whether `Worker#term` had been called.  Also, previous code that rejected workers from the `@workers` array where `dead?` was true was removed.
At the time, I wondered what `dead`'s purpose was.  It was also bothersome that workers contain threads, and `alive?` is a thread method, and most would consider `dead` to be the inverse.  Also, it's confusing, especially since code and comments in `thread_pool.rb` refer to `dead_workers`...
Upon reviewing the code, I cannot see anywhere where the state of `Worker#dead?` or `@dead` is used.  It is set here on line 510:
https://github.com/puma/puma/blob/9fb12283dbadf6e2bad04d5e67fe3fc9c29eede5/lib/puma/cluster.rb#L503-L512
This PR changes line 510 to 'w.term' and removes the …
> cluster.rb - remove worker #dead?, #dead!, @dead

- test/test_puma_server_ssl.rb
See errors in :
https://travis-ci.org/puma/puma/jobs/576834408
`UniquePort.call` is a safety valve, ideally serial (non-parallel) tests should cleanup well enough to not require it, but parallel testing, busy CI VM's, etc make that difficult.
I added `http.send :do_finish` and reverted the port back to 3212, and in two Travis runs in my fork, it passed.  This has been intermittent, so `do_finish` may not fix the real problem.  Regardless, it can't hurt.
`Net::HTTP#do_finish` is a private method that closes the underlying socket.  See:
https://github.com/ruby/ruby/blob/d5b237325b631e06775c2c7b5a8012b61ca5bccf/lib/net/http.rb#L1027-L1032
> test_puma_server_ssl.rb - remove fixed port, add http.send :do_finish

- test/helper.rb
Because when we decide to use `skip_on :darwin` in frustration, we don't want to also have to add it to helper.rb...
> test/helper.rb - add darwin to TestSkips logic

- ext/puma_http11/http11_parser.c
- ext/puma_http11/http11_parser_common.rl
- test/test_http11.rb
Allow unescaped semicolons in the URL, improves compatibility with applications that use it as a parameter separator such as Angular 2 or Redmine.
Fixes #1122
> Allow semicolon in url-path

- lib/puma/accept_nonblock.rb
- test/test_integration.rb
See:
https://github.com/ruby/ruby/commit/68ac33a511929268ff5b0e05601b855a3a031b31
> lib\puma\accept_nonblock.rb - fix socket closing on error

- test/test_puma_server_ssl.rb
Recent CI experimentation has shown system OpenSSL to be different than Ruby OpenSSL.  May cause testing issues.
Adds Ruby OpenSSL version info to test log by test_puma_server_ssl.rb when Minitest loads test files.
> test/test_puma_server_ssl.rb - add Ruby OpenSSL version info

- lib/puma/events.rb
- test/test_events.rb
- test/test_tcp_logger.rb
> Revert "Avoid mutating global STDOUT & STDERR (#1837)"

- lib/puma/cli.rb
- lib/puma/dsl.rb
- lib/puma/launcher.rb
- test/config/prune_bundler_with_deps.rb
- test/rackup/hello-last-load-path.ru
- test/test_integration.rb
- test/test_launcher.rb
Extra gems are sometimes needed in the `before_fork` block or before Bundler gets loaded on the workers. This PR adds the ability to define any extra bundler gems to load when pruning bundler.
As an example, when using https://github.com/schneems/puma_worker_killer, it should be loaded in the before_fork of the `config/puma.rb` file like so:
``` ruby
before_fork do
require 'puma_worker_killer'
PumaWorkerKiller.config do |config|
config.ram           = 1024
config.frequency     = 5
config.percent_usage = 0.98
config.reaper_status_logs = false
end
PumaWorkerKiller.start
end
```
If you have installed the gem from the github repo, and are using the `prune_bundler` option, the `require 'puma_worker_killer'` will fail. The only way to get it to run is to require bundler, and then require the …
> Allow extra runtime deps to be defined when using prune_bundler

- .travis.yml
Add 2.4.7 to the build matrix.
(There was a checksum issue which has now been fixed in rvm.)
https://github.com/rvm/rvm/commit/4eac3b9465a77a3c801ca66cc2e68785d922d465
> CI: Use 2.4.7 which now exists

- lib/puma/binder.rb
- lib/puma/launcher.rb
- test/test_binder.rb
We had a relese called Private Caller, now we have Private Listeners
> Privatize binder listeners

- lib/puma/launcher.rb
- test/test_integration_single.rb
See #1868
The original intent of the trap was to ensure that the socket was removed
properly. It now does, so the trap is no longer necessary.
> Remove unnecessary SIGINT trap for Jruby

- lib/puma.rb
- lib/puma/cluster.rb
- lib/puma/launcher.rb
- lib/puma/plugin.rb
- lib/puma/reactor.rb
- lib/puma/server.rb
- lib/puma/thread_pool.rb
- test/test_integration_cluster.rb
- test/test_thread_pool.rb
This should display thread names in GDB as well
> All Puma threads are named

- lib/puma/binder.rb
- lib/puma/cluster.rb
- lib/puma/launcher.rb
- lib/puma/single.rb
See PR #1886, etc.  Tests to follow after lib file PR's.
> unlink UNIXSocket files, fix Binder#close

- lib/puma/plugin.rb
- test/config/plugin1.rb
- test/test_plugin.rb
1. PluginRegistry#fire_background - fix
2. Add test_plugin.rb with a simple test
May be the first test with `Puma::ControlCLI` that's using TCP, so it runs on Windows...
> PluginRegistry#fire_background - fix up per issue 1972

- README.md
https://rubini.us  -> does not seem to redirect to the new page so maybe we fix it on the README?
Although since the context of Rubinius has changed since so I don't know having the link in the first place makes that much sense.
> Fix Rubinius dead link

- lib/puma/cluster.rb
External Worker `TERM` signals 'enter' on the forked side of the worker, but need to be communicated to other side, especially when an  externally `TERM`'d worker is 'stuck'.
Without doing so, a stuck worker will never be `KILL`'ed by Puma, regardless of whether the timers run out...
> Fix Worker external TERM signalling

- lib/puma/cluster.rb
- test/config/worker_shutdown_timeout_2.rb
- test/helper.rb
- test/helpers/integration.rb
- test/rackup/sleep_pid.ru
- test/rackup/sleep_step.ru
- test/test_cli.rb
- test/test_integration_cluster.rb
- test/test_integration_pumactl.rb
- test/test_integration_single.rb
`#test_term_closes_listeners_tcp`
`#test_term_closes_listeners_unix`
using `#term_closes_listeners`
Send requests 10 per second.  Send 10, then :TERM server, then send another 30.
No more than 10 should throw Errno::ECONNRESET.
`#test_usr1_all_respond_tcp`
`#test_usr1_all_respond_unix`
using `#usr1_all_respond`
Send requests 1 per second.  Send 1, then :USR1 server, then send another 24.
All should be responded to, and at least three workers should be used
`#test_stuck_external_term_spawn`
Tests whether externally TERM'd 'stuck' workers are proper re-spawned.
`#test_stuck_phased_restart`
Tests whether 'stuck' workers are properly shutdown during phased-restart.
1. Changes to allow binding to TCP or UNIX, see kwarg unix:
2. Skip on Windows for signal TERM
> Update test_integration files per PR #1956

- .github/workflows/check_changelog.yml
We frequently forget to ask for a changelog entry, and then when we want to release the release maintainer has to go back and manually add them all. It would be better if the changelog was required at PR time so the original submitter can think of the best wording. If a PR is trivial people can add `[ci skip]` or `[changelog skip]`.
This implementation uses github actions.
> [ci skip] Require Changelog at PR time

- History.md
- lib/puma/binder.rb
- lib/puma/cluster.rb
- lib/puma/launcher.rb
- lib/puma/single.rb
- test/test_binder.rb
- test/test_integration_cluster.rb
Puma should not unlink pre-existing UNIXSocket files. which causes issues with systemd.  See: https://github.com/puma/puma/issues/1842, https://github.com/puma/puma/issues/1988
1st Commit: 'Fix Binder @unix_paths handling'
1. Move removal to launcher from single and cluster.
2. @unix_paths only contains files that Puma creates (pre-existing files are not)
2nd Commit: 'Add tests for pre-existing unix paths'
1. test_binder.rb - test_pre_existing_unix
2. test_integration_cluster.rb - test_pre_existing_unix
> Fix systemd unix path handling

- History.md
- lib/puma/dsl.rb
- test/test_config.rb
Fixes #1222 
`:verify_mode` was expecting strings to be used so this line would fail: https://github.com/puma/puma/blob/master/lib/puma/dsl.rb#L402
> Allow for symbols to be used in verify_mode

- History.md
- ext/puma_http11/org/jruby/puma/Http11.java
- ext/puma_http11/puma_http11.c
- test/test_http11.rb
> Strip header whitespace. Fix #1890. Code by @matthewd

- History.md
- ext/puma_http11/http11_parser.java.rl
- ext/puma_http11/org/jruby/puma/Http11.java
- ext/puma_http11/org/jruby/puma/Http11Parser.java
This PR contains a quick pass over the Http11 class and the generated parser to reduce allocation and other antipatterns.
* Fast path hash access that does not need ThreadContext.
* Reduced transcoding of Java strings into Ruby strings by caching ByteList versions statically.
* Reduced allocation of call back objects by making them static.
* Reduced loads of `runtime` and `parser` fields by passing them into callbacks.
The callbacks could also be made into Java lambdas, removing the anonymous classes from the jar file, but that would tie this code to Java 8 or higher. I believe there may still be some JRuby folks with legacy apps on JRuby 1.7 + Java 7. Lambdas versus anon classes would not make any performance difference here.
> Small JRuby cleanups and optimizations

- .github/workflows/check_changelog.yml
[Travis][] allows both "\<KEYWORD\> skip" and "skip \<KEYWORD\>", as does
[Circleci][]. I never remember which order the words should go in, so it
is a nice convenience if either order works.
I am skipping ci with the reversed word order on this PR to hopefully demonstrate that this still does the right thing. 🤞 
[Travis]: https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build
[Circleci]: https://circleci.com/docs/2.0/skip-build/#skipping-a-build
> Allow reversed word order for skipping changelog [skip ci]

- test/test_puma_server.rb
1. test file was leaking fd's, fixed
2. test file was rather wet.  DRY'd up
3. No new tests, no major changes
> test_puma_server.rb - clean up leaky fd's, refactor (DRY) [changelog skip]

- History.md
Stuff between `<` and `>` wasn't rendered.
> Fix-up Markdown in History.md [ci skip]

- test/test_binder.rb
ios is an `attr_reader`, so this effectively the same thing, but testing
a public method instead of reaching into the internal state of the class
being tested seems like a win to me.
> Use public ios method in test [changelog skip]

- README.md
At present, the Actions badge cannot be branch specific, unlike the Travis badge.
> README - Actions badge [skip ci]

- test/test_binder.rb
1. Add ssl_query method to allow all platforms to run non platform specific tests
2. Small refactor, rearrange tests, etc
3. No additional tests added
> test_binder.rb - refactor

- test/test_cli.rb
The `control` option was deprecated in [6d0efee9] in favor of
`control-url`
[6d0efee9]: https://github.com/puma/puma/commit/6d0efee913905c6b2b9046475cf5f18939ce6b1c
> Avoid deprecated option in test [skip changelog]

- CONTRIBUTING.md
- README.md
Closes #1880
As a recent first-time contributor to puma, these are some of the things
that might have been helpful to have in one place as I worked on my
first changes.
I am also thinking about a resources section that links to the docs
directory and to docs for libraries that might be unfamiliar to someone
looking through puma for the first time (I didn't know much about
TCPSocket, IO.pipe, nio4r, for example)
> Add contribution guide [skip ci]

- test/test_thread_pool.rb
These TODOs were added in 9f4edf4c while cleaning up the tests a bit.
For the first TODO, it looks like there was a point to those two lines: this and the previous test call `Thread.current.kill` in the thread pool block so the threads will die once some work is added. I tried to make this more obvious by starting the `auto_reap!` earlier and checking that it hasn't reaped any threads that are still alive.
For the other TODO I replaced `sleep 10` with the `Thread.pass until
finish` pattern we use in some other tests in this file. Now if `pool.shutdown(0)` fails to raise an error we finish right away rather than waiting for the 5 second ConditionVariable timeout. I also added an assertion to ensure we rescue the `ForceShutdown` error.
> Address thread pool test TODOs [changelog skip]

- History.md
- lib/puma/control_cli.rb
- test/helpers/config_file.rb
- test/test_config.rb
- test/test_pumactl.rb
This PR:
- removes the default environment of `development` from `pumactl`
- defaults to development when searching for config files to load, if one is not provided to `pumactl`
- passes the value passed to the `environment` option over `RACK_ENV` to `pumactl`, if provided
fixes #2023
> Update pumactl to remove development as default environment

- ext/puma_http11/extconf.rb
This fix allows Puma to build when one is starting with a fresh MSYS2 installation.
Ubuntu on Actions is using gcc 7.4.0, MSYS2/MinGW is using 9.2.0.  The changes are currently just used on MinGW.
> extconf.rb - fix for new gcc on MingW

- docs/tcp_mode.md
Document in short launching Puma in the TCP mode
Description may be loo long so please let me know if it should be moved to some other place, e.g. `docs` directory.
Related issue https://github.com/puma/puma/issues/1937
> [README] Add section about TCP mode [changelog skip]

- History.md
- lib/puma/binder.rb
- lib/puma/minissl/context_builder.rb
- lib/puma/runner.rb
- test/helpers/ssl.rb
- test/test_binder.rb
- test/test_cli.rb
This PR includes two commits, one for the refactor and one for the change. I can open two separate PRs if it is easier to review that way.
---
This commit extracts the `MiniSSL::Context` creation into its own
`MiniSSL::ContextBuilder` class along the same lines as in #1989.
This will allow us to reuse this code for adding SSL support to the
control app (issue #2015). Since we will need the `MiniSSL` require
and check in both places, I moved that into the `ContextBuilder` class
as well.
----
This starts to address #2015. I think we will need to add SSL support
to the control cli as well.
> Add SSL support for the control app

- History.md
- lib/puma/control_cli.rb
Fixes closing of file stream when reading pid from pidfile - closes https://github.com/puma/puma/issues/1985
> Close file stream when reading pid from pidfile

- .github/pull_request_template.md
Point to the "blob" on master, so that the link is clickable from the PR
I tried to use the links, and the links were ineffective.
This PR updates the PR template to make the links point directly to the documents.
> PR template: link to contributing, changelog

- History.md
- lib/puma/cli.rb
- test/test_cli.rb
There was a `c` here, and it seemed, out of place.
```ruby
o.on "--extra-runtime-dependencies GEM1,GEM2", "Defines any extra needed gems when using --prune-bundler" do |arg|
c.extra_runtime_dependencies arg.split(',')
end
```
Comparing with `--prune_bundler`, which was mentioned next to this long option, we could try using `user_config` instead.
> Fix typo "c" -> "user_config" for --extra_runtime_dependencies

- .github/pull_request_template.md
My other PR failed the CI check, because the template directs contributors to add `[skip ci]` to the commit message, but it's checking the PR title. I figured the check was correct and the template was in need of an update, but I can see how the reverse might be true, so feel free to close this PR if that is the case.
> PR template Directs Contributors to add "[skip ci]" to PR title

- test/test_pumactl.rb
The `pathname` lib was missing from requirements in `test/test_pumactl.rb` file. This file was failing when ran alone.
Before:
```
20:09:39 ❯ ruby -Ilib test/test_pumactl.rb
Run options: --seed 18025
...EE...
Fabulous run in 0.133826s, 59.7790 runs/s, 119.5581 assertions/s.
1) Error:
TestPumaControlCli#test_default_config_file_exist:
NameError: uninitialized constant TestPumaControlCli::Pathname
test/test_pumactl.rb:29:in `with_config_file'
test/test_pumactl.rb:95:in `block in test_default_config_file_exist'
/home/sebastien/Projects/puma/test/helpers/config_file.rb:10:in `with_env'
test/test_pumactl.rb:94:in `test_default_config_file_exist'
2) Error:
TestPumaControlCli#test_environment_specific_config_file_exist:
NameError: uninitialized constant TestPumaControlCli::Pathname …
```
> add missing require in spec

- History.md
- lib/puma/control_cli.rb
- test/test_pumactl.rb
If I have a server running:
```sh
bundle exec bin/puma test/rackup/hello.ru \
--control-url="ssl://127.0.0.1:9000?key=examples/puma/puma_keypair.pem&cert=examples/puma/cert_puma.pem" \
--control-token="token"
```
This commit will allow me to restart that server (or run any other
control cli command) with:
```sh
bundle exec bin/pumactl restart \
--control-url="ssl://127.0.0.1:9000" \
--control-token="token"
```
Before this commit the pumactl restart command would have raised an
error: `"Invalid scheme: ssl"`
> Add ssl support to the control_cli

- .travis.yml
Closes: https://github.com/puma/puma/issues/2064
Ruby 2.2 doesn't accept this literal with a warning in the Travis build:
```
ruby: warning: unknown argument for --enable: `frozen-string-literal'
```
Ideally I'd prefer to have this as a global variable and add an exception for Ruby 2.2 in case there are more versions added later on. But looking at the docs doesn't seem like there is a way to do that: https://docs.travis-ci.com/user/environment-variables/#global-variables.
> do not set frozen-string-literal env var for ruby 2.2 [changelog skip]

- .travis.yml
just fix a few mistakes
- truffle wasn't actually tested https://github.com/puma/puma/pull/2065
- javaopts were misplaced at allowed failures
- update jruby to 9.2.9.0
- [ x ] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ x ] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` to all commit messages.
- [ x ] I have added appropriate tests if this PR fixes a bug or adds a feature.
- [ x ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ x ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ x ] If this closes any issues, …
> travis fixes [changelog skip]

- History.md
- lib/puma/app/status.rb
- lib/puma/control_cli.rb
- lib/puma/launcher.rb
- test/test_cli.rb
- test/test_integration_cluster.rb
- test/test_integration_single.rb
- test/test_launcher.rb
Completes 1 of 2 items from #1964
This commit adds an endpoint to the status app to print thread
backtraces, and control cli command to call that endpoint.
I tried this locally by starting a server with:
```sh
bundle exec bin/puma test/rackup/hello.ru \
--control-url="unix://test.sock" \
--control-token="token"
```
and then printing the backtraces with:
```sh
bundle exec bin/pumactl thread-backtraces \
--control-url="unix://test.sock" \
--control-token="token"
```
> Add pumactl command to print thread backtraces

- History.md
- README.md
- lib/puma/configuration.rb
- lib/puma/control_cli.rb
- test/test_cli.rb
- test/test_config.rb
- test/test_pumactl.rb
This PR changes configuration defaults.
The **default value for environment** is also read from `RAILS_ENV`, if `RACK_ENV` can't be found.
See #1949
The goal of that Issue is that configuration defaults in [puma/puma-heroku](https://github.com/puma/puma-heroku/blob/master/lib/puma/plugin/heroku.rb) move into [lib/puma/configuration.rb](https://github.com/puma/puma/blob/master/lib/puma/configuration.rb).
> Configuration: Get environment from RAILS_ENV, too

- lib/puma/launcher.rb
Before this commit the SIGINFO thread backtraces looked like:
```
Thread: TID-owjccjjvw puma reactor
/path/to/puma/reactor.rb:136 in 'select'
/path/to/puma/reactor.rb:136 in 'run_internal'
/path/to/puma/reactor.rb:313 in 'run_in_thread'
Thread: TID-owjccjjrg puma threadpool reaper
/path/to/puma/thread_pool.rb:262 in 'sleep'
/path/to/puma/thread_pool.rb:262 in 'block in start!'
```
This format can make it a bit difficult to see where one backtrace ends
and the next begins. This commit indents the backtrace lines for clearer
visual separation.
```
Thread: TID-owjccjjvw puma reactor
/path/to/puma/reactor.rb:136 in 'select'
/path/to/puma/reactor.rb:136 in 'run_internal'
/path/to/puma/reactor.rb:313 in 'run_in_thread'
Thread: TID-owjccjjrg puma threadpool reaper …
```
> Indent SIGINFO thread backtraces [changelog skip]

- History.md
It looks like something went awry with the changelog in https://github.com/puma/puma/pull/2022/files
> Remove duplicate entry from changelog [ci skip]

- test/test_web_server.rb
Closes #2049
Before this commit, `test_trickle_attack` and
`test_file_streamed_request` were each taking an extra 20 seconds to run.
Without the `Connection: close` header, the [connection was kept
alive][keep alive] until it timed out after the
[`PERSISTENT_TIMEOUT`][PERSISTENT_TIMEOUT] duration of 20 seconds.
[keep alive]: https://github.com/puma/puma/blob/3835ac74dec5511d637cbc4ebc140c3b8632b447/lib/puma/server.rb#L706-L708
[PERSISTENT_TIMEOUT]: https://github.com/puma/puma/blob/3835ac74dec5511d637cbc4ebc140c3b8632b447/lib/puma/const.rb#L109-L111
> Close connection in web server tests [skip changelog]

- ext/puma_http11/puma_http11.c
I was just trying to familiarize myself a bit with puma and was trying to track down the usage of the code behind the `if defined(HAVE_QSORT_BSEARCH)`. Looks like it was added back to mongrel in https://github.com/engineyard/mongrel/commit/cd44d2ebc79986933a641b026265867280bf82ea and then added to puma in https://github.com/puma/puma/commit/7c9d988d4de2e08d67f95ca209196427fd89c9af but I don't see it being used.
Looks like it was removed form the Unicorn web server in https://bogomips.org/unicorn.git/commit/?id=9625ad39b73d3d1443ff097e9113d1ec9c9d5f00
Of course this isn't a super helpful change if there's plans to move from the c extension entirely (#1889)..
It doesn't look like there was any test coverage so I didn't add/remove there, but not skipping CI since it is a code change.
> http11: Remove qsort code paths [changelog skip]

- History.md
- lib/puma/app/status.rb
- lib/puma/cluster.rb
- lib/puma/single.rb
- test/test_app_status.rb
- test/test_cli.rb
Having access to the hash allows to produce stats in other ways (such as StatsD) without having to parse JSON of data that is available in memory. Examples of this workaround are:
- https://github.com/yob/puma-plugin-statsd/blob/fa6ba1f5074473618643ef7cf99747801a001dec/lib/puma/plugin/statsd.rb#L112-L114
- https://github.com/appsignal/appsignal-ruby/pull/488/files#diff-72a8958f52e3339e140e6434a391eba0R49
- https://gitlab.com/gitlab-org/gitlab-foss/blob/2c72668c3bd2838ff101815259d0bb704e845493/lib%2Fgitlab%2Fmetrics%2Fsamplers%2Fpuma_sampler.rb#L29
Changed `Puma.stats` to `Puma.stats_json` to help disambiguate. An alias is provided for backwards compatibility. In a new major release `Puma.stats` could point to the hash version or be removed altogether.
> Puma.stats is now a hash, not JSON.

- .travis.yml
- History.md
- lib/puma/cluster.rb
Rub 2.7.0 introduced `GC.compact` which allows manual compaction of Ruby slots. A good time to do this is before forking so that memory fragmentation can be reduced. 
- https://www.ruby-lang.org/en/news/2019/12/17/ruby-2-7-0-rc1-released/
- https://www.youtube.com/watch?v=1F3gXYhQsAY
One issue with memory fragmentation when forking is that while a page in memory might have only one free slot, as that slot is written to after fork, the entire page is written so the benefit of CoW optimizations are greatly reduced. Manually compacting GC reduces the number of pages with empty slots.
This PR manually compacts memory right before Puma forks and after other `before_fork` hooks are called.
> Manually compact GC before fork

- History.md
- lib/puma/plugin.rb
I've been working on adding Puma instrumentation to our internal metrics gem. By reading the plugin code I got it to work in a way we want (no configuration required to enable the plugin from the gem) but I noticed I had to pass a slightly confusing `loader` argument when initializing the plugin.
In the current version of the gem, strangely enough the `Plugin` class is passed as loader, while it happens inside the `PluginLoader` class:
https://github.com/puma/puma/blob/b646fc522337c3c506399e68c0dab034ab98d4fc/lib/puma/plugin.rb#L13
this seems to have been an error made during refactoring in 33e0fa9999de17e85ed7e064d5f8ede8dc009014 as the original implementation made more sense:
https://github.com/puma/puma/blob/663666c5b775fd8224e2acb51399b34d907d753e/lib/puma/plugin_loader.rb#L11
but …
> Remove unused loader argument from Plugin initializer

- .github/workflows/ruby.yml
Using RVM to install 2.3.8 like RubyGems does: https://github.com/rubygems/rubygems/blob/v3.1.2/.github/workflows/ubuntu-rvm.yml
...with OpenSSL 1.0.2 like @MSP-Greg says: #2087 (comment)
> GitHub Actions no longer have Ruby 2.3.x, checkout w/RVM [changelog skip]

- History.md
- lib/puma/configuration.rb
The original implementation is 8 years old from commit 47f76712. I'm guessing it partially reimplemented Ruby's SecureRandom [from that time](https://github.com/ruby/ruby/blob/fb99416115e8e48e6ac8aefefa6221cf572024ad/lib/securerandom.rb) to provide the fallback to using `Kernel#rand` in case the CSPRNG is unavailable. I'm removing it since I don't believe this is very common and I don't think it is Puma's job to fix a broken system.
> Simplify random_token and remove insecure fallback

- lib/puma/client.rb
- This is a documentation edge-case
#1754 mentions a docs edge-case where JRuby versions of methods are defined with the same name - and docs tools have a hard time with that.
Fixes #1754
I could not spy any other conditional JRuby-related methods that had the same name as Ruby ones.
> Add a jruby_-prefixed method alias to conditional method [changelog skip] [ci skip]

- README.md
In https://puma.io/puma/index.html#configuration, when you click to `test`, it's shows bad link (404 not found) same with attachment image.
> [changelog skip][ci skip] Fix 404 link, bug in htpps://puma.io/puma/index.html

- History.md
- lib/puma/cluster.rb
- lib/puma/server.rb
- lib/puma/single.rb
- test/test_cli.rb
- test/test_web_server.rb
For monitoring purpose and in order to create a puma worker killer style plugin (which restart workers after 10k requests) I need to add instrumentation for requests count
I have not yet added test nor the entry in HISTORY.md as I want to be sure this PR wont be rejected before working on this.
> Instrument requests count

- .github/workflows/ruby.yml
Revisions to Actions workflows.
1. All OS's test on Ruby 2.3 thru master/head.  Previously, many master/head builds were not fully tested.  As currently set up, all are fully tested.
2. Bundler is pre-installed on all builds, so it is no longer installed/updated.  Because of that, 'frozen string' does not work in older Rubies.  Added conditional steps to only add 'frozen string' where it will pass.
3. There are several places in the GitHub UI where lists of jobs appear.  I reformatted the string shown to hopefully make it not truncated in any of those places...
4. All OS's (including Windows) can have Ruby 2.2 added, but it is currently failing.  Not sure if it's code or tests.  Another PR can fix that.
5. Puma does compile and test successfully with a Windows mswin build, but changes are …
> Split ruby.yml, revise Actions, all OS's test from 2.3 thru master/head [changelog skip]

- History.md
- lib/rack/handler/puma.rb
- test/test_rack_handler.rb
Remove setting quiet in user settings by default
Closes `#2074`
> remove setting quiet requests inside puma rack handler

- puma.gemspec
Standard Windows Rubies have a mechanism to load the OpenSSL package when installing Puma.  This is done via the gemspec's metadata["msys2_mingw_dependencies"] item.
The MSYS2 package manager only allows installation of the most recently released package, which is currently OpenSSL 1.1.1d.  Windows Ruby 2.4.x builds with OpenSSL 1.0.2.
> puma.gemspec metadata["msys2_mingw_dependencies"]  [changelog skip]

- History.md
- lib/puma/client.rb
- lib/puma/server.rb
- test/test_puma_server.rb
Return a 408 Request Timeout response based on `first_data_timeout` when `queue_requests` is disabled, matching the behavior for when `queue_requests` is enabled (the default).
> Send 408 request timeout even when queue requests is disabled

- History.md
- lib/puma/binder.rb
- lib/puma/runner.rb
Simplifies some code in `Runner#start_control` by reusing similar logic from `Binder#parse`.
~Besides simplifying code, this fixes a bug/issue where a Unix socket created for a control server (e.g., `--control-url unix://control.sock`) was not being properly removed on server shutdown.~
~This is because `Binder#parse` additionally adds its urls to `@listeners`, which allows them to be automatically cleaned up by `Binder#close_listeners` when the server shuts down.~
(Properly fixing the control-socket cleanup issue requires additional code changes not in this PR, but this simplification makes the fix easier to apply.)
> Simplify Runner#start_control URL parsing

- History.md
- lib/puma/client.rb
- test/test_puma_server.rb
Rescue `IO::WaitReadable` instead of `EAGAIN` on calls to `read_nonblock` when a blocking read would occur.
On Windows, `read_nonblock` raises `Errno::EWOULDBLOCK`, which is a different value on this platform from `Errno::EAGAIN`. Both of these errors are extended by `IO::WaitReadable`, which is Ruby's recommended exception class for retrying `read_nonblock`.
I've included a test `test_open_connection_wait_no_queue` which [fails on windows](https://github.com/wjordan/puma/runs/458869490) without this PR applied.
> Rescue IO::WaitReadable instead of EAGAIN for blocking read

- lib/puma/binder.rb
- lib/puma/launcher.rb
- lib/puma/minissl.rb
- lib/puma/server.rb
- test/test_cli.rb
- test/test_events.rb
- test/test_puma_server.rb
- test/test_puma_server_ssl.rb
- test/test_rack_handler.rb
- test/test_rack_server.rb
- test/test_web_server.rb
This work starts the effort of removing connected_port. 
Referencing this issue:
https://github.com/puma/puma/issues/1996
I have moved the code around a bit to get all connected_ports, the tests seem
to pass in the appropriate areas.
I want to verify this path before attempting to remove all UniquePort calls in
the tests.
@nateberkopec Also, I wanna talk about removing UniquePort, as it seems like it is being used for some CLI specs and the `control-url`. Is that approriate? Do we expect to be able to pass `0` in as the port for the control and be able to get it's connected port?
> Removes connected_port, implements connected_ports

- History.md
- lib/puma/const.rb
- lib/puma/server.rb
- test/test_puma_server.rb
+ Fixes a problem in 4.3.2/3.12.3 where we were not splitting newlines in headers according to Rack spec
+ Fixes another vector for HTTP injection - early hints
Closes #2132
> HTTP Injection - fix bug + 1 more vectors

- .travis.yml
This PR updates the CI matrix to use latest JRuby, **9.2.11.0**.
[JRuby 9.2.11.0 release blog post](https://www.jruby.org/2020/03/02/jruby-9-2-11-0.html)
> CI: Use jruby-9.2.11.0

- .github/workflows/ruby.yml
- .travis.yml
- lib/puma/binder.rb
- lib/puma/server.rb
Note that Ruby 2.2 needs a RubyGems update to pass.
Closes https://github.com/puma/puma/issues/2145
> Fix two Ruby 2.2 issues, add to Actions & remove from Travis [changelog skip]

- test/test_rack_handler.rb
A file_log_requests_config variable was assigned but not used, resulting in a warning.
The variable has been removed.
An extra test has been added to show the default log_request config when no file
is present.
Closes #2135
> Remove unused file_log_requests_config variable [changelog skip]

- lib/puma/launcher.rb
Build seems to be having some temporary issues re: Windows downloads, but I think otherwise this is good.
> Use with_unbundled_env for Bundler 2.1+

- test/test_integration_single.rb
`curl` error message could be localized in tests because of not-English locale. It leads to failing the specs. The solution is just to force default (English) locale with `LC_ALL=C`.
Closes #2149.
> Force curl to output error messages in English locale in tests (#2149) [changelog skip]

- .github/workflows/ruby.yml
GitHub has not intentionally installed MSYS2/MinGW tools on their Windows images.  Hence, what they unintentionally installed is out of date.  The MSYS2 servers are having issues, possibly from the Actions CI traffic updating the out of date tools...
Temporary fix for Actions CI issues on Windows.  I'll revert when...
1. Removes updating MSYS2/MinGW gcc tools
2. Remove  Ruby 2.3, as it won't compile jaro-winkler (RuboCop dependency) without the updated gcc
3. Ruby 2.5 thru master still need to download the MSYS2/MinGW OpenSSL 1.1.1 package.  Hopefully, it will work...
This did pass in my fork twice...
> Temp fix for Actions Windows CI [changelog skip]

- test/test_config.rb
Don't show a message 
```
Parsing options from the first comment line is deprecated!`
```
when run tests:
```shell
bundle exec m test/test_config.rb:11
Run options: -n "/^(test_app_from_rackup)$/" --seed 35517
Parsing options from the first comment line is deprecated!
.
Fabulous run in 0.007740s, 129.1990 runs/s, 129.1990 assertions/s.
```
Closes #2158
Since Rack 2.2.0 specifying options in magic comments in a rackup file is deprecated ([Changelog](https://github.com/rack/rack/blob/master/CHANGELOG.md#220---2020-02-08), https://github.com/rack/rack/pull/1574)
Not sure whether we need the `test_app_from_rackup` test at all. At least we can hide the deprecation message.
> Suppress Rack deprecation warning in specs [changelog skip]

- .github/workflows/ruby.yml
- test/test_puma_server_ssl.rb
1. Actions CI - Via a new action, Windows gcc is now being updated again.  This is the gcc that a typical new Windows install would have.  It also allows Ruby 2.3 to be added back into the CI, which was removed in PR https://github.com/puma/puma/pull/2157.  The new action pulls all the MSYS2 packages from a GitHub release, so the current server issues won't be a problem.
2. Actions CI - There were several pairs of conditional steps. Removed them by moving the logic into script.  The first line of script is a brief comment re the reason for the conditional, which appears in the step log.
3. Added `RUBYOPT` in the test 'header'.
As mentioned elsewhere, once GitHub adds MSYS2 to their Windows images, I'll update as needed...
> Show RUBYOPT in test 'header', use setup-ruby-pkgs in Actions CI [changelog skip]

- History.md
- lib/puma/cluster.rb
- lib/puma/configuration.rb
- lib/puma/launcher.rb
- test/test_config.rb
Suppress exceptions in user defined hooks (like `on_worker_boot`). We have just to rescue and log them.
Example of logged message:
```
WARNING hook on_restart failed with exception (RuntimeError) Error from hook
% Traceback (most recent call last):
14: from /Users/andrykonchin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest/parallel.rb:33:in `block (2 levels) in start'
13: from /Users/andrykonchin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:1026:in `run_one_method'
12: from /Users/andrykonchin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest/test.rb:93:in `run'
11: from /Users/andrykonchin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest/test.rb:211:in `with_info_handler' …
```
> Catch exceptions in hooks defined by users

- test/test_redirect_io.rb
I noticed that there weren't any tests for what is supposed to happen when `puma` receives the `SIGHUP` signal. #561 was the PR that introduced the behavior. I didn't really understand what the use case was at first, but [an issue on a unrelated project](https://github.com/influxdata/telegraf/issues/5128) gave a good explanation for why this functionality is desirable.
> [changelog skip] Backfill tests for stdout/stderr redirection on SIGHUP

- test/test_puma_server_ssl.rb
`OpenSSL::SSL::SSLContext#min_version=` and `OpenSSL::SSL::SSLContext#max_version=` are broken on JRuby.
The methods may be called in OpenSSL code or net/http code.  The test may call it in a client used for testing.
> test_puma_server_ssl.rb - fix for JRuby OpenSSL::SSL::SSLContext bug [changelog skip]

- test/test_preserve_bundler_env.rb
- test/test_puma_server_ssl.rb
Skip teardown if setup was skipped in test_preserve_bundler_env
* Otherwise we get
puma/test/helpers/integration.rb:27: warning: instance variable @ios_to_close not initialized
puma/test/helpers/integration.rb:34: warning: instance variable @bind_path not initialized
See https://travis-ci.org/github/puma/puma/jobs/662767158#L469
* Same pattern as in test/test_integration_cluster.rb.
> Fix warnings for !HAS_FORK [changelog skip]

- History.md
- lib/rack/handler/puma.rb
- test/test_rack_handler.rb
Rack has opted to use the double splat operator for options.
See: https://github.com/rack/rack/commit/871c82f0ffa269d7e2e237d3ade9a1eac26418fe
> Update Rack::Handler::Puma.run method options param

- History.md
- docs/signals.md
- lib/puma/launcher.rb
- test/test_integration_cluster.rb
https://github.com/puma/puma/pull/1320 added support for using SIGINFO,
but this is only available on BSD-based systems. SIGWINCH is on Linux.
> Use SIGWINCH to print thread backtraces

- .github/workflows/ruby.yml
- History.md
- lib/puma/minissl.rb
- test/helper.rb
- test/shell/run.rb
- test/shell/t1.rb
- test/shell/t2.rb
- test/shell/t3.rb
- test/test_integration_pumactl.rb
- test/test_redirect_io.rb
- test/test_thread_pool.rb
This PR improves the reliability of tests and as a result all tests now pass on TruffleRuby.
One extra fix was needed in TruffleRuby (https://github.com/oracle/truffleruby/commit/2e046e4400c10c3ed19d2bd14e75741d21d54931).
A major part of getting TruffleRuby to pass Puma's tests was by done by Shopify contributors to TruffleRuby (especially the signal stuff).
Since tests pass on TruffleRuby, I also moved TruffleRuby along with other tested versions in CI, so failures are no longer ignored.
I ran the CI twice in GitHub Actions and it passed in both cases.
cc @chrisseaton @nateberkopec
> Run tests on TruffleRuby, all tests pass now

- History.md
- lib/puma/control_cli.rb
Most sockets are closed in gc, but we should try to close all of them in code.
Change closes the TCP connection, previously it wasn't.
> control_cli.rb - improve ssl connection shutdown

- History.md
- lib/puma/server.rb
- test/test_puma_server.rb
This is a follow on from the suggestions in https://github.com/puma/puma/pull/2182#issuecomment-603638985. I did not make the change around `DefaultLowlevelErrorHandler`, because:
https://github.com/puma/puma/blob/0b737cce42746d8226701520f35685e0624e061b/lib/puma/server.rb#L819-L823
The `leak_stack_on_error` option is stored on the server instance and not options, which leaves no way of getting that data into the handler. I wasn't a fan of passing that through, and reorganizing how `leak_stack_on_error` works also felt out of scope.
Functionality wise, there's no changes besides thread shutdown now goes through lowlevel error handler and we pass `status` to the handler based on arity. If `leak_stack_on_error` …
> Handle thread shutdown responses via low level error messages

- .github/workflows/ruby.yml
- test/test_thread_pool.rb
See https://github.com/puma/puma/runs/553627446 and https://github.com/oracle/truffleruby/issues/1984
The CI fails recently due to `ruby/setup-ruby` defaulting to latest Bundler (= 2) by default.
The failures are rather unclear so I suggest to stick to Bundler 1 to keep CI green, and then investigate what goes wrong with Bundler 2.
> Fix the CI [changelog skip]

- History.md
- lib/puma/server.rb
- test/test_puma_server.rb
When running with `queue_requests=false`, the server closes the connection after each request. However, the server would indicate via the `Connection` header that the connection would be persisted. This was happening because the headers got reported in `handle_request`, _before_ the check to `@queue_requests` in `process_client` forces the connection to be closed. This PR moves the check to be in `handle_request` - this ensures that what the server reports in the headers, and what it actually does with the connection can't get out of whack.
Specifically the behaviour that we want here is:
- for HTTP/1.0, omit the `Connection` header
- for HTTP/1.1, setting `Connection: closed`. This is required by https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html, specifically:
`HTTP/1.1 …
> Set `Connection: closed` when running without request queueing

- History.md
- lib/puma/client.rb
- lib/puma/reactor.rb
- lib/puma/server.rb
- test/test_puma_server.rb
Fixes a concurrency bug during server shutdown when `queue_requests` is enabled (the default), which can can be minimally reproduced by the following sequence:
- s1 and s2 both open client connections
- s1 sends a request
- server shutdown is triggered (but does not complete while s1's request is still in process)
- s2 sends a request
Expected: s2 receives a successful response
Actual: s2 receives a 500 response
Here is the test implementation, currently failing on `master`: https://github.com/puma/puma/blob/17af6cfa8a2fa245b2153479448f54505e7b5de4/test/test_puma_server.rb#L771-L788
The underlying issue is that in a 'graceful' shutdown, the server stops accepting connections and the thread pool stops accepting new work while it waits up to `force_shutdown_after` seconds to finish …
> Pass queued requests to thread pool on server shutdown

- History.md
- lib/puma/cluster.rb
- lib/puma/server.rb
- lib/puma/single.rb
- test/test_cli.rb
- test/test_launcher.rb
Refactoring PR to simplify the cluster worker stats code using `JSON.parse` and `.to_json` in place of regex-parsing and string interpolation.
Also includes refactoring of duplicated server-stats logic into a `Server#stats` method.
> JSON parse cluster worker stats instead of regex

- History.md
- lib/puma/thread_pool.rb
- test/test_thread_pool.rb
This PR refactors some tricky concurrency parts of `TestThreadPool`, in order to make the unit tests more stable (all tests pass on jruby), faster (no more 1-second sleeps), and a bit more readable. Many of the tests now use a subclass of `ThreadPool` that overrides `#<<` to wait on the existing `@not_full` condition variable, to ensure work begins executing on a worker thread before continuing the test.
There are also some small changes to the `ThreadPool` class itself:
- Add `#with_mutex` to make it easier to chain multiple `@mutex.synchronize`-wrapped methods together, and to extend existing mutex-wrapped methods in unit tests.
- Wait for initially-spawned threads to enter the wait loop before returning from `#initialize`. This fixes a subtle edge-case concurrency bug mostly affecting …
> ThreadPool concurrency refactoring

- History.md
- lib/puma/const.rb
- lib/puma/server.rb
- lib/puma/thread_pool.rb
- test/test_puma_server.rb
Fixes #2177. (Thanks @GuiTeK for tracking down this bug!)
Modifies the `out_of_band` hook implementation in the `Server` class to ensure that hooks are fired as expected when the server is configured with >1 max threads.
Compare to #2178, #2180. This implementation is pretty simple. It changes behavior slightly by executing the hooks on the same thread that finished processing the last request (instead of the main acceptor thread), so the server can continue accepting incoming requests if any arrive while the out-of-band hooks are still executing.
I've also added a couple of server tests to ensure out-of-band hooks fire as expected in two scenarios (sequential and parallel requests).
> Fix out_of_band hook

- Gemfile
- History.md
- lib/puma/dsl.rb
- lib/puma/thread_pool.rb
- test/helper.rb
- test/test_puma_server.rb
- test/test_thread_pool.rb
Fixes up `ThreadPool#shutdown` so that the provided `timeout` value (which corresponds to the `force_shutdown_after` configuration option) is more accurate, and can be set as a float instead of just an integer value.
Previously, the shutdown timeout ran a loop `timeout.times`, which called `t.join 1` on each thread (one after another, not parallel), followed by a `sleep 1` each loop iteration, then `t.join SHUTDOWN_GRACE_TIME` on each thread after raising `ForceShutdown`. Instead of forcing shutdown in `timeout` (+ `SHUTDOWN_GRACE_TIME`) seconds, this forced a shutdown in `timeout * (n + 1)` (+ `n * SHUTDOWN_GRACE_TIME`) seconds (where `n` is the number of running threads). The updated code fixes this by joining a maximum of `timeout` seconds (followed by a maximum of `grace` seconds) …
> Fix ThreadPool#shutdown timeout accuracy

- History.md
- test/helper.rb
- test/minitest/verbose.rb
- test/minitest/verbose_progress_plugin.rb
Adds a Minitest plugin to fix verbose progress reporting when running parallel tests.
The default verbose progress reporter interleaves results when test are executed in parallel threads (e.g., in test classes containing `parallelize_me!`), making the printed results entirely useless because the duration/results printed no longer correspond to the correct test names. This made it impossible to debug slow/hanging tests in the CI output and has probably caused all sorts of confusion.
The plugin fixes this by printing `…` when another test starts in parallel, and re-prints the test name along with the result when the test finishes.
For example, [a CI failure on this PR](https://github.com/wjordan/puma/runs/586788575) had a test hang, causing the CI action to time out after 10 minutes. The …
> Support parallel tests in verbose progress reporting

- .github/workflows/check_changelog.yml
- .github/workflows/puma.yml
Should make the experience looking at the checks more consistent  (noticed this from https://github.com/puma/puma/pull/2227#issuecomment-616841613)
The [contains method] is documented as case insensitive so this should be equivalent to what we had.
Add support for skipping the tests with `[skip ci]`.
[contains method]: https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contains
> Do not run the check changelog workflow if skipped [skip ci]

- History.md
- lib/puma/configuration.rb
The usage of `||` fetch is incorrect, as presence of `false` is the correct value.
This change uses `default` value, only if the value is nowhere else defined.
> Fix `UserFileDefaultOptions#fetch` to properly consume `default` value

- lib/puma/control_cli.rb
- test/test_pumactl.rb
This change adds tests for the scenario where the `ControlCLI` exits with an `exit(1)` when:
1. No command is issued to the `ControlCLI`.
2. An invalid command is issued to the `ControlCLI`.
Furthermore, while working on adding the tests, I realized that the CLI could do an early exit when the supplied command is empty/invalid, before waiting to load config and then issuing an `exit` (the loading of `config` options would eventually turn out to be an unnecessary step when the command is invalid or empty).
So I have moved the piece of code that issues the `exit(1)` to before the config is loaded.
> [changelog skip] Add tests for ControlCLI when the supplied command is invalid or empty

- History.md
- lib/puma/dsl.rb
- lib/puma/launcher.rb
- lib/puma/state_file.rb
- test/test_launcher.rb
Before this commit, it was possible that the puma.state file would be world-readable which may not be desirable in production environments. This introduces a new optional configuration option to set desired state file permissions.
```console
<snip>
....................................................................................................................................S.....................S.....S.....S..........................................................................................................................................................S........
Fabulous run in 115.014845s, 2.8692 runs/s, 7.3643 assertions/s.
330 runs, 847 assertions, 0 failures, 0 errors, 5 skips
You have skipped tests. Run with --verbose for details. …
```
> Add optional state file permissions

- .github/workflows/check_changelog.yml
I did this on the rate limit throttle repo and it works https://github.com/zombocom/rate_throttle_client/blob/e9ecec60802d8a0d85904e61dc975c61e9f19de0/.github/workflows/check_changelog.yml#L2-L4
> [ci skip] Allow changelog check to run on edit

- History.md
- lib/puma.rb
- puma.gemspec
- test/test_cli.rb
- test/test_integration_cluster.rb
- test/test_launcher.rb
The change in #2086 is not backwards compatible with existing gems that parse the output of Puma.stats such as Barnes.
Releasing a version of puma with this change would break anyone using the Barnes app and only in production. I'm proposing to keep the existing interface and instead add a new API. This buys us all the features of #2086 without causing any production facing downtime by customers due to API incompatibilities.
Unfortunately, it requires that we serialize and then de-serialize the values. One prior benefit of returning json in a string was that it allowed an end-user to de-serialize using a faster json algorithm such as `oj` via the "multi json" gem. But the performance penalty will be better than a stability break.
> Revert api change from #2086 introduce Puma.stats_hash api

- History.md
- docs/fork_worker.md
- docs/signals.md
- lib/puma/app/status.rb
- lib/puma/cli.rb
- lib/puma/cluster.rb
- lib/puma/control_cli.rb
- lib/puma/dsl.rb
- lib/puma/server.rb
- test/helpers/integration.rb
- test/test_integration_cluster.rb
This is still rather experimental, but I thought I'd share this work in progress to share preliminary results and spark discussion on whether this optimization seems at all interesting to anyone else to pursue further.
This PR adds a config option (`fork_worker`) to spawn new worker processes by forking an existing worker process instead of the master process. It also adds a `refork` command (currently implemented via a `URG` signal) which re-forks all processes in the cluster from this original worker.
Because the existing worker has been serving live requests, forking new workers from this fully-loaded process can potentially reduce memory usage by further optimizing copy-on-write performance across processes, as a step beyond what the `preload_app!` directive accomplishes at …
> Experiment: Fork from existing worker process to optimize copy-on-write performance

- History.md
- benchmarks/wrk/cpu_spin.sh
- lib/puma/dsl.rb
- lib/puma/server.rb
- lib/puma/thread_pool.rb
- test/config/cpu_spin.rb
- test/helper.rb
- test/test_busy_worker.rb
**Describe the bug**
We at GitLab.com are production testing Puma with prepartions for switching to it.
However, we noticed a few oddness when running Puma vs Unicorn in mostly similar configurations.
An worker of Puma when running in Cluster mode has no knowledge about siblings and their utilisation. This results in some of the sockets to be accepted by sub-optimal workers, that are already processing requests. This does have a statistical significance as in my local testing, and GitLab.com testing in the above workload we see an increase of around 20-30% of durations on P60%. Which is a significant increase.
**Capacity of Puma**
Capacity of Puma web-server is defined by `workers * threads`. Each of these
form a slot that can accept a new request. It means that each slot can accept
a new …
> Inject small delay for busy workers to improve requests distribution

- 5.0-Upgrade.md
- History.md
- lib/puma/cli.rb
- lib/puma/cluster.rb
- lib/puma/dsl.rb
- lib/puma/thread_pool.rb
- test/test_integration_cluster.rb
- test/test_integration_single.rb
- test/test_puma_server.rb
Reduce memory usage in preloaded cluster-mode apps by GCing before
fork and compacting, where available.
> Added `nakayoshi_fork` option.

- History.md
- lib/puma/server.rb
- test/test_puma_server.rb
The server accept loop currently has two `rescue` clauses: https://github.com/puma/puma/blob/5a4e744e8a96cbdfd10d5a5c1fe04f479bdd7f88/lib/puma/server.rb#L293-L302
- The `SystemCallError` clause is overly broad, since it would swallow any system failures that would be useful to log as errors (e.g., `EMFILE` which is thrown when the process can't create another file-descriptor);
- The `Errno::ECONNABORTED` clause is unreachable, because it's a subclass of `SystemCallError`. Even if it were reachable, `io.close` is the wrong handler (because `ECONNABORTED` would only ever be thrown by `accept_nonblock` so `io` would always be `nil`).
This PR refactors this code to rescue `IO::WaitReadable` narrowly around the call to `accept_nonblock`, which should be more accurate and more readable as well: …
> Refactor error handling in server accept loop

- lib/puma/events.rb
This changes the error when an HTTP parse error is encountered so it outputs a single line to the error log. Our logging system (Loggly) expects a single line per error, and it doesn't support filtering the second line (`---`) as it contains special characters. As discussed in #986 we experience these errors often on AWS, so is causing a lot of noise for us.
> Change parse error to output a single line log [changelog skip]

- History.md
- ext/puma_http11/mini_ssl.c
- lib/puma/minissl.rb
- test/test_puma_server_ssl.rb
Closes https://github.com/puma/puma/issues/2115
> Fix rejecting HTTP requests when TLS1.3 is used by server

- test/test_redirect_io.rb
Fix teardown
Stops:
warning: instance variable @old_err_file_path not initialized
warning: instance variable @old_out_file_path not initialized
> test_redirect_io.rb - fix teardown for skipped tests [changelog skip]

- test/test_thread_pool.rb
test_shutdown_with_grace - JRuby - rescued array may contain threads that have been GC'd, and hence are nil?
> test_thread_pool.rb - small JRuby fix [changelog skip]

- lib/puma/launcher.rb
- lib/puma/runner.rb
- test/test_integration_pumactl.rb
This is an attempt to fix `IOError: closed stream` errors resulting from the `test_halt_unix` test (which sends the `halt` control command to a server listening on a unix socket). These errors seem to be particularly affecting JRuby, so this fix may relate to #2262.
See examples of these errors on JRuby: [1](https://github.com/puma/puma/runs/687729880?check_suite_focus=true#step:7:346), [2](https://github.com/puma/puma/runs/687729939?check_suite_focus=true#step:7:316), [3](https://github.com/puma/puma/runs/687729995?check_suite_focus=true#step:7:358)
Here are examples where `test_halt_unix` hangs on Ubuntu MRI: [1](https://github.com/puma/puma/runs/683526520?check_suite_focus=true#step:7:161), [2](https://github.com/puma/puma/runs/683526529?check_suite_focus=true#step:7:381)
Here's an …
> Fix errors on test_halt_unix [changelog skip]

- History.md
- lib/puma/cluster.rb
- test/test_integration_cluster.rb
This fixes a bug in `fork_worker` mode (#2099) where an application that spawns subprocesses can sometimes get `nil` instead of an expected `Process::Status` object when waiting on the child (see https://github.com/puma/puma/pull/2099#discussion_r425927136). `test_fork_worker_spawn` demonstrates the regression and currently fails on `master`: https://github.com/puma/puma/blob/2d9b72ecc1e5ae214a964b7d6b692f1740c584a3/test/test_integration_cluster.rb#L171-L183
This PR is one of two approaches for a fix- it stores the list of forked worker pids and the `SIGCHLD` handler calls non-blocking `Process.wait` on each of them, removing the pids that have exited. This is similar to `#wait_workers`.
Worth noting that this approach results in a `wait` syscall for every worker for every subprocess …
> Fix for spawning subprocesses with fork_worker option

- lib/puma/server.rb
Fix rubocop offence introduced in https://github.com/puma/puma/commit/ad8197e4d6e4fc9b11545f455387ff4739f24fdf
> [changelog skip] Fix: Rubocop offence introduced in ad8197e

- lib/puma/launcher.rb
- lib/puma/state_file.rb
In https://github.com/ylecuyer/puma-status/issues/5 we got the problem where the control_url is a unix socket with a relative path. Just with the info within the state file, it is impossible to resolve the full path of the control server.
In this PR I added a `running_from` attribute to the state file which will allow to resolve such relative paths
> Minor: Add running_from to state_file

- History.md
- lib/puma/client.rb
- test/test_puma_server.rb
Fixes https://github.com/puma/puma/issues/1839.
Chunked requests don't contain a Content-Length header, but Puma buffers the entire request body upfront, which means it can determine the length before dispatching to the application.
The Rack spec doesn't mandate the presence of the CONTENT_LENGTH header, but it does refer to it as a "CGI key" and draws a distinction between it and the HTTP Content-Length header:
https://github.com/rack/rack/blob/v2.2.2/SPEC.rdoc
> The environment must not contain the keys HTTP_CONTENT_TYPE or HTTP_CONTENT_LENGTH (use the versions without HTTP_). The CGI keys (named without a period) must have String values.
RFC 3875, which defines the CGI protocol including CONTENT_LENGTH, says:
https://tools.ietf.org/html/rfc3875#section-4.1.2
> The server MUST set this …
> Set CONTENT_LENGTH for chunked requests

- History.md
- lib/puma/binder.rb
- lib/puma/launcher.rb
- test/test_binder.rb
Closes #2174.
This PR dynamically resolves `rack.multithread` and `rack.multiprocess`.
> Dynamically resolve rack.multithread/rack.multiprocess

- ext/puma_http11/org/jruby/puma/MiniSSL.java
- test/helpers/ssl.rb
- test/test_binder.rb
- test/test_cli.rb
- test/test_pumactl.rb
This fixes two JRuby tests that were skipped. It therefore fixes part of issue #2183.
The only production code change is to handle a nil `verify_mode` properly in `MiniSSL.java`. The previous code was throwing an exception 'no implicit conversion of nil into Integer'. Now a nil `verify_mode` will be converted to 0 and behave the same as if 'none' is specified.
The other changes are in the test setup. The keystore password was incorrect and the cipher suites specified are not ones that appear in the list returned by calling `getSupportedCipherSuites()` on the SSLEngine.
New error messages are spat out during the running of these tests, but that's an existing problem. `Puma::MiniSSL::Socket` is calling methods that are only defined by the C engine, such as `init?` and `shutdown`.
> Unskip two jruby ssl tests that were hanging [changelog skip]

- .github/workflows/puma.yml
Run CI using the default version of Bundler
* Which is Bundler on Ruby 2.2 and Bundler 2 on Ruby 2.3+.
This used to fail on TruffleRuby (fixed in https://github.com/oracle/truffleruby/issues/1984) and on Ruby 2.3 (due to https://github.com/ruby/setup-ruby/issues/51, now fixed).
Do not set the --path for bundle install
* This is buggy with Ruby 2.3 + Bundler 2.1.4, see https://github.com/ruby/setup-ruby/issues/51
cc @MSP-Greg, I'm not sure why the `--path` was set but it doesn't seem needed.
> Run CI using the default version of Bundler [changelog skip]

- test/helper.rb
This change tries to prevent hangs in the CI test runner caused by `teardown` hanging after a test times out by adding separate `Timeout.timeout` calls for the teardown hook.
Recent examples of tests that (I think) have failed in this way:
- [`TestIntegrationSingle#test_int_refuse`](https://github.com/puma/puma/runs/687729920?check_suite_focus=true#step:7:496) ([2](https://github.com/puma/puma/runs/682781346?check_suite_focus=true#step:7:247))
- [`TestIntegrationPumactl#test_halt_unix`](https://github.com/puma/puma/runs/683526520?check_suite_focus=true#step:7:161) ([2](https://github.com/puma/puma/runs/683526529?check_suite_focus=true#step:7:381), [3](https://github.com/puma/puma/runs/683526591?check_suite_focus=true#step:7:303))
> Timeout unit tests on teardown [changelog skip]

- History.md
- lib/puma/thread_pool.rb
- test/test_thread_pool.rb
if a thread is in the wait state, but transitions into
a killed state the waiting counter will not be decremented
leaving the pool to believe there is a thread available
and waiting to complete work when that is not the case.
Introduce a begin..ensure block so that any thread exception
raised while in the wait state properly balances the
waiting counter.
- [ x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x ] I have added appropriate tests if this PR fixes a bug or adds a feature.
- [ x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
> resolve waiting counter problem

- Gemfile
- History.md
Constrain `rake-compiler` version to 0.9.4 to fix `ClassNotFound` exception when using MiniSSL with Java8.
Fixes: #2301
Signed-off-by: Utkarsh Gupta <<utkarsh@debian.org>>
---
> Constrain rake-compiler version to 0.9.4

- History.md
- lib/puma/events.rb
- lib/puma/server.rb
- test/helper.rb
- test/test_integration_cluster.rb
CI is unreliable, with random failures across all Ruby types.  Small changes to lib files for shutdown, minor test changes.
Note that incomplete JRuby SSL implementation (`Puma::MiniSSL::Engine` `#init?` & `#shutdown`) will still   intermittently cause CI failure.
> Improve worker shutdown reliability, CI fixes

- docs/deployment.md
fix HAProxy configuration for including X-Request-Start header
source: https://stackoverflow.com/questions/31036893/how-do-i-add-x-request-start-in-haproxy/50060498#50060498
> [changelog skip] [ci skip] fix HAProxy configuration for X-Request-Start header

- test/test_cli.rb
Noticed intermittent test failures re 'port already in use' on port 9292, which is the default.  Change two tests using it to use port 0, they aren't actually using as a client, but they are binding to it...
> test_cli.rb - fix bind port (9292 port in use errors) [changelog skip]

- docs/deployment.md
When starting to transition from Unicorn to Puma, I first tried out puma in development. I initially assumed from skimming the docs that the number of workers for single mode should be 1. This led to our developers sometimes not being able to kill their puma server properly in our dev environment via Ctrl+C since the master process would stick around and try to revive it.
Upon reading the docs more carefully and checking out the issues, I found [I wasn't alone][issue-on-single-mode]. While it's obvious that 1 worker implies the existence of a master process, when you're just starting out it might take you a little while before you get your head around single mode versus cluster mode and having the configuration clearly stated helps with that imo.
So to make it blatantly obvious how to run …
> [changelog skip] [ci skip] Clarify how to run puma in single mode

- lib/puma/server.rb
JRuby has used "java" for RUBY_PLATFORM for 15 years, so the best way to detect the host OS is to use RbConfig's "host_os" value. This allows JRuby to support the TCP_CORK hack and fix benchmarks of very small request/response cycles.
See jruby/jruby#6366 for a more detailed discussion of TCP_CORK.
Detect Linux using RbConfig's "host_os" value rather than RUBY_PLATFORM, which is always "java" on JRuby.
> Detect linux properly across all Ruby impls

- History.md
- lib/puma/server.rb
according to @dentarg feedback https://github.com/puma/puma/pull/2345, we shouldn't use TCP_CORK on JRuby until it's properly supported.
It could also break on very old Linux kernels (< 2.6). Let's just make sure that all Socket constants are usable.
> make sure that TCP_CORK is supported

- History.md
- ext/puma_http11/puma_http11.c
This simply adds `#include <ctype.h>` to puma_http11.c
On the 4.x branch, we get the following warning during compilation:
```
warning: implicitly declaring library function 'isspace' with type 'int (int)'
```
On MacOS Big Sur, this results in a build failure with:
```
include the header <ctype.h> or explicitly provide a declaration for 'isspace' 
1 error generated.
```
This change has already been applied to 5.0.0.beta / master as part of https://github.com/puma/puma/commit/befe00a86447ffaedfad8b94eb5c4f2208f8bf7a
Closes #2304 
This PR is going to the 4.3.5 branch -- unsure if that's where you'd like it merged.
> Explicitly include ctype.h to fix compilation warning

- History.md
- ext/puma_http11/org/jruby/puma/MiniSSL.java
- lib/puma/minissl.rb
- test/test_puma_server_ssl.rb
JRuby implementation has always lacked Puma::MiniSSL::Engine#init? and #teardown methods, which are needed for use with SSL.  Added methods and set all SSL tests to run with JRuby.
> JRuby - Add Puma::MiniSSL::Engine#init? and #teardown methods, run all SSL tests

- test/test_pumactl.rb
When `pumactl` encounters issue, it exits [[1]]. That way also the whole test suite unexpectedly exits. Rescuing `SystemExit` exception keeps the test suite finish.
Fixes #2329
[1]: https://github.com/puma/puma/blob/0f718d516b92cd8bc4120c543b06792b22ac20bb/lib/puma/control_cli.rb#L272
> Do not quite when `pumactl` unexpectedly exits.

- lib/puma/server.rb
I found there's an inconsistency
```socket.setsockopt(Socket::IPPROTO_TCP```
and
```socket.getsockopt(Socket::SOL_TCP```
https://students.mimuw.edu.pl/SO/Linux/Kod/include/linux/socket.h.html
https://linux.die.net/man/7/tcp
* Setsockoptions(2) level. Thanks to BSD these must match IPPROTO_xxx
*To set or get a TCP socket option, call getsockopt(2) to read or setsockopt(2) to write the option with the option level argument set to IPPROTO_TCP. In addition, most IPPROTO_IP socket options are valid on TCP sockets. For more information see ip(7). 
```SOL_``` constants except for ```SOL_SOCKET``` are Linux specific and pretty unreliable even on CRuby. JRuby doesn't define them at all.
so why not just choose ```IPPROTO_TCP``` for both?
> replace SOL_TCP with IPPROTO_TCP [changelog skip]

- test/helper.rb
- test/helpers/integration.rb
- test/test_busy_worker.rb
- test/test_events.rb
- test/test_integration_cluster.rb
- test/test_out_of_band_server.rb
- test/test_persistent.rb
- test/test_puma_server.rb
- test/test_puma_server_ssl.rb
- test/test_rack_server.rb
- test/test_web_server.rb
Before https://github.com/puma/puma/commit/1f40ce031e7df67af4d43f37e295204e824e9b29, each test was wrapped in two threads for timeout guards, one for setup and the test, the other for teardown.  Teardown should be 'bulletproof', so it shouldn't need a timeout thread wrapping it.
The above commit changed it so everything was wrapped in one timeout, but when a test method timed out, that also stopped the teardown code.
The first commit changes it so only the actual test method is wrapped.  There may still be teardown timeout issues, but if so, teardown methods need to be revised so they never timeout.  If they timeout, they're not working correctly, and that may cause issues with subsequent tests.
The second and third commits change test file port handling, and also uses #addr instead of …
> Test fixups, port 0 and timeout handling [changelog skip]

- test/helper.rb
Minitest teardown code intermittently seems to freeze/lock up.
#2318 removed the timeout code for test teardown.  It should not be needed, but some CI jobs intermittently lock up.  Without it, we can't see which test(s) caused the lock up.
> Add back timeout for teardown [changelog skip]

- Gemfile
Current Gemfile uses rake-compiler with constraint `"~> 0.9.4"`, current release is `1.1.1`.
Includes JRuby fix mentioned in https://github.com/puma/puma/pull/2302#issuecomment-655732965
> Gemfile - update rake-compiler to 1.1.1 [changelog skip]

- History.md
- ext/puma_http11/org/jruby/puma/MiniSSL.java
Move initialization of KeyManagerFactory, TrustManagerFactory to server initialization.  This avoids reading the keystore file twice on every ssl request, and also fixes (https://github.com/puma/puma/issues/2299) a filehandle leak from reading the keystore file without closing it properly.
> Move initialization of KeyManagerFactory, TrustManagerFactory to server

- lib/puma/const.rb
- test/helper.rb
- test/helpers/integration.rb
- test/helpers/tmp_path.rb
- test/test_integration_cluster.rb
- test/test_integration_pumactl.rb
- test/test_redirect_io.rb
Currently, helpers/tmp_path.rb uses `#capture_exceptions` to run cleanup code, which is called several times for each test.
Adjusted code in it and test/helpers.rb to run once, after teardown.
This also allows asserts in teardown to work properly, see test_integration_pumactl.rb.
Also, `Tempfile.new` attaches finalizers to each object, which seemed to be intermittently bothering JRuby.
Changed to `Tempfile.create`
test_redirect_io.rb - small fix for setup and teardown.
helper.rb - removed `if ENV['CI']` conditional so that local and cloud CI both use TimeoutEveryTestCase.
> Small test fixes - helpers/tmp_path.rb, helper.rb & test_redirect_io.rb [changelog skip]

- test/test_puma_server_ssl.rb
While working in my fork, JRuby would intermittently have failures/timeouts from the tests in TestPumaServerSSLClient.
These tests can share the SSL Context, so adjust code to create a shared one.  Note that the tests in TestPumaServerSSL yield the Context, so sharing them won't work.
Note that CI passed in my fork:
https://github.com/MSP-Greg/puma/runs/1109220969
> TestPumaServerSSLClient - share Context [changelog skip]

- test/helper.rb
While working on another PR, I noticed one job ([ubuntu-18.04 truffleruby-head](https://github.com/MSP-Greg/puma/runs/1109525323?check_suite_focus=true#step:7:599)) where the log output showed all tests passing, but the job hit the time limit set in the Actions workflow file.
Inspecting the log, it showed three two minute 'pauses' in the log output, which is the current setting in test/helper.rb for non MRI jobs.
A brief look at CI logs seemed to show that the longest test takes approx 30 sec.
This PR changes the settings in TimeoutEveryTestCase to 45 sec for all jobs.  Hopefully, this will result in fewer jobs hitting the ten minute time limit, and hence, passing.
**Note:**  testing in my fork with this patch still had jobs timing out (only non MRI jobs).  So, there are still problems...
> test/helper.rb -TimeoutEveryTestCase - set all timeouts to 45 sec [changelog skip]

- .github/workflows/puma-no-ssl.yml
- History.md
- README.md
- Rakefile
- ext/puma_http11/no_ssl/PumaHttp11Service.java
- ext/puma_http11/puma_http11.c
- lib/puma.rb
- lib/puma/binder.rb
- lib/puma/detect.rb
- lib/puma/minissl.rb
- lib/puma/minissl/context_builder.rb
- lib/puma/reactor.rb
- lib/puma/runner.rb
- lib/puma/server.rb
- test/test_binder.rb
- test/test_cli.rb
- test/test_config.rb
- test/test_minissl.rb
- test/test_puma_server_ssl.rb
- test/test_pumactl.rb
Currently, Puma will not function if built without SSL support.  Also, SSL related files are all loaded regardless, so make them load-on-demand.
1. Allows compiling without OpenSSL & runs 'no ssl' CI on a few jobs
2. SSL test (now `Puma::HAS_SSL` or `Puma.ssl?`) relies on classes that only exist in the compiled extension if properly compiled with OpenSSL.
3. If compiled with 'no ssl', don't load ssl related files in Puma.  Also, don't load Ruby MRI OpenSSL.  JRuby currently  requires it for some reason. (?)
****Commits**** (need to be squashed for bisect)
1. **'Adjust code for compiling without SSL (MRI & JRuby), add ssl detection'** -  Removes MiniSSL.check, replace with Puma::HAS_SSL or Puma.ssl?
2. **'Adjust test files for 'no ssl' compile'**
3. **'Actions - add 'no ssl' workflow, …
> Allow Puma to compile when built without SSL, load SSL files on demand

- docs/signals.md
- ext/puma_http11/mini_ssl.c
- lib/puma.rb
- lib/puma/binder.rb
- lib/puma/client.rb
- lib/puma/cluster.rb
- lib/puma/configuration.rb
- lib/puma/control_cli.rb
- lib/puma/detect.rb
- lib/puma/dsl.rb
- lib/puma/error_logger.rb
- lib/puma/events.rb
- lib/puma/launcher.rb
- lib/puma/minissl.rb
- lib/puma/runner.rb
- lib/puma/server.rb
- lib/puma/thread_pool.rb
Recently spent some time with things other than Puma, came back to it, and...
There have been several additions in 5.0.0, so I added the YARD `@version` tag to all new methods/classes.  Added a few `@see` tags, which link to other methods.  The only actual code changes were a typo in two error messages that I did.
Left as separate commits.  I can generate docs from this if anyone wants to see the changes...
Separate commits for clarity, obviously should be squashed.
> Documentation - add version info, misc fixes [ci skip]

- lib/puma/binder.rb
- lib/puma/dsl.rb
- lib/puma/minissl.rb
Fix my errors in #2368.  Never again will I run without CI...
> Fix my errors in 2368 [changelog skip]

- lib/puma/error_logger.rb
- test/test_error_logger.rb
I've found a couple of mistakes in the new error logging class.
- We don't have to parse the dump of the request if it wasn't parsed
- It failed on error backtrace logging in `#debug` because of a typo
> [changelog skip] Fix error backtrace debug logging && Don't log not parsed request

- History.md
- lib/puma/runner.rb
- lib/puma/server.rb
- test/test_busy_worker.rb
- test/test_integration_pumactl.rb
- test/test_out_of_band_server.rb
- test/test_persistent.rb
- test/test_puma_server.rb
- test/test_pumactl.rb
In normal use, Server is passed an options hash in its initialize method.  Some code is outside of Server, using attr_accessors, some of which may have been created for CI, etc.  They also display in docs, which isn't needed.
1. server.rb - consolidate option handling, remove `attr_accessor` statements, change other lib files as needed.
2. server.rb - Server had a method defined in `class << self` (`tcp_cork_supported?`), and also a method defined as `self.current`.  Move current into `class << self` block.
3. runner.rb - `remove development?` & `test?`, which are only used to set a value based on options in Server.
4. Change test files to use `Server#instance_variable_get`
5. Add YARD `# @!attribute` tags to methods that are actually attributes (no parameters, getter, setter, or …
> Consolidate option handling in Server, Server small refactors, doc changes

- History.md
- lib/puma/events.rb
- lib/puma/reactor.rb
- lib/puma/server.rb
- test/test_events.rb
- test/test_puma_server_ssl.rb
The method signature should include the socket, so it determines what socket info is logged, and also so it can catch exceptions.
Closes #2365, closes #2367
> Change Events#ssl_error signature from (error, peeraddr, peercert) to (error, ssl_socket)

- History.md
- lib/puma/server.rb
- lib/puma/thread_pool.rb
- test/test_puma_server.rb
- test/test_thread_pool.rb
Refactors tests covering shutdown behavior to be less flaky (the current tests depend on fragile `sleep` timing that isn't 100% deterministic), and also fixes a couple of subtle timing edge-cases around force-shutdown behavior:
- Only allow `ForceShutdown` to be raised in a thread during specific areas of the connection-processing cycle (marked by `with_force_shutdown` blocks), to ensure that the raised error is always rescued and handled cleanly. (This fixes an issue where the `force_shutdown_after: 0` option throws uncaught exceptions from the threadpool on shutdown)
- ~Add `@queue_mutex` and helper methods `if_queue_requests` and `queue_client` to `Server` to handle an edge case where the reactor shuts down while a thread is concurrently queuing a client. (#2337)~ A fix for this issue …
> Better error handling during force shutdown

- lib/puma.rb
- lib/puma/binder.rb
- lib/puma/client.rb
- lib/puma/cluster.rb
- lib/puma/launcher.rb
- lib/puma/minissl.rb
- lib/puma/single.rb
- lib/puma/thread_pool.rb
- lib/puma/util.rb
This PR tags methods that can be classed as attributes, typically getters.
> Add more @!attribute tags [skip ci]

- test/test_integration_cluster.rb
- test/test_integration_single.rb
* No need in assigning the output of `connect` when it's only used
in one place.
* Remove inlined config in favor of config file introduced in 39f9c72
> Clean up tests [changelog skip]

- History.md
- lib/puma/client.rb
- lib/puma/server.rb
- test/test_puma_server.rb
This is a continuation from #2382.
One of the ways that an EOFError can be triggered is by opening a connection, not writing to it, then closing it (there may be others). This should be an expected and non-exceptional activity. When it happens we should not log it.
The change to client.rb makes sense to me as this is the initial place where we're reading from the socket and then finding out the stream has been closed. I'm not quite sure why the code in server.rb is needed. I think this comes from when the server is shutting down and trying to finish out connections.
I don't think this is the 100% right way to do things. I'm guessing that if we get an EOFError on a connection we should somehow consider it "dead" and never try to read from it again. I don't know if there's a better way to …
> [close #2371] Do not log EOFError

- History.md
- lib/puma/runner.rb
- lib/puma/server.rb
- test/test_puma_server.rb
Taken from PR #2373, added attr_writer's to maintain API, marked items as deprecated in v6.0.0.
PR #2373 included tests fixes.  Those fixes will be anther PR, this shows that no API changes have been made that break CI here.  I also double checked...
Small timing adjustment for a test that intermittently failed locally.
For one example similar to most of the fixes, see https://github.com/puma/puma/pull/2373#issuecomment-700272552
> Server - Consolidate option handling, small refactors, doc changes

- lib/puma/cluster.rb
- lib/puma/cluster/worker.rb
- lib/puma/cluster/worker_handle.rb
- lib/puma/util.rb
My original motivation for extracting code related to the worker processes is the change described in https://github.com/puma/puma/issues/1875#issuecomment-695143880. I want to be able to create the first worker process (assuming `fork_worker` is on) by first `fork`ing from the master, then immediately `exec`ing into a new process definition with a separate memory space. 
My proof-of-concept in that comment technically _works_ but it's messy because the logic used by the worker process is woven in together with the logic used by the puma master process in `Puma::Cluster`. Worker processes implicitly rely on several instance variables used in `Puma::Cluster`, so for the new process to spin up a new worker, it needs to first spin up a dummy instance of `Puma::Cluster`.
To make it a little …
> Refactor: extract worker process into separate class [changelog skip]

- docs/nginx.md
`$http_host` is vulnerable to host spoofing. Use `$host` instead. See https://github.com/yandex/gixy/blob/f5a54ad161a8f956eed0237ff689d49f7ed3a3e2/docs/en/plugins/hostspoofing.md
> Use $host instead of $http_host in nginx config [ci skip]

- 5.0-Upgrade.md
https://github.com/puma/puma/issues/2393#issuecomment-702359283
> [changelog skip] Mention WEB_CONCURRENCY update in the upgrade doc

- History.md
- docs/jungle/rc.d/puma
Pull request https://github.com/puma/puma/pull/2170/files removed all daemonization code.
The `-d` in the rc.d scripts is a left over from this.
This is replaces by `daemon` (https://www.freebsd.org/cgi/man.cgi?query=daemon&sektion=8)
for daemonization of the process.
> [ci skip] Cleanup daemonization in rc.d script

- History.md
- lib/puma/server.rb
`Server#handle_request` is a very long method, and also has many `#fast_write` calls.  `#fast_write` calls, which involve `rescue` clauses, when done with a reasonably defined string in terms of length, should be minimized.
Also, extract code to assemble the 'early hints' string into `#str_early_hints`.
> Consolidate fast_write calls in Server, extract early_hints assembly

- History.md
- lib/puma/client.rb
Remove JRuby specific methods:
#jruby_start_try_to_finish
#eagerly_finish
This is old code.  As shown below, `jruby_start_try_to_finish` is only called if the io is an `OpenSSL::SSL::SSLSocket`, but those aren't exposed in Puma, the io would only be a `Puma::MiniSSL::Socket`.  Hence, it's never called.
https://github.com/puma/puma/blob/b08976840ec70448b26b66b4a9134369ca3c3a61/lib/puma/client.rb#L227-L232
The MRI code and the JRuby code are identical when accounting for the above.  Most other repos dealing with sockets (EM, nio4r) don't have JRuby specific code for current JRuby (quick check, I've contributed to both).
> client.rb - remove JRuby specific 'finish' code

- lib/puma/queue_close.rb
- lib/puma/reactor.rb
- test/test_puma_server.rb
Quick followup to #2279, this PR extends the `TestPumaServer#shutdown_requests` test-method to pause `Reactor#add` for  the second connection until after shutdown begins, to ensure this edge case is correctly handled.
This adds unit-test coverage for the fix introduced in #2377 and updated in #2279.
This added test revealed that the edge-case wasn't handled properly in Ruby 2.2, so that is fixed in commit 0f4e51f9a170b271b257917a3df841e98ae7a0d3 as well.
Finally, commit e5d04ebb2ffeb4637a985804ee678dfe404f9b4b is a small style-fix followup in the related `Reactor` code.
Verified that this modified test fails on the following commits:
- de2f108fcb0a0b15076e2caac1ff8d4c32f2df27 (commit before #2279):
```
1) Failure:
TestPumaServer#test_shutdown_requests [test/test_puma_server.rb:1016]: …
```
> Test adding connection to Reactor after shutdown [changelog skip]

- History.md
- lib/puma/request.rb
- lib/puma/server.rb
server.rb is a very long file with several very long methods.
1. Extract `default_server_port`, `fast_write`, `fetch_status_code`, `handle_request`, `normalize_env`, `possible_header_injection?`, and `str_early_hints` from server.rb to request.rb
2. Extract `req_env_post_parse` and `str_headers` from `handle_request`
3. Updated comments/documentation
See https://msp-greg.github.io/puma/Puma/Request.html for the doc of the PR.
> Extract req/resp methods to new request.rb from server.rb

- test/helpers/integration.rb
- test/rackup/hello_with_delay.ru
- test/test_integration_cluster.rb
- test/test_integration_pumactl.rb
- test/test_integration_single.rb
Building on PR #2417, this adds testing for whether restart/USR2 drops connections.
1. Adds `hot_restart_does_not_drop_connections` to `helpers/integration.rb`.  The method is used in both `test_integration_cluster.rb` and `test_integration_single.rb` tests.  Each file runs the test two ways, first, with all connections created in one thread, and a second test with connections created in five threads.
2. Currently the test is adding output to the bottom 'debug' section, showing resets, restart count, and connections competed after the the first restart.
3. A file `rackup/hello_with_delay.ru` has been added and used in the test.  A normal 'Hello World' app, with a delay of 0.001 before the return.  The time can be increased to whatever is appropriate.
4. Not sure about whether the test …
> Add hot_restart_does_not_drop_connections tests [changelog skip]

- .github/workflows/non_mri.yml
- test/helper.rb
- test/helpers/integration.rb
- test/test_integration_cluster.rb
- test/test_integration_pumactl.rb
- test/test_integration_single.rb
- test/test_puma_server.rb
- test/test_puma_server_ssl.rb
Two commits:
Jobs still occasionally freeze/time-out in test step.
1. Allows jruby-head to fail (as done previously)
2. Actions - change all Ubuntu JRuby OS's to 20.04 (18.04 uses JDK-8, 20.04 uses JDK-11)
3. Integration tests (cluster, pumactl, single) - only run parallel on MRI Rubies
4. `helper.rb` - `TestSkips` - add `JRUBY_HEAD` constant for use with non-parallel conditionals and skips
5. `test_puma_server.rb` - jruby-head - run non-parallel
6. `test_puma_server_ssl.rb` - `TestPumaServerSSLClient` tests - non-parallel on JRuby, add `Errno::ECONNRESET` to client net/https rescue for TruffleRuby
7. `test_puma_server_ssl.rb` - `TestPumaServerSSL#test_http_rejection` - add `Net::ReadTimeout` to client net/https rescue for TruffleRuby
Added another exception to rescue trapping.  As the …
> Improve reliability of non-MRI CI [changelog skip]

- test/test_puma_server.rb
See https://github.com/puma/puma/issues/2390
Fixed by https://github.com/puma/puma/pull/2279
Fails in 5.0.2, showing EOFError being thrown.
> Add test_client_quick_close_no_lowlevel_error_handler_call [changelog skip]

- History.md
- lib/puma/cluster.rb
- lib/puma/cluster/worker.rb
- lib/puma/single.rb
- test/test_cli.rb
This PR slightly changes the timing behavior of the `on_booted` event, ensuring that the event is only fired after the server is running (that is, after `Server#run` has been called), so server stats are guaranteed to be available when this event fires.
In cluster mode, this is when the first stats 'ping' has been received from all worker processes. The timing of the 'ping' has also been updated to send the first one immediately, instead of after `Const::WORKER_CHECK_INTERVAL` (default 5) seconds have passed.
Fixes #2212.
> Fire on_booted after server starts

- ext/puma_http11/ext_help.h
- ext/puma_http11/mini_ssl.c
- ext/puma_http11/puma_http11.c
'Data_' macros have been 'deprecated' since Ruby 2.3 or earlier, but are still supported.
Update c source to use the 'TypedData_' macros.
> ext_help.h, minissl.c, puma_http11.c - change macros Data_ -> TypedData_ [changelog skip]

- .github/workflows/mri.yml
- .github/workflows/non_mri.yml
- test/helper.rb
- test/test_integration_single.rb
- test/test_launcher.rb
- test/test_out_of_band_server.rb
- test/test_persistent.rb
- test/test_puma_server.rb
This PR contains various updates to (hopefully) increase the stability of the non MRI CI.
I ran this fourteen times, and only two jobs failed (excepting jruby-head). TruffleRuby failed once in `bundle install`, and a JRuby job failed once in the manner shown in PR https://github.com/puma/puma/pull/2432.
1. Big Sur is available on Actions, added a single job in both MRI & non-MRI workflows.
2. Set all JRuby jobs to use JDK11.  Since the matrix is sparse, changed it to an 'include' only matrix.
3. `test/helper.rb
* changed the `run` method prepended into `Minitest::Test`.  `setup` and the test method now run in the same `Timeout` thread.
* Only run one `Timeout.timeout` for teardown methods.
4. `TestIntegrationSingle#test_int_refuse` appears to be the test that was intermittently locking up …
> Updates for non MRI CI stablity [changelog skip]

- lib/puma/server.rb
- lib/puma/single.rb
- test/test_puma_server.rb
This PR fixes a race-condition creating the `@check, @notify` pipe in `Server`, which caused various intermittent test failures on JRuby.
The issue can be triggered by a call to `#run` (which calls `#handle_servers` in a background-thread) followed immediately by `#stop` (which calls `#notify_safely`). This can result in two separate `@check, @notify` pipes getting created concurrently, causing the signal sent by `#stop` to not get picked up by the listen-loop in `#handle_servers`, and therefore fail to exit as expected. This PR adds a test `test_run_stop_thread_safety` demonstrating the race condition that consistently fails on JRuby without this fix (see [this test run](https://github.com/wjordan/puma/actions/runs/314657885)).
The fix moves pipe-creation into `Server#run` (before the …
> Server run thread safety fix [changelog skip]

- History.md
- bin/puma-wild
- lib/puma/launcher.rb
- lib/puma/reactor.rb
- test/config/prune_bundler_with_deps.rb
- test/rackup/hello-last-load-path.ru
- test/test_integration_cluster.rb
- test/test_launcher.rb
Fixes #2018 
A fairly common and reasonable deployment strategy has been broken since the introduction of `nio4r` in puma 4.0. Imagine that a user is using puma in cluster mode. In order to deploy a new version of an application, a user's deployment tool does this:
1. Add new version of the application's source to the server in a new directory
2. Update the "current release" symlink to point to the new release directory (the symlink is configured as puma's `directory` in the config file)
3. Issue a phased restart
4. After verifying that the release was successful, delete the old version of the application from disk
During the next deployment, workers will fail to start. They'll encounter the error `Could not find nio4r-2.5.1 in any of the sources (Bundler::GemNotFound)`. The root cause of …
> Fix Bundler::GemNotFound errors for nio4r gem

- test/test_response_header.rb
This PR tends to solve issue #2137 , adding more test for the response header, and follow the requirement mentioned in the rack doc.
Test include:
1. The header keys must be Strings. 
2. Special headers starting “rack.” are for communicating with the server, and must not be sent back to the client. 
3. The header must not contain a Status key. 
4. The header must conform to RFC7230 token specification, i.e. cannot contain non-printable ASCII, DQUOTE or “(),/:;<=>?@[]{}”. 
5. The values of the header must be Strings, consisting of lines (for multiple header values, e.g. multiple Set-Cookie values) separated by “\n”. The lines must not contain characters below 037.
If my test case is correct, I have found most features mentioned above did not cover yet (so the most tests should fail anyway) …
> Add test case for response header [changelog skip]

- test/config/prune_bundler_print_json_defined.rb
- test/test_integration_cluster.rb
This change adds an integration test for the changes in #2269, in order to prevent regressions similar to #1801.
It's important that in a puma cluster, that the master process doesn't `require`s the `json` gem, because doing to makes it not possible for users to upgrade or downgrade their application using a phased restart if they change the version of the `json` gem they're using.
> Add integration test to help prevent JSON loading regressions [changelog skip]

- lib/puma/cluster.rb
- lib/puma/cluster/worker.rb
- test/test_puma_server.rb
This PR fixes a hang on shutdown that occurred intermittently in `test_refork` ([example](https://github.com/puma/puma/runs/1281242974#step:8:550)). I reproduced the hang more consistently running `test_refork` with an extra `sleep` after the `'b'` (boot) message and before it starts the server (e.g., line 106 below): https://github.com/puma/puma/blob/aae4d4d045e35e1ad79b2009e008f1a9cdd94d71/lib/puma/cluster/worker.rb#L99-L108
The PR contains two small fixes.
1. Prevent server from starting if worker receives `TERM` signal (0018edde2c36011b26a1930bbbeeadc02368635b). This handles some (but not 100% of all) edge cases where the `TERM` signal is received and calls `server.stop` before the server has started.
2. Send TERM to fork_worker child processes in Cluster#wait_workers …
> Fix hang on shutdown in test_refork [changelog skip]

- test/helpers/integration.rb
- test/test_integration_cluster.rb
- test/test_integration_pumactl.rb
- test/test_pumactl.rb
**test_refork** - since refork is unlikely to be used with less than 3 workers, set workers to 3, previous value was 2.  Test sends 1k+ sockets, and will error if all do not receive a response.  Removed 'speed of light' client loop, as they can cause issues with CI.
**hot_restart_does_not_drop_connections** - fixed Windows error.  Removed 'speed of light' client loop.
**test/integration.rb** - added `fast_connect` which opens and sends a request without a read.  Uses `fast_write` (`syswrite`).  Moved `fast_write` to below `fast_connect`.
> Fix-up test_refork, hot_restart_does_not_drop_connections [changelog skip]

- History.md
- lib/puma/client.rb
- lib/puma/reactor.rb
The issue - how to make Puma respond gracefully when a io connection can misbehave/fail at any point in its handling?
This is a difficult thing to test in CI, especially with multiple VM's running on CI runners.
The are infrequent errors in Puma CI, one example below:
```
Error in reactor loop escaped: mode not supported for this object: r (ArgumentError)
org/nio4r/Selector.java:124:in `register'
/Users/runner/work/puma/puma/lib/puma/reactor.rb:93:in `register'
/Users/runner/work/puma/puma/lib/puma/reactor.rb:77:in `select_loop'
/Users/runner/work/puma/puma/lib/puma/reactor.rb:34:in `block in run'
```
The error `mode not supported for this object: r` implies that the socket is no longer valid in some way.
Does it represent a CI specific issue, or is it something that could occur in real …
> Add Client#io_ok?, check before Reactor#register

- History.md
- lib/puma/queue_close.rb
- lib/puma/reactor.rb
Small refactor of queue_close.rb and its loading.  Move comment so it is attached to `QueueClose`.
> queue_close.rb - refactor loading, move comment for docs

- lib/puma/reactor.rb
1. NIO has c, ruby, and java implementations.  Normally, an io object is expected to be passed to NIO::Selector#register, but currently we are providing a Client.  Change to pass the actual Client io.  `NIO::Monitor`'s have a `#value` attribute, and the client is set to that, so changing to an io affects no other code.
2. Puma::Client is a container that contains an 'accepted' io, and also has methods for interacting with other Puma objects.  Several Puma::Reactor methods take a Client as a parameter, but are currently named `io`.  Change to `client`.
> reactor.rb - register the io, not the client, rename parameters [changelog skip]

- History.md
- lib/puma/client.rb
- test/test_puma_server.rb
Fixes #2398 by closing connections that have not yet made requests immediately on shutdown.
> Close idle connections immediately on shutdown

- History.md
- lib/puma/cluster.rb
- test/rackup/write_to_stdout_on_boot.ru
- test/test_integration_cluster.rb
Fixes #2454. A regression introduced in #2374 effectively broke `preload_app`. The puma master process would successfully preload the app before starting any workers, but fail to pass the preloaded app into the workers, who would then load their own version of the app, effectively defeating the point of preloading in the first place.
> Pass preloaded application into new workers if available

- lib/puma/control_cli.rb
- test/test_pumactl.rb
Main change is to replace COMMANDS, an array of command names with CMD_PATH_SIG_MAP, a Hash with keys of command names and values of the signal.
COMMANDS remains for API compatibility
> Refactor control_cli.rb - add CMD_PATH_SIG_MAP [changelog skip]

- lib/puma/cluster.rb
- test/test_integration_cluster.rb
`fork_worker` and `SIGURG` should be independent.  Rearrange code for that.  Small test fix.
@wjordan - agree?  I was working on some refactoring, wanted to add an 'http' based 'refork' command in ControlCLI, and noticed it...
> cluster.rb - rearrange SIGURG & fork_worker code, small test fix [changelog skip]

- History.md
- lib/puma/cluster/worker.rb
- lib/puma/cluster/worker_handle.rb
- test/helpers/integration.rb
- test/test_worker_gem_independence.rb
- test/worker_gem_independence_test/new_json/Gemfile
- test/worker_gem_independence_test/new_json/config.ru
- test/worker_gem_independence_test/new_json/config/puma.rb
- test/worker_gem_independence_test/new_nio4r/Gemfile
- test/worker_gem_independence_test/new_nio4r/config.ru
- test/worker_gem_independence_test/new_nio4r/config/puma.rb
- test/worker_gem_independence_test/old_json/Gemfile
- test/worker_gem_independence_test/old_json/config.ru
- test/worker_gem_independence_test/old_json/config/puma.rb
- test/worker_gem_independence_test/old_nio4r/Gemfile
- test/worker_gem_independence_test/old_nio4r/config.ru
- test/worker_gem_independence_test/old_nio4r/config/puma.rb
This change is the first in a series meant to address phased restart errors related to the `json` gem described in #2471. The changes for this specific PR are described in a comment in the same issue: https://github.com/puma/puma/issues/2471#issuecomment-719834731
This PR essentially reverts the changes to the handling of puma worker stats introduced by #2124 in a way that intentionally avoids the use of the `json` gem.
I added an integration test to ensure that users can upgrade/downgrade the JSON gem as part of phased restart (it reliably reproduces the error reported in #2471). While I was in there, I added a similar integration test for upgrading/downgrading the nio4r gem. That test was effectively fixed by #2427.
> Remove use of json gem from WorkerHandle#ping!

- History.md
- README.md
- lib/puma/configuration.rb
- lib/puma/launcher.rb
- test/test_config.rb
- test/test_launcher.rb
This PR adds support for printing the puma config if an env variable is provided as agreed in #2414 
I'm aware am missing several things including the tests but I just want early feedback if possible, this is my first contribution to the project :) 
Closes #2414 
Here is an example of the output:
> Log the configuration if an env variable is provided

- test/test_worker_gem_independence.rb
From the discussion in https://github.com/puma/puma/pull/2473#issuecomment-720186764 
Running `bundle exec puma` in a clean bundler env is a more realistic way to start puma.
> Run puma cli server in unbundled env in worker gem tests [changelog skip]

- 5.0-Upgrade.md
- History.md
- README.md
- lib/puma/dsl.rb
- test/test_config.rb
As seen from the output below, by default, phased restart is only available with 1 worker 🤔 😆
```
$ WEB_CONCURRENCY=0 puma -C test/config/app.rb -p 0
* Version 5.0.4 (ruby 2.7.1-p83), codename: Spoony Bard
* Min threads: 0, max threads: 5
* Environment: development
* Listening on http://0.0.0.0:49619
Use Ctrl-C to stop
$ WEB_CONCURRENCY=1 puma -C test/config/app.rb -p 0
[61446] Puma starting in cluster mode...
[61446] * Version 5.0.4 (ruby 2.7.1-p83), codename: Spoony Bard
[61446] * Min threads: 0, max threads: 5
[61446] * Environment: development
[61446] * Process workers: 1
[61446] * Phased restart available
[61446] * Listening on http://0.0.0.0:49621
[61446] Use Ctrl-C to stop
[61470] + Gemfile in context: /Users/dentarg/src/puma/Gemfile
[61446] - Worker …
```
> Improve docs around preload_app! and phased restart

- Gemfile
- History.md
- lib/puma.rb
- lib/puma/app/status.rb
- lib/puma/json.rb
- test/config/prune_bundler_print_json_defined.rb
- test/test_cli.rb
- test/test_integration_cluster.rb
- test/test_json.rb
- test/test_worker_gem_independence.rb
- test/worker_gem_independence_test/new_json_with_puma_stats_after_fork/Gemfile
- test/worker_gem_independence_test/new_json_with_puma_stats_after_fork/config.ru
- test/worker_gem_independence_test/new_json_with_puma_stats_after_fork/config/puma.rb
- test/worker_gem_independence_test/old_json_with_puma_stats_after_fork/Gemfile
- test/worker_gem_independence_test/old_json_with_puma_stats_after_fork/config.ru
- test/worker_gem_independence_test/old_json_with_puma_stats_after_fork/config/puma.rb
Fixes #2471. The changes proposed in this PR in particular are described in a [comment](https://github.com/puma/puma/issues/2471#issuecomment-719834731) on the same issue. This PR introduces a new `Puma::JSON` module, which is meant to handle the specific places where Puma needs to perform JSON serialization.
> Remove use of json gem

- History.md
- docs/systemd.md
- lib/puma/binder.rb
- lib/puma/cli.rb
- lib/puma/dsl.rb
- lib/puma/launcher.rb
- test/test_binder.rb
Currently still a draft, based on https://github.com/puma/puma/issues/1360#issuecomment-689548650. Having it as a PR allows me to refer to this work. That's why the checklist is not filled in yet.
Systemd can present sockets as file descriptors that are already opened.  By default Puma will use these but only if it was explicitly told to bind to the socket. If not, it will close the activated sockets. This means all configuration is duplicated.
Binds can contain additional configuration, but only SSL config is really relevant since the unix and TCP socket options are ignored.
This means there is a lot of duplicated configuration for no additional value in most setups. This option tells the launcher to bind to all activated sockets, regardless of existing binds.
Note it does not clear …
> Add option to bind to systemd activated sockets

- History.md
- lib/puma/reactor.rb
The following error happens intermittently in non MRI CI:
```
Error in reactor loop escaped: mode not supported for this object: r (ArgumentError)
```
PR adds a rescue in `Reactor#register.
Note that https://github.com/puma/puma/pull/2432 also attempted to catch this (without a rescue), but some errors still occur.  I tried to remove it, and doing so caused more intermittent errors...
Updated HISTORY.md
> Catch 'Error in reactor loop escaped: mode not supported for this object: r'

- History.md
- lib/puma/control_cli.rb
control_cli.rb (`Puma::ControlCLI.new`) takes a parameter to route output to (defaults to `STDOUT`).  Currently, all output is not routed to it.  Fixed.
> control_cli.rb - all normal output should be to @stdout

- History.md
- docs/compile_options.md
- ext/puma_http11/http11_parser.c
- ext/puma_http11/puma_http11.c
According to #2273 discussion, I add an optional cflags to configure query string max length when we compile puma.
This change is reference @maleksiuk version (https://github.com/maleksiuk/puma/commit/1c56e5f9ae9760b838d4ed8ce972f615a942e55b) to keep source code clean, but I didn't put the environment variable detect part which I think isn't necessary when we have `--cflags` options.
> Allow configuring query string max length

- History.md
- lib/puma/dsl.rb
- test/helpers/ssl.rb
- test/test_config.rb
Fixes up Puma::DSL#ssl_bind, which did not handle JRuby `ssl_cipher_list`.
Adds a class method to Puma::DSL that creates the ssl bind string.  The method should be used in CI for generating bind strings.
> Fix JRuby ssl_cipher_list, add Puma::DSL.ssl_bind_str method

- ext/puma_http11/extconf.rb
extconf.rb - fixup for OpenSSL 1.1.1, change from 1.1.0.  Removes one compile warning when building on newer gcc versions.
> Bug: extconf.rb - fixup for 1.1.1 change from 1.1.0 [changelog skip]

- lib/puma/const.rb
- test/test_launcher.rb
Fix `Puma::Const::ILLEGAL_HEADER_KEY_REGEX` overlap warning
Add backslash as illegal character for header field-name
See https://github.com/puma/puma/pull/2495 and https://github.com/puma/puma/pull/2439
Update `test_launcher.rb`, use parenthesis with regex parameters, removes warning
Re headers, see:
7320 Header Fields
https://tools.ietf.org/html/rfc7230#section-3.2
Tokens
https://tools.ietf.org/html/rfc7230#section-3.2.6
ABNF
https://tools.ietf.org/html/rfc7230#appendix-B
See table from below
http://www.bizcoder.com/everything-you-need-to-know-about-http-header-syntax-but-were-afraid-to-ask#footnote3
> Bug: Fix regex warnings in const.rb & test_launcher.rb [changelog skip]

- lib/puma/runner.rb
- lib/puma/server.rb
Simple PR that does two things:
1. Add the master pid to Puma's startup log output.  All other information needed is already included.
2. Changes the name of the control server thread to 'control'.  Previously named 'server'.
> Add pid to start-up log output, name control server thread 'control' [changelog skip]

- ext/puma_http11/puma_http11.c
This PR changes the name of a locally-defined `#define`, used to quote an explanation.
The definition `EXPLAIN_MAX_LENGTH_VALUE` is only used right here, so this is not a functional change, just spelling. See #2485
> Fix typo in local #define name [changelog skip]

- .github/workflows/mri.yml
- .github/workflows/non_mri.yml
- History.md
- ext/puma_http11/extconf.rb
- ext/puma_http11/http11_parser.c
- ext/puma_http11/http11_parser.java.rl
- ext/puma_http11/http11_parser.rl
- ext/puma_http11/mini_ssl.c
- ext/puma_http11/org/jruby/puma/Http11Parser.java
Added `append_cflags config_string 'WERRORFLAG'` into extconf to instruct compiler to consider warnings as errors. Also fixed all warnings reported by GCC with default configuration.
Closes #1953.
> Fail build if compiling extensions raises warnings (#1953)

- History.md
- lib/puma/control_cli.rb
- lib/puma/error_logger.rb
- lib/puma/events.rb
- lib/puma/runner.rb
- test/test_error_logger.rb
- test/test_events.rb
Closes #1948 
Uses `flush` after writing to stdout and stderr so we don't need to use `sync=true`
> Avoid mutating $stdout and $stderr

- lib/puma/launcher.rb
- test/test_launcher.rb
Currently, `Events#fire_on_stopped!` is called in both `Launcher#stop` and `Launcher#graceful_stop`
Launcher#graceful_stop is called later in Launcher#run, remove the call from `Launcher#stop`.
> Bug: Fix Events#fire_on_stopped! double call [changelog skip]
